/* =====================================================================
   ALUR NYATA v9
   1) Paket Travel: dibuat & dipublish langsung oleh Travel (tanpa approval admin).
   2) Pendaftar: Travel melihat data lengkap jamaah, bukti bayar, dan dokumen yang
      diunggah; memverifikasi / menolak dengan alasan (jamaah diberi tahu).
   3) Withdrawal: diajukan → disetujui / dikembalikan (revisi) / ditahan / ditolak →
      dikirim lagi / dibatalkan → ditransfer (dengan bukti transfer). Saldo ikut nyata.
   File disimpan di tabel control_center.files; metadata di koleksi `uploads`.
   ===================================================================== */
const UPLOADS = [];
const FILECACHE = {};
const DOC_KINDS = [['ktp', ['KTP', 'ID card (KTP)', 'الهوية']], ['passport', ['Paspor', 'Passport', 'الجواز']], ['photo', ['Pas foto 4×6', 'Photo 4×6', 'صورة']], ['kk', ['Kartu Keluarga / Buku Nikah', 'Family card / Marriage book', 'دفتر العائلة']], ['vaccine', ['Sertifikat vaksin meningitis', 'Meningitis vaccine certificate', 'شهادة التطعيم']], ['visa', ['Visa', 'Visa', 'التأشيرة']]];
const docLabel = k => { const d = DOC_KINDS.find(x => x[0] === k); return d ? L3(d[1]) : k === 'payproof' ? L3(['Bukti bayar', 'Payment proof', 'إثبات الدفع']) : k === 'wdproof' ? L3(['Bukti transfer', 'Transfer proof', 'إثبات التحويل']) : k; };
function reroute(pattern, fn) { for (let i = ROUTES.length - 1; i >= 0; i--) if (ROUTES[i].pattern === pattern) ROUTES.splice(i, 1); route(pattern, fn); }

/* ---------- skema tambahan (idempoten, sekali per database) ---------- */
const SCHEMA_V = 3;
async function sbSchemaUpgrade() {
  const r = await sql(`select value #>> '{}' as v from control_center.settings where key = 'schema_version'`).catch(() => []);
  if (+(r[0] && r[0].v) >= SCHEMA_V) return;
  await sql(['begin',
    `create table if not exists control_center.files (id text primary key, ref text, kind text, name text, mime text, size int, data text not null, created_at timestamptz not null default now())`,
    'create index if not exists files_ref_idx on control_center.files (ref)',
    'alter table control_center.files enable row level security',
    'revoke all on control_center.files from anon, authenticated',
    `do $x$ declare c text; begin for c in select conname from pg_constraint where conrelid = 'control_center.withdrawals'::regclass and contype = 'c' and pg_get_constraintdef(oid) ilike '%status%' loop execute format('alter table control_center.withdrawals drop constraint %I', c); end loop; end $x$`,
    `alter table control_center.withdrawals add constraint withdrawals_status_check check (status in ('pending','approved','processing','disbursed','hold','needs_revision','rejected','cancelled'))`,
    `insert into control_center.settings (key, value) values ('schema_version', '${SCHEMA_V}'::jsonb) on conflict (key) do update set value = excluded.value, updated_at = now()`,
    'commit'].join('; ') + ';');
}

/* ---------- unggah & lihat file ---------- */
const MAX_FILE = 4 * 1024 * 1024;
function pickFile(accept) { return new Promise(res => { const i = document.createElement('input'); i.type = 'file'; i.accept = accept || 'image/*,.pdf'; i.onchange = () => res(i.files[0] || null); i.click(); }); }
const readAsDataURL = f => new Promise((res, rej) => { const r = new FileReader(); r.onload = () => res(r.result); r.onerror = rej; r.readAsDataURL(f); });
async function fileToData(f) {
  if (/^image\//.test(f.type) && !/svg/.test(f.type)) {
    const url = await readAsDataURL(f); const img = await new Promise((res, rej) => { const im = new Image(); im.onload = () => res(im); im.onerror = rej; im.src = url; });
    const k = Math.min(1, 1600 / Math.max(img.width, img.height)); const c = document.createElement('canvas'); c.width = Math.round(img.width * k); c.height = Math.round(img.height * k); c.getContext('2d').drawImage(img, 0, 0, c.width, c.height);
    const d = c.toDataURL('image/jpeg', .82); return { mime: 'image/jpeg', data: d.split(',')[1], size: Math.round(d.length * .75) };
  }
  if (f.size > MAX_FILE) throw new Error(L3(['File terlalu besar (maks 4 MB)', 'File too large (max 4 MB)', 'الملف كبير']));
  const d = await readAsDataURL(f); return { mime: f.type || 'application/octet-stream', data: d.split(',')[1], size: f.size };
}
/* simpan file + metadata; dipakai semua portal */
async function saveUpload(file, meta) {
  const x = await fileToData(file); const up = Object.assign({ id: uid('UPL'), name: file.name || 'file', mime: x.mime, size: x.size, state: 'submitted', ts: nowTs() }, meta);
  if (typeof SB !== 'undefined' && SB.on) await sql(`insert into control_center.files (id, ref, kind, name, mime, size, data) values (${dq(up.id)}, ${dq(up.ref || '')}, ${dq(up.kind)}, ${dq(up.name)}, ${dq(up.mime)}, ${up.size}, ${dq(x.data)})`);
  FILECACHE[up.id] = 'data:' + x.mime + ';base64,' + x.data;
  UPLOADS.unshift(up); return up;
}
async function fileURL(id) {
  if (FILECACHE[id]) return FILECACHE[id];
  if (typeof SB === 'undefined' || !SB.on) return null;
  const r = await sql(`select mime, data from control_center.files where id = ${dq(id)}`); if (!r[0]) return null;
  return FILECACHE[id] = 'data:' + r[0].mime + ';base64,' + r[0].data;
}
A['file-view'] = async el => { const up = UPLOADS.find(u => u.id === el.dataset.id); if (!up) return; modal({ title: docLabel(up.kind) + ' · ' + up.name, wide: true, body: `<div id="fv-box" style="min-height:200px;display:grid;place-items:center">${L3(['Memuat…', 'Loading…', 'جارٍ التحميل…'])}</div>` });
  try { const u = await fileURL(up.id); const box = document.getElementById('fv-box'); if (!box) return; if (!u) { box.innerHTML = stateBlock('empty', { title: L3(['File tidak ditemukan', 'File not found', 'غير موجود']) }); return; }
    box.innerHTML = (/^image\//.test(up.mime) ? `<img src="${u}" alt="${esc(up.name)}" style="max-width:100%;max-height:70vh;border-radius:8px">` : /pdf/.test(up.mime) ? `<embed src="${u}" type="application/pdf" style="width:100%;height:70vh">` : `<div class="muted">${esc(up.mime)}</div>`) + `<div style="margin-top:10px"><button class="btn sm" data-act="file-dl" data-id="${up.id}" hidden id="fv-dl">${ic('download', 'sm')}${L3(['Unduh', 'Download', 'تنزيل'])}</button></div>`;
  const dl = document.getElementById('fv-dl'); if (dl && window.claude && window.claude.use && await window.claude.use('downloads')) dl.hidden = false; }
  catch (e) { toast('bad', L3(['Gagal membuka file', 'Failed to open file', 'فشل']), String(e.message || e)); } };
const upState = u => u.state === 'verified' ? st('verified') : u.state === 'rejected' ? st('rejected') : st('submitted');
const upRow = (u, actions) => `<div class="docrow"><span class="fi">${/pdf/.test(u.mime) ? 'PDF' : 'IMG'}</span><span class="body"><b>${esc(docLabel(u.kind))}${u.pax != null ? ' · ' + L3(['Jamaah ', 'Pilgrim ', 'معتمر ']) + (u.pax + 1) : ''}</b><span>${esc(u.name)} · ${fN(Math.round(u.size / 1024))} KB · ${rel(u.ts)}${u.by ? ' · ' + esc(u.by) : ''}${u.reason ? ' · “' + esc(u.reason) + '”' : ''}</span></span>${upState(u)}<button class="btn sm ghost" data-act="file-view" data-id="${u.id}">${ic('eye', 'sm')}${L3(['Lihat', 'View', 'عرض'])}</button>${actions || ''}</div>`;

/* ================= 1) PAKET: publish langsung oleh Travel ================= */
const canPublish = (tr, p) => { if (tr.op !== 'active') return L3(['Tenant belum aktif', 'Tenant not active', 'غير نشط']); if (!licOk(tr, p.cat)) return L3(['Izin ', 'Licence ', 'الترخيص ']) + licFor[p.cat] + L3([' belum terverifikasi', ' not verified', ' غير موثق']); if (tr.sub && ['suspended', 'expired', 'cancelled'].includes(tr.sub.state)) return 'Subscription ' + stLbl(tr.sub.state); return null; };
reroute('/p/travel/packages', () => { const tr = me('travel'); const pk = PACKAGES.filter(p => p.travel === tr.id);
  const btn = (p, v, cls, label, why) => `<button class="btn sm ${cls}" data-act="tp-set" data-id="${p.id}" data-v="${v}" ${why ? `aria-disabled="true" data-tip="${esc(why)}"` : ''}>${label}</button>`;
  return { html: `<div class="page">${pHead('travel', L3(['Paket', 'Packages', 'الباقات']), L3(['Buat paket lalu publish langsung ke Marketplace — tanpa menunggu approval admin. Syarat: tenant aktif & izin sesuai kategori (Umrah→PPIU, Haji→PIHK, Tour→BPW).', 'Create a package and publish it straight to the Marketplace — no admin approval. Requirements: active tenant & matching licence (Umrah→PPIU, Hajj→PIHK, Tour→BPW).', 'انشر مباشرة.']), `<button class="btn primary" data-act="tp-new">${ic('plus')}${L3(['Buat paket', 'Create package', 'إنشاء باقة'])}</button>`)}
  <section class="panel">${tbl([L3(['Paket', 'Package', 'الباقة']), L3(['Kategori', 'Category', 'الفئة']), 'Harga', L3(['Berangkat', 'Departure', 'المغادرة']), 'Seat', t('status'), t('action')], pk.map(p => { const why = canPublish(tr, p); return `<tr><td><b>${esc(p.name)}</b><div class="muted mono" style="font-size:11.5px">${p.id}</div></td><td>${p.cat}${licOk(tr, p.cat) ? '' : ` <span class="st warn">${ic('alert')}${licFor[p.cat]}</span>`}</td><td class="r tnum">${money(p.price)}</td><td>${fD(p.dep)}</td><td class="r tnum">${p.sold}/${p.seats}</td><td>${st(p.state)}</td><td class="r"><div class="actions" style="justify-content:flex-end;flex-wrap:nowrap">${p.state === 'published' ? btn(p, 'unpublished', 'badb', 'Unpublish') : btn(p, 'published', 'primary', p.state === 'unpublished' ? L3(['Publish lagi', 'Publish again', 'إعادة النشر']) : 'Publish', why)}${p.state !== 'published' ? `<button class="btn sm" data-act="tp-edit" data-id="${p.id}">${ic('note', 'sm')}</button>` : ''}</div></td></tr>`; }), L3(['Belum ada paket', 'No packages yet', 'لا باقات']))}</section></div>` }; });
Object.assign(A, {
  'tp-set': el => { const tr = me('travel'); const p = pkgById(el.dataset.id); const v = el.dataset.v; if (!p || p.travel !== tr.id) return; if (v === 'published') { const why = canPublish(tr, p); if (why) { toast('bad', L3(['Belum bisa publish', 'Cannot publish yet', 'لا يمكن النشر']), why); return; } }
    const prev = p.state; p.state = v; if (v === 'published') p.publishedAt = nowTs(); pAudit('travel', 'package.' + (v === 'published' ? 'publish' : v), 'Package/' + p.id, { before: prev, after: v });
    if (v === 'published') pNotif('marketplace', 'info', L3(['Paket baru dipublish', 'New package published', 'باقة جديدة']), p.name + ' · ' + tr.name, '/marketplace/moderation');
    toast('ok', p.name + ' → ' + stLbl(v), v === 'published' ? L3(['Langsung tampil di Marketplace & aplikasi', 'Live on the Marketplace & app now', 'منشور الآن']) : ''); rerender(); },
  'tp-edit': el => { const p = pkgById(el.dataset.id); modal({ title: L3(['Ubah paket', 'Edit package', 'تعديل']), body: fields([{ k: 'name', label: L3(['Nama paket', 'Package name', 'الاسم']), req: true, def: p.name }, { k: 'price', label: 'Harga / pax (Rp)', type: 'number', req: true, def: p.price, step: 100000 }, { k: 'seats', label: 'Seat', type: 'number', def: p.seats, min: 1 }, { k: 'dep', label: L3(['Tanggal berangkat', 'Departure date', 'تاريخ المغادرة']), type: 'date', def: new Date(p.dep).toISOString().slice(0, 10) }], 'te-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="tp-edit-go" data-id="${p.id}">${t('save')}</button>` }); },
  'tp-edit-go': el => { const p = pkgById(el.dataset.id); const v = formVals([{ k: 'name', req: true }, { k: 'price', type: 'number', req: true }, { k: 'seats', type: 'number' }, { k: 'dep' }], 'te-'); if (!v) return; Object.assign(p, { name: v.name, price: v.price, seats: Math.max(p.sold, v.seats || p.seats), dep: new Date(v.dep).getTime() }); pAudit('travel', 'package.update', 'Package/' + p.id); closeOverlays(); toast('ok', L3(['Paket diperbarui', 'Package updated', 'تم التحديث']), p.name); rerender(); }
});

/* ================= 2) PENDAFTAR: data lengkap, bukti bayar, dokumen ================= */
const PILGRIM_F = [['name', ['Nama sesuai paspor', 'Name as in passport', 'الاسم'], 'text', true], ['nik', ['NIK', 'National ID (NIK)', 'رقم الهوية'], 'text'], ['gender', ['Jenis kelamin', 'Gender', 'الجنس'], 'select'], ['birth', ['Tanggal lahir', 'Date of birth', 'تاريخ الميلاد'], 'date'], ['phone', ['Telepon', 'Phone', 'الهاتف'], 'tel'], ['passport', ['No. paspor', 'Passport no.', 'رقم الجواز'], 'text'], ['passportExp', ['Paspor berlaku s/d', 'Passport valid until', 'صلاحية الجواز'], 'date'], ['mahram', ['Mahram / hubungan', 'Mahram / relation', 'المحرم'], 'text']];
function ensurePilgrims(b) { const tv = TRAVELERS.find(x => x.id === b.traveler) || {}; b.pilgrims = b.pilgrims || []; for (let i = b.pilgrims.length; i < b.pax; i++) b.pilgrims.push(i === 0 ? { name: tv.name || '', phone: tv.phone || '' } : { name: '' }); return b.pilgrims; }
const pilgrimDone = p => !!(p && p.name && p.nik && p.birth && p.passport);
const bkUploads = b => UPLOADS.filter(u => u.booking === b.id);
function docsGrid(b, mode) { /* mode: 'travel' | 'traveler' */
  const ups = bkUploads(b).filter(u => u.kind !== 'payproof'); const P = ensurePilgrims(b);
  return P.map((p, i) => `<div style="margin-bottom:12px"><div class="eyebrow" style="margin-bottom:6px">${L3(['Jamaah ', 'Pilgrim ', 'معتمر ']) + (i + 1)} · ${esc(p.name || '—')}</div>${DOC_KINDS.filter(k => k[0] !== 'visa' || mode === 'travel' || ups.some(u => u.kind === 'visa' && u.pax === i)).map(([k]) => { const L = ups.filter(u => u.kind === k && u.pax === i); const cur = L[0];
    const acts = mode === 'travel' ? (cur && cur.state === 'submitted' ? `<button class="btn sm okb" data-act="up-verify" data-id="${cur.id}">${ic('check', 'sm')}${L3(['Valid', 'Valid', 'صحيح'])}</button><button class="btn sm badb" data-act="up-reject" data-id="${cur.id}">${L3(['Tolak', 'Reject', 'رفض'])}</button>` : '') : '';
    const upBtn = (mode === 'traveler' && k !== 'visa' && (!cur || cur.state === 'rejected')) || (mode === 'travel' && (!cur || cur.state === 'rejected' || k === 'visa')) ? `<button class="btn sm" data-act="up-doc" data-b="${b.id}" data-k="${k}" data-i="${i}" data-ws="${mode}">${ic('upload', 'sm')}${cur ? L3(['Unggah ulang', 'Re-upload', 'إعادة']) : L3(['Unggah', 'Upload', 'رفع'])}</button>` : '';
    return cur ? upRow(cur, acts + upBtn) : `<div class="docrow"><span class="fi">—</span><span class="body"><b>${esc(docLabel(k))}</b><span>${L3(['Belum diunggah', 'Not uploaded yet', 'لم يُرفع'])}</span></span>${st('pending')}${upBtn}</div>`; }).join('')}</div>`).join(''); }
function payProofs(b, mode) {
  const pays = PAYMENTS.filter(x => x.booking === b.id);
  return pays.length ? pays.map(x => { const pr = UPLOADS.filter(u => u.kind === 'payproof' && u.payment === x.id);
    return `<div style="border:1px solid var(--line);border-radius:10px;padding:10px;margin-bottom:8px"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><b class="mono">${x.id}</b><span class="tnum">${money(x.amount, true)}</span><span class="muted" style="font-size:12px">${esc(x.channel || '')} · ${esc(x.provider || '')}</span><span style="flex:1"></span>${st(x.status)}</div>
    ${pr.map(u => upRow(u, mode === 'travel' && u.state === 'submitted' && x.status === 'pending' ? `<button class="btn sm primary" data-act="pay-confirm" data-id="${u.id}">${ic('check', 'sm')}${L3(['Konfirmasi lunas', 'Confirm paid', 'تأكيد'])}</button><button class="btn sm badb" data-act="up-reject" data-id="${u.id}">${L3(['Tolak', 'Reject', 'رفض'])}</button>` : '')).join('')}
    ${x.status === 'pending' && mode === 'traveler' && !pr.some(u => u.state === 'submitted') ? `<button class="btn primary" style="width:100%;justify-content:center;margin-top:8px" data-act="up-pay" data-id="${x.id}">${ic('upload')}${L3(['Unggah bukti transfer', 'Upload transfer proof', 'رفع إثبات التحويل'])} · ${money(x.amount)}</button>` : ''}
    ${x.status === 'pending' && mode === 'traveler' && pr.some(u => u.state === 'submitted') ? `<div class="muted" style="font-size:12.5px;margin-top:6px">${ic('clock', 'sm')} ${L3(['Menunggu verifikasi Travel', 'Awaiting Travel verification', 'بانتظار التحقق'])}</div>` : ''}
    ${x.status === 'pending' && mode === 'travel' && !pr.length ? `<div class="muted" style="font-size:12.5px;margin-top:6px">${L3(['Belum ada bukti bayar dari jamaah', 'No payment proof yet', 'لا إثبات بعد'])}</div>` : ''}</div>`; }).join('') : `<span class="muted">—</span>`; }
function pilgrimTable(b, editable) { const P = ensurePilgrims(b);
  return `<div class="tbl-wrap"><table class="t"><thead><tr><th>#</th>${PILGRIM_F.map(f => `<th>${esc(L3(f[1]))}</th>`).join('')}<th>${t('status')}</th></tr></thead><tbody>${P.map((p, i) => `<tr><td>${i + 1}</td>${PILGRIM_F.map(f => `<td>${esc(f[2] === 'date' && p[f[0]] ? fD(new Date(p[f[0]]).getTime()) : p[f[0]] || '—')}</td>`).join('')}<td>${pilgrimDone(p) ? st('verified') : st('pending')}${editable ? ` <button class="btn sm ghost" data-act="pg-edit" data-b="${b.id}" data-i="${i}">${ic('note', 'sm')}</button>` : ''}</td></tr>`).join('')}</tbody></table></div>`; }
function bookingProgress(b) { const P = ensurePilgrims(b); const need = P.length * 5; const ups = bkUploads(b); const docOk = P.reduce((s, p, i) => s + DOC_KINDS.filter(k => k[0] !== 'visa' && ups.some(u => u.kind === k[0] && u.pax === i && u.state === 'verified')).length, 0);
  return { data: P.filter(pilgrimDone).length + '/' + P.length, docs: docOk + '/' + need, pay: pct(b.paid / b.total * 100, 0), waiting: ups.filter(u => u.state === 'submitted').length }; }

reroute('/p/travel/bookings/:id', p => { const tr = me('travel'); const b = bookingById(p.id); if (!b || b.travel !== tr.id) return { html: `<div class="page">${stateBlock('noperm', { desc: L3(['Booking ini bukan milik Travel Anda.', 'This booking does not belong to your Travel.', 'ليس لك.']) })}</div>` };
  const tv = TRAVELERS.find(x => x.id === b.traveler) || {}; const nx = BK_NEXT[b.state]; const exc = BK_EXC.includes(b.state) ? b.state : null; const pg = bookingProgress(b);
  const hist = AUDIT.filter(a => String(a.resource || '').includes(b.id) || bkUploads(b).some(u => String(a.resource || '').includes(u.id))).slice(0, 12);
  return { html: `<div class="page">${phead({ crumbs: [[L3(WS.travel.label), '/p/travel'], ['Booking', '/p/travel/bookings'], [b.id, '']], title: b.id + ' · ' + esc(tv.name || ''), desc: esc((pkgById(b.pkg) || {}).name || '') + ' · ' + b.pax + ' pax · ' + fD(b.dep), actions: (nx ? `<button class="btn primary" data-act="tb-next" data-id="${b.id}">${ic('check')}${esc(L3(nx[1]))}</button>` : '') + (['awaiting_payment', 'partially_paid'].includes(b.state) ? `<button class="btn" data-act="tb-remind" data-id="${b.id}">${ic('bell')}${L3(['Kirim pengingat bayar', 'Send payment reminder', 'تذكير'])}</button>` : '') + (!exc && !['departed', 'completed'].includes(b.state) ? `<button class="btn badb" data-act="bk-cancel" data-id="${b.id}">${ic('ban')}${L3(['Batalkan', 'Cancel', 'إلغاء'])}</button>` : '') })}
  <section class="panel" style="padding:12px 14px;margin-bottom:14px">${lifeBar(BK_FLOW, exc ? (b.paid ? 'confirmed' : 'awaiting_payment') : b.state, exc)}</section>
  ${kpiRow([{ k: L3(['Data jamaah lengkap', 'Pilgrim data complete', 'البيانات']), v: pg.data, icon: 'users' }, { k: L3(['Dokumen terverifikasi', 'Documents verified', 'المستندات']), v: pg.docs, icon: 'filecheck' }, { k: L3(['Terbayar', 'Paid', 'مدفوع']), v: pg.pay, icon: 'wallet' }, { k: L3(['Menunggu dicek', 'Awaiting review', 'بانتظار المراجعة']), v: fN(pg.waiting), icon: 'clock' }])}
  <div class="grid g2" style="margin-top:14px">${pnl(L3(['Pemesan', 'Booker', 'صاحب الحجز']), `<dl class="dl"><dt>${L3(['Nama', 'Name', 'الاسم'])}</dt><dd>${esc(tv.name || '—')} <span class="mono muted">${esc(b.traveler)}</span></dd><dt>${L3(['Telepon', 'Phone', 'الهاتف'])}</dt><dd class="mono">${esc(tv.phone || '—')}</dd><dt>Email</dt><dd class="mono">${esc(tv.email || '—')}</dd><dt>${L3(['Kota', 'City', 'المدينة'])}</dt><dd>${esc(tv.city || '—')}</dd><dt>${L3(['Sumber', 'Source', 'المصدر'])}</dt><dd>${esc(b.source)}${b.mitra ? ' · ' + esc((MITRA.find(m => m.id === b.mitra) || {}).name) : ''}${b.agen ? ' → ' + esc((AGEN.find(a => a.id === b.agen) || {}).name) : ''}${b.aff ? ' · Affiliate ' + esc((AFFILIATES.find(a => a.id === b.aff) || {}).name) : ''}</dd><dt>Total</dt><dd class="tnum">${money(b.total, true)}</dd><dt>${L3(['Terbayar', 'Paid', 'مدفوع'])}</dt><dd class="tnum">${money(b.paid, true)}</dd><dt>${L3(['Dibuat', 'Created', 'أنشئ'])}</dt><dd>${fDT(b.created)}</dd></dl>`, { icon: 'user' })}
  ${pnl(L3(['Pembayaran & bukti bayar', 'Payments & proofs', 'المدفوعات']), payProofs(b, 'travel'), { icon: 'card' })}</div>
  <div style="margin-top:14px">${pnl(L3(['Data jamaah', 'Pilgrim data', 'بيانات المعتمرين']), pilgrimTable(b, true), { raw: true, icon: 'users' })}</div>
  <div class="grid g12" style="margin-top:14px"><div class="c7">${pnl(L3(['Dokumen', 'Documents', 'المستندات']), docsGrid(b, 'travel'), { icon: 'folder' })}</div><div class="c5">${pnl(L3(['Riwayat', 'History', 'السجل']), hist.length ? `<ul class="tl">${hist.map(a => `<li><span class="dotc ${a.result === 'success' ? 'ok' : 'warn'}"></span><b>${esc(a.action)}</b><div class="muted" style="font-size:12px">${esc(a.actor)} · ${rel(a.ts)}${a.reason ? ' · ' + esc(a.reason) : ''}</div></li>`).join('')}</ul>` : '<span class="muted">—</span>', { icon: 'history' })}</div></div></div>` }; });

/* daftar booking travel: kolom kelengkapan */
reroute('/p/travel/bookings', () => { const tr = me('travel'); const bk = BOOKINGS.filter(b => b.travel === tr.id).sort((a, b) => b.created - a.created);
  return { html: `<div class="page">${pHead('travel', L3(['Booking & Pendaftar', 'Bookings & Registrants', 'الحجوزات']), L3(['Semua pendaftar paket Anda. Buka baris untuk melihat data lengkap jamaah, bukti bayar, dan dokumen.', 'Everyone registered for your packages. Open a row for full pilgrim data, payment proofs and documents.', 'كل المسجلين.']))}<section class="panel">${tbl(['Booking', L3(['Pemesan', 'Booker', 'صاحب الحجز']), L3(['Paket', 'Package', 'الباقة']), 'Pax', L3(['Data', 'Data', 'البيانات']), L3(['Dokumen', 'Docs', 'المستندات']), L3(['Bayar', 'Paid', 'مدفوع']), L3(['Perlu dicek', 'To review', 'للمراجعة']), t('status')], bk.map(b => { const g = bookingProgress(b); return rowLink('/p/travel/bookings/' + b.id, `<td class="mono">${b.id}<div class="muted" style="font-size:11px">${esc(b.source)}</div></td><td>${esc(trvName(b.traveler))}</td><td>${esc((pkgById(b.pkg) || {}).name || '')}</td><td class="r tnum">${b.pax}</td><td class="tnum">${g.data}</td><td class="tnum">${g.docs}</td><td class="tnum">${g.pay}</td><td class="r tnum">${g.waiting ? `<span class="st warn">${g.waiting}</span>` : '—'}</td><td>${st(b.state)}</td>`); }), L3(['Belum ada pendaftar', 'No registrants yet', 'لا مسجلين']))}</section></div>` }; });

/* aplikasi pengguna: booking detail dengan unggah dokumen & bukti bayar */
reroute('/p/traveler/bookings/:id', p => { const u = me('traveler'); const b = bookingById(p.id); if (!b || b.traveler !== u.id) return { html: phone(stateBlock('noperm', { desc: L3(['Booking ini bukan milik Anda.', 'This booking is not yours.', 'ليس لك.']) }), '/bookings') };
  const exc = BK_EXC.includes(b.state) ? b.state : null; const g = bookingProgress(b); const P = ensurePilgrims(b);
  return { html: phone(`<div class="ph-top"><a href="#/p/traveler/bookings" style="color:inherit">${icd('chevL', 'sm')}</a> <b class="mono">${b.id}</b></div><div class="ph-body"><div style="display:flex;justify-content:space-between;align-items:center"><b>${esc((pkgById(b.pkg) || {}).name)}</b>${st(b.state)}</div><div class="muted" style="font-size:12px">${esc(travelById(b.travel).name)} · ${fD(b.dep)} · ${b.pax} pax</div>
  <ul class="tl" style="margin-top:14px">${BK_FLOW.slice(1, 7).map(s => { const i = BK_FLOW.indexOf(s), cur = BK_FLOW.indexOf(exc ? 'awaiting_payment' : b.state); return `<li><span class="dotc ${i < cur ? 'ok' : i === cur ? 'info' : ''}"></span><b style="font-weight:${i === cur ? 700 : 500}">${esc(L3(STATUS[s].slice(2)))}</b></li>`; }).join('')}</ul>
  <div class="eyebrow" style="margin:12px 0 6px">${L3(['Pembayaran', 'Payment', 'الدفع'])} · ${g.pay}</div>${payProofs(b, 'traveler')}
  <div class="eyebrow" style="margin:12px 0 6px">${L3(['Data jamaah', 'Pilgrim data', 'البيانات'])} · ${g.data}</div>${P.map((x, i) => `<button class="docrow" style="width:100%;text-align:start" data-act="pg-edit" data-b="${b.id}" data-i="${i}"><span class="fi">${i + 1}</span><span class="body"><b>${esc(x.name || L3(['Isi data jamaah', 'Fill in pilgrim data', 'أدخل البيانات']))}</b><span>${x.nik ? 'NIK ' + esc(x.nik) : '—'}${x.passport ? ' · ' + esc(x.passport) : ''}</span></span>${pilgrimDone(x) ? st('verified') : st('pending')}</button>`).join('')}
  <div class="eyebrow" style="margin:12px 0 6px">${L3(['Dokumen', 'Documents', 'المستندات'])} · ${g.docs}</div>${docsGrid(b, 'traveler')}
  <a class="btn" style="width:100%;justify-content:center;margin-top:10px" href="#/p/traveler/chat">${ic('msg')}${L3(['Chat dengan Travel', 'Chat with Travel', 'راسل الشركة'])}</a></div>`, '/bookings') }; });

Object.assign(A, {
  'pg-edit': el => { const b = bookingById(el.dataset.b); const i = +el.dataset.i; const p = ensurePilgrims(b)[i];
    modal({ title: L3(['Data jamaah ', 'Pilgrim ', 'معتمر ']) + (i + 1) + ' · ' + b.id, body: fields(PILGRIM_F.map(f => ({ k: f[0], label: L3(f[1]), type: f[2], req: f[3], def: p[f[0]] || '', options: f[0] === 'gender' ? [['', '—'], ['L', L3(['Laki-laki', 'Male', 'ذكر'])], ['P', L3(['Perempuan', 'Female', 'أنثى'])]] : undefined })), 'pg-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="pg-save" data-b="${b.id}" data-i="${i}">${t('save')}</button>` }); },
  'pg-save': el => { const b = bookingById(el.dataset.b); const i = +el.dataset.i; const v = formVals(PILGRIM_F.map(f => ({ k: f[0], req: f[3] })), 'pg-'); if (!v) return; if (v.nik && !/^\d{16}$/.test(v.nik)) { document.getElementById('pg-nik').style.borderColor = 'var(--bad)'; toast('warn', 'NIK', L3(['NIK harus 16 digit', 'NIK must be 16 digits', '16 رقماً'])); return; }
    ensurePilgrims(b)[i] = Object.assign(b.pilgrims[i], v); const ws = wsOf(); const who = ws === 'admin' ? 'Admin Pusat' : me(ws).name; audit(who, 'booking.pilgrim.update', 'Booking/' + b.id + '/pax' + (i + 1), 'success', { source: ws === 'admin' ? 'Control Center' : L3(WS[ws].label) });
    if (ws === 'traveler') partyNotify([ntKey('travel', b.travel)], 'booking', 'info', L3(['Data jamaah diperbarui', 'Pilgrim data updated', 'تحديث البيانات']), b.id + ' · ' + v.name, { travel: '/p/travel/bookings/' + b.id });
    closeOverlays(); toast('ok', L3(['Data jamaah tersimpan', 'Pilgrim data saved', 'حُفظت']), v.name); rerender(); },
  'up-doc': async el => { const b = bookingById(el.dataset.b); const k = el.dataset.k; const i = +el.dataset.i; const f = await pickFile(); if (!f) return; await doUploadDoc(b, k, i, f); },
  'up-pay': async el => { const x = PAYMENTS.find(y => y.id === el.dataset.id); const f = await pickFile(); if (!f) return; await doUploadPay(x, f); },
  'up-verify': el => { const u = UPLOADS.find(x => x.id === el.dataset.id); if (!u) return; u.state = 'verified'; u.reviewedBy = me('travel').name; u.reviewedAt = nowTs(); u.reason = ''; pAudit('travel', 'document.verify', 'Upload/' + u.id, { after: docLabel(u.kind) });
    if (u.kind === 'passport' && u.pax === 0) { const tv = TRAVELERS.find(x => x.id === u.traveler); if (tv) tv.passport = 'verified'; }
    partyNotify([ntKey('traveler', u.traveler)], 'booking', 'ok', docLabel(u.kind) + ' ' + L3(['diterima', 'accepted', 'مقبول']), u.booking, { traveler: '/p/traveler/bookings/' + u.booking }); toast('ok', docLabel(u.kind), L3(['Ditandai valid', 'Marked valid', 'صحيح'])); rerender(); },
  'up-reject': el => { const u = UPLOADS.find(x => x.id === el.dataset.id); if (!u) return; confirmAction({ title: L3(['Tolak ', 'Reject ', 'رفض ']) + docLabel(u.kind), desc: L3(['Jamaah akan diminta mengunggah ulang. Tulis alasan yang jelas.', 'The pilgrim will be asked to re-upload. Give a clear reason.', 'سيُطلب إعادة الرفع.']), tone: 'danger', label: L3(['Tolak', 'Reject', 'رفض']), resource: 'Upload/' + u.id, onOk: r => { u.state = 'rejected'; u.reason = r; u.reviewedAt = nowTs(); pAudit('travel', u.kind === 'payproof' ? 'payment.proof.reject' : 'document.reject', 'Upload/' + u.id, { reason: r });
    if (u.kind === 'passport' && u.pax === 0) { const tv = TRAVELERS.find(x => x.id === u.traveler); if (tv) tv.passport = 'rejected'; }
    partyNotify([ntKey('traveler', u.traveler)], u.kind === 'payproof' ? 'payment' : 'booking', 'bad', docLabel(u.kind) + ' ' + L3(['ditolak — unggah ulang', 'rejected — please re-upload', 'مرفوض']), r, { traveler: '/p/traveler/bookings/' + u.booking }); toast('ok', L3(['Ditolak & jamaah diberi tahu', 'Rejected & pilgrim notified', 'رُفض']), r); rerender(); } }); },
  'pay-confirm': el => { const u = UPLOADS.find(x => x.id === el.dataset.id); const x = u && PAYMENTS.find(y => y.id === u.payment); const b = x && bookingById(x.booking); if (!b) return;
    confirmAction({ title: L3(['Konfirmasi pembayaran ', 'Confirm payment ', 'تأكيد الدفع ']) + x.id, desc: L3(['Pastikan dana ', 'Make sure ', 'تأكد ']) + '<b>' + money(x.amount, true) + '</b>' + L3([' sudah masuk ke rekening. Booking akan diperbarui otomatis.', ' has arrived in the account. The booking updates automatically.', ' وصل.']), label: L3(['Konfirmasi lunas', 'Confirm paid', 'تأكيد']), reason: false, resource: 'Payment/' + x.id, onOk: () => {
      u.state = 'verified'; u.reviewedAt = nowTs(); x.status = 'paid'; x.ts = nowTs(); x.channel = x.channel || 'Transfer manual'; x.proof = u.id; b.paid = Math.min(b.total, b.paid + x.amount); const prev = b.state; b.state = b.paid >= b.total ? 'confirmed' : 'partially_paid';
      if (b.state === 'partially_paid' && !PAYMENTS.some(y => y.booking === b.id && y.status === 'pending')) PAYMENTS.unshift({ id: uid('PAY'), booking: b.id, travel: b.travel, payer: b.traveler, amount: b.total - b.paid, provider: x.provider, channel: 'Transfer manual', ref: (x.ref || 'TRF') + '-2', status: 'pending', ts: nowTs(), recon: 'pending', flow: b.payMode, fee: 0 });
      pAudit('travel', 'payment.proof.confirm', 'Payment/' + x.id, { before: prev, after: b.state }); partyNotify([ntKey('traveler', b.traveler)], 'payment', 'ok', L3(['Pembayaran diterima', 'Payment received', 'تم استلام الدفع']), x.id + ' · ' + money(x.amount), { traveler: '/p/traveler/bookings/' + b.id }); recompute(); toast('ok', L3(['Pembayaran dikonfirmasi', 'Payment confirmed', 'تم التأكيد']), 'Booking → ' + stLbl(b.state)); rerender(); } }); }
});
async function doUploadDoc(b, k, i, f) { const ws = wsOf(); const who = ws === 'admin' ? 'Admin Pusat' : me(ws).name;
  try { toast('info', L3(['Mengunggah…', 'Uploading…', 'جارٍ الرفع…']), f.name); const old = UPLOADS.filter(u => u.booking === b.id && u.kind === k && u.pax === i); const up = await saveUpload(f, { ref: b.id, booking: b.id, traveler: b.traveler, travel: b.travel, kind: k, pax: i, by: who, byWs: ws, state: ws === 'travel' ? 'verified' : 'submitted' }); old.forEach(o => { if (o.state !== 'verified') o.state = 'replaced'; });
    UPLOADS.splice(0, UPLOADS.length, ...UPLOADS.filter(u => u.state !== 'replaced'));
    audit(who, 'document.upload', 'Upload/' + up.id, 'success', { source: ws === 'admin' ? 'Control Center' : L3(WS[ws].label), after: b.id + ' · ' + docLabel(k) });
    if (ws === 'traveler') partyNotify([ntKey('travel', b.travel)], 'booking', 'info', L3(['Dokumen baru: ', 'New document: ', 'مستند جديد: ']) + docLabel(k), b.id + ' · ' + trvName(b.traveler), { travel: '/p/travel/bookings/' + b.id });
    else partyNotify([ntKey('traveler', b.traveler)], 'booking', 'info', docLabel(k) + ' ' + L3(['diunggah Travel', 'uploaded by your Travel', 'رفعته الشركة']), b.id, { traveler: '/p/traveler/bookings/' + b.id });
    if (typeof sbFlush === 'function') await sbFlush(); toast('ok', L3(['Dokumen terunggah', 'Document uploaded', 'تم الرفع']), docLabel(k)); rerender(); return up; }
  catch (e) { toast('bad', L3(['Gagal mengunggah', 'Upload failed', 'فشل الرفع']), String(e.message || e)); } }
async function doUploadPay(x, f) { const b = bookingById(x.booking); const u = me('traveler');
  try { toast('info', L3(['Mengunggah…', 'Uploading…', 'جارٍ الرفع…']), f.name); const up = await saveUpload(f, { ref: b.id, booking: b.id, traveler: b.traveler, travel: b.travel, kind: 'payproof', payment: x.id, by: u.name, byWs: 'traveler' }); x.proof = up.id;
    audit(u.name, 'payment.proof.upload', 'Payment/' + x.id, 'success', { source: 'Aplikasi Pengguna', after: money(x.amount) });
    partyNotify([ntKey('travel', b.travel)], 'payment', 'warn', L3(['Bukti bayar masuk — perlu dicek', 'Payment proof received — please check', 'إثبات دفع جديد']), b.id + ' · ' + money(x.amount) + ' · ' + u.name, { travel: '/p/travel/bookings/' + b.id });
    if (typeof sbFlush === 'function') await sbFlush(); toast('ok', L3(['Bukti bayar terkirim', 'Proof sent', 'أُرسل']), L3(['Travel akan memverifikasi', 'Your Travel will verify it', 'ستتحقق الشركة'])); rerender(); return up; }
  catch (e) { toast('bad', L3(['Gagal mengunggah', 'Upload failed', 'فشل الرفع']), String(e.message || e)); } }
/* unggah paspor dari profil = dokumen jamaah 1 di booking aktif terbaru */
A['u-passport'] = async () => { const u = me('traveler'); const b = BOOKINGS.find(x => x.traveler === u.id && !BK_EXC.includes(x.state)); const f = await pickFile(); if (!f) return;
  if (b) { await doUploadDoc(b, 'passport', 0, f); u.passport = 'submitted'; rerender(); return; }
  try { await saveUpload(f, { ref: u.id, traveler: u.id, kind: 'passport', pax: 0, by: u.name, byWs: 'traveler' }); u.passport = 'submitted'; audit(u.name, 'traveler.passport.upload', 'Traveler/' + u.id, 'success', { source: 'Aplikasi Pengguna' }); toast('ok', L3(['Paspor diunggah', 'Passport uploaded', 'رُفع الجواز']), ''); rerender(); } catch (e) { toast('bad', 'Upload', String(e.message || e)); } };

/* ================= 3) WITHDRAWAL: aksi nyata dua arah ================= */
const WD_FLOW = ['pending', 'approved', 'disbursed'];
const wdWs = w => ({ Travel: 'travel', Vendor: 'vendor', Affiliate: 'affiliate' })[w.partyType];
const wdHist = (w, state, by, reason, extra) => { w.history = w.history || []; w.history.push(Object.assign({ state, by, reason: reason || '', ts: nowTs() }, extra || {})); };
function wdApproval(w) { return APPROVALS.find(a => a.type === 'withdrawal' && (a.wd === w.id || (!a.wd && a.requester === w.party && a.amount === w.amount))); }
function wdSyncApproval(w, v, reason) { const a = wdApproval(w); if (!a) return; const map = { approved: 'approved', disbursed: 'approved', rejected: 'rejected', cancelled: 'rejected', needs_revision: 'needs_revision', hold: 'in_progress', pending: 'waiting' }; const s = map[v]; if (!s || a.status === s) return; a.status = s; a.history = a.history || []; a.history.push({ t: 'Withdrawal → ' + stLbl(v), ts: nowTs(), tone: s === 'approved' ? 'ok' : s === 'rejected' ? 'bad' : 'warn', by: 'Finance', reason }); }
/* dana kembali ke pihak saat ditolak / dibatalkan */
function wdRefund(w) { if (w.refunded) return; w.refunded = true; const ws = wdWs(w); if (ws === 'affiliate') { (w.comms || []).forEach(id => { const c = COMMISSIONS.find(x => x.id === id); if (c && c.state === 'paid') c.state = 'approved'; }); } if (typeof recompute === 'function') recompute(); }
function wdAdminActs(w) { const b = (a, cls, label) => permBtn('finance.withdrawal', label, `data-act="wd-do" data-a="${a}" data-id="${w.id}" data-mut`, 'sm ' + cls);
  return ({ pending: [b('approve', 'primary', t('approve')), b('revise', '', L3(['Kembalikan', 'Return', 'إرجاع'])), b('hold', '', L3(['Tahan', 'Hold', 'تعليق'])), b('reject', 'badb', t('reject'))], hold: [b('release', 'primary', L3(['Lepas tahan', 'Release', 'إلغاء التعليق'])), b('reject', 'badb', t('reject'))], approved: [b('pay', 'primary', L3(['Tandai ditransfer', 'Mark transferred', 'تم التحويل'])), b('unapprove', '', L3(['Batalkan persetujuan', 'Revoke approval', 'إلغاء الموافقة']))] })[w.state] || []; }
function wdTimeline(w) { const H = (w.history && w.history.length) ? w.history : [{ state: 'pending', by: w.party, ts: w.ts }]; return `<ul class="tl">${H.map(h => `<li><span class="dotc ${stTone2(h.state) === 'ok' ? 'ok' : stTone2(h.state) === 'bad' ? 'bad' : 'info'}"></span><b>${esc(stLbl(h.state))}</b><div class="muted" style="font-size:12px">${esc(h.by || '')} · ${fDT(h.ts)}${h.reason ? '<br>“' + esc(h.reason) + '”' : ''}${h.ref ? '<br>Ref ' + esc(h.ref) : ''}</div></li>`).join('')}</ul>`; }
function wdDetail(w, mode) { const proof = UPLOADS.find(u => u.kind === 'wdproof' && u.ref === w.id);
  return `<section class="panel" style="padding:12px 14px;margin-bottom:14px">${lifeBar(WD_FLOW, ['needs_revision', 'hold'].includes(w.state) ? 'pending' : ['rejected', 'cancelled'].includes(w.state) ? 'pending' : w.state, ['needs_revision', 'hold', 'rejected', 'cancelled'].includes(w.state) ? w.state : null)}</section>
  <div class="grid g2">${pnl('Detail', `<dl class="dl"><dt>ID</dt><dd class="mono">${w.id}</dd><dt>${L3(['Pihak', 'Party', 'الطرف'])}</dt><dd>${esc(w.party)} <span class="chip">${w.partyType}</span></dd><dt>${L3(['Jumlah', 'Amount', 'المبلغ'])}</dt><dd class="tnum"><b>${money(w.amount, true)}</b></dd><dt>Basis</dt><dd>${esc(w.basis || '—')}</dd><dt>${L3(['Rekening tujuan', 'Payout account', 'الحساب'])}</dt><dd>${w.bank ? esc(w.bank.name + ' · ' + w.bank.no + ' · a.n. ' + w.bank.holder) : '—'}</dd><dt>${L3(['Catatan', 'Note', 'ملاحظة'])}</dt><dd>${esc(w.note || '—')}</dd><dt>${L3(['Dikirim ulang', 'Resubmitted', 'أُعيد'])}</dt><dd>${fN(w.resubmits || 0)}×</dd><dt>${t('status')}</dt><dd>${st(w.state)}</dd>${w.transferRef ? `<dt>Ref transfer</dt><dd class="mono">${esc(w.transferRef)}</dd>` : ''}</dl>${proof ? upRow(proof) : ''}`, { icon: 'arrowur' })}${pnl(L3(['Riwayat', 'History', 'السجل']), wdTimeline(w), { icon: 'history' })}</div>`; }

/* admin: daftar + detail */
reroute('/finance/withdrawal', () => dirPage({ nav: 'fin_wd', desc: L3(['Penarikan saldo Vendor, Travel (VIA_SEGALOKA), dan Affiliate. Finance dapat menyetujui, mengembalikan untuk revisi, menahan, menolak, lalu menandai sudah ditransfer dengan bukti. Pihak terkait diberi tahu di setiap langkah.', 'Balance withdrawals for Vendors, Travels (VIA_SEGALOKA) and Affiliates. Finance can approve, return for revision, hold, reject, then mark as transferred with proof. The party is notified at each step.', 'السحوبات.']), tableId: 'wd', cfg: { name: 'Withdrawal', search: r => r.id + r.party, rows: () => WITHDRAWALS, route: r => '/finance/withdrawal/' + r.id, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'todo', label: L3(['Perlu tindakan', 'Needs action', 'بحاجة لإجراء']), fn: r => ['pending', 'hold', 'approved'].includes(r.state) }, ...['Vendor', 'Travel', 'Affiliate'].map(s => ({ v: s, label: s, fn: r => r.partyType === s })), { v: 'needs_revision', label: L3(['Dikembalikan', 'Returned', 'مُرجع']), fn: r => r.state === 'needs_revision' }], cols: [{ k: 'id', label: 'ID', render: r => `<a class="mono" href="#/finance/withdrawal/${r.id}"><b>${r.id}</b></a><div class="muted" style="font-size:11.5px">${rel(r.ts)}${r.resubmits ? ' · ' + L3(['kirim ulang ', 'resubmitted ', 'أُعيد ']) + r.resubmits + '×' : ''}</div>` }, { k: 'party', label: L3(['Penerima', 'Recipient', 'المستفيد']), render: r => `${esc(r.party)} <span class="chip" style="height:18px">${r.partyType}</span>` }, { k: 'basis', label: 'Basis' }, { k: 'amount', label: 'Amount', cls: 'r tnum', render: r => money(r.amount, true) }, { k: 'state', label: t('status'), render: r => st(r.state) }, { k: 'act', label: t('action'), cls: 'r', sort: false, render: r => { const L = wdAdminActs(r); return L.length ? `<div class="actions" style="justify-content:flex-end;flex-wrap:nowrap">${L.slice(0, 2).join('')}${L.length > 2 ? `<a class="btn sm ghost" href="#/finance/withdrawal/${r.id}">${ic('more', 'sm')}</a>` : ''}</div>` : '—'; } }] } }));
route('/finance/withdrawal/:id', p => { const w = WITHDRAWALS.find(x => x.id === p.id); if (!w) return { html: `<div class="page">${stateBlock('empty')}</div>` };
  return { html: `<div class="page">${phead({ crumbs: [[t('g_fin'), '/finance'], ['Withdrawal', '/finance/withdrawal'], [w.id, '']], title: 'Withdrawal ' + w.id, desc: esc(w.party) + ' · ' + money(w.amount, true), actions: wdAdminActs(w).join('') })}${wdDetail(w, 'admin')}</div>` }; });
A['wd-approve'] = el => { el.dataset.a = 'approve'; A['wd-do'](el); };
A['wd-do'] = el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); if (!w) return; const a = el.dataset.a; const ws = wdWs(w);
  const cfg = { approve: [t('approve'), 'primary', 'approved', w.amount > 50e6], revise: [L3(['Kembalikan untuk revisi', 'Return for revision', 'إرجاع للمراجعة']), '', 'needs_revision', true], hold: [L3(['Tahan', 'Hold', 'تعليق']), '', 'hold', true], reject: [t('reject'), 'danger', 'rejected', true], release: [L3(['Lepas tahan', 'Release', 'إلغاء التعليق']), 'primary', 'pending', false], unapprove: [L3(['Batalkan persetujuan', 'Revoke approval', 'إلغاء الموافقة']), '', 'pending', true] }[a];
  if (a === 'pay') { modal({ title: L3(['Tandai sudah ditransfer · ', 'Mark as transferred · ', 'تم التحويل · ']) + w.id, body: `<p class="muted" style="margin-top:0">${esc(w.party)} · <b>${money(w.amount, true)}</b>${w.bank ? ' → ' + esc(w.bank.name + ' ' + w.bank.no) : ''}</p>` + fields([{ k: 'ref', label: L3(['No. referensi transfer', 'Transfer reference', 'مرجع التحويل']), req: true }], 'wp-') + `<div class="field"><label for="wp-file">${L3(['Bukti transfer (opsional)', 'Transfer proof (optional)', 'إثبات التحويل'])}</label><input type="file" id="wp-file" accept="image/*,.pdf"></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="wd-pay-go" data-id="${w.id}">${L3(['Simpan', 'Save', 'حفظ'])}</button>` }); return; }
  if (!cfg) return;
  confirmAction({ title: cfg[0] + ' · ' + w.id, desc: esc(w.party) + ' (' + w.partyType + ') · <b>' + money(w.amount, true) + '</b>' + (a === 'revise' ? '<br>' + L3(['Pihak terkait bisa memperbaiki lalu mengirim ulang.', 'The party can fix it and resubmit.', 'يمكن التعديل.']) : a === 'reject' ? '<br>' + L3(['Saldo dikembalikan ke pihak terkait.', 'The balance is returned to the party.', 'يعاد الرصيد.']) : ''), tone: cfg[1] || 'primary', label: cfg[0], reason: cfg[3], resource: 'Withdrawal/' + w.id, onOk: r => { const prev = w.state; w.state = cfg[2]; w.updated = nowTs(); wdHist(w, cfg[2], 'Finance · Admin Pusat', r); if (cfg[2] === 'rejected') wdRefund(w); wdSyncApproval(w, cfg[2], r);
    audit('Admin Pusat', 'withdrawal.' + a, 'Withdrawal/' + w.id, 'success', { before: prev, after: cfg[2], reason: r }); toast('ok', 'Withdrawal ' + w.id + ' → ' + stLbl(cfg[2]), esc(w.party)); rerender(); } }); };
A['wd-pay-go'] = async el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); const v = formVals([{ k: 'ref', req: true }], 'wp-'); if (!v) return; const f = (document.getElementById('wp-file') || {}).files; const file = f && f[0];
  try { if (file) await saveUpload(file, { ref: w.id, kind: 'wdproof', by: 'Finance · Admin Pusat', byWs: 'admin', state: 'verified' }); } catch (e) { toast('bad', 'Upload', String(e.message || e)); return; }
  const prev = w.state; w.state = 'disbursed'; w.transferRef = v.ref; w.disbursedAt = nowTs(); wdHist(w, 'disbursed', 'Finance · Admin Pusat', '', { ref: v.ref }); wdSyncApproval(w, 'disbursed');
  audit('Admin Pusat', 'withdrawal.disburse', 'Withdrawal/' + w.id, 'success', { before: prev, after: 'disbursed', reason: 'Ref ' + v.ref }); closeOverlays(); toast('ok', L3(['Ditandai sudah ditransfer', 'Marked as transferred', 'تم التحويل']), w.id + ' · ' + v.ref); rerender(); };

/* approval center → withdrawal memakai id yang tepat */
const _decideApproval = decideApproval;
decideApproval = function (id, v, reason) { const a = APPROVALS.find(x => x.id === id); if (a && a.type === 'withdrawal') { const w = WITHDRAWALS.find(x => x.id === a.wd) || WITHDRAWALS.find(x => x.party === a.requester && x.state === 'pending'); if (w && ['pending', 'hold'].includes(w.state)) { const to = v === 'approved' ? 'approved' : v === 'rejected' ? 'rejected' : v === 'needs_revision' ? 'needs_revision' : 'hold'; const prev = w.state; w.state = to; wdHist(w, to, 'Finance · Approval Center', reason); if (to === 'rejected') wdRefund(w); audit('Admin Pusat', 'withdrawal.' + to, 'Withdrawal/' + w.id, 'success', { before: prev, after: to, reason }); a.wd = w.id; a.type = 'withdrawal_done'; const r = _decideApproval(id, v, reason); a.type = 'withdrawal'; return r; } } return _decideApproval(id, v, reason); };

/* portal (Travel / Vendor / Affiliate): ajukan, kirim ulang, batalkan, lihat riwayat */
const wdBalance = (ws, x) => ws === 'affiliate' ? COMMISSIONS.filter(c => c.aff === x.id && c.state === 'approved').reduce((s, c) => s + c.amount, 0) : (x.balance || 0);
const WD_FORM = (w, bal) => [{ k: 'amount', label: 'Jumlah (Rp)', type: 'number', req: true, min: 100000, step: 100000, def: w ? w.amount : Math.min(bal, 50000000) }, { k: 'bank', label: L3(['Bank', 'Bank', 'البنك']), req: true, def: w && w.bank ? w.bank.name : 'BSI' }, { k: 'no', label: L3(['No. rekening', 'Account no.', 'رقم الحساب']), req: true, def: w && w.bank ? w.bank.no : '' }, { k: 'holder', label: L3(['Atas nama', 'Account holder', 'صاحب الحساب']), req: true, def: w && w.bank ? w.bank.holder : '' }, { k: 'note', label: L3(['Catatan untuk Finance', 'Note for Finance', 'ملاحظة']), type: 'textarea', def: w ? w.note || '' : '' }];
A['wd-req'] = el => { const ws = el.dataset.ws; const x = me(ws); const bal = wdBalance(ws, x); modal({ title: L3(['Ajukan withdrawal', 'Request withdrawal', 'طلب سحب']), body: `<p class="muted" style="margin-top:0">${L3(['Saldo tersedia', 'Available', 'متاح'])}: <b class="tnum">${money(bal, true)}</b></p>` + fields(WD_FORM(null, bal), 'wr-') + `<div class="auditbox">${ic('shieldc')}<span>${L3(['Finance memeriksa pengajuan: bisa disetujui, dikembalikan untuk diperbaiki, ditahan, atau ditolak. Anda diberi tahu di setiap langkah.', 'Finance reviews the request: it can be approved, returned for fixes, held or rejected. You are notified at each step.', 'تتم المراجعة.'])}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="wd-go" data-ws="${ws}">${L3(['Ajukan', 'Submit', 'إرسال'])}</button>` }); };
A['wd-go'] = el => { const ws = el.dataset.ws; const x = me(ws); const bal = wdBalance(ws, x); const v = formVals(WD_FORM(null, bal).map(f => ({ k: f.k, type: f.type, req: f.req })), 'wr-'); if (!v) return; if (v.amount > bal || v.amount < 100000) { document.getElementById('wr-amount').style.borderColor = 'var(--bad)'; toast('bad', L3(['Jumlah tidak valid / melebihi saldo', 'Invalid amount / exceeds balance', 'غير صالح']), money(bal, true)); return; }
  const pt = { travel: 'Travel', vendor: 'Vendor', affiliate: 'Affiliate' }[ws]; const w = { id: uid('WD'), party: x.name, partyType: pt, ref: x.id, amount: v.amount, bank: { name: v.bank, no: v.no, holder: v.holder }, note: v.note, state: 'pending', basis: ws === 'vendor' ? 'Order selesai' : ws === 'travel' ? 'Saldo settlement' : 'Komisi tervalidasi', ts: nowTs(), resubmits: 0, history: [] }; wdHist(w, 'pending', x.name);
  if (ws === 'affiliate') { let left = v.amount; w.comms = []; COMMISSIONS.filter(c => c.aff === x.id && c.state === 'approved').forEach(c => { if (left > 0) { c.state = 'paid'; left -= c.amount; w.comms.push(c.id); } }); } WITHDRAWALS.unshift(w);
  const a = pApproval({ type: 'withdrawal', wd: w.id, domain: 'Keuangan', title: 'Withdrawal ' + x.name, requester: x.name, reqRef: x.id, reqRoute: '/finance/withdrawal/' + w.id, amount: v.amount, priority: v.amount > 50e6 ? 'p1' : 'p2', risk: v.amount > 200e6 ? 45 : 18, ctx: [['Nominal', v.amount], ['Pihak', pt], ['Rekening', v.bank + ' ' + v.no + ' a.n. ' + v.holder]], source: 'Portal ' + pt });
  recompute(); pAudit(ws, 'withdrawal.request', 'Withdrawal/' + w.id, { after: String(v.amount) }); pNotif('approval', 'info', L3(['Withdrawal baru', 'New withdrawal', 'سحب جديد']), x.name + ' · ' + money(v.amount), '/finance/withdrawal/' + w.id); closeOverlays(); toast('ok', L3(['Withdrawal diajukan', 'Withdrawal requested', 'طُلب السحب']), money(v.amount, true) + ' → Finance'); rerender(); };
A['wd-edit'] = el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); const ws = wdWs(w); const x = me(ws); const bal = wdBalance(ws, x) + (ws === 'affiliate' ? 0 : 0); const last = (w.history || []).slice().reverse().find(h => h.state === 'needs_revision');
  modal({ title: L3(['Perbaiki & kirim lagi · ', 'Fix & resubmit · ', 'تعديل وإعادة · ']) + w.id, body: (last && last.reason ? `<div class="banner warn" style="border-radius:10px;margin-bottom:10px">${ic('alert')}<span><b>${L3(['Catatan Finance', 'Finance note', 'ملاحظة'])}:</b> ${esc(last.reason)}</span></div>` : '') + fields(WD_FORM(w, bal), 'we-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="wd-resubmit" data-id="${w.id}">${ic('send', 'sm')}${L3(['Kirim lagi', 'Resubmit', 'إعادة الإرسال'])}</button>` }); };
A['wd-resubmit'] = el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); const ws = wdWs(w); const x = me(ws); const v = formVals(WD_FORM(w, 0).map(f => ({ k: f.k, type: f.type, req: f.req })), 'we-'); if (!v) return;
  const avail = ws === 'affiliate' ? w.amount : wdBalance(ws, x) + w.amount; if (v.amount > avail || v.amount < 100000) { document.getElementById('we-amount').style.borderColor = 'var(--bad)'; toast('bad', L3(['Jumlah tidak valid / melebihi saldo', 'Invalid amount / exceeds balance', 'غير صالح']), money(avail, true)); return; }
  const prev = w.state; Object.assign(w, { amount: v.amount, bank: { name: v.bank, no: v.no, holder: v.holder }, note: v.note, state: 'pending', resubmits: (w.resubmits || 0) + 1, updated: nowTs() }); wdHist(w, 'pending', x.name, L3(['Dikirim ulang', 'Resubmitted', 'أُعيد الإرسال']));
  const a = wdApproval(w); if (a) { a.status = 'waiting'; a.amount = v.amount; a.fresh = true; a.history = a.history || []; a.history.push({ t: L3(['Dikirim ulang oleh ', 'Resubmitted by ', 'أعاد ']) + x.name, ts: nowTs(), tone: 'info' }); }
  recompute(); pAudit(ws, 'withdrawal.resubmit', 'Withdrawal/' + w.id, { before: prev, after: 'pending' }); pNotif('approval', 'info', L3(['Withdrawal dikirim ulang', 'Withdrawal resubmitted', 'أُعيد الإرسال']), x.name + ' · ' + money(w.amount), '/finance/withdrawal/' + w.id); closeOverlays(); toast('ok', L3(['Dikirim lagi ke Finance', 'Resubmitted to Finance', 'أُعيد']), w.id); rerender(); };
A['wd-cancel'] = el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); const ws = wdWs(w); const x = me(ws); confirmAction({ title: L3(['Batalkan withdrawal · ', 'Cancel withdrawal · ', 'إلغاء السحب · ']) + w.id, desc: money(w.amount, true) + ' — ' + L3(['saldo dikembalikan ke akun Anda.', 'the balance returns to your account.', 'يعاد الرصيد.']), tone: 'danger', label: L3(['Batalkan', 'Cancel', 'إلغاء']), reason: false, resource: 'Withdrawal/' + w.id, onOk: () => { const prev = w.state; w.state = 'cancelled'; wdHist(w, 'cancelled', x.name); wdRefund(w); wdSyncApproval(w, 'cancelled'); pAudit(ws, 'withdrawal.cancel', 'Withdrawal/' + w.id, { before: prev, after: 'cancelled' }); pNotif('approval', 'neu', L3(['Withdrawal dibatalkan pemohon', 'Withdrawal cancelled by requester', 'أُلغي']), x.name + ' · ' + money(w.amount), '/finance/withdrawal/' + w.id); toast('ok', L3(['Withdrawal dibatalkan', 'Withdrawal cancelled', 'أُلغي']), L3(['Saldo dikembalikan', 'Balance returned', 'أعيد الرصيد'])); rerender(); } }); };
A['wd-view'] = el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); drawer({ title: 'Withdrawal ' + w.id, sub: st(w.state), body: wdDetail(w, 'party') }); };
function wdPartyTable(ws, x) { const wd = WITHDRAWALS.filter(w => w.ref === x.id).sort((a, b) => b.ts - a.ts);
  return tbl(['ID', 'Amount', L3(['Rekening', 'Account', 'الحساب']), t('status'), L3(['Waktu', 'Time', 'الوقت']), t('action')], wd.map(w => { const last = (w.history || []).slice(-1)[0]; return `<tr><td class="mono">${w.id}</td><td class="r tnum">${money(w.amount, true)}</td><td>${w.bank ? esc(w.bank.name + ' ' + w.bank.no) : '—'}</td><td>${st(w.state)}${last && last.reason ? `<div class="muted" style="font-size:11.5px;max-width:240px">“${esc(last.reason)}”</div>` : ''}</td><td>${rel(w.ts)}</td><td class="r"><div class="actions" style="justify-content:flex-end;flex-wrap:nowrap"><button class="btn sm ghost" data-act="wd-view" data-id="${w.id}">${ic('eye', 'sm')}</button>${w.state === 'needs_revision' ? `<button class="btn sm primary" data-act="wd-edit" data-id="${w.id}">${ic('note', 'sm')}${L3(['Perbaiki & kirim lagi', 'Fix & resubmit', 'تعديل'])}</button>` : ''}${['pending', 'needs_revision', 'hold'].includes(w.state) ? `<button class="btn sm badb" data-act="wd-cancel" data-id="${w.id}">${L3(['Batalkan', 'Cancel', 'إلغاء'])}</button>` : ''}</div></td></tr>`; }), L3(['Belum ada withdrawal', 'No withdrawals yet', 'لا سحوبات'])); }
reroute('/p/travel/finance', () => { const tr = me('travel'); const via = tr.payMode === 'VIA_SEGALOKA'; const wd = WITHDRAWALS.filter(w => w.ref === tr.id); const pays = PAYMENTS.filter(p => p.travel === tr.id);
  return { html: `<div class="page">${pHead('travel', L3(['Keuangan', 'Finance', 'المالية']), via ? L3(['VIA_SEGALOKA: dana jamaah masuk ke ledger Segaloka lalu di-settle. Tarik saldo lewat withdrawal — Finance bisa menyetujui, mengembalikan untuk diperbaiki, atau menolak.', 'VIA_SEGALOKA: pilgrim funds go to the Segaloka ledger. Withdraw via a request — Finance can approve, return it for fixes, or reject.', 'عبر المنصة.']) : L3(['DIRECT_TO_TRAVEL: dana jamaah langsung ke rekening Anda. Tidak ada saldo di Segaloka.', 'DIRECT_TO_TRAVEL: pilgrim funds go straight to your account. No balance is held by Segaloka.', 'مباشر.']), via ? `<button class="btn primary" data-act="wd-req" data-ws="travel">${ic('arrowur')}${L3(['Tarik saldo', 'Withdraw', 'سحب'])}</button>` : '')}
  ${kpiRow([{ k: 'Payment flow', v: `<span class="chip mono" style="font-size:12px">${tr.payMode}</span>` }, { k: L3(['Saldo tersedia', 'Available balance', 'الرصيد']), v: via ? money(tr.balance) : '—' }, { k: L3(['Pembayaran masuk', 'Payments in', 'المدفوعات']), v: money(pays.filter(p => p.status === 'paid').reduce((s, p) => s + p.amount, 0)) }, { k: L3(['Withdrawal perlu tindakan Anda', 'Withdrawals needing your action', 'بحاجة لإجراء']), v: fN(wd.filter(w => w.state === 'needs_revision').length) }])}
  <div style="margin-top:14px">${pnl('Withdrawal', wdPartyTable('travel', tr), { raw: true, icon: 'arrowur' })}</div><div style="margin-top:14px">${pnl('Payment', tbl(['Payment', 'Booking', 'Amount', t('status')], pays.slice(0, 12).map(x => `<tr><td class="mono">${x.id}</td><td><a class="mono" href="#/p/travel/bookings/${x.booking}">${x.booking}</a></td><td class="r tnum">${money(x.amount, true)}</td><td>${st(x.status)}</td></tr>`)), { raw: true, icon: 'card' })}</div></div>` }; });
reroute('/p/vendor/finance', () => { const v = me('vendor'); const wd = WITHDRAWALS.filter(w => w.ref === v.id); const ok = v.verif === 'verified' && v.status !== 'inactive';
  return { html: `<div class="page">${pHead('vendor', L3(['Keuangan', 'Finance', 'المالية']), L3(['Saldo dari order selesai (dipotong fee 5%). Withdrawal diperiksa Finance: disetujui, dikembalikan untuk diperbaiki, atau ditolak.', 'Balance from completed orders (minus 5% fee). Finance reviews withdrawals: approve, return for fixes, or reject.', 'المالية.']), `<button class="btn primary" data-act="wd-req" data-ws="vendor" ${ok ? '' : `aria-disabled="true" data-tip="${esc(L3(['Vendor harus terverifikasi & aktif', 'Vendor must be verified & active', 'يجب التوثيق']))}"`}>${ic('arrowur')}${L3(['Tarik saldo', 'Withdraw', 'سحب'])}</button>`)}${kpiRow([{ k: L3(['Saldo tersedia', 'Available', 'متاح']), v: money(v.balance) }, { k: L3(['Dalam proses', 'In progress', 'قيد المعالجة']), v: money(wd.filter(w => ['pending', 'approved', 'hold', 'needs_revision'].includes(w.state)).reduce((s, w) => s + w.amount, 0)) }, { k: L3(['Sudah ditransfer', 'Transferred', 'محوّل']), v: money(wd.filter(w => w.state === 'disbursed').reduce((s, w) => s + w.amount, 0)) }, { k: 'Fee', v: '5%' }])}<div style="margin-top:14px">${pnl('Withdrawal', wdPartyTable('vendor', v), { raw: true, icon: 'arrowur' })}</div></div>` }; });
reroute('/p/affiliate/payout', () => { const a = me('affiliate'); const ap = wdBalance('affiliate', a);
  return { html: `<div class="page">${pHead('affiliate', 'Payout', L3(['Komisi yang disetujui dapat dicairkan. Finance bisa menyetujui, mengembalikan untuk diperbaiki, atau menolak.', 'Approved commission can be paid out. Finance can approve, return for fixes, or reject.', 'الصرف.']), `<button class="btn primary" data-act="wd-req" data-ws="affiliate" ${ap > 0 ? '' : `aria-disabled="true" data-tip="${esc(L3(['Belum ada komisi disetujui', 'No approved commission yet', 'لا عمولة']))}"`}>${ic('arrowur')}${L3(['Cairkan', 'Pay out', 'صرف'])} · ${money(ap)}</button>`)}<section class="panel">${wdPartyTable('affiliate', a)}</section></div>` }; });

A['file-dl'] = async el => { const up = UPLOADS.find(u => u.id === el.dataset.id); if (!up) return; try { const dls = await window.claude.use('downloads'); if (!dls) return; const u = await fileURL(up.id); const bin = Uint8Array.from(atob(u.split(',')[1]), c => c.charCodeAt(0)); const ext = /pdf/.test(up.mime) ? 'pdf' : /png/.test(up.mime) ? 'png' : 'jpg'; const base = (up.name || 'file').replace(/\.[^.]+$/, ''); await dls.save({ filename: base + '.' + ext, data: new Blob([bin]) }); } catch (e) { if (e && e.code !== 'declined') toast('warn', L3(['Unduhan tidak tersedia', 'Download unavailable', 'غير متاح']), (e && e.message) || ''); } };
