/* ============ i18n — key: [Indonesia, English, العربية] ============ */
const DICT = {
// groups
g_utama:["Utama","Main","الرئيسية"], g_eko:["Ekosistem","Ecosystem","المنظومة"], g_mp:["Marketplace","Marketplace","السوق"],
g_omni:["Omnichannel","Omnichannel","القنوات الموحدة"], g_ads:["Ads & Promotion","Ads & Promotion","الإعلانات والترويج"],
g_book:["Booking & Operasional","Booking & Operations","الحجز والتشغيل"], g_fin:["Keuangan","Finance","المالية"],
g_saas:["SaaS & Subscription","SaaS & Subscription","SaaS والاشتراكات"], g_plat:["Platform","Platform","المنصة"],
g_comp:["Compliance & Security","Compliance & Security","الامتثال والأمان"], g_ana:["Analytics","Analytics","التحليلات"], g_sys:["System","System","النظام"],
// nav
overview:["Overview","Overview","نظرة عامة"], approval:["Approval Center","Approval Center","مركز الموافقات"],
travel:["Travel","Travel","شركات السفر"], travel_all:["Semua Travel","All Travel","كل شركات السفر"], travel_branch:["Cabang Travel","Travel Branches","فروع شركات السفر"],
travel_legal:["Legalitas & Perizinan","Legality & Licensing","الترخيص والتصاريح"], travel_subs:["Subscription Travel","Travel Subscription","اشتراكات شركات السفر"], travel_web:["Website Travel","Travel Website","موقع شركة السفر"],
vendor:["Vendor","Vendor","الموردون"], vendor_all:["Semua Vendor","All Vendors","كل الموردين"], vendor_cat:["Kategori Vendor","Vendor Categories","فئات الموردين"], vendor_verif:["Verifikasi Vendor","Vendor Verification","توثيق الموردين"], vendor_prod:["Produk & Layanan","Products & Services","المنتجات والخدمات"],
affiliate:["Affiliate","Affiliate","المسوّقون بالعمولة"], aff_all:["Semua Affiliate","All Affiliates","كل المسوّقين"], aff_ref:["Referral","Referral","الإحالات"], aff_com:["Komisi","Commission","العمولات"], aff_perf:["Performance","Performance","الأداء"],
mitra:["Mitra Travel","Travel Partner","شركاء شركة السفر"], agen:["Agen","Agents","الوكلاء"], traveler:["Traveler","Traveler","المسافرون"],
mp_ov:["Overview Marketplace","Marketplace Overview","نظرة على السوق"], mp_pkg:["Paket Travel","Travel Packages","باقات السفر"], mp_vprod:["Produk Vendor","Vendor Products","منتجات الموردين"], segadeals:["SegaDeals","SegaDeals","SegaDeals"], mp_rev:["Ulasan","Reviews","التقييمات"], mp_cat:["Kategori","Categories","الفئات"], mp_mod:["Moderasi Produk","Product Moderation","مراجعة المنتجات"],
om_ov:["Overview","Overview","نظرة عامة"], om_inbox:["Inbox","Inbox","صندوق الوارد"], om_conv:["Percakapan","Conversations","المحادثات"], om_chan:["Channel","Channels","القنوات"],
om_wa:["WhatsApp","WhatsApp","واتساب"], om_tg:["Telegram","Telegram","تيليجرام"], om_app:["Pesan Aplikasi","In-app Messages","رسائل التطبيق"], om_dash:["Pesan Dashboard","Dashboard Messages","رسائل لوحة التحكم"], om_push:["Push & Notifikasi","Push & Notifications","الإشعارات الفورية"], om_ig:["Instagram","Instagram","إنستغرام"], om_fb:["Facebook","Facebook","فيسبوك"], om_email:["Email","Email","البريد الإلكتروني"], om_web:["Web Chat","Web Chat","دردشة الموقع"],
om_contact:["Contacts / Audience","Contacts / Audience","جهات الاتصال / الجمهور"], om_tpl:["Template Pesan","Message Templates","قوالب الرسائل"], om_bc:["Broadcast","Broadcast","البث الجماعي"], om_auto:["Automation","Automation","الأتمتة"], om_route:["Routing & Assignment","Routing & Assignment","التوجيه والإسناد"], om_sla:["SLA & Response","SLA & Response","اتفاقية الخدمة والاستجابة"], om_ana:["Omnichannel Analytics","Omnichannel Analytics","تحليلات القنوات"],
ads_ov:["Overview Ads","Ads Overview","نظرة على الإعلانات"], ads_camp:["Campaign","Campaigns","الحملات"], ads_ads:["Ads","Ads","الإعلانات"], ads_set:["Ad Set / Audience","Ad Set / Audience","المجموعات / الجمهور"], ads_cre:["Creative","Creative","التصاميم الإعلانية"], ads_plc:["Placement / Channel","Placement / Channel","المواضع / القنوات"], ads_bud:["Budget","Budget","الميزانية"], ads_vou:["Voucher & Promo","Voucher & Promo","القسائم والعروض"], ads_trk:["Tracking","Tracking","التتبع"], ads_conv:["Conversion","Conversion","التحويل"], ads_attr:["Attribution","Attribution","الإسناد"], ads_perf:["Ads Performance","Ads Performance","أداء الإعلانات"],
booking:["Booking","Booking","الحجوزات"], manifest:["Manifest","Manifest","كشف الركاب"], roomlist:["Room List","Room List","توزيع الغرف"], pkginfo:["Paket Info","Package Info","معلومات الباقة"], opsdoc:["Dokumen Operasional","Operational Documents","الوثائق التشغيلية"],
fin_ov:["Overview Keuangan","Finance Overview","نظرة مالية"], fin_tx:["Transaksi","Transactions","المعاملات"], fin_pg:["Payment Gateway","Payment Gateway","بوابة الدفع"], fin_set:["Settlement","Settlement","التسوية"], fin_wd:["Withdrawal","Withdrawal","السحب"], fin_dep:["Deposit Travel","Travel Deposit","وديعة شركة السفر"], fin_ref:["Refund","Refund","الاسترداد"], fin_rec:["Reconciliation","Reconciliation","المطابقة"], fin_fee:["Fee & Commission","Fee & Commission","الرسوم والعمولات"],
sub:["Subscription","Subscription","الاشتراكات"], plan:["Plan & Pricing","Plan & Pricing","الخطط والأسعار"], addon:["Add-on","Add-on","الإضافات"], website:["Website Travel","Travel Website","موقع شركة السفر"], crm:["CRM","CRM","إدارة العملاء"],
users:["User Management","User Management","إدارة المستخدمين"], roles:["Role & Permission","Role & Permission","الأدوار والصلاحيات"], notif:["Notification","Notification","الإشعارات"], ai:["Segaloka AI","Segaloka AI","Segaloka AI"],
legal:["Legalitas","Legality","الترخيص"], audit:["Audit Log","Audit Log","سجل التدقيق"], security:["Security","Security","الأمان"], risk:["Risk & Fraud","Risk & Fraud","المخاطر والاحتيال"],
an_exec:["Executive Analytics","Executive Analytics","التحليلات التنفيذية"], an_mp:["Marketplace Analytics","Marketplace Analytics","تحليلات السوق"], an_travel:["Travel Analytics","Travel Analytics","تحليلات شركات السفر"], an_vendor:["Vendor Analytics","Vendor Analytics","تحليلات الموردين"], an_fin:["Finance Analytics","Finance Analytics","التحليلات المالية"], an_omni:["Omnichannel Analytics","Omnichannel Analytics","تحليلات القنوات"], an_ads:["Ads Performance","Ads Performance","أداء الإعلانات"], an_camp:["Campaign Performance","Campaign Performance","أداء الحملات"], an_conv:["Conversion & Attribution","Conversion & Attribution","التحويل والإسناد"], an_growth:["Growth Analytics","Growth Analytics","تحليلات النمو"],
sys_cfg:["Configuration","Configuration","الإعدادات"], sys_brand:["Brand & Appearance","Brand & Appearance","الهوية والمظهر"], sys_lang:["Language & Localization","Language & Localization","اللغة والتوطين"], sys_cur:["Currency","Currency","العملة"], sys_pay:["Payment Configuration","Payment Configuration","إعدادات الدفع"], sys_ncfg:["Notification Configuration","Notification Configuration","إعدادات الإشعارات"], sys_flag:["Feature Flags","Feature Flags","مفاتيح الميزات"], sys_int:["Integration & API","Integration & API","التكامل وواجهات API"], sys_health:["System Health","System Health","صحة النظام"],
iamap:["Peta Arsitektur","Architecture Map","خريطة البنية"],
// shell
control_center:["Control Center","Control Center","مركز التحكم"], search_ph:["Cari Travel, Booking, Transaksi, Campaign…","Search Travel, Booking, Transaction, Campaign…","ابحث عن شركة سفر، حجز، معاملة، حملة…"],
filter_menu:["Filter menu…","Filter menu…","تصفية القائمة…"], collapse:["Ciutkan sidebar","Collapse sidebar","طي الشريط الجانبي"], expand:["Bentangkan sidebar","Expand sidebar","توسيع الشريط الجانبي"],
env_demo:["DEMO · Data simulasi","DEMO · Mock data","عرض · بيانات تجريبية"], theme_light:["Terang","Light","فاتح"], theme_dark:["Gelap","Dark","داكن"], theme_system:["Sistem","System","النظام"],
notifications:["Notifikasi","Notifications","الإشعارات"], mark_all:["Tandai semua dibaca","Mark all read","تعليم الكل كمقروء"], all:["Semua","All","الكل"],
account:["Akun","Account","الحساب"], role_sim:["Simulasi permission (dari backend)","Permission simulation (from backend)","محاكاة الصلاحيات (من الخادم)"], ux_sim:["Pratinjau UX state","UX state preview","معاينة حالات الواجهة"],
normal:["Normal","Normal","عادي"], loading:["Memuat","Loading","تحميل"], empty:["Kosong","Empty","فارغ"], error:["Error","Error","خطأ"], offline:["Offline / reconnect","Offline / reconnecting","غير متصل / إعادة الاتصال"],
signout:["Keluar","Sign out","تسجيل الخروج"], preferences:["Preferensi","Preferences","التفضيلات"], language:["Bahasa","Language","اللغة"], theme:["Tema","Theme","المظهر"],
// common
export:["Export data","Export data","تصدير البيانات"], preview:["Preview data","Preview data","معاينة البيانات"], add_travel:["Tambah travel","Add travel","إضافة شركة سفر"],
search:["Cari","Search","بحث"], filters_more:["Filter lainnya","More filters","مرشحات أخرى"], columns:["Kolom","Columns","الأعمدة"],
f_all:["Semua","All","الكل"], f_active:["Aktif","Active","نشط"], f_review:["Review","Review","قيد المراجعة"], f_inactive:["Nonaktif","Inactive","غير نشط"],
action:["Aksi","Action","إجراء"], status:["Status","Status","الحالة"], view:["Lihat","View","عرض"], open_detail:["Buka detail","Open detail","فتح التفاصيل"],
showing:["Menampilkan","Showing","عرض"], of:["dari","of","من"], rows:["baris","rows","صفوف"], per_page:["per halaman","per page","لكل صفحة"], prev:["Sebelumnya","Previous","السابق"], next:["Berikutnya","Next","التالي"],
selected:["dipilih","selected","محدد"], clear:["Hapus pilihan","Clear","مسح"], cancel:["Batal","Cancel","إلغاء"], confirm:["Konfirmasi","Confirm","تأكيد"], close:["Tutup","Close","إغلاق"], save:["Simpan","Save","حفظ"], back:["Kembali","Back","رجوع"],
approve:["Setujui","Approve","موافقة"], reject:["Tolak","Reject","رفض"], revise:["Minta revisi","Request revision","طلب تعديل"],
reason:["Alasan","Reason","السبب"], reason_req:["Wajib diisi untuk keputusan ini","Required for this decision","مطلوب لهذا القرار"],
audit_note:["Keputusan ini dicatat di Audit Log dengan aktor, waktu, alasan, dan sumber.","This decision is recorded in the Audit Log with actor, time, reason and source.","يُسجَّل هذا القرار في سجل التدقيق مع المنفّذ والوقت والسبب والمصدر."],
no_perm_t:["Anda tidak memiliki akses ke halaman ini","You don't have access to this page","ليست لديك صلاحية لهذه الصفحة"],
no_perm_d:["Backend menolak permission yang dibutuhkan. Membuka URL langsung tidak memberi akses — hubungi admin untuk meminta permission.","The backend denied the required permission. Opening the URL directly does not grant access — ask an admin to request it.","رفض الخادم الصلاحية المطلوبة. فتح الرابط مباشرة لا يمنح الوصول — اطلب الصلاحية من المسؤول."],
no_perm_action:["Tidak ada permission","No permission","لا توجد صلاحية"],
empty_t:["Belum ada data","No data yet","لا توجد بيانات بعد"], empty_d:["Data akan tampil di sini setelah ada aktivitas pada modul ini.","Data will appear here once there is activity in this module.","ستظهر البيانات هنا عند وجود نشاط في هذه الوحدة."],
noresult_t:["Tidak ada hasil","No results","لا توجد نتائج"], noresult_d:["Coba kata kunci lain atau hapus filter.","Try another keyword or clear filters.","جرّب كلمة أخرى أو امسح المرشحات."], reset_filters:["Reset filter","Reset filters","إعادة ضبط المرشحات"],
error_t:["Data gagal dimuat","Data failed to load","تعذر تحميل البيانات"], error_d:["Server mengembalikan error 503 (req_7f2c91). Data terakhir tidak ditampilkan agar tidak menyesatkan.","The server returned 503 (req_7f2c91). Stale data is hidden so it won't mislead.","أعاد الخادم الخطأ 503 (req_7f2c91). تم إخفاء البيانات القديمة لتجنب التضليل."], retry:["Coba lagi","Retry","إعادة المحاولة"],
offline_b:["Koneksi realtime terputus — mencoba menyambung kembali… Aksi yang mengubah data dinonaktifkan sementara.","Realtime connection lost — reconnecting… Actions that change data are paused.","انقطع الاتصال الفوري — جارٍ إعادة الاتصال… الإجراءات المعدِّلة موقوفة مؤقتاً."],
mock_b:["Anda melihat data demonstrasi. Backend belum terhubung — angka, nama, dan transaksi di bawah adalah simulasi untuk presentasi.","You are viewing demonstration data. Backend is not connected — figures, names and transactions are simulated for presentation.","أنت تشاهد بيانات تجريبية. الخادم غير متصل — الأرقام والأسماء والمعاملات محاكاة للعرض."],
live:["Realtime","Realtime","مباشر"], updated:["Diperbarui","Updated","تم التحديث"], just_now:["baru saja","just now","الآن"],
// placeholder
ph_status:["Initial state — belum diimplementasikan","Initial state — not implemented yet","حالة أولية — لم تُنفَّذ بعد"],
ph_desc:["Route dan posisi IA sudah final. Halaman ini menampilkan blueprint: bagian yang direncanakan, entitas data, lifecycle, dan relasi domain.","Route and IA position are final. This page shows the blueprint: planned sections, data entities, lifecycle and domain relations.","المسار وموقعه في البنية نهائيان. تعرض هذه الصفحة المخطط: الأقسام المخططة والكيانات ودورة الحياة والعلاقات."],
planned:["Bagian yang direncanakan","Planned sections","الأقسام المخططة"], entities:["Entitas & field inti","Core entities & fields","الكيانات والحقول الأساسية"], lifecycle:["Lifecycle","Lifecycle","دورة الحياة"], relations:["Terhubung ke","Connected to","مرتبط بـ"], perms:["Permission yang dibutuhkan","Required permissions","الصلاحيات المطلوبة"], states_req:["UX state wajib","Required UX states","حالات الواجهة المطلوبة"],
lvl_hi:["Fidelity tinggi","High fidelity","دقة عالية"], lvl_md:["Fungsional (medium)","Functional (medium)","وظيفي (متوسط)"], lvl_ph:["Placeholder / blueprint","Placeholder / blueprint","مخطط مبدئي"],
// overview
ov_title:["Control Center","Control Center","مركز التحكم"], ov_desc:["Kondisi platform Segaloka hari ini — apa yang perlu ditindaklanjuti, dan bagaimana ekosistem bergerak.","Segaloka platform today — what needs action, and how the ecosystem is moving.","حالة منصة Segaloka اليوم — ما يحتاج إلى إجراء وكيف تتحرك المنظومة."],
snapshot:["Platform Snapshot","Platform Snapshot","لمحة المنصة"], attention:["Perlu Tindakan","Needs Attention","يحتاج إلى إجراء"], ophealth:["Operational Health","Operational Health","الصحة التشغيلية"], mpact:["Marketplace Activity","Marketplace Activity","نشاط السوق"], finsnap:["Financial Snapshot","Financial Snapshot","لمحة مالية"], apq:["Approval Queue","Approval Queue","قائمة الموافقات"], recent:["Recent Activity","Recent Activity","النشاط الأخير"], riskalerts:["Risk / Security Alerts","Risk / Security Alerts","تنبيهات المخاطر والأمان"], omnisnap:["Omnichannel Snapshot","Omnichannel Snapshot","لمحة القنوات"], adssnap:["Ads Snapshot","Ads Snapshot","لمحة الإعلانات"], syshealth:["System Health","System Health","صحة النظام"], quick:["Quick Actions","Quick Actions","إجراءات سريعة"],
gmv:["GMV (30 hari)","GMV (30 days)","إجمالي قيمة المبيعات (30 يوماً)"], revenue:["Revenue platform","Platform revenue","إيرادات المنصة"], bookings:["Booking","Bookings","الحجوزات"], see_all:["Lihat semua","See all","عرض الكل"],
// approval
ap_title:["Approval Center","Approval Center","مركز الموافقات"], ap_desc:["Antrean keputusan lintas domain. Setiap keputusan tercatat dan dapat diaudit.","Cross-domain decision queue. Every decision is recorded and auditable.","قائمة قرارات عبر المجالات. كل قرار مسجَّل وقابل للتدقيق."],
domain:["Domain","Domain","المجال"], reqtype:["Tipe request","Request type","نوع الطلب"], priority:["Prioritas","Priority","الأولوية"], submitted:["Diajukan","Submitted","تاريخ التقديم"], assignee:["Assignee","Assignee","المُسنَد إليه"],
requester:["Pemohon","Requester","مقدّم الطلب"], context:["Konteks request","Request context","سياق الطلب"], supdocs:["Dokumen pendukung","Supporting documents","المستندات الداعمة"], timeline:["Timeline","Timeline","الخط الزمني"], riskind:["Indikator risiko","Risk indicator","مؤشر المخاطر"], notes:["Catatan internal","Internal notes","ملاحظات داخلية"],
// travel
tr_title:["Travel & Legalitas","Travel & Legality","شركات السفر والترخيص"], tr_desc:["Kelola tenant travel, status perizinan, legalitas, subscription, dan cabang dalam satu workspace.","Manage travel tenants, licensing status, legality, subscriptions and branches in one workspace.","إدارة شركات السفر وحالة التراخيص والامتثال والاشتراكات والفروع في مساحة واحدة."],
k_total:["Total Travel","Total Travel","إجمالي شركات السفر"], k_verified:["Legalitas Terverifikasi","Verified Legality","ترخيص موثّق"], k_waiting:["Menunggu Verifikasi","Awaiting Verification","بانتظار التوثيق"], k_branch:["Cabang Aktif","Active Branches","الفروع النشطة"],
c_travel:["Travel","Travel","شركة السفر"], c_license:["Perizinan","Licenses","التصاريح"], c_legal:["Legalitas","Legality","الترخيص"], c_sub:["Subscription","Subscription","الاشتراك"], c_branch:["Cabang","Branches","الفروع"],
tr_search:["Cari nama Travel, Travel ID, atau kota","Search Travel name, Travel ID or city","ابحث باسم الشركة أو المعرّف أو المدينة"],
t_ov:["Overview","Overview","نظرة عامة"], t_id:["Identitas","Identity","الهوية"], t_legal:["Legalitas & Perizinan","Legality & Licensing","الترخيص والتصاريح"], t_branch:["Cabang","Branches","الفروع"], t_sub:["Subscription","Subscription","الاشتراك"], t_web:["Website","Website","الموقع"], t_team:["User / Team","User / Team","المستخدمون / الفريق"], t_mp:["Marketplace","Marketplace","السوق"], t_book:["Booking","Booking","الحجوزات"], t_fin:["Finance","Finance","المالية"], t_act:["Activity / Audit","Activity / Audit","النشاط / التدقيق"],
suspend:["Suspend travel","Suspend travel","تعليق الشركة"], reactivate:["Aktifkan kembali","Reactivate","إعادة التفعيل"], contact_travel:["Hubungi","Contact","تواصل"],
// omni
inbox_t:["Inbox","Inbox","صندوق الوارد"], mine:["Milik saya","Mine","الخاصة بي"], unassigned:["Unassigned","Unassigned","غير مُسنَدة"], type_msg:["Tulis balasan… (Enter untuk kirim, Shift+Enter baris baru)","Write a reply… (Enter to send, Shift+Enter new line)","اكتب رداً… (Enter للإرسال)"],
send:["Kirim","Send","إرسال"], internal_note:["Catatan internal","Internal note","ملاحظة داخلية"], template:["Template","Template","قالب"], assign:["Assign","Assign","إسناد"], resolve:["Resolve","Resolve","حل"],
ctx_profile:["Profil kontak","Contact profile","ملف جهة الاتصال"], ctx_links:["Relasi","Relations","العلاقات"],
// ads
ads_title:["Ads & Promotion","Ads & Promotion","الإعلانات والترويج"], ads_desc:["Iklan di Website & Aplikasi Segaloka — dari campaign hingga booking dan revenue yang teratribusi.","Advertising on the Segaloka Website & App — from campaign to attributed bookings and revenue.","عمليات الإعلان عبر القنوات — من الحملة إلى الحجوزات والإيرادات المنسوبة."],
new_campaign:["Buat campaign","Create campaign","إنشاء حملة"], pause:["Pause","Pause","إيقاف مؤقت"], resume:["Lanjutkan","Resume","استئناف"], submit_review:["Kirim ke review","Submit for review","إرسال للمراجعة"], archive:["Arsipkan","Archive","أرشفة"],
// finance
fin_title:["Overview Keuangan","Finance Overview","نظرة مالية"], fin_desc:["Payment, settlement, withdrawal, refund, dan reconciliation dipisahkan per lifecycle — semua bersumber dari ledger yang sama.","Payment, settlement, withdrawal, refund and reconciliation are separated by lifecycle — all sourced from the same ledger.","الدفع والتسوية والسحب والاسترداد والمطابقة منفصلة حسب دورة الحياة — كلها من دفتر الأستاذ نفسه."]
};
const LANGS = { id:0, en:1, ar:2 };
function t(k){ const r = DICT[k]; if(!r) return k; return r[LANGS[S.lang]] || r[1] || r[0]; }
/* Status labels: key: [tone, icon, id, en, ar] */
const STATUS = {
 active:["ok","check","Aktif","Active","نشط"], verified:["ok","check","Terverifikasi","Verified","موثّق"], published:["ok","check","Published","Published","منشور"], approved:["ok","check","Disetujui","Approved","تمت الموافقة"],
 confirmed:["ok","check","Confirmed","Confirmed","مؤكد"], completed:["ok","check","Completed","Completed","مكتمل"], paid:["ok","check","Paid","Paid","مدفوع"], settled:["ok","check","Settled","Settled","تمت التسوية"], reconciled:["ok","check","Matched","Matched","مطابق"], resolved:["ok","check","Resolved","Resolved","تم الحل"], ready:["ok","check","Ready","Ready","جاهز"], healthy:["ok","check","Normal","Healthy","سليم"], refunded:["neu","undo","Refunded","Refunded","مسترد"], success:["ok","check","Sukses","Success","نجاح"], disbursed:["ok","check","Disbursed","Disbursed","تم الصرف"],
 review:["warn","clock","Review","Review","قيد المراجعة"], under_review:["warn","clock","Under Review","Under Review","قيد المراجعة"], submitted:["warn","clock","Submitted","Submitted","مُقدَّم"], pending:["warn","clock","Pending","Pending","معلق"], waiting:["warn","clock","Menunggu","Waiting","بانتظار"],
 awaiting_payment:["warn","clock","Awaiting Payment","Awaiting Payment","بانتظار الدفع"], partially_paid:["warn","clock","Partially Paid","Partially Paid","مدفوع جزئياً"], grace:["warn","alert","Grace Period","Grace Period","فترة سماح"], needs_revision:["warn","undo","Butuh Revisi","Needs Revision","بحاجة لتعديل"], refund_requested:["warn","undo","Refund Requested","Refund Requested","طلب استرداد"], hold:["warn","pause","On Hold","On Hold","معلّق"], paused:["warn","pause","Paused","Paused","متوقف مؤقتاً"], degraded:["warn","alert","Degraded","Degraded","متدهور"], unmatched:["warn","alert","Unmatched","Unmatched","غير مطابق"], expiring:["warn","alert","Segera Expired","Expiring","قارب على الانتهاء"],
 rejected:["bad","x","Ditolak","Rejected","مرفوض"], failed:["bad","x","Failed","Failed","فشل"], expired:["bad","x","Expired","Expired","منتهي"], suspended:["bad","ban","Suspended","Suspended","موقوف"], critical:["bad","alert","Kritis","Critical","حرج"], mismatch:["bad","alert","Mismatch","Mismatch","عدم تطابق"], cancelled:["neu","ban","Cancelled","Cancelled","ملغى"], down:["bad","x","Down","Down","متوقف"],
 draft:["neu","minus","Draft","Draft","مسودة"], inactive:["neu","minus","Nonaktif","Inactive","غير نشط"], archived:["neu","archive","Archived","Archived","مؤرشف"], unpublished:["neu","minus","Unpublished","Unpublished","غير منشور"], closed:["neu","minus","Closed","Closed","مغلق"], none:["neu","minus","Tidak ada","None","لا يوجد"],
 processing:["info","loader","Processing","Processing","قيد المعالجة"], scheduled:["info","clock","Scheduled","Scheduled","مجدول"], created:["info","plus","Created","Created","تم الإنشاء"], departed:["info","plane","Departed / In Service","Departed / In Service","غادر / قيد الخدمة"], open:["info","circle","Open","Open","مفتوح"], in_progress:["info","loader","Dalam proses","In progress","قيد التنفيذ"], trial:["info","clock","Trial","Trial","تجريبي"]
};
