/* =============================== OMNICHANNEL INBOX =============================== */
const CH = { wa: ['WA', 'WhatsApp'], ig: ['IG', 'Instagram'], fb: ['FB', 'Facebook'], email: ['EM', 'Email'], web: ['WEB', 'Web Chat'] };
const chanBadge = c => `<span class="chan ${c === 'email' ? 'em' : c}" title="${CH[c][1]}" aria-label="${CH[c][1]}">${CH[c][0]}</span>`;
const OMNI = window.OMNI = { active: null, tab: 'all', chan: 'all', status: 'active', q: '', mode: 'reply', showCtx: false,
  list() { return CONVERSATIONS.filter(c => (this.tab === 'all' || (this.tab === 'unassigned' ? !c.assignee : this.tab === 'assigned' ? !!c.assignee : c.sla != null && c.sla < 0)) && (this.chan === 'all' || c.channel === this.chan) && (this.status === 'all' || (this.status === 'active' ? ['open', 'pending'].includes(c.status) : c.status === this.status)) && (!this.q || (c.contact + c.id + c.messages.map(m => m.text).join(' ')).toLowerCase().includes(this.q.toLowerCase()))).sort((a, b) => b.ts - a.ts); },
  onIncoming(c) { if (c.id === this.active) { c.unread = 0; const ch = document.getElementById('chat'); if (ch) { ch.insertAdjacentHTML('beforeend', msgHTML(c.messages[c.messages.length - 1])); ch.scrollTop = ch.scrollHeight; } } else toast('info', L3(['Pesan baru', 'New message', 'رسالة جديدة']) + ' · ' + c.contact, c.messages[c.messages.length - 1].text, '/omni/inbox/' + c.id); this.drawList(c.id); },
  drawList(flashId) { const el = document.getElementById('convlist'); if (!el) return; el.innerHTML = convListHTML(); if (flashId) { const it = el.querySelector(`[data-cid="${flashId}"]`); if (it) it.classList.add('flash'); } }
};
function slaChip(c) { if (c.sla == null) return ''; return c.sla < 0 ? `<span class="st bad">${ic('timer')}SLA +${-c.sla}m</span>` : c.sla < 8 ? `<span class="st warn">${ic('timer')}${c.sla}m</span>` : `<span class="chip">${ic('timer', 'sm')}${c.sla}m</span>`; }
function convListHTML() { if (S.ux === 'loading') return skel(7); if (S.ux === 'error') return stateBlock('error'); const L = S.ux === 'empty' ? [] : OMNI.list(); if (!L.length) return S.ux === 'empty' ? stateBlock('empty', { title: 'Inbox zero', desc: L3(['Semua percakapan sudah ditangani.', 'All conversations handled.', 'تمت معالجة كل المحادثات.']) }) : stateBlock('noresult'); return L.map(c => { const last = c.messages.filter(m => m.dir !== 'sys').slice(-1)[0]; const ag = AGENTS.find(a => a.id === c.assignee); return `<a class="qitem" data-cid="${c.id}" href="#/omni/inbox/${c.id}" aria-current="${OMNI.active === c.id}" style="color:inherit;text-decoration:none">${chanBadge(c.channel)}<span class="body"><span class="t1"><b>${esc(c.contact)}</b><span class="muted" style="font-size:11px">${esc(rel(c.ts))}</span></span><span class="t2">${last.dir === 'out' ? '↩ ' : ''}${esc(last.text)}</span><span class="t3">${st(c.status)}${ag ? `<span class="chip">${ic('user', 'sm')}${esc(ag.name.split(' ')[0])}</span>` : `<span class="st warn">${ic('user')}Unassigned</span>`}${slaChip(c)}${c.campaign ? `<span class="chip">${ic('target', 'sm')}Campaign</span>` : ''}</span></span>${c.unread ? `<span class="nbadge alert" style="margin-top:2px">${c.unread}</span>` : ''}</a>`; }).join(''); }
function msgHTML(m) { if (m.dir === 'sys') return `<div class="msg sys">${ic('zap', 'sm')} ${esc(m.text)} · ${esc(fDT(m.ts))}</div>`; if (m.dir === 'note') return `<div class="msg note"><b>${ic('lock', 'sm')} ${L3(['Catatan internal', 'Internal note', 'ملاحظة داخلية'])} · ${esc(m.by)}</b><div>${esc(m.text)}</div><div class="mt">${esc(fDT(m.ts))} · ${L3(['tidak terlihat oleh kontak', 'not visible to contact', 'غير مرئية للعميل'])}</div></div>`; return `<div class="msg ${m.dir}">${esc(m.text)}<div class="mt">${m.by ? esc(m.by) + ' · ' : ''}${esc(fD(m.ts, { hour: '2-digit', minute: '2-digit' }))}${m.dir === 'out' ? ' · ✓✓' : ''}</div></div>`; }
function convHTML(c) {
  if (!c) return `<div style="margin:auto">${stateBlock('empty', { title: L3(['Pilih percakapan', 'Select a conversation', 'اختر محادثة']), desc: L3(['Percakapan dari WhatsApp, Instagram, Facebook, Email, dan Web Chat terpusat di sini.', 'Conversations from WhatsApp, Instagram, Facebook, Email and Web Chat are centralized here.', 'المحادثات من جميع القنوات مجمعة هنا.']) })}</div>`;
  const ag = AGENTS.find(a => a.id === c.assignee); const canReply = can('omni.reply');
  return `<div class="pane-h" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><button class="btn sm ghost backm" data-act="omni-back">${icd('chevL', 'sm')}</button>${chanBadge(c.channel)}<div style="flex:1;min-width:140px"><b style="font-size:14px">${esc(c.contact)}</b><div class="muted" style="font-size:11.5px"><span class="mono">${c.id}</span> · ${CH[c.channel][1]} · ${c.tags.map(esc).join(', ')}</div></div>
    <select class="select" id="cv-status" aria-label="${t('status')}" ${canReply ? '' : 'disabled'}>${['open', 'pending', 'resolved', 'closed'].map(s => `<option value="${s}" ${c.status === s ? 'selected' : ''}>${L3(STATUS[s].slice(2))}</option>`).join('')}</select>
    <button class="btn sm" data-act="cv-assign" data-id="${c.id}" aria-haspopup="menu">${ic('user', 'sm')}${esc(ag ? ag.name : L3(['Assign agent', 'Assign agent', 'إسناد']))}${ic('chevD', 'sm')}</button>
    ${c.status !== 'resolved' ? permBtn('omni.reply', ic('check', 'sm') + t('resolve'), `data-act="cv-resolve" data-id="${c.id}" data-mut`, 'sm okb') : ''}
    <button class="iconbtn ctx-toggle" data-act="ctx-toggle" aria-label="Context">${ic('info')}</button></div>
  <div class="chat" id="chat" aria-live="polite"><div class="msg sys">${L3(['Percakapan dimulai', 'Conversation started', 'بدأت المحادثة'])} · ${esc(fDT(c.messages[0].ts))} · ${L3(['routing', 'routing', 'التوجيه'])}: ${c.channel === 'wa' ? 'WA → Umrah queue' : 'Default queue'}</div>${c.messages.map(msgHTML).join('')}</div>
  <div class="composer">${canReply ? `<div class="seg" role="tablist" style="margin-bottom:8px"><button data-act="cv-mode" data-v="reply" aria-pressed="${OMNI.mode === 'reply'}">${icd('send', 'sm')}${L3(['Balas', 'Reply', 'رد'])} · ${CH[c.channel][1]}</button><button data-act="cv-mode" data-v="note" aria-pressed="${OMNI.mode === 'note'}">${ic('lock', 'sm')}${t('internal_note')}</button></div><label class="sr" for="cv-text">${t('type_msg')}</label><textarea id="cv-text" placeholder="${esc(OMNI.mode === 'note' ? L3(['Catatan hanya terlihat oleh tim…', 'Note visible to team only…', 'ملاحظة للفريق فقط…']) : t('type_msg'))}" style="${OMNI.mode === 'note' ? 'background:var(--warn-bg);border-color:var(--warn-line)' : ''}"></textarea><div class="cr"><button class="btn sm ghost" data-act="cv-tpl">${ic('filetext', 'sm')}${t('template')}</button><button class="btn sm ghost" data-act="cv-attach">${ic('clip', 'sm')}${L3(['Lampiran', 'Attach', 'إرفاق'])}</button><button class="btn sm ghost" data-act="cv-ai">${ic('sparkles', 'sm')}${L3(['Saran AI', 'AI suggest', 'اقتراح'])}</button><span style="flex:1"></span>${c.channel === 'wa' ? `<span class="muted" style="font-size:11.5px">${L3(['Jendela 24 jam WA: aktif', 'WA 24h window: open', 'نافذة 24 ساعة: مفتوحة'])}</span>` : ''}${permBtn('omni.reply', icd('send', 'sm') + t('send'), `data-act="cv-send" data-id="${c.id}" data-mut`, 'primary sm')}</div>` : `<div class="banner warn" style="border-radius:8px;border:1px solid var(--warn-line)">${ic('lock')}${t('no_perm_action')}: omni.reply</div>`}</div>`;
}
function ctxHTML(c) {
  if (!c) return '';
  const trv = TRAVELERS.find(x => x.id === c.traveler); const bk = c.booking ? bookingById(c.booking) : null; const cp = c.campaign ? campById(c.campaign) : null; const tr = travelById(c.travel); const pays = bk ? PAYMENTS.filter(p => p.booking === bk.id) : [];
  return `<div class="pane-h" style="display:flex;align-items:center"><b style="flex:1">${L3(['Konteks kontak', 'Contact context', 'سياق جهة الاتصال'])}</b><button class="iconbtn ctx-toggle" data-act="ctx-toggle" aria-label="${t('close')}">${ic('x')}</button></div>
  <div class="ctx-sec"><div style="display:flex;gap:10px;align-items:center"><span class="avatar" style="width:40px;height:40px">${esc(initials(c.contact))}</span><div><b>${esc(c.contact)}</b><div class="muted" style="font-size:12px">${trv ? `Traveler · <span class="mono">${trv.id}</span>` : 'Lead · ' + L3(['belum terdaftar', 'not registered', 'غير مسجل'])}</div></div></div>${trv ? `<dl class="dl" style="margin-top:10px;font-size:12.5px"><dt>${L3(['Telepon', 'Phone', 'الهاتف'])}</dt><dd class="mono">${esc(trv.phone)}</dd><dt>Email</dt><dd class="mono" style="font-size:11.5px">${esc(trv.email)}</dd><dt>${L3(['Kota', 'City', 'المدينة'])}</dt><dd>${esc(trv.city)}</dd><dt>${L3(['Paspor', 'Passport', 'الجواز'])}</dt><dd>${st(trv.passport)}</dd></dl>` : `<button class="btn sm" style="margin-top:10px" data-act="lead-convert" data-id="${c.id}">${ic('plus', 'sm')}${L3(['Konversi ke Traveler', 'Convert to Traveler', 'تحويل إلى مسافر'])}</button>`}</div>
  <div class="ctx-sec"><h5>${ic('link', 'sm')}${t('ctx_links')}</h5>
   ${bk ? `<a class="linkcard" href="#/booking/${bk.id}">${ic('calendar')}<span class="body"><b>${bk.id}</b><span>${esc((pkgById(bk.pkg) || {}).name)} · ${bk.pax} pax</span></span>${st(bk.state)}</a>` : ''}
   ${pays.slice(0, 2).map(p => `<a class="linkcard" href="#/finance/payment/${p.id}">${ic('card')}<span class="body"><b>${p.id}</b><span>${money(p.amount)} · ${p.provider} · ${p.channel}</span></span>${st(p.status)}</a>`).join('')}
   ${tr ? `<a class="linkcard" href="#/travel/${tr.id}">${ic('building')}<span class="body"><b>${esc(tr.name)}</b><span class="mono">${tr.id}</span></span></a>` : ''}
   ${bk ? `<a class="linkcard" href="#/marketplace/packages">${ic('package')}<span class="body"><b>${esc((pkgById(bk.pkg) || {}).name)}</b><span>${money((pkgById(bk.pkg) || {}).price)} / pax</span></span></a>` : ''}
   ${cp ? `<a class="linkcard" href="#/ads/campaign/${cp.id}">${ic('target')}<span class="body"><b>${esc(cp.name)}</b><span>${L3(['Sumber lead · atribusi', 'Lead source · attribution', 'مصدر العميل'])}</span></span>${st(cp.state)}</a>` : ''}
   ${!bk && !cp ? `<div class="muted" style="font-size:12.5px">${L3(['Belum terhubung ke Booking/Campaign.', 'Not linked to a Booking/Campaign yet.', 'غير مرتبطة بعد.'])}</div>` : ''}</div>
  <div class="ctx-sec"><h5>${ic('user', 'sm')}${L3(['Agent', 'Agent', 'الوكيل'])}</h5>${AGENTS.map(a => `<div style="display:flex;align-items:center;gap:8px;padding:3px 0;font-size:12.5px"><span style="width:7px;height:7px;border-radius:50%;background:${a.online ? 'var(--ok)' : 'var(--ink-3)'}"></span><span style="flex:1">${esc(a.name)}${a.id === c.assignee ? ' <b>(assigned)</b>' : ''}</span><span class="muted tnum">${a.load} open</span></div>`).join('')}</div>
  <div class="ctx-sec"><h5>${ic('tag', 'sm')}Tags</h5><div style="display:flex;gap:6px;flex-wrap:wrap">${c.tags.map(x => `<span class="chip">${esc(x)}</span>`).join('')}<button class="chip" data-act="cv-tag" data-id="${c.id}" style="border:1px dashed var(--line-strong);background:transparent">${ic('plus', 'sm')}Tag</button></div></div>
  <div class="ctx-sec"><h5>${ic('history', 'sm')}${t('timeline')}</h5><ul class="tl">${[[L3(['Pesan masuk via ', 'Inbound via ', 'وارد عبر ']) + CH[c.channel][1], c.messages[0].ts, 'info'], ...(c.assignee ? [['Routing → ' + (AGENTS.find(a => a.id === c.assignee) || {}).name, c.messages[0].ts + 60e3, 'neu']] : []), ...(bk ? [['Booking ' + bk.id + ' · ' + L3(STATUS[bk.state].slice(2)), bk.created, 'ok']] : []), ...(cp ? [['Klik iklan · ' + cp.name, c.messages[0].ts - 20 * 60e3, 'neu']] : [])].sort((a, b) => b[1] - a[1]).map(h => `<li><span class="dotc ${h[2]}"></span><b style="font-weight:500;font-size:12.5px">${esc(h[0])}</b><div class="m">${esc(fDT(h[1]))}</div></li>`).join('')}</ul></div>`;
}
function inboxPage(p) {
  OMNI.active = p.id || null; const c = CONVERSATIONS.find(x => x.id === OMNI.active); if (c) c.unread = 0;
  const cnt = k => CONVERSATIONS.filter(x => k === 'all' ? true : k === 'unassigned' ? !x.assignee : k === 'assigned' ? !!x.assignee : x.sla != null && x.sla < 0).filter(x => ['open', 'pending'].includes(x.status)).length;
  const html = `<div class="page full"><div class="split3 ${c ? 'show-conv' : ''} ${OMNI.showCtx ? 'showctx' : ''}" id="omni" style="height:100%">
   <div class="pane qlist"><div class="pane-h">${crumbs([[t('g_omni'), '/omni'], [t('om_inbox'), '/omni/inbox']])}<div style="display:flex;align-items:center;gap:8px"><h1 style="margin:0;font-family:var(--font-display);font-size:20px;flex:1">${t('inbox_t')}</h1><span class="live ${S.ux === 'offline' ? 'off' : ''}"><i></i>${S.ux === 'offline' ? 'Reconnecting' : t('live')}</span></div>
    <div class="tabs" role="tablist" style="margin:8px -14px 8px;padding:0 8px">${[['all', t('all')], ['unassigned', t('unassigned')], ['assigned', 'Assigned'], ['sla', 'SLA breach']].map(([k, l]) => `<button class="tab" role="tab" aria-selected="${OMNI.tab === k}" data-act="omni-tab" data-v="${k}">${esc(l)}<span class="n">${cnt(k)}</span></button>`).join('')}</div>
    <label class="input" style="min-width:0;width:100%;flex:none">${ic('search', 'sm')}<input id="omq" type="search" value="${esc(OMNI.q)}" placeholder="${L3(['Cari kontak / pesan', 'Search contact / message', 'ابحث'])}"></label>
    <div style="display:flex;gap:6px;margin-top:8px"><select class="select" id="om-chan" aria-label="Channel" style="flex:1"><option value="all">${L3(['Semua channel', 'All channels', 'كل القنوات'])}</option>${Object.entries(CH).map(([k, v]) => `<option value="${k}" ${OMNI.chan === k ? 'selected' : ''}>${v[1]}</option>`).join('')}</select><select class="select" id="om-status" aria-label="${t('status')}" style="flex:1">${[['active', 'Open + Pending'], ['all', t('all')], ['open', 'Open'], ['pending', 'Pending'], ['resolved', 'Resolved'], ['closed', 'Closed']].map(([k, l]) => `<option value="${k}" ${OMNI.status === k ? 'selected' : ''}>${l}</option>`).join('')}</select></div></div>
    <div id="convlist">${convListHTML()}</div></div>
   <div class="pane conv" id="convpane" style="display:flex;flex-direction:column;overflow:hidden">${convHTML(c)}</div>
   <div class="pane ctxpane" id="ctxpane">${c ? ctxHTML(c) : `<div class="ctx-sec muted">${L3(['Konteks tampil setelah percakapan dipilih.', 'Context appears after selecting a conversation.', 'يظهر السياق بعد الاختيار.'])}</div>`}</div></div></div>`;
  return { html, mount() { const q = document.getElementById('omq'); q.addEventListener('input', () => { OMNI.q = q.value; OMNI.drawList(); }); document.getElementById('om-chan').addEventListener('change', e => { OMNI.chan = e.target.value; OMNI.drawList(); }); document.getElementById('om-status').addEventListener('change', e => { OMNI.status = e.target.value; OMNI.drawList(); }); bindComposer(); const ch = document.getElementById('chat'); if (ch) ch.scrollTop = ch.scrollHeight; } };
}
function bindComposer() { const ta = document.getElementById('cv-text'); if (ta) ta.addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMsg(OMNI.active); } }); const s = document.getElementById('cv-status'); if (s) s.addEventListener('change', () => { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const prev = c.status; c.status = s.value; c.messages.push({ dir: 'sys', text: 'Status: ' + prev + ' → ' + s.value + ' · Admin Pusat', ts: nowTs() }); audit('Admin Pusat', 'conversation.status', 'Conversation/' + c.id, 'success', { before: prev, after: s.value }); redrawConv(); OMNI.drawList(); toast('ok', 'Status → ' + L3(STATUS[s.value].slice(2)), c.id); }); }
function redrawConv() { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const p = document.getElementById('convpane'); if (p) { p.innerHTML = convHTML(c); bindComposer(); const ch = document.getElementById('chat'); if (ch) ch.scrollTop = ch.scrollHeight; } const x = document.getElementById('ctxpane'); if (x && c) x.innerHTML = ctxHTML(c); }
function sendMsg(id) { if (S.ux === 'offline') { toast('warn', L3(['Pesan tertahan', 'Message queued', 'الرسالة في الانتظار']), t('offline_b')); return; } const ta = document.getElementById('cv-text'); const v = ta.value.trim(); if (!v) { ta.focus(); return; } const c = CONVERSATIONS.find(x => x.id === id); const m = { dir: OMNI.mode === 'note' ? 'note' : 'out', text: v, ts: nowTs(), by: 'Admin Pusat' }; c.messages.push(m); c.ts = nowTs(); if (m.dir === 'out' && c.status === 'open') c.status = 'pending'; ta.value = ''; const ch = document.getElementById('chat'); ch.insertAdjacentHTML('beforeend', msgHTML(m)); ch.scrollTop = ch.scrollHeight; OMNI.drawList(); const s = document.getElementById('cv-status'); if (s) s.value = c.status; ta.focus(); }
route('/omni/inbox', inboxPage); route('/omni/inbox/:id', inboxPage);
const TEMPLATES = [['Salam pembuka', 'Assalamualaikum Bapak/Ibu {nama}, terima kasih telah menghubungi kami. Ada yang bisa kami bantu terkait perjalanan ibadah Anda?'], ['Info pembayaran VA', 'Pembayaran dapat dilakukan melalui Virtual Account yang tertera di invoice. Status akan otomatis diperbarui setelah bank mengonfirmasi (±5 menit).'], ['Persyaratan paspor', 'Mohon kirimkan foto paspor (halaman identitas) dengan masa berlaku minimal 8 bulan dari tanggal keberangkatan.'], ['Status refund', 'Permohonan refund Anda sedang diproses tim Finance. Estimasi 7–14 hari kerja sejak disetujui.']];

/* =============================== ADS OVERVIEW =============================== */
const campRoas = c => c.spent ? c.revenue / c.spent : 0;
PAGES.adsOverview = () => {
  const L = CAMPAIGNS.filter(c => ['active', 'paused', 'completed'].includes(c.state)); const sum = k => L.reduce((s, c) => s + c[k], 0);
  const spend = sum('spent'), impr = sum('impr'), reach = sum('reach'), clicks = sum('clicks'), leads = sum('leads'), bks = sum('bookings'), rev = sum('revenue');
  const byCh = AD_CHANNELS.map(ch => { const cs = L.filter(c => c.channels.includes(ch)); const f = k => cs.reduce((s, c) => s + c[k] / c.channels.length, 0); return { ch, spend: f('spent'), impr: f('impr'), clicks: f('clicks'), leads: f('leads'), bookings: f('bookings'), revenue: f('revenue') }; }).filter(x => x.spend > 0 || x.ch === 'Marketplace Placement');
  const convs = CONVERSATIONS.filter(c => c.campaign).length * 41;
  const tb = defTable('camps', { name: 'Campaign', placeholder: L3(['Cari campaign / ID', 'Search campaign / ID', 'ابحث']), search: r => r.name + ' ' + r.id, rows: () => CAMPAIGNS, route: r => '/ads/campaign/' + r.id,
    filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...['active', 'review', 'scheduled', 'paused', 'draft', 'completed', 'archived'].map(s => ({ v: s, label: L3(STATUS[s].slice(2)), fn: r => r.state === s }))],
    cols: [{ k: 'name', label: 'Campaign', render: r => `<b>${esc(r.name)}</b><div class="muted" style="font-size:11.5px"><span class="mono">${r.id}</span> · ${esc(r.owner ? travelById(r.owner).name : 'Segaloka (platform)')}</div>` }, { k: 'objective', label: 'Objective', render: r => `<span class="chip">${esc(L3(OBJECTIVES[r.objective]))}</span>` }, { k: 'state', label: t('status'), render: r => st(r.state) }, { k: 'spent', label: 'Spend / Budget', render: r => `<div style="min-width:120px"><div class="tnum" style="font-size:12px">${money(r.spent)} / ${money(r.budget)}</div><div class="meter ${r.spent / r.budget > .85 ? 'warn' : ''}"><i style="width:${r.spent / r.budget * 100}%"></i></div></div>` }, { k: 'clicks', label: 'CTR', cls: 'r tnum', render: r => r.impr ? pct(r.clicks / r.impr * 100, 2) : '—', sv: r => r.impr ? r.clicks / r.impr : 0 }, { k: 'leads', label: 'Leads', cls: 'r tnum', render: r => fN(r.leads) }, { k: 'bookings', label: 'Booking', cls: 'r tnum', render: r => fN(r.bookings) }, { k: 'revenue', label: 'Revenue', cls: 'r tnum', render: r => money(r.revenue) }, { k: 'roas', label: 'ROAS', cls: 'r tnum', render: r => r.spent ? `<b style="color:var(--${campRoas(r) >= 5 ? 'ok' : campRoas(r) >= 2 ? 'ink' : 'bad'})">${fN(campRoas(r), { maximumFractionDigits: 1 })}×</b>` : '—', sv: campRoas }],
    card: r => `<div style="display:flex;justify-content:space-between;gap:8px"><b>${esc(r.name)}</b>${st(r.state)}</div><div class="row"><span class="tnum" style="font-size:12px">${money(r.spent)} / ${money(r.budget)}</span><span class="tnum" style="font-size:12px">${fN(r.leads)} leads · ${fN(r.bookings)} booking</span></div>` });
  const html = `<div class="page">${phead({ crumbs: [[t('g_ads'), '/ads'], [t('ads_ov'), '/ads']], title: t('ads_title'), desc: t('ads_desc'), actions: `${periodSel()}<button class="btn" data-act="export" data-what="Ads">${ic('download')}Export</button>${permBtn('ads.create', ic('plus') + t('new_campaign'), 'data-act="wizard" data-mut', 'primary')}` })}
  ${mockBanner()}
  ${gate(`<div class="kpis" style="grid-template-columns:repeat(5,minmax(0,1fr))">${[['Spend', money(spend), delta(12.1, true)], ['Impressions', fC(impr), delta(18.4)], ['Reach', fC(reach), delta(9.2)], ['Clicks', fC(clicks), delta(7.7)], ['CTR', pct(clicks / impr * 100, 2), delta(-0.4)]].map(k => `<div class="kpi"><div class="k">${k[0]}</div><div class="v">${k[1]}</div><div class="d">${k[2]}</div></div>`).join('')}</div><div class="kpis" style="grid-template-columns:repeat(5,minmax(0,1fr));margin-top:-1px;border-top-left-radius:0;border-top-right-radius:0">${[['Leads', fN(leads), delta(14.2)], ['Booking', fN(bks), delta(11.0)], ['Conversion (lead→booking)', pct(bks / leads * 100), delta(-1.2)], ['Revenue ' + L3(['teratribusi', 'attributed', 'منسوبة']), money(rev), delta(15.8)], ['ROAS', fN(rev / spend, { maximumFractionDigits: 1 }) + '×', delta(3.3)]].map(k => `<div class="kpi"><div class="k">${k[0]}</div><div class="v">${k[1]}</div><div class="d">${k[2]}</div></div>`).join('')}</div>`, 4)}
  <div class="grid g12" style="margin-top:14px">
   <div class="c5">${pnl(L3(['Funnel end-to-end', 'End-to-end funnel', 'القمع الكامل']), gate(`${hbars([['Impressions', impr], ['Clicks', clicks], ['Leads', leads], [L3(['Percakapan', 'Conversations', 'محادثات']), convs], ['Booking', bks], [L3(['Booking terbayar', 'Paid bookings', 'حجوزات مدفوعة']), Math.round(bks * .78)]], fC)}<p class="muted" style="font-size:12px;margin:10px 0 0">Campaign → Lead → Conversation (Omnichannel) → Booking → Payment → Revenue. ${L3(['Skala per tahap berbeda — lihat angka.', 'Stages differ in scale — read the values.', 'المقاييس مختلفة.'])}</p>`), { icon: 'funnel' })}</div>
   <div class="c7">${pnl(L3(['Spend harian', 'Daily spend', 'الإنفاق اليومي']), gate(areaChart(ser(), { key: 'spend', fmt: v => money(v), h: 150, label: 'Spend' }) + `<div class="eyebrow" style="margin:10px 0 4px">Leads / ${L3(['hari', 'day', 'يوم'])}</div>` + barChart(ser(), { key: 'leads', fmt: v => fN(Math.round(v)), h: 110, label: 'Leads' })), { icon: 'trend', small: L3(['dua grafik, satu skala masing-masing', 'two charts, one scale each', 'مخططان منفصلان']) })}</div>
  </div>
  <div style="margin-top:14px">${pnl('Channel performance', gate(`<div class="tbl-wrap"><table class="t"><thead><tr><th>Placement / Channel</th><th class="r">Spend</th><th class="r">Impr.</th><th class="r">Clicks</th><th class="r">CTR</th><th class="r">Leads</th><th class="r">Booking</th><th class="r">Revenue</th><th class="r">ROAS</th></tr></thead><tbody>${byCh.map(x => `<tr><td><b>${esc(x.ch)}</b></td><td class="r tnum">${money(x.spend)}</td><td class="r tnum">${fC(x.impr)}</td><td class="r tnum">${fC(x.clicks)}</td><td class="r tnum">${x.impr ? pct(x.clicks / x.impr * 100, 2) : '—'}</td><td class="r tnum">${fN(Math.round(x.leads))}</td><td class="r tnum">${fN(Math.round(x.bookings))}</td><td class="r tnum">${money(x.revenue)}</td><td class="r tnum"><b>${x.spend ? fN(x.revenue / x.spend, { maximumFractionDigits: 1 }) + '×' : '—'}</b></td></tr>`).join('')}</tbody></table></div>`), { raw: true, icon: 'grid', right: `<a class="btn sm ghost" href="#/ads/placement">${icd('chevR', 'sm')}</a>` })}</div>
  <div class="section-title"><h2>Campaign</h2><span class="rule"></span><span class="muted" style="font-size:12px">Draft → Review → Scheduled → Active → Paused → Completed → Archived</span></div>
  <section class="panel">${tb}</section></div>`;
  return { html, mount() { if (location.hash.includes('?new')) setTimeout(openWizard, 60); } };
};
route('/ads', PAGES.adsOverview);

/* ---------- Campaign creation wizard ---------- */
const WZ_STEPS = ['objective', 'audience', 'creative', 'placement', 'budget', 'schedule', 'review'];
let WZ = null;
function openWizard() { WZ = { step: 0, name: 'Umrah Awal Tahun 1448 — Leads', objective: 'leads', owner: TRAVELS[0].id, pkg: (PACKAGES.find(p => p.travel === TRAVELS[0].id) || PACKAGES[0]).id, audience: 'Jamaah 30–55 th · Jabodetabek', lookalike: true, creatives: [0, 1], placement: ['Meta Ads', 'WhatsApp Click-to-Chat'], budget: 60e6, daily: 2e6, start: '2026-10-01', end: '2026-10-30', landing: 'wa' }; drawWizard(); }
function drawWizard() {
  const s = WZ_STEPS[WZ.step]; const lbl = { objective: 'Objective', audience: 'Audience', creative: 'Creative', placement: 'Placement / Channel', budget: 'Budget', schedule: 'Schedule', review: 'Review' };
  let body = '';
  if (s === 'objective') body = `<div class="field"><label for="wz-name">${L3(['Nama campaign', 'Campaign name', 'اسم الحملة'])}</label><input type="text" id="wz-name" value="${esc(WZ.name)}"></div><div class="grid g2" style="gap:10px"><div class="field"><label for="wz-owner">${L3(['Pemilik (Travel)', 'Owner (Travel)', 'المالك'])}</label><select id="wz-owner">${TRAVELS.filter(x => x.op === 'active').slice(0, 12).map(x => `<option value="${x.id}" ${WZ.owner === x.id ? 'selected' : ''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label for="wz-pkg">${L3(['Paket Marketplace (landing)', 'Marketplace package (landing)', 'باقة الهبوط'])}</label><select id="wz-pkg">${PACKAGES.filter(p => p.travel === WZ.owner).map(p => `<option value="${p.id}" ${WZ.pkg === p.id ? 'selected' : ''}>${esc(p.name)} · ${L3(STATUS[p.state].slice(2))}</option>`).join('') || '<option>—</option>'}</select></div></div><div class="optgrid" role="radiogroup" aria-label="Objective">${Object.entries(OBJECTIVES).map(([k, v]) => `<button class="opt" role="radio" aria-checked="${WZ.objective === k}" data-act="wz-set" data-f="objective" data-v="${k}">${ic({ leads: 'users', booking: 'calendar', traffic: 'arrowur', awareness: 'megaphone' }[k])}<span><b>${esc(L3(v))}</b><span>${{ leads: L3(['Kumpulkan kontak → Omnichannel', 'Collect contacts → Omnichannel', 'جمع جهات الاتصال']), booking: L3(['Optimasi ke booking terbayar', 'Optimize for paid bookings', 'تحسين للحجوزات']), traffic: L3(['Kunjungan ke halaman paket', 'Visits to package page', 'زيارات']), awareness: L3(['Jangkauan & frekuensi', 'Reach & frequency', 'الوصول']) }[k]}</span></span></button>`).join('')}</div>`;
  if (s === 'audience') body = `<div class="field"><label for="wz-aud">${L3(['Segmen audience', 'Audience segment', 'شريحة الجمهور'])}</label><select id="wz-aud">${['Jamaah 30–55 th · Jabodetabek', 'Komunitas kajian · Sumatera', 'Retargeting pengunjung paket 30 hari', 'Keluarga muda · Jawa Timur', 'Lookalike booking 2025 (1%)'].map(a => `<option ${WZ.audience === a ? 'selected' : ''}>${a}</option>`).join('')}</select><span class="hint">${L3(['Sumber: Contacts / Audience (Omnichannel) + event booking. Data pribadi tidak dikirim mentah ke platform iklan.', 'Source: Contacts / Audience (Omnichannel) + booking events. Personal data is not sent raw to ad platforms.', 'المصدر: جهات الاتصال وأحداث الحجز.'])}</span></div><label style="display:flex;gap:8px;font-size:13px"><input type="checkbox" id="wz-lal" ${WZ.lookalike ? 'checked' : ''}> ${L3(['Perluas dengan lookalike', 'Expand with lookalike', 'توسيع بالمشابهين'])}</label><div class="grid g3" style="margin-top:14px">${[['Est. reach', '420 rb – 610 rb'], [L3(['Kota', 'Cities', 'المدن']), '6'], [L3(['Ukuran seed', 'Seed size', 'حجم البذرة']), '12.480']].map(k => `<div class="kpi" style="border:1px solid var(--line);border-radius:10px"><div class="k">${k[0]}</div><div class="v" style="font-size:18px">${k[1]}</div></div>`).join('')}</div>`;
  if (s === 'creative') body = `<p class="muted" style="margin-top:0">${L3(['Pilih creative dari library. Klaim sensitif ("pasti berangkat", "termurah") akan ditandai saat review.', 'Pick creatives from the library. Sensitive claims ("guaranteed departure", "cheapest") are flagged at review.', 'اختر التصاميم.'])}</p><div class="grid g3" style="gap:10px">${['Kaaba skyline · 1080×1350', 'Testimoni jamaah · video 15s', 'Carousel itinerary 9 hari', 'Promo voucher UMRAH1448', 'Story 9:16 · countdown', 'Brosur PDF'].map((n, i) => `<button class="opt" style="flex-direction:column;padding:8px" role="checkbox" aria-checked="${WZ.creatives.includes(i)}" data-act="wz-toggle" data-f="creatives" data-v="${i}"><div style="width:100%;aspect-ratio:4/3;max-width:100%;border-radius:7px;background:linear-gradient(${30 + i * 50}deg,${['#1f3b2f', '#2b3e72', '#5a3a22', '#3d2d62', '#194a55', '#5d2a2a'][i]},${['#c9a45a', '#6f8cff', '#e0a36a', '#b78cf0', '#6fd0c4', '#f09a8a'][i]});display:grid;place-items:center;color:#fff;font-family:var(--font-display);font-weight:650;font-size:13px">${i === 1 ? '▶' : 'Umrah 1448'}</div><b style="font-size:12px">${n}</b></button>`).join('')}</div>`;
  if (s === 'placement') body = `<div class="optgrid">${AD_CHANNELS.map(ch => `<button class="opt" role="checkbox" aria-checked="${WZ.placement.includes(ch)}" data-act="wz-toggle" data-f="placement" data-v="${esc(ch)}">${ic(ch.includes('WhatsApp') ? 'msg' : ch.includes('Marketplace') ? 'bag' : ch === 'Email' ? 'mail' : 'megaphone')}<span><b>${esc(ch)}</b><span>${ch.includes('WhatsApp') ? L3(['Landing ke Inbox Omnichannel', 'Lands in Omnichannel Inbox', 'يهبط في صندوق الوارد']) : ch.includes('Marketplace') ? L3(['Slot sponsor di hasil pencarian Marketplace', 'Sponsored slot in Marketplace search', 'موضع مدعوم']) : L3(['Integrasi platform iklan eksternal', 'External ad platform integration', 'منصة خارجية'])}</span></span></button>`).join('')}</div><div class="field" style="margin-top:12px"><label for="wz-land">Landing destination</label><select id="wz-land"><option value="wa" ${WZ.landing === 'wa' ? 'selected' : ''}>WhatsApp → Inbox (routing: Umrah queue)</option><option value="pkg" ${WZ.landing === 'pkg' ? 'selected' : ''}>${L3(['Halaman paket Marketplace', 'Marketplace package page', 'صفحة الباقة'])}</option><option value="web" ${WZ.landing === 'web' ? 'selected' : ''}>Website Travel</option></select></div>`;
  if (s === 'budget') body = `<div class="grid g2" style="gap:10px"><div class="field"><label for="wz-bud">Total budget (Rp)</label><input type="number" id="wz-bud" value="${WZ.budget}" step="1000000" min="1000000"></div><div class="field"><label for="wz-day">Daily cap (Rp)</label><input type="number" id="wz-day" value="${WZ.daily}" step="100000"></div></div><div class="auditbox">${ic('shieldc')}<span>${L3(['Budget di atas Rp 100 jt membutuhkan approval Finance. Spend ditagihkan ke saldo iklan tenant; tidak memotong settlement booking.', 'Budgets above Rp 100M require Finance approval. Spend is billed to the tenant ad balance; it does not deduct booking settlements.', 'الميزانيات الكبيرة تتطلب موافقة.'])}</span></div>`;
  if (s === 'schedule') body = `<div class="grid g2" style="gap:10px"><div class="field"><label for="wz-start">${L3(['Mulai', 'Start', 'البداية'])}</label><input type="date" id="wz-start" value="${WZ.start}"></div><div class="field"><label for="wz-end">${L3(['Selesai', 'End', 'النهاية'])}</label><input type="date" id="wz-end" value="${WZ.end}"></div></div><p class="muted" style="font-size:12.5px">${L3(['Setelah Review disetujui, campaign berstatus Scheduled dan otomatis Active pada tanggal mulai.', 'Once review passes, the campaign becomes Scheduled and auto-activates on start date.', 'بعد الموافقة تصبح مجدولة.'])}</p>`;
  if (s === 'review') { const pk = pkgById(WZ.pkg); body = `<dl class="dl"><dt>Campaign</dt><dd><b>${esc(WZ.name)}</b></dd><dt>Owner</dt><dd>${esc(travelById(WZ.owner).name)}</dd><dt>Objective</dt><dd>${esc(L3(OBJECTIVES[WZ.objective]))}</dd><dt>Landing</dt><dd>${pk ? esc(pk.name) : '—'} · ${WZ.landing}</dd><dt>Audience</dt><dd>${esc(WZ.audience)}${WZ.lookalike ? ' + lookalike' : ''}</dd><dt>Creative</dt><dd>${WZ.creatives.length} item</dd><dt>Placement</dt><dd>${WZ.placement.map(p => `<span class="chip">${esc(p)}</span>`).join(' ')}</dd><dt>Budget</dt><dd class="tnum">${money(WZ.budget, true)} · cap ${money(WZ.daily, true)}/${L3(['hari', 'day', 'يوم'])}</dd><dt>Schedule</dt><dd>${WZ.start} → ${WZ.end}</dd><dt>Attribution</dt><dd>Last non-direct click · 7d click / 1d view</dd></dl>${!WZ.placement.length || !WZ.creatives.length ? `<div class="banner bad" style="border-radius:8px;margin-top:12px">${ic('alert')}${L3(['Pilih minimal 1 creative dan 1 placement.', 'Select at least 1 creative and 1 placement.', 'اختر تصميماً وموضعاً.'])}</div>` : ''}`; }
  modal({ title: t('new_campaign'), wide: true, body: `<div class="wiz" style="margin:-16px -18px"><nav class="wiz-steps" aria-label="Steps">${WZ_STEPS.map((k, i) => `<button data-act="wz-go" data-v="${i}" class="${i < WZ.step ? 'done' : ''}" ${i === WZ.step ? 'aria-current="step"' : ''}><span class="n">${i < WZ.step ? '✓' : i + 1}</span>${lbl[k]}</button>`).join('')}</nav><div style="padding:18px" id="wzbody"><div class="eyebrow" style="margin-bottom:10px">${L3(['Langkah', 'Step', 'الخطوة'])} ${WZ.step + 1} / ${WZ_STEPS.length} · ${lbl[s]}</div>${body}</div></div>`, foot: `<button class="btn ghost" data-act="wz-draft">${L3(['Simpan sebagai Draft', 'Save as Draft', 'حفظ كمسودة'])}</button><span style="flex:1"></span>${WZ.step ? `<button class="btn" data-act="wz-go" data-v="${WZ.step - 1}">${icd('chevL', 'sm')}${t('back')}</button>` : ''}${s === 'review' ? `<button class="btn primary" data-act="wz-submit" ${!WZ.placement.length || !WZ.creatives.length ? 'disabled' : ''}>${t('submit_review')}</button>` : `<button class="btn primary" data-act="wz-go" data-v="${WZ.step + 1}">${t('next')}${icd('chevR', 'sm')}</button>`}` });
}
function wzCollect() { const g = id => document.getElementById(id); if (g('wz-name')) WZ.name = g('wz-name').value; if (g('wz-owner')) { if (WZ.owner !== g('wz-owner').value) { WZ.owner = g('wz-owner').value; const p = PACKAGES.find(p => p.travel === WZ.owner); WZ.pkg = p ? p.id : null; } else if (g('wz-pkg')) WZ.pkg = g('wz-pkg').value; } if (g('wz-aud')) WZ.audience = g('wz-aud').value; if (g('wz-lal')) WZ.lookalike = g('wz-lal').checked; if (g('wz-land')) WZ.landing = g('wz-land').value; if (g('wz-bud')) WZ.budget = +g('wz-bud').value || WZ.budget; if (g('wz-day')) WZ.daily = +g('wz-day').value || WZ.daily; if (g('wz-start')) WZ.start = g('wz-start').value; if (g('wz-end')) WZ.end = g('wz-end').value; }
function wzCreate(state) { const id = 'CMP-' + (26700 + CAMPAIGNS.length * 3); const c = { id, name: WZ.name, objective: WZ.objective, owner: WZ.owner, pkg: WZ.pkg, channels: WZ.placement.slice(), budget: WZ.budget, daily: WZ.daily, spent: 0, impr: 0, reach: 0, clicks: 0, leads: 0, bookings: 0, revenue: 0, state, start: new Date(WZ.start).getTime(), end: new Date(WZ.end).getTime(), attribution: 'Last non-direct click · 7d click / 1d view', audience: WZ.audience, creatives: WZ.creatives.length, voucher: null, created: true }; CAMPAIGNS.unshift(c); audit('Admin Pusat', 'campaign.create', 'Campaign/' + id + ' (' + state + ')', 'success'); if (state === 'review') { APPROVALS.unshift({ id: 'APR-' + (19800 + CAMPAIGNS.length), type: 'campaign', domain: 'Ads', title: 'Review campaign — ' + c.name, requester: travelById(c.owner).name, reqRef: id, reqRoute: '/ads/campaign/' + id, status: 'waiting', priority: WZ.budget > 100e6 ? 'p1' : 'p2', assignee: null, ts: nowTs(), risk: 14, docs: [['PNG', 'Creative set (' + c.creatives + ')', '—']], ctx: [['Budget', c.budget], ['Channel', c.channels.join(', ')], ['Objective', c.objective]], notes: [], history: [{ t: 'Diajukan dari Control Center', ts: nowTs(), tone: 'info' }], fresh: true }); } closeOverlays(); toast('ok', state === 'review' ? L3(['Campaign dikirim ke Review', 'Campaign submitted for Review', 'أُرسلت الحملة للمراجعة']) : L3(['Draft tersimpan', 'Draft saved', 'حُفظت المسودة']), c.name + ' · ' + id, '/ads/campaign/' + id); go('/ads/campaign/' + id); }

/* ---------- Campaign detail ---------- */
const CAMP_FLOW = ['draft', 'review', 'scheduled', 'active', 'paused', 'completed', 'archived'];
const CTABS = ['performance', 'audience', 'creative', 'placement', 'attribution', 'activity'];
function campaignDetail(p) {
  const c = campById(p.id); if (!c) return { html: `<div class="page">${stateBlock('noresult', { title: 'Campaign tidak ditemukan', desc: p.id })}</div>` };
  const tab = CTABS.includes(p.tab) ? p.tab : 'performance'; const tr = c.owner ? travelById(c.owner) : null; const pk = c.pkg ? pkgById(c.pkg) : null;
  const acts = { draft: [['review', t('submit_review'), 'primary', 'send']], review: [['draft', t('reject'), 'badb', 'x'], ['scheduled', t('approve'), 'primary', 'check']], scheduled: [['active', L3(['Aktifkan sekarang', 'Activate now', 'تفعيل الآن']), 'primary', 'play']], active: [['paused', t('pause'), 'warnb', 'pause'], ['completed', L3(['Selesaikan', 'Complete', 'إنهاء']), '', 'check']], paused: [['active', t('resume'), 'primary', 'play'], ['completed', L3(['Selesaikan', 'Complete', 'إنهاء']), '', 'check']], completed: [['archived', t('archive'), '', 'archive']], archived: [] }[c.state];
  const pacing = c.budget ? c.spent / c.budget : 0; const days = Math.max(1, Math.round((c.end - c.start) / D)); const elapsed = Math.min(1, Math.max(0, (nowTs() - c.start) / (c.end - c.start)));
  const attrBk = BOOKINGS.filter(b => b.campaign === c.id); const attrConv = CONVERSATIONS.filter(x => x.campaign === c.id);
  const perDay = ser().map((d, i) => ({ ts: d.ts, spend: c.spent ? d.spend * c.spent / ser().reduce((s, x) => s + x.spend, 0) : 0, leads: c.leads ? d.leads * c.leads / ser().reduce((s, x) => s + x.leads, 0) : 0 }));
  let body = '';
  if (tab === 'performance') body = c.spent ? `<div class="kpis" style="grid-template-columns:repeat(6,minmax(0,1fr))">${[['Spend', money(c.spent)], ['Impressions', fC(c.impr)], ['Reach', fC(c.reach)], ['Clicks · CTR', fC(c.clicks) + ' <small class="muted" style="font-size:12px">' + pct(c.clicks / c.impr * 100, 2) + '</small>'], ['Leads · CPL', fN(c.leads) + ' <small class="muted" style="font-size:12px">' + money(c.spent / Math.max(1, c.leads)) + '</small>'], ['ROAS', fN(campRoas(c), { maximumFractionDigits: 1 }) + '×']].map(k => `<div class="kpi"><div class="k">${k[0]}</div><div class="v">${k[1]}</div></div>`).join('')}</div><div class="grid g12" style="margin-top:14px"><div class="c8">${pnl(L3(['Spend harian', 'Daily spend', 'الإنفاق']), areaChart(perDay, { key: 'spend', fmt: v => money(v), h: 160, label: 'spend' }) + `<div class="eyebrow" style="margin:10px 0 4px">Leads</div>` + barChart(perDay, { key: 'leads', fmt: v => fN(Math.round(v)), h: 100 }), { icon: 'trend' })}</div><div class="c4">${pnl(L3(['Budget pacing', 'Budget pacing', 'وتيرة الميزانية']), `<div class="kpi" style="padding:0;border:0"><div class="v">${pct(pacing * 100, 0)}</div><div class="d">${money(c.spent, true)} / ${money(c.budget, true)}</div></div><div class="meter ${pacing > elapsed + .1 ? 'warn' : 'ok'}" style="margin:10px 0 4px;height:8px"><i style="width:${pacing * 100}%"></i></div><div class="muted" style="font-size:12px">${L3(['Waktu berjalan', 'Time elapsed', 'الوقت المنقضي'])}: ${pct(elapsed * 100, 0)} · ${days} ${L3(['hari', 'days', 'أيام'])}</div>${pacing > elapsed + .1 ? `<div class="banner warn" style="border-radius:8px;margin-top:10px;border:1px solid var(--warn-line)">${ic('alert')}${L3(['Overpacing — pertimbangkan turunkan daily cap', 'Overpacing — consider lowering daily cap', 'إنفاق زائد'])}</div>` : ''}<div class="aibox" style="margin-top:12px"><div class="h">${ic('sparkles', 'sm')}Optimize</div><p>${L3(['Placement WhatsApp Click-to-Chat menghasilkan CPL 38% lebih rendah. Saran: geser 15% budget. Perubahan tetap lewat aksi & permission Anda.', 'WhatsApp Click-to-Chat yields 38% lower CPL. Suggest shifting 15% budget. Changes still go through your actions & permissions.', 'اقتراح: نقل 15% من الميزانية.'])}</p></div>`, { icon: 'wallet' })}</div></div>` : stateBlock('empty', { title: L3(['Belum ada data performa', 'No performance data yet', 'لا بيانات أداء']), desc: L3(['Data muncul setelah campaign Active dan event tracking diterima.', 'Data appears once the campaign is Active and tracking events arrive.', 'تظهر البيانات بعد التفعيل.']) });
  if (tab === 'audience') body = pnl('Ad Set / Audience', `<div class="tbl-wrap"><table class="t"><thead><tr><th>Ad set</th><th>Audience</th><th>Placement</th><th class="r">Budget share</th><th class="r">Leads</th><th>${t('status')}</th></tr></thead><tbody>${c.channels.map((ch, i) => `<tr><td class="mono">AS-${c.id.slice(4)}-${i + 1}</td><td>${esc(i ? 'Lookalike 1% · ' + c.audience.split('·')[1] : c.audience)}</td><td>${esc(ch)}</td><td class="r tnum">${pct(100 / c.channels.length, 0)}</td><td class="r tnum">${fN(Math.round(c.leads / c.channels.length))}</td><td>${st(c.state === 'active' ? 'active' : c.state)}</td></tr>`).join('')}</tbody></table></div>`, { raw: true, icon: 'layers' });
  if (tab === 'creative') body = `<div class="grid g4">${Array.from({ length: c.creatives }, (_, i) => `<div class="panel" style="overflow:hidden"><div style="aspect-ratio:4/5;max-width:100%;background:linear-gradient(${40 + i * 60}deg,${['#1f3b2f', '#2b3e72', '#5a3a22', '#3d2d62', '#194a55', '#5d2a2a'][i % 6]},${['#c9a45a', '#6f8cff', '#e0a36a', '#b78cf0', '#6fd0c4', '#f09a8a'][i % 6]});display:grid;place-items:end start;padding:12px;color:#fff;font-family:var(--font-display);font-weight:650">${esc(c.name.split(' ').slice(0, 3).join(' '))}</div><div class="panel-b" style="font-size:12.5px"><b>CR-${c.id.slice(4)}-${i + 1}</b><div class="muted">${['1080×1350', 'Video 15s', 'Carousel', '9:16 Story', 'Brosur', 'Banner'][i % 6]} · CTR ${pct(1.1 + i * .3, 2)}</div>${i === 0 && c.state === 'review' ? `<div style="margin-top:6px">${st('needs_revision')}</div>` : ''}</div></div>`).join('')}</div>`;
  if (tab === 'placement') body = `<div class="grid g2">${pnl('Placement / Channel', hbars(c.channels.map(ch => [ch, c.spent / c.channels.length * (ch.includes('WhatsApp') ? .8 : 1.1)]), v => money(v)), { icon: 'grid' })}${pnl('Budget & schedule', `<dl class="dl"><dt>Total budget</dt><dd class="tnum">${money(c.budget, true)}</dd><dt>Daily cap</dt><dd class="tnum">${money(c.daily, true)}</dd><dt>${L3(['Mulai', 'Start', 'البداية'])}</dt><dd>${fD(c.start)}</dd><dt>${L3(['Selesai', 'End', 'النهاية'])}</dt><dd>${fD(c.end)}</dd><dt>Voucher</dt><dd>${c.voucher ? `<span class="chip mono">${c.voucher}</span> <a href="#/ads/voucher">Voucher & Promo</a>` : '—'}</dd></dl>`, { icon: 'wallet' })}</div>`;
  if (tab === 'attribution') body = `${pnl('Campaign → Lead → Conversation → Booking → Payment → Revenue', `<div class="chain">${[['Campaign', fC(c.clicks), 'clicks', null], ['Lead', fN(c.leads), 'CPL ' + money(c.spent / Math.max(1, c.leads)), '/omni/contacts'], [L3(['Percakapan', 'Conversation', 'محادثة']), fN(Math.round(c.leads * .62)), 'Omnichannel', '/omni/inbox'], ['Booking', fN(c.bookings), pct(c.bookings / Math.max(1, c.leads) * 100) + ' conv.', '/booking'], ['Payment', fN(Math.round(c.bookings * .78)), 'paid', '/finance/transactions'], ['Revenue', money(c.revenue), 'ROAS ' + fN(campRoas(c), { maximumFractionDigits: 1 }) + '×', '/analytics/conversion']].map((n, i, a) => `${n[3] ? `<a class="cn" href="#${n[3]}">` : '<div class="cn">'}<span class="k">${esc(n[0])}</span><span class="v">${n[1]}</span><span class="s">${esc(n[2])}</span>${n[3] ? '</a>' : '</div>'}${i < a.length - 1 ? `<span class="ca">${icd('arrowR', 'sm')}</span>` : ''}`).join('')}</div><p class="muted" style="font-size:12px;margin:10px 0 0">Model: ${esc(c.attribution)}</p>`, { icon: 'branch' })}
   <div class="grid g2" style="margin-top:14px">${pnl(L3(['Booking teratribusi', 'Attributed bookings', 'حجوزات منسوبة']), attrBk.length ? `<div class="list" style="margin:-14px">${attrBk.map(b => `<a class="li" href="#/booking/${b.id}"><span class="body"><b class="mono" style="font-weight:600">${b.id}</b><span class="sub">${esc(trvName(b.traveler))} · ${money(b.total)}</span></span>${st(b.state)}</a>`).join('')}</div>` : `<span class="muted">—</span>`, { icon: 'calendar' })}${pnl(L3(['Percakapan dari campaign', 'Conversations from campaign', 'محادثات من الحملة']), attrConv.length ? `<div class="list" style="margin:-14px">${attrConv.map(x => `<a class="li" href="#/omni/inbox/${x.id}">${chanBadge(x.channel)}<span class="body"><b>${esc(x.contact)}</b><span class="sub">${esc(x.messages[x.messages.length - 1].text)}</span></span>${st(x.status)}</a>`).join('')}</div>` : `<span class="muted">—</span>`, { icon: 'msg' })}</div>`;
  if (tab === 'activity') body = pnl(t('t_act'), `<ul class="tl">${[...AUDIT.filter(a => a.resource.includes(c.id)).map(a => [a.action + (a.after ? ' → ' + a.after : ''), a.ts, 'ok', a.actor]), ['campaign.created', c.start - 5 * D, 'neu', 'Tenant'], ['campaign.review.approved', c.start - 2 * D, 'ok', 'Tim Ads Review']].map(h => `<li><span class="dotc ${h[2]}"></span><b style="font-weight:550" class="mono">${esc(h[0])}</b><div class="m">${esc(h[3])} · ${esc(fDT(h[1]))}</div></li>`).join('')}</ul>`, { icon: 'history' });
  const html = `<div class="page">${crumbs([[t('g_ads'), '/ads'], [t('ads_camp'), '/ads/campaigns'], [c.name, '']])}
  <div class="phead"><div class="ttl"><h1>${esc(c.name)}</h1><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px;align-items:center"><span class="chip mono">${c.id}</span>${st(c.state)}<span class="chip">${ic('target', 'sm')}${esc(L3(OBJECTIVES[c.objective]))}</span>${tr ? `<a class="chip" href="#/travel/${tr.id}">${ic('building', 'sm')}${esc(tr.name)}</a>` : '<span class="chip">Segaloka (platform)</span>'}${pk ? `<a class="chip" href="#/marketplace/packages">${ic('package', 'sm')}${esc(pk.name)}</a>` : ''}<span class="chip">${ic('calendar', 'sm')}${fD(c.start, { day: 'numeric', month: 'short' })} – ${fD(c.end)}</span></div></div>
  <div class="actions">${acts.map(a => permBtn(c.state === 'review' ? 'ads.approve' : 'ads.manage', ic(a[3]) + esc(a[1]), `data-act="camp-set" data-id="${c.id}" data-v="${a[0]}" data-mut`, a[2])).join('')}<button class="btn" data-act="export" data-what="${c.id}">${ic('download')}</button></div></div>
  <section class="panel" style="padding:12px 14px;margin-bottom:14px"><div class="eyebrow" style="margin-bottom:8px">Campaign lifecycle</div>${lifeBar(CAMP_FLOW, c.state)}<div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:10px;font-size:12px" class="muted">${['Objective', 'Audience', 'Creative', 'Placement', 'Budget', 'Schedule', 'Review', 'Active', 'Monitor', 'Optimize', 'Complete', 'Analyze'].map((s, i) => { const reached = { draft: 5, review: 6, scheduled: 7, active: 9, paused: 8, completed: 11, archived: 12 }[c.state]; return `<span class="chip" style="${i < reached ? 'background:var(--ok-bg);color:var(--ok)' : ''}">${i < reached ? '✓ ' : ''}${s}</span>`; }).join('')}</div></section>
  <div class="tabs" role="tablist">${CTABS.map(k => `<a class="tab" role="tab" aria-selected="${k === tab}" href="#/ads/campaign/${c.id}${k === 'performance' ? '' : '/' + k}">${{ performance: 'Performance', audience: 'Ad Set / Audience', creative: 'Creative', placement: 'Placement & Budget', attribution: 'Conversion & Attribution', activity: 'Activity' }[k]}</a>`).join('')}</div>
  <div style="margin-top:14px">${gate(body)}</div></div>`;
  return { html };
}
route('/ads/campaign/:id', campaignDetail); route('/ads/campaign/:id/:tab', campaignDetail);

/* =============================== FINANCE OVERVIEW =============================== */
PAGES.finance = () => {
  const paid = PAYMENTS.filter(p => p.status === 'paid'); const vol = paid.reduce((s, p) => s + p.amount, 0); const via = paid.filter(p => p.flow === 'VIA_SEGALOKA').reduce((s, p) => s + p.amount, 0);
  const stBy = k => SETTLEMENTS.filter(s => s.state === k); const wd = WITHDRAWALS.filter(w => w.state === 'pending'); const recon = { reconciled: 0, pending: 0, unmatched: 0, mismatch: 0 }; paid.forEach(p => recon[p.recon]++);
  const lane = (icon, title, route, rows, foot) => `<a class="panel" href="#${route}" style="color:inherit;text-decoration:none;display:block"><div class="panel-h"><h3>${ic(icon, 'sm')}${esc(title)}</h3>${icd('chevR', 'sm muted')}</div><div class="panel-b" style="display:grid;gap:6px">${rows.map(r => `<div style="display:flex;align-items:center;gap:8px">${st(r[0])}<span style="flex:1"></span><b class="tnum">${r[1]}</b></div>`).join('')}</div>${foot ? `<div class="panel-f muted">${foot}</div>` : ''}</a>`;
  const tb = defTable('fintx', { name: 'Transaksi', placeholder: L3(['Cari PAY-, booking, ref gateway', 'Search PAY-, booking, gateway ref', 'ابحث']), search: r => r.id + ' ' + r.booking + ' ' + r.ref, rows: () => PAYMENTS, route: r => '/finance/payment/' + r.id, size: 8,
    filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'paid', label: 'Paid', fn: r => r.status === 'paid' }, { v: 'pending', label: 'Pending', fn: r => r.status === 'pending' }, { v: 'failed', label: 'Failed / Expired', fn: r => ['failed', 'expired'].includes(r.status) }, { v: 'recon', label: 'Unmatched', fn: r => ['unmatched', 'mismatch'].includes(r.recon) }],
    cols: [{ k: 'id', label: 'Payment', render: r => `<b class="mono" style="font-weight:600">${r.id}</b><div class="muted" style="font-size:11.5px">${esc(fDT(r.ts))}</div>` }, { k: 'booking', label: 'Booking', render: r => `<span class="mono">${r.booking}</span><div class="muted" style="font-size:11.5px">${esc(trvName(r.payer))}</div>` }, { k: 'amount', label: 'Amount', cls: 'r tnum', render: r => money(r.amount, true) }, { k: 'provider', label: 'Provider · Channel', render: r => `${esc(r.provider)}<div class="muted" style="font-size:11.5px">${esc(r.channel)}</div>` }, { k: 'flow', label: 'Flow', render: r => `<span class="chip mono" style="font-size:10.5px">${r.flow}</span>` }, { k: 'status', label: 'Payment', render: r => st(r.status) }, { k: 'recon', label: 'Recon', render: r => st(r.recon) }],
    card: r => `<div style="display:flex;justify-content:space-between"><b class="mono">${r.id}</b>${st(r.status)}</div><div class="row"><span>${esc(r.provider)} · ${esc(r.channel)}</span><b class="tnum">${money(r.amount)}</b></div>` });
  const html = `<div class="page">${phead({ crumbs: [[t('g_fin'), '/finance'], [t('fin_ov'), '/finance']], title: t('fin_title'), desc: t('fin_desc'), actions: `<span class="muted" id="fin-upd" style="font-size:12px">${t('updated')} ${esc(rel(nowTs() - 90e3))}</span><button class="btn" data-act="export" data-what="Finance">${ic('download')}Export</button>${permBtn('finance.reconcile', ic('scale') + L3(['Jalankan rekonsiliasi', 'Run reconciliation', 'تشغيل المطابقة']), 'data-act="run-recon" data-mut', 'primary')}` })}
  ${mockBanner()}
  ${gate(`<div class="kpis">${[[L3(['Volume terbayar (30d)', 'Paid volume (30d)', 'الحجم المدفوع']), money(vol), delta(8.2)], ['VIA_SEGALOKA (ledger)', money(via), pct(via / vol * 100, 0) + ' ' + L3(['dari volume', 'of volume', 'من الحجم'])], [L3(['Fee platform', 'Platform fees', 'رسوم المنصة']), money(vol * .025 + paid.reduce((s, p) => s + p.fee, 0)), delta(6.5)], [L3(['Dana ditahan (reserve + hold)', 'Funds held (reserve + hold)', 'أموال محتجزة']), money(SETTLEMENTS.reduce((s, x) => s + x.reserve, 0) + stBy('hold').reduce((s, x) => s + x.net, 0)), stBy('hold').length + ' settlement hold']].map(k => `<div class="kpi"><div class="k">${k[0]}</div><div class="v">${k[1]}</div><div class="d">${k[2]}</div></div>`).join('')}</div>`, 3)}
  <div class="section-title"><h2>${L3(['Lifecycle terpisah', 'Separate lifecycles', 'دورات منفصلة'])}</h2><span class="rule"></span></div>
  <div class="grid" style="grid-template-columns:repeat(5,minmax(0,1fr))" id="finlanes">
   ${lane('card', 'Payment', '/finance/transactions', [['paid', paid.length], ['pending', PAYMENTS.filter(p => p.status === 'pending').length], ['failed', PAYMENTS.filter(p => p.status === 'failed').length], ['expired', PAYMENTS.filter(p => p.status === 'expired').length]], L3(['Event dari webhook gateway', 'Events from gateway webhooks', 'أحداث من البوابة']))}
   ${lane('landmark', 'Settlement', '/finance/settlement', [['scheduled', stBy('scheduled').length], ['processing', stBy('processing').length], ['settled', stBy('settled').length], ['hold', stBy('hold').length], ['failed', stBy('failed').length]], 'Cycle T+3 · reserve 5%')}
   ${lane('arrowur', 'Withdrawal', '/finance/withdrawal', [['pending', wd.length], ['approved', WITHDRAWALS.filter(w => w.state === 'approved').length], ['disbursed', WITHDRAWALS.filter(w => w.state === 'disbursed').length], ['hold', WITHDRAWALS.filter(w => w.state === 'hold').length]], 'Vendor · Travel · Affiliate')}
   ${lane('undo', 'Refund', '/finance/refund', [['pending', REFUNDS.filter(r => r.state === 'pending').length], ['refunded', REFUNDS.filter(r => r.state === 'refunded').length], ['rejected', REFUNDS.filter(r => r.state === 'rejected').length]], L3(['Butuh approval', 'Requires approval', 'تتطلب موافقة']))}
   ${lane('scale', 'Reconciliation', '/finance/reconciliation', [['reconciled', recon.reconciled], ['pending', recon.pending], ['unmatched', recon.unmatched], ['mismatch', recon.mismatch]], 'Batch REC-260923')}
  </div>
  <div class="grid g12" style="margin-top:14px">
   <div class="c8">${pnl(L3(['Volume pembayaran harian', 'Daily payment volume', 'حجم الدفع اليومي']), gate(areaChart(ser(), { key: 'gmv', fmt: v => money(v), label: 'volume' })), { icon: 'trend' })}</div>
   <div class="c4">${pnl('Ledger model · VIA_SEGALOKA', `<ul class="tl">${[['Payment captured', 'Gateway → rekening escrow Segaloka', 'ok'], ['Ledger posted', L3(['Kredit saldo tenant, debit fee & reserve', 'Credit tenant balance, debit fee & reserve', 'قيد الرصيد']), 'info'], ['Settlement T+3', L3(['Batch ke rekening Travel terverifikasi', 'Batch to verified Travel account', 'دفعة إلى الحساب']), 'info'], ['Withdrawal', L3(['Vendor/Affiliate sesuai transaksi', 'Vendor/Affiliate per transaction', 'حسب المعاملات']), 'neu'], ['Reconciliation', L3(['Mutasi bank vs ledger vs gateway', 'Bank statement vs ledger vs gateway', 'مطابقة ثلاثية']), 'neu']].map(x => `<li><span class="dotc ${x[2]}"></span><b style="font-weight:550">${x[0]}</b><div class="m">${esc(x[1])}</div></li>`).join('')}</ul><div class="muted" style="font-size:12px">DIRECT_TO_TRAVEL: ${L3(['gateway → rekening Travel; Segaloka mencatat event, fee ditagih terpisah.', 'gateway → Travel account; Segaloka records events, fee billed separately.', 'مباشر إلى الشركة.'])}</div>`, { icon: 'layers' })}</div>
  </div>
  <div class="grid g12" style="margin-top:14px">
   <div class="c7">${pnl('Payment Gateway', `<div class="tbl-wrap"><table class="t"><thead><tr><th>Provider</th><th>${t('status')}</th><th class="r">Success</th><th class="r">p95 latency</th><th class="r">Share</th><th>Routing</th></tr></thead><tbody>${PROVIDERS.map(p => `<tr><td><b>${p.name}</b></td><td>${st(p.status)}</td><td class="r tnum">${pct(p.success)}</td><td class="r tnum">${fN(p.latency)} ms</td><td class="r tnum">${p.share}%</td><td style="font-size:12px">${p.id === 'midtrans' ? 'VA, QRIS (primary)' : p.id === 'xendit' ? 'VA, Kartu Kredit' : 'QRIS (failover off)'}</td></tr>`).join('')}</tbody></table></div>`, { raw: true, icon: 'card', right: permBtn('system.payment', ic('sliders', 'sm') + 'Routing', 'data-act="nav" data-r="/system/payment"', 'sm') })}</div>
   <div class="c5">${pnl(L3(['Withdrawal menunggu approval', 'Withdrawals awaiting approval', 'سحوبات بانتظار الموافقة']), wd.length ? `<div class="list" style="margin:-14px">${wd.map(w => `<div class="li"><span class="body"><b>${esc(w.party)}</b><span class="sub"><span class="chip" style="height:18px">${w.partyType}</span> ${esc(w.basis)} · <span class="mono">${w.id}</span></span></span><b class="tnum">${money(w.amount)}</b>${permBtn('finance.withdrawal', t('approve'), `data-act="wd-approve" data-id="${w.id}" data-mut`, 'sm primary')}</div>`).join('')}</div>` : stateBlock('empty'), { icon: 'arrowur' })}</div>
  </div>
  <div class="section-title"><h2>${t('fin_tx')}</h2><span class="rule"></span><span class="live ${S.ux === 'offline' ? 'off' : ''}"><i></i>${L3(['Webhook realtime', 'Realtime webhooks', 'مباشر'])}</span></div>
  <section class="panel">${tb}</section>
  <div class="grid g3" style="margin-top:14px">${pnl('Risk controls', `<dl class="dl"><dt>Limit withdrawal/hari</dt><dd class="tnum">Rp 2 M / tenant</dd><dt>Auto-hold</dt><dd>${L3(['Perubahan rekening < 72 jam', 'Account change < 72h', 'تغيير حساب < 72 ساعة'])}</dd><dt>Reserve</dt><dd>5% · rolling 30 hari</dd><dt>Approval</dt><dd>Refund & withdrawal > Rp 50 jt</dd></dl>`, { icon: 'shield', right: `<a class="btn sm ghost" href="#/system/payment">${icd('chevR', 'sm')}</a>` })}${pnl('Deposit Travel', `<div class="kpi" style="padding:0;border:0"><div class="v">${money(1.62e9)}</div><div class="d">${TRAVELS.filter(x => x.op === 'active').length} tenant · ${L3(['jaminan operasional', 'operational guarantee', 'ضمان تشغيلي'])}</div></div>`, { icon: 'download', right: `<a class="btn sm ghost" href="#/finance/deposit">${icd('chevR', 'sm')}</a>` })}${pnl('Fee & Commission', hbars([['Fee platform 2,5%', vol * .025], ['MDR gateway', paid.reduce((s, p) => s + p.fee, 0)], ['Komisi affiliate', AFFILIATES.reduce((s, a) => s + a.commission, 0)]], v => money(v)), { icon: 'percent' })}</div></div>`;
  return { html };
};
route('/finance', PAGES.finance);

/* ---------- Payment detail ---------- */
route('/finance/payment/:id', p => {
  const x = PAYMENTS.find(y => y.id === p.id); if (!x) return { html: `<div class="page">${stateBlock('noresult', { title: 'Payment tidak ditemukan', desc: p.id })}</div>` };
  const b = bookingById(x.booking); const tr = travelById(x.travel); const stl = SETTLEMENTS.find(s => s.travel === x.travel);
  const ev = [['payment.created', x.ts - 20 * 60e3, 'info', 'Control Center · checkout'], ['charge.pending · VA issued', x.ts - 19 * 60e3, 'info', x.provider + ' API · 201'], ...(x.status === 'paid' || x.status === 'refunded' ? [['webhook payment.paid', x.ts, 'ok', x.provider + ' → /webhooks/' + x.provider.toLowerCase() + ' · sig ✓ · idempotent'], ['ledger.posted', x.ts + 2e3, 'ok', 'Ledger · ' + (x.flow === 'VIA_SEGALOKA' ? 'credit tenant balance' : 'record only')], ['booking.state → ' + (b ? b.state : 'confirmed'), x.ts + 3e3, 'ok', 'Booking service']] : []), ...(x.status === 'failed' ? [['webhook payment.failed', x.ts, 'bad', 'Issuer declined (51)']] : []), ...(x.status === 'expired' ? [['payment.expired', x.ts + 24 * H, 'warn', 'VA TTL 24 jam']] : []), ...(x.recon === 'reconciled' ? [['reconciliation.matched', x.ts + 20 * H, 'ok', 'Bank statement REC-260923']] : x.recon === 'unmatched' ? [['reconciliation.unmatched', x.ts + 20 * H, 'warn', L3(['Tidak ditemukan di mutasi bank', 'Not found in bank statement', 'غير موجود'])]] : x.recon === 'mismatch' ? [['reconciliation.mismatch', x.ts + 20 * H, 'bad', 'Selisih Rp 2.500 (biaya admin bank)']] : [])];
  const html = `<div class="page">${crumbs([[t('g_fin'), '/finance'], [t('fin_tx'), '/finance/transactions'], [x.id, '']])}
  <div class="phead"><div class="ttl"><h1 class="mono" style="font-family:var(--font-mono)">${x.id}</h1><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px;align-items:center"><span class="muted" style="font-size:12px">Payment</span>${st(x.status)}<span class="muted" style="font-size:12px">Reconciliation</span>${st(x.recon)}${stl && x.flow === 'VIA_SEGALOKA' ? `<span class="muted" style="font-size:12px">Settlement</span>${st(stl.state)}` : ''}<span class="chip mono">${x.flow}</span></div></div><div class="actions">${x.status === 'paid' ? permBtn('finance.refund', ic('undo') + L3(['Ajukan refund', 'Request refund', 'طلب استرداد']), `data-act="pay-refund" data-id="${x.id}" data-mut`, '') : ''}${permBtn('finance.reconcile', ic('scale') + L3(['Match manual', 'Manual match', 'مطابقة يدوية']), `data-act="pay-match" data-id="${x.id}" data-mut`, '')}</div></div>
  <div class="grid g12"><div class="c7" style="display:grid;gap:14px;align-content:start">${pnl('Detail', `<dl class="dl"><dt>Amount</dt><dd><b class="tnum" style="font-size:18px;font-family:var(--font-display)">${money(x.amount, true)}</b></dd><dt>Payer</dt><dd>${esc(trvName(x.payer))} <span class="mono muted">${x.payer}</span></dd><dt>Booking</dt><dd><a href="#/booking/${x.booking}" class="mono">${x.booking}</a> ${b ? st(b.state) : ''}</dd><dt>Travel</dt><dd><a href="#/travel/${tr.id}">${esc(tr.name)}</a></dd><dt>Provider</dt><dd>${esc(x.provider)}</dd><dt>Channel</dt><dd>${esc(x.channel)}</dd><dt>Transaction ref</dt><dd class="mono">${esc(x.ref)} <button class="btn sm ghost" data-act="copy" data-v="${esc(x.ref)}" aria-label="Copy">${ic('copy', 'sm')}</button></dd><dt>MDR</dt><dd class="tnum">${money(x.fee, true)}</dd><dt>Created</dt><dd>${fDT(x.ts - 20 * 60e3)}</dd><dt>Paid at</dt><dd>${x.status === 'paid' || x.status === 'refunded' ? fDT(x.ts) : '—'}</dd></dl>`, { icon: 'card' })}</div>
  <div class="c5">${pnl('Webhook / event timeline', `<ul class="tl">${ev.map(e => `<li><span class="dotc ${e[2]}"></span><b class="mono" style="font-weight:550;font-size:12.5px">${esc(e[0])}</b><div class="m">${esc(fDT(e[1]))} · ${esc(e[3])}</div></li>`).join('')}</ul>`, { icon: 'zap' })}</div></div></div>`;
  return { html };
});
