/* =============================== BOOKING & OPERASIONAL =============================== */
const DEPS = (() => { const m = {}; BOOKINGS.filter(b => ['confirmed', 'processing', 'ready', 'partially_paid', 'departed'].includes(b.state)).forEach(b => { (m[b.pkg] = m[b.pkg] || []).push(b); }); return Object.entries(m).map(([pkg, bks], i) => { const p = pkgById(pkg); const pax = []; bks.forEach(b => { const tv = TRAVELERS.find(x => x.id === b.traveler); for (let k = 0; k < b.pax; k++) pax.push({ id: b.id + '-' + (k + 1), name: k ? (tv.name.split(' ')[0] + ' — pendamping ' + k) : tv.name, booking: b.id, passport: k === 0 ? tv.passport : (rnd() < .7 ? 'verified' : 'pending'), visa: rnd() < .55 ? 'verified' : rnd() < .5 ? 'submitted' : 'pending', room: null, g: k % 2 ? 'P' : 'L' }); }); return { id: 'DEP-' + pkg.slice(4), pkg, name: p.name + ' · ' + fD(p.dep, { day: 'numeric', month: 'short' }), travel: p.travel, dep: p.dep, pax, state: i % 4 === 0 ? 'review' : 'draft', rooms: [], roomState: 'draft' }; }).sort((a, b) => a.dep - b.dep); })();
DEPS.forEach(d => { let no = 101; for (let i = 0; i < d.pax.length; i += 4) { d.rooms.push({ no: 'R' + no++, type: 'Quad', hotel: 'Hotel · Makkah', cap: 4 }); } d.pax.forEach((p, i) => { if (i % 5 !== 3) p.room = d.rooms[Math.floor(i / 4)].no; }); });
let DEPSEL = DEPS[0] ? DEPS[0].id : null;
const depSel = act => `<select class="select" id="dep-sel" aria-label="Keberangkatan" data-act-change="${act}" style="max-width:360px">${DEPS.map(d => `<option value="${d.id}" ${DEPSEL === d.id ? 'selected' : ''}>${esc(d.name)} · ${d.pax.length} pax</option>`).join('')}</select>`;
route('/booking/manifest', () => { const d = DEPS.find(x => x.id === DEPSEL); if (!d) return { html: `<div class="page">${stateBlock('empty')}</div>` }; const ok = d.pax.every(p => p.passport === 'verified' && p.visa === 'verified');
  return { html: `<div class="page">${phead({ crumbs: [[t('g_book'), '/booking'], ['Manifest', '/booking/manifest']], title: 'Manifest', desc: L3(['Manifest per keberangkatan. Manifest dapat ditandai Ready hanya jika semua paspor & visa terverifikasi.', 'Manifest per departure. It can be marked Ready only when every passport & visa is verified.', 'كشف لكل رحلة.']), actions: depSel('dep-pick') + `<button class="btn" data-act="export" data-what="Manifest">${ic('download')}Export</button>` })}
  <section class="panel" style="padding:12px 14px;margin-bottom:14px"><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:10px"><b>${esc(d.name)}</b>${trvLink(d.travel)}<span class="chip">${d.pax.length} pax</span><span style="flex:1"></span>${d.state === 'ready' ? st('ready') : permBtn('booking.manage', ic('check') + L3(['Tandai Ready', 'Mark Ready', 'جاهز']), ok ? 'data-act="mani-ready" data-mut' : 'aria-disabled="true" data-tip="' + esc(L3(['Masih ada paspor/visa belum terverifikasi', 'Some passports/visas not verified', 'مستندات غير موثقة'])) + '"', 'primary')}</div>${lifeBar(['draft', 'review', 'verified', 'ready'], d.state)}</section>
  ${kpiRow([{ k: 'Pax', v: fN(d.pax.length) }, { k: L3(['Paspor terverifikasi', 'Passports verified', 'جوازات موثقة']), v: d.pax.filter(p => p.passport === 'verified').length + ' / ' + d.pax.length }, { k: L3(['Visa terverifikasi', 'Visas verified', 'تأشيرات']), v: d.pax.filter(p => p.visa === 'verified').length + ' / ' + d.pax.length }, { k: L3(['Berangkat', 'Departs', 'المغادرة']), v: fD(d.dep, { day: 'numeric', month: 'short' }), d: rel(d.dep) }])}
  <section class="panel" style="margin-top:14px"><div class="toolbar"><b style="flex:1">${L3(['Daftar jamaah', 'Pilgrim list', 'قائمة المعتمرين'])}</b>${permBtn('booking.manage', ic('check', 'sm') + L3(['Verifikasi semua paspor valid', 'Verify all valid passports', 'توثيق الكل']), 'data-act="mani-all" data-mut', 'sm')}</div><div class="tbl-wrap"><table class="t"><thead><tr><th>#</th><th>${L3(['Nama', 'Name', 'الاسم'])}</th><th>Booking</th><th>${L3(['Paspor', 'Passport', 'الجواز'])}</th><th>Visa</th><th>Room</th><th class="r">${t('action')}</th></tr></thead><tbody>${d.pax.map((p, i) => `<tr><td class="tnum">${i + 1}</td><td><b>${esc(p.name)}</b></td><td><a class="mono" href="#/booking/${p.booking}">${p.booking}</a></td><td>${st(p.passport)}</td><td>${st(p.visa)}</td><td>${p.room ? `<span class="chip mono">${p.room}</span>` : '<span class="st warn">—</span>'}</td><td class="r"><div class="actions" style="justify-content:flex-end;flex-wrap:nowrap">${p.passport !== 'verified' ? permBtn('booking.manage', L3(['Paspor ✓', 'Passport ✓', 'جواز ✓']), `data-act="mani-set" data-i="${i}" data-f="passport" data-mut`, 'sm') : ''}${p.visa !== 'verified' ? permBtn('booking.manage', 'Visa ✓', `data-act="mani-set" data-i="${i}" data-f="visa" data-mut`, 'sm') : ''}</div></td></tr>`).join('')}</tbody></table></div></section></div>` }; });
route('/booking/rooms', () => { const d = DEPS.find(x => x.id === DEPSEL); if (!d) return { html: `<div class="page">${stateBlock('empty')}</div>` }; const un = d.pax.filter(p => !p.room);
  return { html: `<div class="page">${phead({ crumbs: [[t('g_book'), '/booking'], ['Room List', '/booking/rooms']], title: 'Room List', desc: L3(['Rooming per keberangkatan. Konfirmasi room list mengirim data ke vendor hotel.', 'Rooming per departure. Confirming the room list sends it to the hotel vendor.', 'توزيع الغرف.']), actions: depSel('dep-pick') + permBtn('booking.manage', ic('plus') + L3(['Tambah kamar', 'Add room', 'إضافة غرفة']), 'data-act="room-add" data-mut', '') + (d.roomState === 'confirmed' ? st('confirmed') : permBtn('booking.manage', ic('check') + L3(['Konfirmasi ke hotel', 'Confirm to hotel', 'تأكيد']), un.length ? 'aria-disabled="true" data-tip="' + esc(un.length + ' jamaah belum mendapat kamar') + '"' : 'data-act="room-confirm" data-mut', 'primary')) })}
  ${kpiRow([{ k: L3(['Kamar', 'Rooms', 'الغرف']), v: fN(d.rooms.length) }, { k: L3(['Terisi', 'Assigned', 'مخصص']), v: (d.pax.length - un.length) + ' / ' + d.pax.length }, { k: L3(['Belum dapat kamar', 'Unassigned', 'بدون غرفة']), v: `<span style="color:var(--${un.length ? 'warn' : 'ok'})">${un.length}</span>` }, { k: t('status'), v: st(d.roomState) }])}
  <div class="grid g12" style="margin-top:14px"><div class="c4">${pnl(L3(['Belum dapat kamar', 'Unassigned', 'بدون غرفة']), un.length ? `<div class="list" style="margin:-14px">${un.map(p => `<div class="li"><span class="body"><b>${esc(p.name)}</b><span class="sub mono">${p.booking}</span></span><select class="select" data-act-change="room-assign" data-p="${p.id}" aria-label="Pilih kamar"><option value="">${L3(['Pilih kamar', 'Pick room', 'اختر'])}</option>${d.rooms.filter(r => d.pax.filter(x => x.room === r.no).length < r.cap).map(r => `<option value="${r.no}">${r.no} · ${d.pax.filter(x => x.room === r.no).length}/${r.cap}</option>`).join('')}</select></div>`).join('')}</div>` : stateBlock('empty', { title: L3(['Semua jamaah sudah dapat kamar', 'Everyone is assigned', 'الكل مخصص']) }), { icon: 'users' })}</div>
  <div class="c8"><div class="grid g2">${d.rooms.map(r => { const occ = d.pax.filter(x => x.room === r.no); return `<section class="panel"><div class="panel-h"><h3>${ic('bed', 'sm')}${r.no} <small>${r.type} · ${esc(r.hotel)}</small></h3><span class="chip tnum">${occ.length}/${r.cap}</span></div><div class="list">${occ.map(p => `<div class="li"><span class="body"><b style="font-weight:500">${esc(p.name)}</b></span>${d.roomState !== 'confirmed' ? `<button class="iconbtn" data-act="room-out" data-p="${p.id}" aria-label="Keluarkan">${ic('x', 'sm')}</button>` : ''}</div>`).join('') || `<div class="li muted">${L3(['Kosong', 'Empty', 'فارغة'])}</div>`}</div></section>`; }).join('')}</div></div></div></div>` }; });
Object.assign(A, {
  'dep-pick': el => { DEPSEL = el.value; rerender(); },
  'mani-set': el => { const d = DEPS.find(x => x.id === DEPSEL); const p = d.pax[+el.dataset.i]; p[el.dataset.f] = 'verified'; audit('Admin Pusat', 'manifest.' + el.dataset.f + '.verify', 'Manifest/' + d.id + '/' + p.id, 'success'); if (d.state === 'draft') d.state = 'review'; if (d.pax.every(x => x.passport === 'verified' && x.visa === 'verified')) d.state = 'verified'; rerender(); },
  'mani-all': () => { const d = DEPS.find(x => x.id === DEPSEL); let n = 0; d.pax.forEach(p => { if (p.passport !== 'verified') { p.passport = 'verified'; n++; } }); if (d.state === 'draft') d.state = 'review'; if (d.pax.every(x => x.passport === 'verified' && x.visa === 'verified')) d.state = 'verified'; audit('Admin Pusat', 'manifest.passport.bulk_verify', 'Manifest/' + d.id, 'success', { after: n + ' paspor' }); toast('ok', n + ' ' + L3(['paspor diverifikasi', 'passports verified', 'جوازات']), d.name); rerender(); },
  'mani-ready': () => { const d = DEPS.find(x => x.id === DEPSEL); confirmAction({ title: 'Manifest Ready · ' + d.name, desc: L3(['Manifest dikunci dan dikirim ke dokumen operasional & vendor.', 'Manifest is locked and sent to ops documents & vendors.', 'يُقفل الكشف.']), reason: false, resource: d.id, onOk: () => { d.state = 'ready'; BOOKINGS.filter(b => b.pkg === d.pkg && ['confirmed', 'processing'].includes(b.state)).forEach(b => b.state = 'ready'); audit('Admin Pusat', 'manifest.ready', 'Manifest/' + d.id, 'success'); toast('ok', 'Manifest Ready', L3(['Booking terkait → Ready', 'Related bookings → Ready', 'الحجوزات جاهزة'])); rerender(); } }); },
  'room-assign': el => { if (!el.value) return; const d = DEPS.find(x => x.id === DEPSEL); d.pax.find(p => p.id === el.dataset.p).room = el.value; rerender(); },
  'room-out': el => { const d = DEPS.find(x => x.id === DEPSEL); d.pax.find(p => p.id === el.dataset.p).room = null; rerender(); },
  'room-add': () => { const d = DEPS.find(x => x.id === DEPSEL); d.rooms.push({ no: 'R' + (101 + d.rooms.length), type: 'Quad', hotel: 'Hotel · Makkah', cap: 4 }); rerender(); },
  'room-confirm': () => { const d = DEPS.find(x => x.id === DEPSEL); confirmAction({ title: L3(['Konfirmasi room list', 'Confirm room list', 'تأكيد']), desc: d.rooms.length + ' kamar · ' + d.pax.length + ' pax → vendor hotel', reason: false, resource: d.id, onOk: () => { d.roomState = 'confirmed'; audit('Admin Pusat', 'roomlist.confirm', 'RoomList/' + d.id, 'success'); toast('ok', L3(['Room list dikonfirmasi', 'Room list confirmed', 'تم التأكيد']), L3(['Dikirim ke vendor hotel', 'Sent to hotel vendor', 'أُرسل للفندق'])); rerender(); } }); }
});
const PKGINFO = {}; let PKGSEL = PACKAGES[0].id;
const pinfo = id => PKGINFO[id] || (PKGINFO[id] = { days: ['Berangkat CGK → JED, transfer ke Madinah', 'Ziarah Masjid Nabawi & Raudhah', 'City tour Madinah: Quba, Uhud, Kebun Kurma', 'Perjalanan ke Makkah, miqat Bir Ali, umrah', 'Ibadah mandiri di Masjidil Haram', 'City tour Makkah: Jabal Tsur, Arafah, Mina', 'Ibadah mandiri', 'Thawaf wada, transfer ke Jeddah', 'Tiba di Indonesia'], hotelMk: 'Hotel ★4 · 300 m ke Haram', hotelMd: 'Hotel ★4 · 150 m ke Nabawi', air: 'Direct flight · bagasi 30 kg', leader: 'Ust. ' + pick(PEOPLE).replace(/^(H\.|Hj\.)\s*/, '') });
route('/booking/package-info', () => { const p = pkgById(PKGSEL); if (!p) return { html: `<div class="page">${phead({ crumbs: [[t('g_book'), '/booking'], [t('pkginfo'), '']], title: t('pkginfo') })}<div class="panel">${stateBlock('empty')}</div></div>` }; const inf = pinfo(PKGSEL);
  return { html: `<div class="page">${phead({ crumbs: [[t('g_book'), '/booking'], [t('pkginfo'), '']], title: t('pkginfo'), desc: L3(['Itinerary, hotel, penerbangan, dan tour leader. Perubahan tersinkron ke website Travel, Marketplace, dan dokumen operasional.', 'Itinerary, hotels, flights and tour leader. Changes sync to Travel website, Marketplace and ops documents.', 'معلومات الباقة.']), actions: `<select class="select" data-act-change="pkg-pick" aria-label="Paket" style="max-width:360px">${PACKAGES.filter(x => ['published', 'review'].includes(x.state)).map(x => `<option value="${x.id}" ${x.id === PKGSEL ? 'selected' : ''}>${esc(x.name)} · ${esc(travelById(x.travel).name)}</option>`).join('')}</select>` + permBtn('booking.manage', ic('check') + t('save'), 'data-act="pinfo-save" data-mut', 'primary') })}
  <div class="grid g12"><div class="c7">${pnl('Itinerary', `<ol style="margin:0;padding:0;list-style:none;display:grid;gap:8px" id="itin">${inf.days.map((d, i) => `<li style="display:flex;gap:8px;align-items:center"><span class="chip tnum" style="min-width:64px;justify-content:center">${L3(['Hari', 'Day', 'اليوم'])} ${i + 1}</span><input class="input" style="min-width:0;flex:1;height:34px" id="it-${i}" value="${esc(d)}" aria-label="Hari ${i + 1}"><button class="iconbtn" data-act="it-del" data-i="${i}" aria-label="Hapus">${ic('x', 'sm')}</button></li>`).join('')}</ol><button class="btn sm" style="margin-top:10px" data-act="it-add">${ic('plus', 'sm')}${L3(['Tambah hari', 'Add day', 'إضافة يوم'])}</button>`, { icon: 'list' })}</div>
  <div class="c5">${pnl(L3(['Detail layanan', 'Service details', 'التفاصيل']), `<div class="field"><label for="pi-mk">Hotel Makkah</label><input type="text" id="pi-mk" value="${esc(inf.hotelMk)}"></div><div class="field"><label for="pi-md">Hotel Madinah</label><input type="text" id="pi-md" value="${esc(inf.hotelMd)}"></div><div class="field"><label for="pi-air">${L3(['Penerbangan', 'Flight', 'الطيران'])}</label><input type="text" id="pi-air" value="${esc(inf.air)}"></div><div class="field"><label for="pi-tl">Tour leader</label><input type="text" id="pi-tl" value="${esc(inf.leader)}"></div><dl class="dl"><dt>Travel</dt><dd>${trvLink(p.travel)}</dd><dt>${L3(['Berangkat', 'Departs', 'المغادرة'])}</dt><dd>${fD(p.dep)}</dd><dt>Seat</dt><dd class="tnum">${p.sold}/${p.seats}</dd></dl>`, { icon: 'info' })}</div></div></div>` }; });
const pinfoCollect = () => { const inf = pinfo(PKGSEL); inf.days = inf.days.map((d, i) => { const el = document.getElementById('it-' + i); return el ? el.value : d; }); ['mk', 'md', 'air', 'tl'].forEach(k => { const el = document.getElementById('pi-' + k); if (el) inf[{ mk: 'hotelMk', md: 'hotelMd', air: 'air', tl: 'leader' }[k]] = el.value; }); };
Object.assign(A, { 'pkg-pick': el => { PKGSEL = el.value; rerender(); }, 'it-add': () => { pinfoCollect(); pinfo(PKGSEL).days.push(''); rerender(); }, 'it-del': el => { pinfoCollect(); pinfo(PKGSEL).days.splice(+el.dataset.i, 1); rerender(); }, 'pinfo-save': () => { pinfoCollect(); audit('Admin Pusat', 'package_info.update', 'Package/' + PKGSEL, 'success', { after: pinfo(PKGSEL).days.length + ' hari' }); toast('ok', L3(['Info paket disimpan', 'Package info saved', 'تم الحفظ']), L3(['Tersinkron ke website, Marketplace & dokumen operasional', 'Synced to website, Marketplace & ops documents', 'تمت المزامنة'])); } });
const OPSDOCS = []; DEPS.slice(0, 5).forEach(d => d.pax.slice(0, 6).forEach(p => ['Paspor', 'Visa', 'Vaksin meningitis'].forEach((k, j) => OPSDOCS.push({ id: 'DOC-' + (30100 + OPSDOCS.length), name: k + ' · ' + p.name, type: k, booking: p.booking, dep: d.name, state: j === 0 ? p.passport : j === 1 ? p.visa : wpick(['verified', 'submitted', 'pending', 'rejected'], [55, 20, 20, 5]) }))));
route('/booking/documents', () => resPage({ id: 'odoc', nav: 'opsdoc', noun: 'Dokumen', desc: L3(['Dokumen per jamaah & grup: paspor, visa, vaksin, tiket, voucher hotel.', 'Per-pilgrim & group documents: passport, visa, vaccine, tickets, hotel vouchers.', 'المستندات.']), data: OPSDOCS, states: ['pending', 'submitted', 'verified', 'rejected'], lifecycle: ['pending', 'submitted', 'verified'], create: false, bulk: [{ k: 'remind', label: L3(['Minta dokumen via WA', 'Request via WA', 'طلب']) }],
  cols: [{ k: 'name', label: L3(['Dokumen', 'Document', 'المستند']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'type', label: L3(['Tipe', 'Type', 'النوع']), render: r => `<span class="chip">${r.type}</span>` }, { k: 'booking', label: 'Booking', render: r => `<a class="mono" href="#/booking/${r.booking}">${r.booking}</a>` }, { k: 'dep', label: L3(['Keberangkatan', 'Departure', 'الرحلة']) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  acts: r => r.state === 'verified' ? [] : [{ label: L3(['Verifikasi', 'Verify', 'توثيق']), to: 'verified', tone: 'primary', why: r.state === 'pending' ? L3(['Dokumen belum diunggah', 'Not uploaded yet', 'لم يُرفع']) : null }, { label: t('reject'), to: 'rejected', tone: 'badb', reason: true, when: r.state === 'submitted' }] }));

/* =============================== FINANCE =============================== */
const WEBHOOKS = PAYMENTS.slice(0, 30).map((p, i) => ({ id: 'WH-' + (880100 + i * 7), name: 'payment.' + (p.status === 'paid' ? 'paid' : p.status === 'failed' ? 'failed' : 'pending'), provider: p.provider, payment: p.id, ts: p.ts, code: i === 4 || i === 17 ? 500 : 200, state: i === 4 || i === 17 ? 'failed' : 'success', attempts: i === 4 || i === 17 ? 3 : 1 }));
route('/finance/gateway', () => resPage({ id: 'wh', nav: 'fin_pg', noun: 'Webhook', title: 'Payment Gateway', desc: L3(['Semua pembayaran lewat gateway terintegrasi. Webhook ditandatangani & idempoten; yang gagal bisa di-replay.', 'All payments go through integrated gateways. Webhooks are signed & idempotent; failed ones can be replayed.', 'بوابات الدفع.']), data: WEBHOOKS, states: ['success', 'failed'], create: false,
  top: () => `<section class="panel"><div class="panel-h"><h3>${ic('card', 'sm')}Provider</h3><a class="btn sm" href="#/system/payment">${ic('sliders', 'sm')}Routing & fee</a></div><div class="tbl-wrap"><table class="t"><thead><tr><th>Provider</th><th>${t('status')}</th><th class="r">Success</th><th class="r">p95</th><th class="r">Share</th><th class="r">${t('action')}</th></tr></thead><tbody>${PROVIDERS.map(p => `<tr><td><b>${p.name}</b></td><td>${st(p.status)}</td><td class="r tnum">${pct(p.success)}</td><td class="r tnum">${fN(p.latency)} ms</td><td class="r tnum">${p.share}%</td><td class="r">${permBtn('system.payment', p.status === 'down' ? L3(['Aktifkan', 'Enable', 'تفعيل']) : L3(['Nonaktifkan', 'Disable', 'تعطيل']), `data-act="prov-toggle" data-id="${p.id}" data-mut`, 'sm ' + (p.status === 'down' ? 'primary' : 'badb'))}</td></tr>`).join('')}</tbody></table></div></section>`,
  cols: [{ k: 'id', label: 'Webhook', render: r => `<b class="mono" style="font-weight:600">${r.id}</b><div class="muted" style="font-size:11.5px">${fDT(r.ts)}</div>` }, { k: 'name', label: 'Event', render: r => `<span class="mono">${r.name}</span>` }, { k: 'provider', label: 'Provider' }, { k: 'payment', label: 'Payment', render: r => `<a class="mono" href="#/finance/payment/${r.payment}">${r.payment}</a>` }, { k: 'code', label: 'HTTP', cls: 'tnum', render: r => `<span class="chip mono" style="color:var(--${r.code === 200 ? 'ok' : 'bad'})">${r.code}</span>` }, { k: 'attempts', label: 'Attempts', cls: 'r tnum' }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  acts: r => r.state === 'failed' ? [{ label: 'Replay', to: 'success', tone: 'primary', perm: 'finance.reconcile', fn: x => { x.code = 200; x.attempts++; }, desc: L3(['Handler idempoten — replay tidak menggandakan ledger.', 'Handler is idempotent — replay never double-posts the ledger.', 'معالج آمن.']) }] : [] }));
A['prov-toggle'] = el => { const p = PROVIDERS.find(x => x.id === el.dataset.id); const off = p.status !== 'down'; confirmAction({ title: (off ? 'Disable ' : 'Enable ') + p.name, desc: off ? L3(['Traffic dialihkan ke provider failover sesuai Payment Configuration.', 'Traffic fails over per Payment Configuration.', 'تحويل الحركة.']) : '', tone: off ? 'danger' : 'primary', reason: true, resource: 'Provider/' + p.name, onOk: r => { p.status = off ? 'down' : 'healthy'; audit('Admin Pusat', 'provider.' + (off ? 'disable' : 'enable'), 'Provider/' + p.name, 'success', { reason: r }); toast(off ? 'warn' : 'ok', p.name + ' · ' + L3(STATUS[p.status].slice(2)), ''); rerender(); } }); };
const DEPOSITS = TRAVELS.filter(x => x.op !== 'inactive').map((x, i) => ({ id: 'DPS-' + x.id.slice(4), name: x.name, travel: x.id, balance: [50, 50, 25, 75, 50][i % 5] * 1e6 - (i % 7 === 3 ? 30e6 : 0), min: 50e6, state: i % 7 === 3 ? 'hold' : 'active' }));
route('/finance/deposit', () => resPage({ id: 'dps', nav: 'fin_dep', noun: 'Deposit', desc: L3(['Deposit jaminan operasional per Travel. Saldo di bawah minimum menahan (hold) settlement.', 'Operational guarantee deposit per Travel. Balance below minimum holds settlements.', 'الوديعة.']), data: DEPOSITS, states: ['active', 'hold'], create: false,
  kpis: () => [{ k: 'Total deposit', v: money(DEPOSITS.reduce((s, d) => s + d.balance, 0)) }, { k: L3(['Di bawah minimum', 'Below minimum', 'أقل من الحد']), v: fN(DEPOSITS.filter(d => d.balance < d.min).length) }, { k: 'Minimum', v: money(50e6) }, { k: 'Tenant', v: fN(DEPOSITS.length) }],
  cols: [{ k: 'name', label: 'Travel', render: r => trvLink(r.travel) }, { k: 'balance', label: L3(['Saldo', 'Balance', 'الرصيد']), cls: 'r tnum', render: r => money(r.balance, true) }, { k: 'min', label: 'Minimum', cls: 'r tnum', render: r => money(r.min, true) }, { k: 'cov', label: L3(['Cakupan', 'Coverage', 'التغطية']), render: r => pctBar(r.balance / r.min, r.balance < r.min ? 'bad' : 'ok'), sort: false }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  acts: r => [{ label: 'Top-up', tone: 'primary', icon: 'plus', fields: [{ k: 'amount', label: 'Jumlah (Rp)', type: 'number', req: true, min: 1e6, step: 1e6, def: Math.max(1e6, r.min - r.balance) }], fn: (x, _, v) => { x.balance += v.amount; if (x.balance >= x.min) x.state = 'active'; } }, { label: L3(['Potong deposit', 'Deduct', 'خصم']), tone: 'badb', fields: [{ k: 'amount', label: 'Jumlah (Rp)', type: 'number', req: true, min: 1e5 }, { k: 'reason', label: t('reason'), type: 'textarea', req: true }], fn: (x, _, v) => { x.balance -= v.amount; if (x.balance < x.min) x.state = 'hold'; } }] }));
const BANK = (() => { const L = []; PAYMENTS.filter(p => p.status === 'paid').forEach((p, i) => { if (p.recon === 'unmatched') return; L.push({ id: 'BNK-' + (60100 + i), ref: p.recon === 'pending' && i % 3 === 0 ? 'TRF ' + ri(1e5, 9e5) : p.ref, amount: p.recon === 'mismatch' ? p.amount - 2500 : p.amount, ts: p.ts + 3 * H, payment: p.recon === 'reconciled' ? p.id : null }); }); for (let k = 0; k < 3; k++) L.push({ id: 'BNK-' + (69000 + k), ref: 'TRF MANUAL ' + ri(100, 999), amount: ri(5, 40) * 1e6, ts: T0 - ri(5, 40) * H, payment: null }); return L; })();
let RECSEL = { p: null, b: null };
route('/finance/reconciliation', () => { const openP = PAYMENTS.filter(p => p.status === 'paid' && p.recon !== 'reconciled'); const openB = BANK.filter(b => !b.payment); const paid = PAYMENTS.filter(p => p.status === 'paid');
  return { html: `<div class="page">${phead({ crumbs: [[t('g_fin'), '/finance'], ['Reconciliation', '/finance/reconciliation']], title: 'Reconciliation', desc: L3(['Pencocokan tiga arah: mutasi bank ↔ ledger ↔ event gateway. Pilih satu payment dan satu mutasi bank untuk match manual.', 'Three-way match: bank statement ↔ ledger ↔ gateway events. Pick one payment and one bank line to match manually.', 'مطابقة ثلاثية.']), actions: permBtn('finance.reconcile', ic('zap') + 'Auto-match', 'data-act="rec-auto" data-mut', '') + permBtn('finance.reconcile', ic('link') + L3(['Match terpilih', 'Match selected', 'مطابقة']), RECSEL.p && RECSEL.b ? 'data-act="rec-match" data-mut' : 'aria-disabled="true" data-tip="' + esc(L3(['Pilih 1 payment & 1 mutasi bank', 'Pick 1 payment & 1 bank line', 'اختر'])) + '"', 'primary') })}
  ${kpiRow([{ k: 'Match rate', v: pct(paid.filter(p => p.recon === 'reconciled').length / paid.length * 100) }, { k: 'Payment belum match', v: fN(openP.length) }, { k: L3(['Mutasi bank belum match', 'Unmatched bank lines', 'حركات غير مطابقة']), v: fN(openB.length) }, { k: L3(['Selisih', 'Difference', 'الفرق']), v: money(openP.reduce((s, p) => s + p.amount, 0) - openB.reduce((s, b) => s + b.amount, 0), true) }])}
  <div class="grid g2" style="margin-top:14px">${pnl('Ledger / gateway', openP.length ? `<div class="list" style="margin:-14px">${openP.map(p => `<button class="li" data-act="rec-pick" data-k="p" data-id="${p.id}" style="${RECSEL.p === p.id ? 'background:var(--accent-soft);box-shadow:inset 3px 0 0 var(--accent)' : ''}"><span class="body"><b class="mono">${p.id}</b><span class="sub">${p.provider} · ref <span class="mono">${esc(p.ref)}</span> · ${fDT(p.ts)}</span></span><b class="tnum">${money(p.amount, true)}</b>${st(p.recon)}</button>`).join('')}</div>` : stateBlock('empty', { title: 'All matched' }), { icon: 'layers', small: openP.length })}
  ${pnl(L3(['Mutasi bank', 'Bank statement', 'كشف البنك']), openB.length ? `<div class="list" style="margin:-14px">${openB.map(b => `<button class="li" data-act="rec-pick" data-k="b" data-id="${b.id}" style="${RECSEL.b === b.id ? 'background:var(--accent-soft);box-shadow:inset 3px 0 0 var(--accent)' : ''}"><span class="body"><b class="mono">${b.id}</b><span class="sub">${esc(b.ref)} · ${fDT(b.ts)}</span></span><b class="tnum">${money(b.amount, true)}</b></button>`).join('')}</div>` : stateBlock('empty'), { icon: 'landmark', small: openB.length })}</div></div>` }; });
Object.assign(A, {
  'rec-pick': el => { RECSEL[el.dataset.k] = RECSEL[el.dataset.k] === el.dataset.id ? null : el.dataset.id; rerender(); },
  'rec-auto': () => { let n = 0; PAYMENTS.filter(p => p.status === 'paid' && p.recon !== 'reconciled').forEach(p => { const b = BANK.find(x => !x.payment && x.ref === p.ref && x.amount === p.amount); if (b) { b.payment = p.id; p.recon = 'reconciled'; n++; } else if (p.recon === 'pending') { const b2 = BANK.find(x => !x.payment && x.amount === p.amount); if (b2) { b2.payment = p.id; p.recon = 'reconciled'; n++; } } }); audit('Admin Pusat', 'reconciliation.auto', 'Batch/REC-' + fD(nowTs(), { day: '2-digit', month: '2-digit' }), 'success', { after: n + ' matched' }); toast('ok', 'Auto-match · ' + n + ' matched', L3(['Sisa butuh review manual', 'Remaining need manual review', 'الباقي يدوي'])); rerender(); },
  'rec-match': () => { const p = PAYMENTS.find(x => x.id === RECSEL.p), b = BANK.find(x => x.id === RECSEL.b); const diff = b.amount - p.amount; confirmAction({ title: 'Match ' + p.id + ' ↔ ' + b.id, desc: diff ? `<b style="color:var(--warn)">${L3(['Selisih', 'Difference', 'الفرق'])} ${money(diff, true)}</b> — ${L3(['akan dicatat sebagai penyesuaian', 'will be booked as an adjustment', 'سيُسجل كتعديل'])}` : L3(['Nominal cocok.', 'Amounts match.', 'المبالغ متطابقة.']), reason: true, resource: p.id, onOk: r => { b.payment = p.id; p.recon = 'reconciled'; RECSEL = { p: null, b: null }; audit('Admin Pusat', 'reconciliation.manual_match', 'Payment/' + p.id + ' ↔ ' + b.id, 'success', { reason: r, after: diff ? 'adjustment ' + diff : null }); toast('ok', 'Matched · ' + p.id, b.id); rerender(); } }); }
});
const FEES = [['Fee platform · Starter', 'Travel · Starter', 'Persentase GMV', 3, 'active'], ['Fee platform · Growth', 'Travel · Growth', 'Persentase GMV', 2.5, 'active'], ['Fee platform · Enterprise', 'Travel · Enterprise', 'Persentase GMV', 1.8, 'active'], ['MDR VA', 'Semua', 'Flat per transaksi', 4000, 'active'], ['MDR QRIS', 'Semua', 'Persentase', 0.7, 'active'], ['MDR Kartu Kredit', 'Semua', 'Persentase', 2.9, 'active'], ['Komisi Affiliate default', 'Affiliate', 'Persentase booking', 2.5, 'active'], ['Fee vendor marketplace', 'Vendor', 'Persentase order', 5, 'draft']].map((f, i) => ({ id: 'FEE-' + (11 + i), name: f[0], scope: f[1], type: f[2], rate: f[3], state: f[4] }));
route('/finance/fee', () => resPage({ id: 'fee', nav: 'fin_fee', noun: 'Aturan fee', desc: L3(['Aturan fee & komisi. Perubahan berlaku untuk transaksi baru dan tercatat before/after.', 'Fee & commission rules. Changes apply to new transactions and are audited before/after.', 'قواعد الرسوم.']), data: FEES, states: ['active', 'draft', 'archived'], newLabel: L3(['Tambah aturan', 'Add rule', 'إضافة']),
  cols: [{ k: 'name', label: L3(['Aturan', 'Rule', 'القاعدة']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'scope', label: 'Scope' }, { k: 'type', label: L3(['Tipe', 'Type', 'النوع']) }, { k: 'rate', label: 'Rate', cls: 'r tnum', render: r => r.type.startsWith('Flat') ? money(r.rate, true) : r.rate + '%' }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'scope', label: 'Scope', type: 'select', options: ['Semua', 'Travel · Starter', 'Travel · Growth', 'Travel · Enterprise', 'Vendor', 'Affiliate'] }, { k: 'type', label: L3(['Tipe', 'Type', 'النوع']), type: 'select', options: ['Persentase GMV', 'Persentase', 'Flat per transaksi', 'Persentase booking', 'Persentase order'] }, { k: 'rate', label: 'Rate', type: 'number', step: '0.1', req: true }], make: v => ({ id: 'FEE-' + (11 + FEES.length), ...v, state: 'draft' }), perm: 'finance.manage',
  acts: r => r.state === 'draft' ? [{ label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary', reason: true }] : r.state === 'active' ? [{ label: t('archive'), to: 'archived', tone: 'badb', reason: true }] : [] }));

/* =============================== SAAS =============================== */
const PLANS = [['Starter', 1490000, 2, 3, 'Tidak', 'Website + Marketplace'], ['Growth', 3490000, 2, 10, 'WhatsApp', 'Website + Marketplace + CRM'], ['Enterprise', 8900000, 2, 50, 'Semua channel', 'Semua modul + SLA']].map((p, i) => ({ id: 'PLAN-' + p[0].toUpperCase(), name: p[0], price: p[1], branches: p[2], seats: p[3], omni: p[4], ent: p[5], tenants: TRAVELS.filter(x => x.sub.plan === p[0]).length, state: 'active' }));
route('/saas/plans', () => resPage({ id: 'plan', nav: 'plan', noun: 'Plan', desc: L3(['Semua plan default mencakup maksimal 2 cabang. Subscription dibayar di muka; trial hanya via request.', 'Every plan covers up to 2 branches by default. Subscriptions are prepaid; trial only via request.', 'الخطط.']), data: PLANS, states: ['active', 'archived'],
  top: () => `<div class="grid g3" style="margin-bottom:14px">${PLANS.map(p => `<section class="panel" style="${p.name === 'Growth' ? 'border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)' : ''}"><div class="panel-b"><div class="eyebrow">${esc(p.name)}</div><div class="kpi" style="padding:0;border:0"><div class="v">${money(p.price, true)}<small class="muted" style="font-size:12px"> /bln</small></div></div><ul style="margin:10px 0 0;padding:0;list-style:none;display:grid;gap:4px;font-size:12.5px"><li>${yes(true, p.branches + ' cabang default')}</li><li>${yes(true, p.seats + ' seat CRM')}</li><li>${yes(p.omni !== 'Tidak', 'Omnichannel: ' + p.omni, 'Omnichannel')}</li><li>${yes(true, esc(p.ent))}</li></ul><div class="muted" style="font-size:12px;margin-top:8px">${p.tenants} tenant</div></div></section>`).join('')}</div>`,
  cols: [{ k: 'name', label: 'Plan', render: r => `<b>${r.name}</b>` }, { k: 'price', label: L3(['Harga/bln', 'Price/mo', 'السعر']), cls: 'r tnum', render: r => money(r.price, true) }, { k: 'branches', label: L3(['Cabang', 'Branches', 'الفروع']), cls: 'r tnum' }, { k: 'seats', label: 'Seat CRM', cls: 'r tnum' }, { k: 'omni', label: 'Omnichannel' }, { k: 'tenants', label: 'Tenant', cls: 'r tnum' }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'price', label: L3(['Harga / bulan (Rp)', 'Price / month (Rp)', 'السعر']), type: 'number', req: true, step: 10000 }, { k: 'seats', label: 'Seat CRM', type: 'number' }, { k: 'omni', label: 'Omnichannel', type: 'select', options: ['Tidak', 'WhatsApp', 'Semua channel'] }], make: v => ({ id: 'PLAN-' + v.name.toUpperCase().replace(/\W/g, ''), ...v, branches: 2, ent: '—', tenants: 0, state: 'active' }), onEdit: r => TRAVELS.forEach(x => { if (x.sub.plan === r.name) x.sub.price = r.price; }),
  acts: r => [r.state === 'active' ? { label: t('archive'), to: 'archived', tone: 'badb', reason: true, why: r.tenants ? L3(['Masih dipakai tenant aktif', 'Still used by tenants', 'مستخدمة']) : null } : { label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }] }));
const ADDONS = [['Cabang tambahan', 450000, '/cabang/bln', TRAVELS.reduce((s, x) => s + x.sub.addonBranch, 0)], ['Seat CRM tambahan', 75000, '/seat/bln', 38], ['Nomor WhatsApp tambahan', 350000, '/nomor/bln', 9], ['Kredit broadcast 10.000', 900000, '/paket', 21]].map((a, i) => ({ id: 'ADD-' + (1 + i), name: a[0], price: a[1], unit: a[2], active: a[3], state: 'active' }));
route('/saas/addons', () => resPage({ id: 'addon', nav: 'addon', noun: 'Add-on', desc: L3(['Add-on berbayar di atas plan. Cabang ke-3 dan seterusnya selalu add-on.', 'Paid add-ons on top of plans. The 3rd branch onward is always an add-on.', 'الإضافات.']), data: ADDONS, states: ['active', 'archived'],
  cols: [{ k: 'name', label: 'Add-on', render: r => `<b>${esc(r.name)}</b>` }, { k: 'price', label: L3(['Harga', 'Price', 'السعر']), cls: 'r tnum', render: r => money(r.price, true) + ' <span class="muted">' + r.unit + '</span>' }, { k: 'active', label: L3(['Aktif', 'Active', 'نشط']), cls: 'r tnum' }, { k: 'mrr', label: 'MRR', cls: 'r tnum', render: r => money(r.price * r.active), sort: false }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'price', label: L3(['Harga (Rp)', 'Price (Rp)', 'السعر']), type: 'number', req: true }, { k: 'unit', label: 'Unit', def: '/bln' }], make: v => ({ id: 'ADD-' + (1 + ADDONS.length), ...v, active: 0, state: 'active' }),
  acts: r => [r.state === 'active' ? { label: t('archive'), to: 'archived', tone: 'badb', reason: true } : { label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }] }));
route('/saas/website', () => { const r = ROUTES.find(x => x.pattern === '/travel/website'); const out = r.fn({}); out.html = out.html.replace(esc(t('travel_web')), esc(t('website'))); return out; });
const STAGES = ['Baru', 'Dihubungi', 'Kualifikasi', 'Penawaran', 'Booking', 'Lost'];
const LEADS = CONTACTS.slice(0, 18).map((c, i) => ({ id: 'LD-' + (4100 + i), name: c.name, travel: TRAVELS[i % 8].id, interest: PKG_TPL[i % PKG_TPL.length][0], value: PKG_TPL[i % PKG_TPL.length][2] * (1 + i % 3), stage: STAGES[i % 6], owner: AGENTS[i % 4].name }));
route('/saas/crm', () => ({ html: `<div class="page">${phead({ crumbs: [[t('g_saas'), '/saas/subscription'], ['CRM', '']], title: 'CRM', desc: L3(['Pipeline lead tenant Travel. Lead dari Omnichannel & Campaign masuk otomatis sebagai "Baru".', 'Travel tenant lead pipeline. Leads from Omnichannel & Campaigns land automatically as "New".', 'خط العملاء.']), actions: permBtn('saas.manage', ic('plus') + L3(['Tambah lead', 'Add lead', 'إضافة']), 'data-act="lead-new" data-mut', 'primary') })}
  ${kpiRow([{ k: 'Lead aktif', v: fN(LEADS.filter(l => !['Booking', 'Lost'].includes(l.stage)).length) }, { k: L3(['Nilai pipeline', 'Pipeline value', 'قيمة']), v: money(LEADS.filter(l => !['Booking', 'Lost'].includes(l.stage)).reduce((s, l) => s + l.value, 0)) }, { k: 'Won', v: fN(LEADS.filter(l => l.stage === 'Booking').length) }, { k: 'Win rate', v: pct(LEADS.filter(l => l.stage === 'Booking').length / Math.max(1, LEADS.filter(l => ['Booking', 'Lost'].includes(l.stage)).length) * 100, 0) }])}
  <div style="display:grid;grid-template-columns:repeat(6,minmax(200px,1fr));gap:10px;overflow-x:auto;margin-top:14px;padding-bottom:6px">${STAGES.map((s, si) => { const L = LEADS.filter(l => l.stage === s); return `<section class="panel" style="background:var(--surface-2)"><div class="panel-h"><h3>${esc(s)}</h3><span class="chip tnum">${L.length}</span></div><div style="padding:8px;display:grid;gap:8px">${L.map(l => `<div class="panel" style="padding:10px"><b style="font-size:13px">${esc(l.name)}</b><div class="muted" style="font-size:12px">${esc(l.interest)}</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:6px"><b class="tnum" style="font-size:12.5px">${money(l.value)}</b><span class="muted" style="font-size:11px">${esc(l.owner.split(' ')[0])}</span></div><div style="display:flex;gap:4px;margin-top:8px">${si > 0 ? `<button class="btn sm ghost" data-act="lead-mv" data-id="${l.id}" data-d="-1" aria-label="Mundur">${icd('chevL', 'sm')}</button>` : ''}<span style="flex:1"></span>${si < STAGES.length - 1 ? `<button class="btn sm" data-act="lead-mv" data-id="${l.id}" data-d="1">${esc(STAGES[si + 1])}${icd('chevR', 'sm')}</button>` : ''}</div></div>`).join('') || `<div class="muted" style="font-size:12px;padding:6px">—</div>`}</div></section>`; }).join('')}</div></div>` }));
Object.assign(A, { 'lead-mv': el => { const l = LEADS.find(x => x.id === el.dataset.id); const i = STAGES.indexOf(l.stage) + +el.dataset.d; const prev = l.stage; l.stage = STAGES[i]; audit('Admin Pusat', 'lead.stage', 'Lead/' + l.id, 'success', { before: prev, after: l.stage }); if (l.stage === 'Booking') toast('ok', L3(['Lead menjadi booking', 'Lead won', 'تم الفوز']), l.name + ' · ' + money(l.value)); rerender(); },
  'lead-new': () => { modal({ title: L3(['Tambah lead', 'Add lead', 'إضافة']), body: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'interest', label: L3(['Minat paket', 'Package interest', 'الاهتمام']), type: 'select', options: PKG_TPL.map(p => p[0]) }, { k: 'travel', label: 'Travel', type: 'select', options: travelOpts }].map(f => fieldHTML(f, null, 'ld-')).join(''), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="lead-save">${t('save')}</button>` }); },
  'lead-save': () => { const v = formVals([{ k: 'name', req: true }, { k: 'interest' }, { k: 'travel' }], 'ld-'); if (!v) return; LEADS.unshift({ id: 'LD-' + (4100 + LEADS.length), ...v, value: (PKG_TPL.find(p => p[0] === v.interest) || [0, 0, 30e6])[2], stage: 'Baru', owner: AGENTS[0].name }); closeOverlays(); toast('ok', 'Lead dibuat', v.name); rerender(); } });

/* =============================== PLATFORM =============================== */
const USERS = [['Admin Pusat', 'admin@segaloka.example', 'super_admin', true], ['Reza Pratama', 'reza@segaloka.example', 'compliance', true], ['Maya Safitri', 'maya@segaloka.example', 'finance_ops', true], ['Rahma Aulia', 'rahma@segaloka.example', 'cs_agent', true], ['Fikri Hidayat', 'fikri@segaloka.example', 'cs_agent', true], ['Salma Nur', 'salma@segaloka.example', 'cs_agent', false], ['Dimas Arya', 'dimas@segaloka.example', 'finance_ops', true], ['Tim Risk', 'risk@segaloka.example', 'compliance', true], ['Budi (magang)', 'budi@segaloka.example', 'cs_agent', false]].map((u, i) => ({ id: 'USR-' + (1001 + i), name: u[0], email: u[1], role: u[2], mfa: u[3], last: T0 - (i * 5 + 1) * H, state: i === 8 ? 'pending' : i === 5 ? 'suspended' : 'active' }));
route('/platform/users', () => resPage({ id: 'usr', nav: 'users', noun: 'User', desc: L3(['User platform. Akses ditentukan oleh permission granular pada role, bukan nama role.', 'Platform users. Access is determined by granular permissions on roles, not role names.', 'المستخدمون.']), data: USERS, states: ['active', 'pending', 'suspended'], newLabel: L3(['Undang user', 'Invite user', 'دعوة']), perm: 'platform.manage',
  cols: [{ k: 'name', label: 'User', render: r => ent(r.name, r.email, colorFor(r.name)) }, { k: 'role', label: 'Role', render: r => `<span class="chip">${esc((ROLES[r.role] || { label: r.role }).label)}</span>` }, { k: 'mfa', label: '2FA', render: r => st(r.mfa ? 'active' : 'inactive') }, { k: 'last', label: L3(['Login terakhir', 'Last login', 'آخر دخول']), render: r => r.state === 'pending' ? '—' : rel(r.last) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: () => [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'email', label: 'Email', type: 'email', req: true }, { k: 'role', label: 'Role', type: 'select', options: Object.entries(ROLES).map(([k, r]) => [k, r.label]) }], make: v => ({ id: 'USR-' + (1001 + USERS.length), ...v, mfa: false, last: 0, state: 'pending' }),
  acts: r => ({ active: [{ label: 'Suspend', to: 'suspended', tone: 'badb', reason: true, why: r.id === 'USR-1001' ? L3(['Tidak bisa suspend akun sendiri', 'Cannot suspend yourself', 'لا يمكن']) : null }, { label: L3(['Reset 2FA', 'Reset 2FA', 'إعادة 2FA']), reason: true, fn: x => x.mfa = false }], pending: [{ label: L3(['Kirim ulang undangan', 'Resend invite', 'إعادة الدعوة']), confirm: false, fn: () => {}, msg: L3(['Email undangan dikirim ulang', 'Invite email resent', 'أُعيد الإرسال']) }], suspended: [{ label: t('reactivate'), to: 'active', tone: 'primary', reason: true }] })[r.state] }));
const PERM_CATALOG = [['Utama', ['overview.view', 'approval.view', 'approval.decide:travel', 'approval.decide:vendor', 'approval.decide:legal', 'approval.decide:finance', 'approval.decide:security', 'approval.decide:ads']], ['Ekosistem', ['travel.view', 'travel.create', 'travel.edit', 'travel.suspend', 'vendor.view', 'vendor.manage', 'affiliate.view', 'mitra.view', 'traveler.view']], ['Marketplace', ['marketplace.view', 'marketplace.moderate']], ['Omnichannel', ['omni.view', 'omni.reply', 'omni.assign', 'omni.manage']], ['Ads', ['ads.view', 'ads.create', 'ads.manage', 'ads.approve']], ['Booking', ['booking.view', 'booking.manage']], ['Keuangan', ['finance.view', 'finance.withdrawal', 'finance.refund', 'finance.reconcile', 'finance.manage']], ['SaaS', ['saas.view', 'saas.manage']], ['Platform', ['platform.view', 'platform.manage']], ['Compliance', ['compliance.view', 'compliance.verify', 'audit.view']], ['Analytics', ['analytics.view']], ['System', ['system.view', 'system.brand', 'system.payment']]];
let ROLEDRAFT = null;
const hasP = (ps, p) => ps.includes('*') || ps.includes(p) || ps.includes(p.split(/[.:]/)[0] + '.*');
route('/platform/roles', () => { if (!ROLEDRAFT) ROLEDRAFT = Object.fromEntries(Object.entries(ROLES).map(([k, r]) => [k, [...r.perms]])); const keys = Object.keys(ROLES); const changed = keys.filter(k => JSON.stringify(ROLEDRAFT[k].slice().sort()) !== JSON.stringify(ROLES[k].perms.slice().sort()));
  return { html: `<div class="page">${phead({ crumbs: [[t('g_plat'), '/platform/users'], [t('roles'), '']], title: t('roles'), desc: L3(['Role = kumpulan permission granular. UI membaca permission dari backend; mengubah matrix di sini langsung mengubah menu & aksi yang tersedia untuk role tersebut.', 'Role = set of granular permissions. The UI reads permissions from the backend; changing this matrix immediately changes the menus & actions available to that role.', 'الأدوار والصلاحيات.']), actions: (changed.length ? `<span class="st warn">${ic('alert')}${changed.length} role ${L3(['berubah', 'changed', 'تغير'])}</span><button class="btn" data-act="role-reset">${L3(['Batalkan', 'Discard', 'تجاهل'])}</button>` : '') + permBtn('platform.manage', ic('check') + L3(['Simpan perubahan', 'Save changes', 'حفظ']), changed.length ? 'data-act="role-save" data-mut' : 'aria-disabled="true" data-tip="' + esc(L3(['Tidak ada perubahan', 'No changes', 'لا تغييرات'])) + '"', 'primary') })}
  <section class="panel"><div class="tbl-wrap"><table class="t"><thead><tr><th>Permission</th>${keys.map(k => `<th style="text-align:center">${esc(ROLES[k].label)}${k === 'super_admin' ? ' 🔒' : ''}</th>`).join('')}</tr></thead><tbody>${PERM_CATALOG.map(([g, ps]) => `<tr><td colspan="${keys.length + 1}" style="background:var(--surface-2);font-size:11px;letter-spacing:.08em;text-transform:uppercase;font-weight:650;color:var(--ink-2)">${g}</td></tr>${ps.map(p => `<tr><td class="mono" style="font-size:12px">${p}</td>${keys.map(k => { const on = hasP(ROLEDRAFT[k], p); const orig = hasP(ROLES[k].perms, p); return `<td style="text-align:center;${on !== orig ? 'background:var(--warn-bg)' : ''}"><input type="checkbox" aria-label="${esc(k + ' ' + p)}" data-act="role-cell" data-r="${k}" data-p="${p}" ${on ? 'checked' : ''} ${k === 'super_admin' || !can('platform.manage') ? 'disabled' : ''}></td>`; }).join('')}</tr>`).join('')}`).join('')}</tbody></table></div></section></div>` }; });
Object.assign(A, { 'role-cell': el => { const ps = ROLEDRAFT[el.dataset.r]; const p = el.dataset.p; const base = p.split(/[.:]/)[0] + '.*'; if (el.checked) ps.push(p); else { if (ps.includes(base)) { ps.splice(ps.indexOf(base), 1); PERM_CATALOG.flatMap(x => x[1]).filter(q => q.startsWith(p.split(/[.:]/)[0] + '.') || q.startsWith(p.split(/[.:]/)[0] + ':')).forEach(q => { if (q !== p && !ps.includes(q)) ps.push(q); }); } const i = ps.indexOf(p); if (i >= 0) ps.splice(i, 1); } rerender(); },
  'role-reset': () => { ROLEDRAFT = null; rerender(); },
  'role-save': () => { const keys = Object.keys(ROLES).filter(k => JSON.stringify(ROLEDRAFT[k].slice().sort()) !== JSON.stringify(ROLES[k].perms.slice().sort())); const diff = keys.map(k => { const add = ROLEDRAFT[k].filter(p => !ROLES[k].perms.includes(p)), rm = ROLES[k].perms.filter(p => !ROLEDRAFT[k].includes(p)); return `<div style="margin-bottom:8px"><b>${esc(ROLES[k].label)}</b><div class="mono" style="font-size:12px">${add.map(p => `<span style="color:var(--ok)">+ ${p}</span>`).join('<br>')}${add.length && rm.length ? '<br>' : ''}${rm.map(p => `<span style="color:var(--bad)">− ${p}</span>`).join('<br>')}</div></div>`; }).join(''); confirmAction({ title: L3(['Ubah permission', 'Change permissions', 'تغيير الصلاحيات']), desc: diff, tone: 'danger', reason: true, resource: keys.join(', '), onOk: r => { keys.forEach(k => { audit('Admin Pusat', 'role.update', 'Role/' + k, 'success', { before: JSON.stringify(ROLES[k].perms), after: JSON.stringify(ROLEDRAFT[k]), reason: r }); ROLES[k].perms = [...ROLEDRAFT[k]]; }); ROLEDRAFT = null; toast('ok', L3(['Permission diperbarui', 'Permissions updated', 'تم التحديث']), L3(['User dengan role ini melihat perubahan tanpa logout', 'Users with these roles see changes without logging out', 'دون تسجيل خروج'])); renderSide(); rerender(); } }); } });
route('/platform/notification', () => resPage({ id: 'ntf', nav: 'notif', noun: 'Notifikasi', desc: L3(['Riwayat notifikasi Anda. Setiap notifikasi deep-link ke resource terkait.', 'Your notification history. Every notification deep-links to its resource.', 'سجل الإشعارات.']), data: NOTIFS, rows: () => NOTIFS.map((n, i) => Object.assign(n, { id: n.id || 'NTF-' + (500 + i), name: n.title, state: n.unread ? 'open' : 'closed' })), filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'u', label: 'Unread', fn: r => r.unread }], create: false, topActs: `<button class="btn" data-act="notif-read2">${t('mark_all')}</button>`,
  cols: [{ k: 'title', label: L3(['Notifikasi', 'Notification', 'الإشعار']), render: r => `<b style="font-weight:${r.unread ? 700 : 500}">${esc(r.title)}</b><div class="muted" style="font-size:12px">${esc(r.sub)}</div>` }, { k: 'cat', label: L3(['Kategori', 'Category', 'الفئة']), render: r => `<span class="chip">${r.cat}</span>` }, { k: 'ts', label: L3(['Waktu', 'Time', 'الوقت']), render: r => rel(r.ts) }, { k: 'route', label: 'Resource', render: r => `<a class="mono" href="#${r.route}">${esc(r.route)}</a>` }],
  acts: r => [r.unread ? { label: L3(['Tandai dibaca', 'Mark read', 'مقروء']), confirm: false, fn: x => x.unread = false } : { label: L3(['Tandai belum dibaca', 'Mark unread', 'غير مقروء']), confirm: false, fn: x => x.unread = true }] }));
A['notif-read2'] = () => { NOTIFS.forEach(n => n.unread = false); renderTop(); rerender(); };
const AICHAT = [];
function aiAnswer(q) { try { return aiAnswer0(q); } catch (e) { return L3(['Belum ada data yang cukup untuk menjawab pertanyaan ini.', 'Not enough data yet to answer this.', 'لا توجد بيانات كافية بعد.']); } }
function aiAnswer0(q) { const s = q.toLowerCase(); const L = (a, b) => `<a href="#${b}">${esc(a)}</a>`;
  if (/approval|persetujuan|موافق/.test(s)) { const o = APPROVALS.filter(a => ['waiting', 'in_progress'].includes(a.status)); return `${o.length} approval ${L3(['terbuka', 'open', 'مفتوحة'])}, ${o.filter(a => a.priority === 'p1').length} ${L3(['prioritas tinggi', 'high priority', 'عالية'])}. ${L3(['Risiko tertinggi', 'Highest risk', 'الأعلى خطورة'])}: ${L(o.sort((a, b) => b.risk - a.risk)[0].title, '/approval/' + o[0].id)} (risk ${o[0].risk}).`; }
  if (/izin|legal|ppiu|pihk|bpw|expired/.test(s)) { const ex = TRAVELS.filter(x => ['expired', 'expiring', 'rejected'].includes(x.legal)); return `${ex.length} Travel ${L3(['dengan legalitas bermasalah', 'with legality issues', 'بمشكلات ترخيص'])}: ${ex.slice(0, 4).map(x => L(x.name + ' (' + L3(STATUS[x.legal].slice(2)) + ')', '/travel/' + x.id + '/legal')).join(', ')}${ex.length > 4 ? '…' : ''}. ${L('Legalitas & Perizinan', '/travel/legal')}`; }
  if (/campaign|roas|iklan|ads/.test(s)) { const c = CAMPAIGNS.filter(x => x.spent).sort((a, b) => campRoas(b) - campRoas(a)); return `ROAS ${L3(['tertinggi', 'highest', 'الأعلى'])}: ${L(c[0].name, '/ads/campaign/' + c[0].id)} (${fN(campRoas(c[0]), { maximumFractionDigits: 1 })}×). ${L3(['Terendah', 'Lowest', 'الأدنى'])}: ${L(c[c.length - 1].name, '/ads/campaign/' + c[c.length - 1].id)} (${fN(campRoas(c[c.length - 1]), { maximumFractionDigits: 1 })}×).`; }
  if (/settle|withdraw|refund|rekonsil|recon|keuangan|finance/.test(s)) return `Settlement: ${SETTLEMENTS.filter(x => x.state === 'failed').length} failed, ${SETTLEMENTS.filter(x => x.state === 'hold').length} hold. Withdrawal pending: ${WITHDRAWALS.filter(w => w.state === 'pending').length} (${money(WITHDRAWALS.filter(w => w.state === 'pending').reduce((s, w) => s + w.amount, 0))}). Unmatched: ${PAYMENTS.filter(p => ['unmatched', 'mismatch'].includes(p.recon)).length}. ${L('Finance Overview', '/finance')} · ${L('Reconciliation', '/finance/reconciliation')}`;
  if (/sla|inbox|percakapan|chat|pesan/.test(s)) return `${CONVERSATIONS.filter(c => c.status === 'open').length} open, ${CONVERSATIONS.filter(c => !c.assignee && ['open', 'pending'].includes(c.status)).length} unassigned, ${CONVERSATIONS.filter(c => c.sla != null && c.sla < 0).length} SLA breach. ${L('Inbox', '/omni/inbox')}`;
  const tr = TRAVELS.find(x => s.includes(x.name.toLowerCase().split(' ')[0].toLowerCase()) || s.includes(x.id.toLowerCase())); if (tr) return `${L(tr.name, '/travel/' + tr.id)} · ${L3(STATUS[tr.op === 'review' ? 'review' : tr.op].slice(2))} · legal ${L3(STATUS[tr.legal].slice(2))} · ${tr.sub.plan} (${L3(STATUS[tr.sub.state].slice(2))}) · GMV 30d ${money(tr.gmv30)} · ${tr.payMode}.`;
  return L3(['Saya bisa merangkum: approval, legalitas/izin, campaign & ROAS, settlement/withdrawal/refund, Inbox & SLA, atau Travel tertentu (sebut nama/ID).', 'I can summarize: approvals, legality/licences, campaigns & ROAS, settlement/withdrawal/refund, Inbox & SLA, or a specific Travel (name/ID).', 'يمكنني تلخيص: الموافقات، التراخيص، الحملات، المالية، صندوق الوارد.']); }
route('/platform/ai', () => ({ html: `<div class="page">${phead({ crumbs: [[t('g_plat'), '/platform/users'], ['Segaloka AI', '']], title: 'Segaloka AI', desc: L3(['Asisten lintas domain yang membaca state platform. AI hanya merangkum & menyarankan — tidak menggantikan authorization, permission, policy, validation, maupun business rules, dan tidak mengeksekusi aksi.', 'A cross-domain assistant that reads platform state. It only summarizes & suggests — it never replaces authorization, permission, policy, validation or business rules, and never executes actions.', 'مساعد يلخص فقط.']) })}
  <div class="banner warn" style="border:1px solid var(--warn-line);border-radius:10px;margin-bottom:14px">${ic('flag')}<span>${L3(['Mode demo: jawaban dihitung lokal dari data simulasi, bukan model AI sungguhan.', 'Demo mode: answers are computed locally from mock data, not a real AI model.', 'وضع العرض: إجابات محلية.'])}</span></div>
  <section class="panel" style="display:flex;flex-direction:column;min-height:420px"><div class="chat" id="aichat" style="min-height:300px">${AICHAT.length ? AICHAT.map(m => `<div class="msg ${m.me ? 'out' : 'in'}">${m.me ? esc(m.t) : m.t}</div>`).join('') : `<div class="msg sys">${L3(['Tanyakan sesuatu tentang platform…', 'Ask something about the platform…', 'اسأل…'])}</div>`}</div>
  <div class="composer"><div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px">${[L3(['Approval apa yang paling berisiko?', 'Which approval is riskiest?', 'أخطر موافقة؟']), L3(['Travel dengan izin bermasalah', 'Travels with licence issues', 'تراخيص']), L3(['Campaign ROAS tertinggi', 'Highest ROAS campaign', 'أعلى عائد']), L3(['Ringkas keuangan hari ini', 'Summarize finance today', 'ملخص مالي']), L3(['Kondisi Inbox & SLA', 'Inbox & SLA status', 'حالة الوارد'])].map(p => `<button class="fchip" data-act="ai-ask" data-q="${esc(p)}">${ic('sparkles', 'sm')}${esc(p)}</button>`).join('')}</div><div style="display:flex;gap:8px"><label class="input" style="flex:1;min-width:0"><span class="sr">Pertanyaan</span><input id="aiq" placeholder="${L3(['Tulis pertanyaan…', 'Type a question…', 'اكتب سؤالاً…'])}"></label><button class="btn primary" data-act="ai-ask">${icd('send', 'sm')}${t('send')}</button></div></div></section></div>`, mount() { const q = document.getElementById('aiq'); q.addEventListener('keydown', e => { if (e.key === 'Enter') A['ai-ask']({ dataset: {} }); }); const c = document.getElementById('aichat'); c.scrollTop = c.scrollHeight; } }));
A['ai-ask'] = el => { const q = (el.dataset && el.dataset.q) || document.getElementById('aiq').value.trim(); if (!q) return; AICHAT.push({ me: true, t: q }, { me: false, t: aiAnswer(q) }); rerender(); const i = document.getElementById('aiq'); if (i) i.focus(); };

/* =============================== COMPLIANCE =============================== */
const SECEV = [['Login gagal berulang', 'admin@segaloka', '103.21.x.x', 'bad', 'open'], ['Login dari negara baru', 'maya@segaloka', '5.62.x.x (SG)', 'warn', 'open'], ['API key dibuat', 'Integrasi Xendit', 'Control Center', 'neu', 'resolved'], ['2FA dinonaktifkan', 'salma@segaloka', 'Control Center', 'warn', 'open'], ['Akses dokumen legal massal', 'reza@segaloka', '36.72.x.x', 'warn', 'in_progress'], ['Token webhook dirotasi', 'System', 'Worker', 'neu', 'resolved'], ['Percobaan akses tanpa permission', 'budi@segaloka', '/finance/withdrawal', 'warn', 'open'], ['Password reset', 'fikri@segaloka', 'Email', 'neu', 'resolved']].map((e, i) => ({ id: 'SEC-' + (7100 + i), name: e[0], actor: e[1], source: e[2], sev: e[3], state: e[4], ts: T0 - (i * 3 + 1) * H }));
const SECPOL = { mfa: true, ipblock: true, session: 12 };
route('/compliance/security', () => resPage({ id: 'sec', nav: 'security', noun: 'Event', desc: L3(['Event keamanan: login, sesi, 2FA, API key, akses tanpa permission.', 'Security events: logins, sessions, 2FA, API keys, unauthorized access.', 'أحداث الأمان.']), data: SECEV, states: ['open', 'in_progress', 'resolved'], create: false,
  top: () => `<section class="panel" style="margin-bottom:14px"><div class="panel-h"><h3>${ic('shield', 'sm')}${L3(['Kebijakan', 'Policy', 'السياسة'])}</h3>${permBtn('compliance.manage', ic('check', 'sm') + t('save'), 'data-act="secpol-save" data-mut', 'sm primary')}</div><div class="panel-b" style="display:flex;gap:24px;flex-wrap:wrap;align-items:center"><label style="display:flex;gap:8px;font-size:13px"><input type="checkbox" id="sp-mfa" ${SECPOL.mfa ? 'checked' : ''}> ${L3(['Wajib 2FA untuk semua admin', 'Require 2FA for all admins', 'إلزام 2FA'])}</label><label style="display:flex;gap:8px;font-size:13px"><input type="checkbox" id="sp-ip" ${SECPOL.ipblock ? 'checked' : ''}> ${L3(['Blokir IP setelah 10 login gagal', 'Block IP after 10 failed logins', 'حظر IP'])}</label><label style="display:flex;gap:8px;font-size:13px;align-items:center">${L3(['Sesi berakhir (jam)', 'Session timeout (h)', 'انتهاء الجلسة'])} <input type="number" id="sp-s" value="${SECPOL.session}" min="1" max="72" style="width:70px;border:1px solid var(--line-strong);border-radius:6px;padding:4px 6px;background:var(--surface)"></label><span class="muted" style="font-size:12px">2FA coverage: ${pct(USERS.filter(u => u.mfa).length / USERS.length * 100, 0)}</span></div></section>`,
  cols: [{ k: 'name', label: 'Event', render: r => `<div style="display:flex;gap:8px;align-items:center"><span class="sev ${r.sev}" style="height:28px"></span><b>${esc(r.name)}</b></div>` }, { k: 'actor', label: 'Actor', render: r => `<span class="mono" style="font-size:12px">${esc(r.actor)}</span>` }, { k: 'source', label: 'Source', render: r => `<span class="mono" style="font-size:12px">${esc(r.source)}</span>` }, { k: 'ts', label: L3(['Waktu', 'Time', 'الوقت']), render: r => rel(r.ts) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  acts: r => r.state === 'resolved' ? [] : [{ label: L3(['Investigasi', 'Investigate', 'تحقيق']), to: 'in_progress', when: r.state === 'open', confirm: false }, { label: t('resolve'), to: 'resolved', tone: 'primary', reason: true }, { label: L3(['Blokir actor', 'Block actor', 'حظر']), tone: 'badb', reason: true, when: /@/.test(r.actor), fn: x => { const u = USERS.find(u => u.email.startsWith(x.actor.split('@')[0])); if (u) u.state = 'suspended'; x.state = 'resolved'; }, msg: L3(['Akun di-suspend & sesi dicabut', 'Account suspended & sessions revoked', 'عُلّق الحساب']) }] }));
A['secpol-save'] = () => { const b = JSON.stringify(SECPOL); SECPOL.mfa = document.getElementById('sp-mfa').checked; SECPOL.ipblock = document.getElementById('sp-ip').checked; SECPOL.session = +document.getElementById('sp-s').value; audit('Admin Pusat', 'security.policy.update', 'Config/security', 'success', { before: b, after: JSON.stringify(SECPOL) }); toast('ok', L3(['Kebijakan keamanan disimpan', 'Security policy saved', 'تم الحفظ']), ''); };
const RISKS = [['Pola refund tidak wajar', 'Traveler · 3 refund dari 1 device', 81, 'open'], ['Chargeback kartu kredit', 'PAY-7700250 · Rp 12,4 jt', 64, 'in_progress'], ['Perubahan rekening + device baru', 'Zamzam Barokah Travel', 81, 'open'], ['Lonjakan withdrawal vendor', 'Al-Kiswah Hospitality · 3× rata-rata', 52, 'open'], ['Voucher abuse', 'UMRAH1448 · 14 akun baru', 47, 'resolved'], ['Duplikasi identitas jamaah', '2 booking, paspor sama', 38, 'open']].map((r, i) => ({ id: 'RSK-' + (301 + i), name: r[0], subject: r[1], score: r[2], state: r[3], hold: false, owner: i % 2 ? 'Tim Risk' : null }));
route('/compliance/risk', () => resPage({ id: 'risk', nav: 'risk', noun: 'Kasus', desc: L3(['Kasus risiko & fraud dari rule engine. Hold dana menahan settlement/withdrawal terkait sampai kasus selesai.', 'Risk & fraud cases from the rule engine. Holding funds pauses related settlements/withdrawals until resolved.', 'حالات المخاطر.']), data: RISKS, states: ['open', 'in_progress', 'resolved', 'closed'], lifecycle: ['open', 'in_progress', 'resolved', 'closed'], create: false,
  cols: [{ k: 'name', label: L3(['Kasus', 'Case', 'الحالة']), render: r => `<b>${esc(r.name)}</b><div class="muted" style="font-size:12px">${esc(r.subject)}</div>` }, { k: 'score', label: 'Score', render: r => `<b class="tnum" style="color:var(--${r.score >= 60 ? 'bad' : r.score >= 40 ? 'warn' : 'ok'})">${r.score}</b>` }, { k: 'hold', label: 'Hold', render: r => r.hold ? st('hold') : '—' }, { k: 'owner', label: 'Owner', render: r => esc(r.owner || '—') }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  acts: r => r.state === 'closed' ? [] : [{ label: L3(['Ambil kasus', 'Take case', 'استلام']), to: 'in_progress', when: r.state === 'open', confirm: false, fn: x => x.owner = 'Admin Pusat' }, { label: L3(['Hold dana', 'Hold funds', 'احتجاز']), tone: 'warnb', reason: true, when: !r.hold && r.state !== 'resolved', fn: x => x.hold = true }, { label: t('resolve'), to: 'resolved', tone: 'primary', reason: true, when: r.state !== 'resolved', fn: x => x.hold = false }, { label: t('close'), to: 'closed', when: r.state === 'resolved', confirm: false }] }));

/* =============================== ANALYTICS =============================== */
const anaHead = (nav, desc) => phead({ crumbs: [[t('g_ana'), '/analytics/executive'], [t(nav), '']], title: t(nav), desc, actions: periodSel() + `<button class="btn" data-act="export" data-what="${esc(t(nav))}">${ic('download')}Export</button>` });
const sumK = k => ser().reduce((s, d) => s + d[k], 0);
const ANA = {
 an_exec: () => { const g = sumK('gmv'); return `${kpiRow([{ k: 'GMV', v: money(g), d: realDelta('gmv') }, { k: L3(['Revenue platform', 'Platform revenue', 'الإيرادات']), v: money(platRev()), d: '' }, { k: 'Take rate', v: g ? pct(platRev() / g * 100) : '—' }, { k: 'Booking', v: fN(sumK('book')), d: realDelta('book') }])}<div class="grid g12" style="margin-top:14px"><div class="c8">${pnl('GMV', areaChart(ser(), { key: 'gmv', fmt: v => money(v) }), { icon: 'trend' })}</div><div class="c4">${pnl(L3(['Revenue per sumber', 'Revenue by source', 'الإيرادات حسب المصدر']), hbars([['Fee marketplace', platformRevenue(perPaid()) - perPaid().reduce((s, p) => s + (p.fee || 0), 0)], ['Subscription (MRR)', TRAVELS.filter(x => x.sub.state === 'active').reduce((s, x) => s + x.sub.price, 0) * PERIOD / 30], ['Payment fee', perPaid().reduce((s, p) => s + (p.fee || 0), 0)], ['Ads', CAMPAIGNS.reduce((s, c) => s + (c.spent || 0), 0)]], v => money(v)), { icon: 'bars' })}</div></div><section class="panel" style="margin-top:14px"><div class="panel-h"><h3>Top Travel</h3></div><div class="tbl-wrap"><table class="t"><thead><tr><th>Travel</th><th class="r">GMV</th><th class="r">Booking</th><th>Plan</th><th>Legal</th></tr></thead><tbody>${TRAVELS.slice().sort((a, b) => b.gmv30 - a.gmv30).slice(0, 8).map(x => `<tr class="clickable" data-href="/travel/${x.id}"><td>${ent(x.name, x.id, x.color)}</td><td class="r tnum">${money(x.gmv30)}</td><td class="r tnum">${x.book30}</td><td>${x.sub.plan}</td><td>${st(x.legal)}</td></tr>`).join('')}</tbody></table></div></section>`; },
 an_mp: () => { const v = PACKAGES.reduce((s, p) => s + p.views30, 0); return `${kpiRow([{ k: 'Views', v: fC(v) }, { k: 'Booking', v: fN(sumK('book')) }, { k: 'CVR', v: pct(sumK('book') / v * 100, 2) }, { k: 'Listing aktif', v: fN(PACKAGES.filter(p => p.state === 'published').length) }])}<div class="grid g2" style="margin-top:14px">${pnl('Funnel', hbars([['View paket', v], ['Booking', sumK('book')], ['Paid', BOOKINGS.filter(b => b.created >= nowTs() - PERIOD * D && b.paid > 0).length]], fC), { icon: 'funnel' })}${pnl(L3(['Kategori', 'Categories', 'الفئات']), hbars(['Umrah', 'Haji', 'Halal Tour', 'Tour'].map(c => [c, PACKAGES.filter(p => p.cat === c).reduce((s, p) => s + p.sold * p.price, 0)]), v => money(v)), { icon: 'grid' })}</div><div style="margin-top:14px">${pnl('Booking / hari', barChart(ser(), { key: 'book', fmt: v => fN(Math.round(v)) }), { icon: 'bars' })}</div>`; },
 an_travel: () => `${kpiRow([{ k: 'Travel aktif', v: fN(TRAVELS.filter(x => x.op === 'active').length) }, { k: 'Legal OK', v: pct(TRAVELS.filter(x => ['verified', 'expiring'].includes(x.legal)).length / TRAVELS.length * 100, 0) }, { k: 'Sub aktif', v: pct(TRAVELS.filter(x => x.sub.state === 'active').length / TRAVELS.length * 100, 0) }, { k: 'Seat terisi', v: pct(PACKAGES.reduce((s, p) => s + p.sold, 0) / PACKAGES.reduce((s, p) => s + p.seats, 0) * 100, 0) }])}<div class="grid g2" style="margin-top:14px">${pnl('GMV per Travel', hbars(TRAVELS.slice().sort((a, b) => b.gmv30 - a.gmv30).slice(0, 10).map(x => [x.name, x.gmv30]), v => money(v)), { icon: 'bars' })}${pnl(L3(['Kesehatan legal', 'Legal health', 'الصحة القانونية']), hbars(['verified', 'expiring', 'under_review', 'expired', 'rejected'].map(s => [L3(STATUS[s].slice(2)), TRAVELS.filter(x => x.legal === s).length, s === 'verified' ? 'var(--s3)' : s === 'expiring' || s === 'under_review' ? 'var(--s1)' : 'var(--s2)']), fN), { icon: 'filecheck' })}</div>`,
 an_vendor: () => `${kpiRow([{ k: 'Vendor', v: fN(VENDORS.length) }, { k: 'GMV', v: money(VENDORS.reduce((s, v) => s + v.gmv30, 0)) }, { k: 'SLA rata-rata', v: pct(VENDORS.reduce((s, v) => s + v.sla, 0) / VENDORS.length, 0) }, { k: 'Order', v: fN(VENDORS.reduce((s, v) => s + v.orders30, 0)) }])}<div class="grid g2" style="margin-top:14px">${pnl('GMV per vendor', hbars(VENDORS.slice().sort((a, b) => b.gmv30 - a.gmv30).slice(0, 10).map(v => [v.name, v.gmv30]), v => money(v)), { icon: 'bars' })}${pnl('SLA', hbars(VENDORS.slice().sort((a, b) => a.sla - b.sla).slice(0, 10).map(v => [v.name, v.sla, v.sla < 90 ? 'var(--s2)' : 'var(--s3)']), v => v + '%'), { icon: 'timer' })}</div>`,
 an_fin: () => { const paid = PAYMENTS.filter(p => p.status === 'paid'); return `${kpiRow([{ k: 'Volume', v: money(sumK('gmv')) }, { k: 'Success rate', v: pct(paid.length / PAYMENTS.length * 100, 0) }, { k: 'Recon match', v: pct(paid.filter(p => p.recon === 'reconciled').length / paid.length * 100, 0) }, { k: 'Withdrawal pending', v: money(WITHDRAWALS.filter(w => w.state === 'pending').reduce((s, w) => s + w.amount, 0)) }])}<div class="grid g12" style="margin-top:14px"><div class="c8">${pnl('Volume', areaChart(ser(), { key: 'gmv', fmt: v => money(v) }), { icon: 'trend' })}</div><div class="c4">${pnl('Payment flow', hbars([['VIA_SEGALOKA', paid.filter(p => p.flow === 'VIA_SEGALOKA').reduce((s, p) => s + p.amount, 0)], ['DIRECT_TO_TRAVEL', paid.filter(p => p.flow === 'DIRECT_TO_TRAVEL').reduce((s, p) => s + p.amount, 0)]], v => money(v)), { icon: 'repeat' })}<div style="margin-top:14px">${pnl('Withdrawal', hbars(['Vendor', 'Travel', 'Affiliate'].map(k => [k, WITHDRAWALS.filter(w => w.partyType === k).reduce((s, w) => s + w.amount, 0)]), v => money(v)), { icon: 'arrowur' })}</div></div></div>`; },
 an_omni: () => omniAnaBody(),
 an_ads: () => { const L = CAMPAIGNS.filter(c => c.spent); const s = L.reduce((a, c) => a + c.spent, 0), r = L.reduce((a, c) => a + c.revenue, 0); return `${kpiRow([{ k: 'Spend', v: money(s) }, { k: L3(['Revenue teratribusi', 'Attributed revenue', 'إيرادات']), v: money(r) }, { k: 'ROAS', v: fN(r / s, { maximumFractionDigits: 1 }) + '×' }, { k: L3(['Share GMV dari Ads', 'Share of GMV from Ads', 'حصة']), v: pct(r / Math.max(1, sumK('gmv') * 90 / PERIOD) * 100, 1) }])}<div class="grid g2" style="margin-top:14px">${pnl('Spend', areaChart(ser(), { key: 'spend', fmt: v => money(v), h: 160 }), { icon: 'trend' })}${pnl(L3(['Revenue per channel', 'Revenue by channel', 'حسب القناة']), hbars(AD_CHANNELS.map(ch => [ch, L.filter(c => c.channels.includes(ch)).reduce((a, c) => a + c.revenue / c.channels.length, 0)]).filter(x => x[1]), v => money(v)) + `<div class="muted" style="font-size:12px;margin-top:8px">Website Segaloka ${money(L.reduce((a, c) => a + c.revenue * c.channels.filter(ch => AD_SURF(ch) === 'Website Segaloka').length / c.channels.length, 0))} · Aplikasi Segaloka ${money(L.reduce((a, c) => a + c.revenue * c.channels.filter(ch => AD_SURF(ch) === 'Aplikasi Segaloka').length / c.channels.length, 0))}</div>`, { icon: 'bars' })}</div>`; },
 an_camp: () => `<section class="panel"><div class="tbl-wrap"><table class="t"><thead><tr><th>Campaign</th><th>Owner</th><th>${t('status')}</th><th class="r">Spend</th><th class="r">Leads</th><th class="r">Booking</th><th class="r">Revenue</th><th class="r">ROAS</th></tr></thead><tbody>${CAMPAIGNS.slice().sort((a, b) => campRoas(b) - campRoas(a)).map(c => `<tr class="clickable" data-href="/ads/campaign/${c.id}"><td><b>${esc(c.name)}</b></td><td>${c.owner ? esc(travelById(c.owner).name) : 'Segaloka'}</td><td>${st(c.state)}</td><td class="r tnum">${money(c.spent)}</td><td class="r tnum">${fN(c.leads)}</td><td class="r tnum">${c.bookings}</td><td class="r tnum">${money(c.revenue)}</td><td class="r tnum"><b>${c.spent ? fN(campRoas(c), { maximumFractionDigits: 1 }) + '×' : '—'}</b></td></tr>`).join('')}</tbody></table></div></section><div style="margin-top:14px">${pnl('Revenue per campaign', hbars(CAMPAIGNS.filter(c => c.revenue).map(c => [c.name, c.revenue]), v => money(v)), { icon: 'bars' })}</div>`,
 an_conv: () => { const src = {}; BOOKINGS.forEach(b => src[b.source] = (src[b.source] || 0) + 1); const L = CAMPAIGNS.filter(c => c.spent); const k = x => L.reduce((a, c) => a + c[x], 0); return `${pnl('Campaign → Lead → Conversation → Booking → Payment → Revenue', `<div class="chain">${[['Clicks', fC(k('clicks'))], ['Leads', fN(k('leads'))], [L3(['Percakapan', 'Conversations', 'محادثات']), fN(CONVERSATIONS.filter(c => c.campaign && L.some(x => x.id === c.campaign)).length)], ['Booking', fN(k('bookings'))], ['Paid', fN(BOOKINGS.filter(b => b.campaign && L.some(x => x.id === b.campaign) && b.paid > 0).length)], ['Revenue', money(k('revenue'))]].map((n, i, a) => `<div class="cn"><span class="k">${n[0]}</span><span class="v">${n[1]}</span></div>${i < a.length - 1 ? `<span class="ca">${icd('arrowR', 'sm')}</span>` : ''}`).join('')}</div><p class="muted" style="font-size:12px;margin:10px 0 0">Model: ${esc((CAMPAIGNS[0] || {}).attribution || '')} · <a href="#/ads/attribution">${L3(['Ubah model', 'Change model', 'تغيير'])}</a></p>`, { icon: 'branch' })}<div class="grid g2" style="margin-top:14px">${pnl(L3(['Booking per sumber', 'Bookings by source', 'حسب المصدر']), hbars(Object.entries(src).sort((a, b) => b[1] - a[1]), fN), { icon: 'bars' })}${pnl(L3(['Konversi per hari', 'Conversions per day', 'التحويلات']), barChart(ser(), { key: 'book', fmt: v => fN(Math.round(v)), h: 160 }), { icon: 'trend' })}</div>`; },
 an_growth: () => { const months = {}; TRAVELS.forEach(x => { const k = fD(x.joined, { month: 'short', year: '2-digit' }); months[k] = (months[k] || 0) + 1; }); const m = TRAVELS.slice().sort((a, b) => a.joined - b.joined).reduce((acc, x) => { const k = fD(x.joined, { year: 'numeric' }); acc[k] = (acc[k] || 0) + 1; return acc; }, {}); return `${kpiRow([{ k: 'Tenant baru (tahun ini)', v: fN(TRAVELS.filter(x => x.joined > T0 - 270 * D).length) }, { k: 'Traveler baru (30d)', v: '+' + fN(TRAVELERS.filter(x => (x.joined || x.since || x.created || 0) >= nowTs() - 30 * D).length) }, { k: 'Retensi tenant', v: TRAVELS.length ? pct(TRAVELS.filter(x => !['expired', 'cancelled'].includes(x.sub.state)).length / TRAVELS.length * 100, 0) : '—' }, { k: L3(['Kontribusi affiliate', 'Affiliate contribution', 'مساهمة']), v: pct(BOOKINGS.filter(b => b.source === 'Affiliate').length / BOOKINGS.length * 100, 0) }])}<div class="grid g2" style="margin-top:14px">${pnl(L3(['Tenant bergabung per tahun', 'Tenants joined per year', 'الشركات حسب السنة']), hbars(Object.entries(m), fN), { icon: 'building' })}${pnl(L3(['Booking per hari', 'Bookings per day', 'الحجوزات']), areaChart(ser(), { key: 'book', fmt: v => fN(Math.round(v)), h: 160 }), { icon: 'trend' })}</div>`; }
};
const ANAROUTES = { an_exec: 'executive', an_mp: 'marketplace', an_travel: 'travel', an_vendor: 'vendor', an_fin: 'finance', an_omni: 'omnichannel', an_ads: 'ads', an_camp: 'campaign', an_conv: 'conversion', an_growth: 'growth' };
Object.entries(ANAROUTES).forEach(([nav, r]) => route('/analytics/' + r, () => ({ html: `<div class="page">${anaHead(nav, L3(['Layer analitik terkonsolidasi — menggabungkan data lintas domain untuk keputusan manajemen.', 'Consolidated analytics layer — combining cross-domain data for management decisions.', 'طبقة تحليلية موحدة.']))}${mockBanner()}${gate(ANA[nav]())}</div>` })));

/* =============================== SYSTEM =============================== */
const CONFIG = [['refund.policy.days_before', '30', 'Batas hari refund 75%'], ['refund.approval.threshold', '50000000', 'Refund di atas nilai ini butuh approval'], ['settlement.cycle', 'T+3', 'Siklus settlement VIA_SEGALOKA'], ['settlement.reserve_pct', '5', 'Reserve (%)'], ['subscription.grace_days', '14', 'Grace period subscription'], ['subscription.default_branches', '2', 'Cabang default per subscription'], ['omni.sla.default_frt_min', '10', 'SLA first response default'], ['booking.hold_minutes', '60', 'Hold seat saat checkout'], ['kyc.passport_min_months', '8', 'Masa berlaku paspor minimal'], ['ads.budget.approval_threshold', '100000000', 'Budget campaign butuh approval Finance']].map((c, i) => ({ id: c[0], name: c[0], value: c[1], desc: c[2], version: ri(1, 6), state: 'active' }));
route('/system/config', () => resPage({ id: 'cfg', nav: 'sys_cfg', noun: 'Parameter', desc: L3(['Parameter & kebijakan bisnis global. Setiap perubahan membuat versi baru dan tercatat before/after.', 'Global business parameters & policies. Every change creates a new version with before/after audit.', 'المعاملات العامة.']), data: CONFIG, create: false, perm: 'system.manage',
  cols: [{ k: 'name', label: 'Key', render: r => `<span class="mono">${esc(r.name)}</span>` }, { k: 'value', label: L3(['Nilai', 'Value', 'القيمة']), render: r => `<b class="mono">${esc(r.value)}</b>` }, { k: 'desc', label: L3(['Keterangan', 'Description', 'الوصف']) }, { k: 'version', label: 'Ver.', cls: 'r tnum' }],
  form: [{ k: 'value', label: L3(['Nilai', 'Value', 'القيمة']), req: true }], onEdit: r => r.version++, acts: () => [] }));
const LANGS_CFG = [{ id: 'id', name: 'Bahasa Indonesia', dir: 'LTR', def: true, on: true }, { id: 'en', name: 'English', dir: 'LTR', def: false, on: true }, { id: 'ar', name: 'العربية', dir: 'RTL', def: false, on: true }];
let LANGQ = '';
route('/system/language', () => { const keys = Object.keys(DICT).filter(k => !LANGQ || (k + DICT[k].join(' ')).toLowerCase().includes(LANGQ.toLowerCase())).slice(0, 40); const cov = i => pct(Object.values(DICT).filter(r => r[i] && r[i] !== r[0] || i === 0).length / Object.keys(DICT).length * 100, 0);
  return { html: `<div class="page">${phead({ crumbs: [[t('g_sys'), '/system/config'], [t('sys_lang'), '']], title: t('sys_lang'), desc: L3(['Bahasa aktif, arah teks, dan kamus terjemahan. Perubahan kamus langsung diterapkan ke UI.', 'Active languages, text direction, and translation dictionary. Dictionary edits apply to the UI immediately.', 'اللغات والترجمة.']) })}
  <div class="grid g3">${LANGS_CFG.map((l, i) => pnl(l.name, `<dl class="dl"><dt>Kode</dt><dd class="mono">${l.id}</dd><dt>Arah</dt><dd>${l.dir}</dd><dt>Coverage</dt><dd>${cov(i)}</dd><dt>Default</dt><dd>${l.def ? st('active') : '—'}</dd></dl>`, { icon: 'languages' })).join('')}</div>
  <section class="panel" style="margin-top:14px"><div class="toolbar"><label class="input">${ic('search', 'sm')}<input id="lang-q" type="search" value="${esc(LANGQ)}" placeholder="${L3(['Cari key / teks', 'Search key / text', 'ابحث'])}"></label><span style="flex:1"></span>${permBtn('system.manage', ic('check', 'sm') + t('save'), 'data-act="dict-save" data-mut', 'sm primary')}</div><div class="tbl-wrap"><table class="t"><thead><tr><th>Key</th><th>ID</th><th>EN</th><th>AR</th></tr></thead><tbody>${keys.map(k => `<tr><td class="mono" style="font-size:11.5px">${k}</td>${[0, 1, 2].map(i => `<td><input data-dk="${k}" data-di="${i}" value="${esc(DICT[k][i] || '')}" ${i === 2 ? 'dir="rtl"' : ''} aria-label="${k} ${['id', 'en', 'ar'][i]}" style="width:100%;min-width:140px;border:1px solid var(--line);border-radius:6px;padding:5px 7px;background:var(--surface)"></td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="pager muted">${keys.length} / ${Object.keys(DICT).length} key</div></section></div>`, mount() { const q = document.getElementById('lang-q'); q.addEventListener('change', () => { LANGQ = q.value; rerender(); }); } }; });
A['dict-save'] = () => { let n = 0; document.querySelectorAll('[data-dk]').forEach(inp => { const r = DICT[inp.dataset.dk]; const i = +inp.dataset.di; if (r[i] !== inp.value) { r[i] = inp.value; n++; } }); audit('Admin Pusat', 'i18n.update', 'Dictionary', 'success', { after: n + ' string' }); renderTop(); rerender(); toast('ok', n + ' ' + L3(['terjemahan diperbarui', 'translations updated', 'ترجمات']), L3(['Diterapkan langsung ke UI', 'Applied to the UI immediately', 'طُبقت فوراً'])); };
const CURS = [['IDR', 'Rupiah', 1, true, true], ['SAR', 'Riyal Saudi', 4210, true, false], ['USD', 'US Dollar', 15790, true, false], ['MYR', 'Ringgit', 3560, false, false]].map(c => ({ id: c[0], name: c[0] + ' · ' + c[1], rate: c[2], display: c[3], base: c[4], state: c[3] ? 'active' : 'inactive', src: c[4] ? '—' : 'Bank Indonesia (JISDOR) · harian' }));
route('/system/currency', () => resPage({ id: 'cur', nav: 'sys_cur', noun: 'Mata uang', desc: L3(['Mata uang dasar transaksi & ledger: IDR. Mata uang lain hanya untuk tampilan (mis. harga land arrangement dalam SAR).', 'Base currency for transactions & ledger: IDR. Other currencies are display-only (e.g. land arrangement prices in SAR).', 'العملة الأساسية.']), data: CURS, create: false, perm: 'system.manage',
  cols: [{ k: 'name', label: L3(['Mata uang', 'Currency', 'العملة']), render: r => `<b>${esc(r.name)}</b>${r.base ? ' <span class="chip">Base</span>' : ''}` }, { k: 'rate', label: 'Kurs → IDR', cls: 'r tnum', render: r => fN(r.rate) }, { k: 'src', label: L3(['Sumber kurs', 'Rate source', 'المصدر']) }, { k: 'state', label: L3(['Tampilan', 'Display', 'العرض']), render: r => st(r.state) }],
  form: [{ k: 'rate', label: 'Kurs → IDR', type: 'number', req: true }], acts: r => r.base ? [] : [r.state === 'active' ? { label: L3(['Sembunyikan', 'Hide', 'إخفاء']), to: 'inactive', confirm: false } : { label: L3(['Tampilkan', 'Show', 'إظهار']), to: 'active', tone: 'primary', confirm: false }] }));
const PAYCFG = { routing: { 'VA BCA': ['Midtrans', 'Xendit'], 'VA Mandiri': ['Midtrans', 'Xendit'], 'VA BSI': ['Xendit', 'Midtrans'], QRIS: ['Midtrans', 'DOKU'], 'Kartu Kredit': ['Xendit', 'Midtrans'] }, cycle: 'T+3', reserve: 5, wdLimit: 2e9, refundThr: 50e6, wdThr: 50e6, holdHours: 72 };
route('/system/payment', () => { const P = PROVIDERS.map(p => p.name); return { html: `<div class="page">${phead({ crumbs: [[t('g_sys'), '/system/config'], [t('sys_pay'), '']], title: t('sys_pay'), desc: L3(['Provider, routing, fee, settlement, withdrawal, reserve, hold, approval, limit, dan risk control. Perubahan ditampilkan sebagai diff dan wajib alasan.', 'Providers, routing, fees, settlement, withdrawal, reserve, hold, approval, limits and risk controls. Changes are shown as a diff and require a reason.', 'إعدادات الدفع.']), actions: permBtn('system.payment', ic('check') + L3(['Tinjau & simpan', 'Review & save', 'مراجعة وحفظ']), 'data-act="paycfg-save" data-mut', 'primary') })}
  <div class="grid g12"><div class="c7">${pnl('Routing per channel', `<div class="tbl-wrap"><table class="t"><thead><tr><th>Channel</th><th>Primary</th><th>Failover</th></tr></thead><tbody>${Object.entries(PAYCFG.routing).map(([ch, [a, b]]) => `<tr><td><b>${ch}</b></td><td><select class="select" id="pr-${ch.replace(/\W/g, '')}-0">${P.map(p => `<option ${p === a ? 'selected' : ''}>${p}</option>`).join('')}</select></td><td><select class="select" id="pr-${ch.replace(/\W/g, '')}-1">${P.map(p => `<option ${p === b ? 'selected' : ''}>${p}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`, { raw: true, icon: 'route' })}</div>
  <div class="c5">${pnl('Settlement & kontrol', `<div class="grid g2" style="gap:10px"><div class="field"><label for="pc-cycle">Settlement cycle</label><select id="pc-cycle">${['T+1', 'T+2', 'T+3', 'T+7'].map(x => `<option ${PAYCFG.cycle === x ? 'selected' : ''}>${x}</option>`).join('')}</select></div><div class="field"><label for="pc-res">Reserve (%)</label><input type="number" id="pc-res" value="${PAYCFG.reserve}" min="0" max="20"></div><div class="field"><label for="pc-wdl">Limit withdrawal/hari (Rp)</label><input type="number" id="pc-wdl" value="${PAYCFG.wdLimit}" step="100000000"></div><div class="field"><label for="pc-hold">Auto-hold setelah ganti rekening (jam)</label><input type="number" id="pc-hold" value="${PAYCFG.holdHours}"></div><div class="field"><label for="pc-rt">Approval refund > (Rp)</label><input type="number" id="pc-rt" value="${PAYCFG.refundThr}" step="1000000"></div><div class="field"><label for="pc-wt">Approval withdrawal > (Rp)</label><input type="number" id="pc-wt" value="${PAYCFG.wdThr}" step="1000000"></div></div><a href="#/finance/fee">Fee & Commission →</a>`, { icon: 'shield' })}</div></div></div>` }; });
A['paycfg-save'] = () => { const nw = JSON.parse(JSON.stringify(PAYCFG)); Object.keys(nw.routing).forEach(ch => { const k = ch.replace(/\W/g, ''); nw.routing[ch] = [document.getElementById('pr-' + k + '-0').value, document.getElementById('pr-' + k + '-1').value]; }); nw.cycle = document.getElementById('pc-cycle').value; nw.reserve = +document.getElementById('pc-res').value; nw.wdLimit = +document.getElementById('pc-wdl').value; nw.holdHours = +document.getElementById('pc-hold').value; nw.refundThr = +document.getElementById('pc-rt').value; nw.wdThr = +document.getElementById('pc-wt').value;
  const diff = []; Object.keys(nw.routing).forEach(ch => { if (nw.routing[ch].join() !== PAYCFG.routing[ch].join()) diff.push([ch, PAYCFG.routing[ch].join(' → '), nw.routing[ch].join(' → ')]); if (nw.routing[ch][0] === nw.routing[ch][1]) diff.push([ch, '⚠', L3(['Primary = failover', 'Primary = failover', 'نفس المزود'])]); }); ['cycle', 'reserve', 'wdLimit', 'holdHours', 'refundThr', 'wdThr'].forEach(k => { if (nw[k] !== PAYCFG[k]) diff.push([k, PAYCFG[k], nw[k]]); });
  if (!diff.length) { toast('info', L3(['Tidak ada perubahan', 'No changes', 'لا تغييرات']), ''); return; }
  confirmAction({ title: t('sys_pay'), desc: `<div style="border:1px solid var(--line);border-radius:8px;overflow:hidden"><div class="diffrow diffhead"><div>Field</div><div>Before</div><div>After</div></div>${diff.map(d => `<div class="diffrow"><div class="muted">${esc(d[0])}</div><div class="b">${esc(d[1])}</div><div class="a">${esc(d[2])}</div></div>`).join('')}</div>`, tone: 'danger', reason: true, resource: 'Config/payment', onOk: r => { audit('Admin Pusat', 'payment_config.update', 'Config/payment', 'success', { before: JSON.stringify(PAYCFG).slice(0, 200), after: JSON.stringify(nw).slice(0, 200), reason: r }); Object.assign(PAYCFG, nw); SETTLEMENTS.forEach(s => s.cycle = nw.cycle); toast('ok', L3(['Konfigurasi pembayaran disimpan', 'Payment configuration saved', 'تم الحفظ']), diff.length + ' ' + L3(['perubahan', 'changes', 'تغييرات'])); } }); };
const NEVENTS = ['approval', 'booking', 'payment', 'settlement', 'legal', 'security', 'subscription', 'marketplace', 'omnichannel', 'ads']; const NCH = ['In-app', 'Email', 'WhatsApp', 'Push'];
const NCFG = Object.fromEntries(NEVENTS.map((e, i) => [e, [true, i % 2 === 0, ['security', 'payment', 'approval'].includes(e), i % 3 === 0]]));
route('/system/notification', () => ({ html: `<div class="page">${phead({ crumbs: [[t('g_sys'), '/system/config'], [t('sys_ncfg'), '']], title: t('sys_ncfg'), desc: L3(['Event → channel notifikasi. In-app selalu aktif untuk event keamanan.', 'Event → notification channel. In-app is always on for security events.', 'إعدادات الإشعارات.']), actions: permBtn('system.manage', ic('check') + t('save'), 'data-act="ncfg-save" data-mut', 'primary') })}<section class="panel"><div class="tbl-wrap"><table class="t"><thead><tr><th>Event</th>${NCH.map(c => `<th style="text-align:center">${c}</th>`).join('')}</tr></thead><tbody>${NEVENTS.map(e => `<tr><td><b>${e}</b></td>${NCH.map((c, i) => `<td style="text-align:center"><input type="checkbox" id="nc-${e}-${i}" aria-label="${e} ${c}" ${NCFG[e][i] ? 'checked' : ''} ${e === 'security' && i === 0 ? 'disabled' : ''}></td>`).join('')}</tr>`).join('')}</tbody></table></div></section></div>` }));
A['ncfg-save'] = () => { let n = 0; NEVENTS.forEach(e => NCH.forEach((c, i) => { const v = document.getElementById('nc-' + e + '-' + i).checked; if (NCFG[e][i] !== v) { NCFG[e][i] = v; n++; } })); audit('Admin Pusat', 'notification_config.update', 'Config/notification', 'success', { after: n + ' perubahan' }); toast('ok', L3(['Konfigurasi notifikasi disimpan', 'Notification config saved', 'تم الحفظ']), n + ' ' + L3(['perubahan', 'changes', 'تغييرات'])); };
const FLAGS = [['ai.assistant', 'Segaloka AI di Control Center', 100, true], ['omni.instagram_comments', 'Balas komentar Instagram dari Inbox', 50, true], ['mp.segadeals_v2', 'SegaDeals v2 (permintaan pengguna → penawaran Travel)', 100, true], ['finance.auto_recon', 'Auto-match rekonsiliasi harian', 100, true], ['ads.app_inbox', 'Placement Notifikasi In-App (Aplikasi Segaloka)', 0, false], ['booking.installment', 'Cicilan Haji Khusus', 10, true], ['travel.website_builder_v3', 'Website builder v3', 0, false], ['i18n.ar_dates_hijri', 'Tanggal Hijriah di UI Arab', 100, true]].map(f => ({ id: f[0], name: f[0], desc: f[1], rollout: f[2], on: f[3], state: f[3] ? 'active' : 'inactive' }));
route('/system/flags', () => resPage({ id: 'flag', nav: 'sys_flag', noun: 'Flag', desc: L3(['Feature flag per tenant/role dengan rollout bertahap. Flag tidak pernah membuka akses di luar permission.', 'Feature flags per tenant/role with gradual rollout. Flags never grant access beyond permissions.', 'مفاتيح الميزات.']), data: FLAGS, states: ['active', 'inactive'], perm: 'system.manage',
  cols: [{ k: 'name', label: 'Flag', render: r => `<span class="mono">${r.name}</span><div class="muted" style="font-size:12px">${esc(r.desc)}</div>` }, { k: 'rollout', label: 'Rollout', render: r => pctBar(r.rollout / 100) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: 'Key', req: true }, { k: 'desc', label: L3(['Deskripsi', 'Description', 'الوصف']) }, { k: 'rollout', label: 'Rollout (%)', type: 'number', min: 0, max: 100, def: 0 }], make: v => ({ id: v.name, ...v, on: false, state: 'inactive' }),
  acts: r => [r.state === 'active' ? { label: L3(['Matikan', 'Turn off', 'إيقاف']), to: 'inactive', tone: 'badb', reason: true } : { label: L3(['Nyalakan', 'Turn on', 'تشغيل']), to: 'active', tone: 'primary', fn: x => { if (!x.rollout) x.rollout = 10; } }] }));
const INTEGS = [['Midtrans', 'Payment gateway', 'active'], ['Xendit', 'Payment gateway', 'active'], ['DOKU', 'Payment gateway', 'degraded'], ['WhatsApp Business (BSP)', 'Omnichannel', 'active'], ['Ad server Segaloka (web + app)', 'Ads · internal', 'active'], ['Push & in-app messaging (App)', 'Aplikasi Segaloka', 'active'], ['Email (SMTP/API)', 'Omnichannel', 'active'], ['Public API · tenant', 'API', 'active']].map((x, i) => ({ id: 'INT-' + (1 + i), name: x[0], kind: x[1], state: x[2], key: i === 7 ? 'sk_live_••••' + ri(1000, 9999) : '••••' + ri(1000, 9999), last: T0 - (i + 1) * 17 * 60e3 }));
route('/system/integration', () => resPage({ id: 'int', nav: 'sys_int', noun: 'Integrasi', desc: L3(['Integrasi eksternal & API key. Rahasia tidak pernah ditampilkan penuh.', 'External integrations & API keys. Secrets are never shown in full.', 'التكاملات.']), data: INTEGS, states: ['active', 'degraded', 'inactive'], create: false, perm: 'system.manage',
  cols: [{ k: 'name', label: L3(['Integrasi', 'Integration', 'التكامل']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'kind', label: L3(['Tipe', 'Type', 'النوع']), render: r => `<span class="chip">${esc(r.kind)}</span>` }, { k: 'key', label: 'Credential', render: r => `<span class="mono">${esc(r.key)}</span>` }, { k: 'last', label: L3(['Sinkron terakhir', 'Last sync', 'آخر مزامنة']), render: r => rel(r.last) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  acts: r => [{ label: L3(['Uji koneksi', 'Test connection', 'اختبار']), confirm: false, fn: x => { x.last = nowTs(); if (x.state === 'degraded') x.state = 'active'; }, when: r.state !== 'inactive', msg: '200 OK' }, { label: L3(['Rotasi key', 'Rotate key', 'تدوير']), tone: 'warnb', reason: true, fn: x => x.key = x.key.slice(0, -4) + ri(1000, 9999), msg: L3(['Key lama dicabut dalam 24 jam', 'Old key revoked within 24h', 'يُلغى القديم']) }, r.state === 'inactive' ? { label: L3(['Hubungkan', 'Connect', 'ربط']), to: 'active', tone: 'primary' } : { label: L3(['Putuskan', 'Disconnect', 'قطع']), to: 'inactive', tone: 'badb', reason: true }] }));
const SERVICES = [['API Gateway', 'healthy', 99.99, 182], ['Auth service', 'healthy', 99.98, 95], ['Booking service', 'healthy', 99.95, 210], ['Ledger service', 'healthy', 99.99, 140], ['Webhook consumer', 'healthy', 99.97, 60], ['Realtime (WebSocket)', 'healthy', 99.9, 35], ['Search', 'healthy', 99.93, 120], ['Notification worker', 'healthy', 99.96, 80], ['DOKU adapter', 'degraded', 98.1, 1840], ['WhatsApp BSP', 'healthy', 99.8, 420]];
const INCIDENTS = [{ id: 'INC-2609-01', name: 'DOKU latency tinggi', svc: 'DOKU adapter', sev: 'warn', state: 'open', created: T0 - 3 * H }, { id: 'INC-2609-00', name: 'Keterlambatan webhook Xendit', svc: 'Webhook consumer', sev: 'warn', state: 'resolved', created: T0 - 30 * H }];
route('/system/health', () => resPage({ id: 'inc', nav: 'sys_health', noun: 'Incident', title: t('sys_health'), desc: L3(['Uptime & latency per service, plus manajemen incident.', 'Uptime & latency per service, plus incident management.', 'صحة النظام.']), data: INCIDENTS, states: ['open', 'in_progress', 'resolved'], newLabel: L3(['Buat incident', 'Declare incident', 'إعلان حادثة']), perm: 'system.manage',
  top: () => `<section class="panel"><div class="health">${SERVICES.map(s => `<div class="hs">${st(S.ux === 'offline' && s[0].startsWith('Realtime') ? 'down' : s[1])}<span class="nm"><b style="font-weight:550">${s[0]}</b><span>${s[2]}% · p95 ${fN(s[3])} ms</span></span>${spark(Array.from({ length: 20 }, (_, i) => s[3] * (0.8 + ((i * 7 + s[3]) % 9) / 20)), s[1] === 'healthy' ? 'var(--s3)' : 'var(--s2)', 60, 20)}</div>`).join('')}</div></section>`,
  cols: [{ k: 'name', label: 'Incident', render: r => `<b>${esc(r.name)}</b><div class="muted mono" style="font-size:11.5px">${r.id}</div>` }, { k: 'svc', label: 'Service' }, { k: 'created', label: L3(['Mulai', 'Started', 'البدء']), render: r => rel(r.created) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Judul', 'Title', 'العنوان']), req: true }, { k: 'svc', label: 'Service', type: 'select', options: SERVICES.map(s => s[0]) }], make: v => ({ id: 'INC-' + fD(nowTs(), { day: '2-digit', month: '2-digit' }).replace(/\D/g, '') + '-' + (INCIDENTS.length + 1), ...v, sev: 'warn', state: 'open' }),
  acts: r => r.state === 'resolved' ? [] : [{ label: L3(['Tangani', 'Acknowledge', 'استلام']), to: 'in_progress', when: r.state === 'open', confirm: false }, { label: t('resolve'), to: 'resolved', tone: 'primary', reason: true, fn: x => { const s = SERVICES.find(q => q[0] === x.svc); if (s) s[1] = 'healthy'; } }] }));
