const PAGES = {};
const mockBanner = () => SB.on ? `<div class="banner info" style="border:1px solid var(--ok-line);background:var(--ok-bg);color:var(--ok);border-radius:10px;margin-bottom:14px">${ic('check')}<span style="flex:1">${esc(L3(['Terhubung ke Supabase (project segaloka). Semua perubahan tersimpan di Postgres. Data awal adalah seed demo — nama & angka fiktif, ditandai is_demo di database.', 'Connected to Supabase (project segaloka). Every change is saved in Postgres. Initial data is a demo seed — fictional names & figures, flagged is_demo in the database.', 'متصل بـ Supabase. البيانات الأولية تجريبية.']))}</span></div>` : `<div class="banner info" style="border:1px solid var(--info-line);border-radius:10px;margin-bottom:14px">${ic('flag')}<span style="flex:1">${esc(t('mock_b'))} ${SB.state === 'local' ? esc(L3(['Mode lokal: perubahan tidak disimpan.', 'Local mode: changes are not saved.', 'وضع محلي.'])) + (SB.err ? ' (' + esc(sbErrText(SB.err)) + ')' : '') : ''}</span>${mockmark()}</div>`;
const pnl = (title, body, opts = {}) => `<section class="panel ${opts.cls || ''}" ${opts.id ? `id="${opts.id}"` : ''}><div class="panel-h"><h3>${opts.icon ? ic(opts.icon, 'sm') : ''}${esc(title)}${opts.small ? ` <small>${opts.small}</small>` : ''}</h3>${opts.right || ''}</div>${opts.raw ? body : `<div class="panel-b">${body}</div>`}${opts.foot ? `<div class="panel-f">${opts.foot}</div>` : ''}</section>`;
const seeAll = r => `<a href="#${r}" class="btn sm ghost">${t('see_all')}${icd('chevR', 'sm')}</a>`;
const DOMKEY = { Travel: 'travel', Vendor: 'vendor', Legalitas: 'legal', Keuangan: 'finance', Keamanan: 'security', Ads: 'ads', Marketplace: 'marketplace', SaaS: 'saas' };
const pkgById = id => PACKAGES.find(p => p.id === id);
const trvName = id => (TRAVELERS.find(x => x.id === id) || {}).name || id;

/* =============================== OVERVIEW =============================== */
PAGES.overview = () => {
  const gmv = ser().reduce((s, d) => s + d.gmv, 0), prevG = gmv * .885; const rev = gmv * .031; const bk = ser().reduce((s, d) => s + d.book, 0);
  const paidN = PAYMENTS.filter(p => p.status === 'paid').length, failN = PAYMENTS.filter(p => p.status === 'failed' || p.status === 'expired').length; const succ = paidN / (paidN + failN) * 100;
  const apOpen = APPROVALS.filter(a => a.status === 'waiting' || a.status === 'in_progress');
  const lic30 = TRAVELS.reduce((s, x) => s + x.lic.filter(l => l.status === 'expiring').length, 0);
  const slaBreach = CONVERSATIONS.filter(c => c.sla != null && c.sla < 0).length || 3;
  const stFail = SETTLEMENTS.filter(s => s.state === 'failed'); const stHold = SETTLEMENTS.filter(s => s.state === 'hold');
  const grace = TRAVELS.filter(x => x.sub.state === 'grace'); const unmatched = PAYMENTS.filter(p => p.recon === 'unmatched' || p.recon === 'mismatch').length;
  const sens = APPROVALS.find(a => a.type === 'sensitive');
  const att = [
    ['bad', 'shield', L3(['Perubahan rekening berisiko tinggi', 'High-risk payout account change', 'تغيير حساب صرف عالي المخاطر']), sens.requester + ' · risk ' + sens.risk + '/100 · device baru', '/approval/' + sens.id, rel(sens.ts)],
    ...stFail.map(s => ['bad', 'landmark', L3(['Settlement gagal', 'Settlement failed', 'فشل التسوية']) + ' · ' + s.id, travelById(s.travel).name + ' · ' + money(s.net) + ' · rekening ditolak bank', '/finance/settlement', rel(T0 - 2 * H)]),
    ['warn', 'card', 'DOKU ' + L3(['terdegradasi', 'degraded', 'متدهور']) + ' — success 91,2%', L3(['Routing QRIS otomatis dialihkan ke Midtrans', 'QRIS routing auto-failover to Midtrans', 'تم تحويل QRIS تلقائياً']), '/finance/gateway', '12 mnt'],
    ['warn', 'filecheck', lic30 + ' ' + L3(['izin expired < 30 hari', 'licenses expire < 30 days', 'تراخيص تنتهي خلال 30 يوماً']), 'PPIU · BPW · PIHK', '/travel/legal', ''],
    ['warn', 'timer', slaBreach + ' ' + L3(['percakapan melewati SLA', 'conversations breached SLA', 'محادثات تجاوزت SLA']), L3(['Antrian Unassigned · WhatsApp & IG', 'Unassigned queue · WhatsApp & IG', 'غير مسندة']), '/omni/inbox', ''],
    ['warn', 'scale', unmatched + ' ' + L3(['transaksi belum match rekonsiliasi', 'transactions unmatched in reconciliation', 'معاملات غير مطابقة']), 'Batch REC-260923', '/finance/reconciliation', ''],
    ...grace.slice(0, 2).map(x => ['warn', 'refresh', 'Grace Period · ' + x.name, 'Subscription ' + x.sub.plan + ' · website tetap aktif s.d. akhir grace', '/travel/' + x.id + '/subscription', '']),
    ['info', 'arrowur', WITHDRAWALS.filter(w => w.state === 'pending').length + ' withdrawal ' + L3(['menunggu approval', 'awaiting approval', 'بانتظار الموافقة']), 'Vendor · Travel · Affiliate', '/finance/withdrawal', '']
  ];
  const bkByState = {}; BOOKINGS.forEach(b => bkByState[b.state] = (bkByState[b.state] || 0) + 1);
  const subBy = {}; TRAVELS.forEach(x => subBy[x.sub.state] = (subBy[x.sub.state] || 0) + 1);
  const legalBy = {}; TRAVELS.forEach(x => legalBy[x.legal] = (legalBy[x.legal] || 0) + 1);
  const topPkg = PACKAGES.filter(p => p.state === 'published').sort((a, b) => b.sold - a.sold).slice(0, 5);
  const activeC = CAMPAIGNS.filter(c => c.state === 'active'); const spend = activeC.reduce((s, c) => s + c.spent, 0), crev = activeC.reduce((s, c) => s + c.revenue, 0), cl = activeC.reduce((s, c) => s + c.leads, 0), cb = activeC.reduce((s, c) => s + c.bookings, 0);
  const openConv = CONVERSATIONS.filter(c => c.status === 'open').length, unas = CONVERSATIONS.filter(c => !c.assignee && c.status !== 'closed').length;
  const html = `<div class="page">
  ${phead({ crumbs: [[BRAND.name, '/overview'], [t('overview'), '/overview']], title: t('ov_title'), desc: t('ov_desc'), actions: `<span class="live ${S.ux === 'offline' ? 'off' : ''}"><i></i>${t('live')}</span>${periodSel()}<button class="btn" data-act="export" data-what="Overview">${ic('download')}${t('export')}</button>` })}
  ${mockBanner()}
  <div class="section-title"><h2>${t('snapshot')}</h2><span class="rule"></span></div>
  ${gate(`<div class="hero"><div class="main-k"><div class="eyebrow">GMV (${perLbl()})</div><div class="big"><small>Rp</small>${esc(fN(gmv / 1e9, { maximumFractionDigits: 1 }))} ${L3(['M', 'B', 'مليار'])}</div><div class="muted" style="margin:4px 0 8px">${delta((gmv / prevG - 1) * 100)} vs ${perLbl()} ${L3(['sebelumnya', 'prior', 'السابقة'])} · ${L3(['semua payment flow (DIRECT_TO_TRAVEL + VIA_SEGALOKA)', 'all payment flows (DIRECT_TO_TRAVEL + VIA_SEGALOKA)', 'كل مسارات الدفع'])}</div>${areaChart(ser(), { key: 'gmv', fmt: v => money(v), label: 'GMV' })}</div>
  <div class="mini">${[[t('revenue'), money(rev), delta(9.4), 'percent', '/finance/fee'], [t('bookings'), fN(bk), delta(6.1), 'calendar', '/booking'], ['Payment success', pct(succ), delta(-0.8), 'card', '/finance/gateway'], [t('approval'), fN(apOpen.length), `<span class="prio p1"><i></i>${apOpen.filter(a => a.priority === 'p1').length} ${L3(['prioritas tinggi', 'high priority', 'أولوية عالية'])}</span>`, 'approval', '/approval']].map(k => `<a class="kpi btnlike" href="#${k[4]}" style="color:inherit;text-decoration:none"><div class="k">${ic(k[3], 'sm')}${esc(k[0])}</div><div class="v">${k[1]}</div><div class="d">${k[2]}</div></a>`).join('')}</div></div>`, 6)}
  <div class="eco" style="margin-top:14px">${[['building', 'Travel', TRAVELS.filter(x => x.op === 'active').length, TRAVELS.length + ' total · ' + TRAVELS.filter(x => x.op === 'review').length + ' review', '/travel'], ['store', 'Vendor', VENDORS.filter(v => v.status === 'active').length, VENDORS.length + ' total · ' + VENDORS.filter(v => v.verif !== 'verified').length + ' verifikasi', '/vendor'], ['link', 'Affiliate', AFFILIATES.length, fN(AFFILIATES.reduce((s, a) => s + a.conv, 0)) + ' konversi', '/affiliate'], ['users', t('mitra'), MITRA.filter(m => m.status === 'active').length, L3(['1 Mitra → 1 Travel', '1 Partner → 1 Travel', 'شريك واحد ← شركة واحدة']), '/mitra'], ['user', 'Traveler', fN(48213), '+' + fN(1284) + ' ' + L3(['bulan ini', 'this month', 'هذا الشهر']), '/traveler']].map(e => `<a href="#${e[4]}"><div class="k">${ic(e[0], 'sm')}${esc(e[1])}</div><div class="v">${typeof e[2] === 'number' ? fN(e[2]) : e[2]}</div><div class="s">${esc(e[3])}</div></a>`).join('')}</div>

  <div class="grid g12" style="margin-top:14px">
    <div class="c7">${pnl(t('attention'), gate(`<div class="list">${att.map(a => `<a class="li" href="#${a[4]}"><span class="sev ${a[0]}"></span><span style="color:var(--${a[0] === 'info' ? 'info' : a[0]})">${ic(a[1])}</span><span class="body"><b>${esc(a[2])}</b><span class="sub">${esc(a[3])}</span></span>${a[5] ? `<span class="when">${esc(a[5])}</span>` : ''}${icd('chevR', 'sm muted')}</a>`).join('')}</div>`), { raw: true, icon: 'alert', small: att.length + ' item', right: `<span class="chip">${ic('sparkles', 'sm')}${L3(['Diurutkan oleh severity', 'Sorted by severity', 'مرتب حسب الخطورة'])}</span>` })}</div>
    <div class="c5">${pnl(t('apq'), gate(`<div class="list">${apOpen.slice(0, 6).map(a => `<a class="li" href="#/approval/${a.id}"><span class="body"><b style="font-weight:550">${esc(a.title)}</b><span class="sub">${esc(a.domain)} · ${esc(L3(AP_TYPES[a.type].slice(1).concat(AP_TYPES[a.type][2])))} · ${esc(rel(a.ts))}</span></span>${prio(a.priority)}</a>`).join('')}</div>`), { raw: true, icon: 'approval', small: apOpen.length + ' ' + L3(['terbuka', 'open', 'مفتوحة']), right: seeAll('/approval') })}</div>
  </div>

  <div class="section-title"><h2>${t('finsnap')}</h2><span class="rule"></span><span class="muted" style="font-size:12px">${L3(['Payment · Settlement · Withdrawal · Refund · Reconciliation — status terpisah', 'Payment · Settlement · Withdrawal · Refund · Reconciliation — separate states', 'حالات منفصلة'])}</span></div>
  <section class="panel">${gate(`<div class="flow">${[['card', 'Payment masuk', money(PAYMENTS.filter(p => p.status === 'paid').reduce((s, p) => s + p.amount, 0)), paidN + ' paid · ' + PAYMENTS.filter(p => p.status === 'pending').length + ' pending', '/finance/transactions'], ['layers', 'Ledger VIA_SEGALOKA', money(SETTLEMENTS.reduce((s, x) => s + x.gross, 0)), L3(['Saldo tenant di escrow', 'Tenant balance in escrow', 'رصيد الشركات']), '/finance'], ['landmark', 'Settlement', money(SETTLEMENTS.filter(s => s.state === 'settled').reduce((s, x) => s + x.net, 0)), SETTLEMENTS.filter(s => s.state === 'scheduled').length + ' scheduled · ' + stHold.length + ' hold · ' + stFail.length + ' failed', '/finance/settlement'], ['arrowur', 'Withdrawal', money(WITHDRAWALS.filter(w => w.state === 'pending').reduce((s, w) => s + w.amount, 0)), WITHDRAWALS.filter(w => w.state === 'pending').length + ' pending approval', '/finance/withdrawal'], ['undo', 'Refund', money(REFUNDS.filter(r => r.state === 'pending').reduce((s, r) => s + r.amount, 0)), REFUNDS.filter(r => r.state === 'pending').length + ' requested', '/finance/refund'], ['scale', 'Reconciliation', pct(PAYMENTS.filter(p => p.recon === 'reconciled').length / paidN * 100), unmatched + ' unmatched', '/finance/reconciliation']].map((f, i, a) => `<a class="fs" href="#${f[4]}" style="color:inherit;text-decoration:none"><div class="k">${ic(f[0], 'sm')}${esc(f[1])}</div><div class="v">${f[2]}</div><div class="s">${esc(f[3])}</div>${i < a.length - 1 ? `<span class="arrow">${icd('chevR', 'sm')}</span>` : ''}</a>`).join('')}</div>`)}</section>

  <div class="grid g12" style="margin-top:14px">
    <div class="c8">${pnl(t('mpact'), gate(`<div style="display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:18px" class="mpgrid"><div><div class="legend" style="margin-bottom:6px"><span><i style="background:var(--s1)"></i>${L3(['Booking per hari', 'Bookings per day', 'الحجوزات يومياً'])}</span></div>${barChart(ser(), { key: 'book', fmt: v => fN(Math.round(v)), label: 'Booking per hari' })}</div><div><div class="eyebrow" style="margin-bottom:8px">${L3(['Paket terlaris', 'Top packages', 'الباقات الأعلى'])}</div>${hbars(topPkg.map(p => [p.name + ' · ' + travelById(p.travel).name.split(' ')[0], p.sold]), v => fN(v) + ' pax')}<div class="muted" style="font-size:12px;margin-top:10px">${PACKAGES.filter(p => p.state === 'published').length} published · ${PACKAGES.filter(p => p.state === 'review').length} ${L3(['menunggu moderasi', 'awaiting moderation', 'بانتظار المراجعة'])} · ${typeof SD_REQ !== 'undefined' ? SD_REQ.filter(r => ['open', 'offered'].includes(r.state)).length : 0} ${L3(['permintaan SegaDeals terbuka', 'open SegaDeals requests', 'طلبات SegaDeals'])}</div></div></div>`), { icon: 'bag', right: seeAll('/marketplace/packages') })}</div>
    <div class="c4">${pnl(t('ophealth'), gate(`<div class="eyebrow" style="margin-bottom:6px">Booking lifecycle</div>${hbars(['awaiting_payment', 'partially_paid', 'confirmed', 'processing', 'ready', 'departed', 'refund_requested'].map(s => [L3(STATUS[s].slice(2)), bkByState[s] || 0, s === 'refund_requested' ? 'var(--s2)' : 'var(--s1)']), fN)}<div class="eyebrow" style="margin:14px 0 6px">Subscription</div><div style="display:flex;gap:6px;flex-wrap:wrap">${['active', 'trial', 'grace', 'pending', 'suspended', 'expired'].map(s => `<a href="#/travel/subscription">${st(s)}</a><span class="tnum" style="font-weight:600;margin-inline-end:6px">${subBy[s] || 0}</span>`).join('')}</div><div class="eyebrow" style="margin:14px 0 6px">${t('c_legal')}</div><div style="display:flex;gap:6px;flex-wrap:wrap">${['verified', 'expiring', 'under_review', 'expired', 'rejected'].map(s => `${st(s)}<span class="tnum" style="font-weight:600;margin-inline-end:6px">${legalBy[s] || 0}</span>`).join('')}</div>`), { icon: 'activity' })}</div>
  </div>

  <div class="grid g3" style="margin-top:14px">
    ${pnl(t('omnisnap'), gate(`<div class="grid g2" style="gap:10px"><div><div class="eyebrow">Open</div><div class="kpi" style="padding:0;border:0"><div class="v">${openConv}</div></div></div><div><div class="eyebrow">Unassigned</div><div class="kpi" style="padding:0;border:0"><div class="v" style="color:var(--warn)">${unas}</div></div></div><div><div class="eyebrow">First response</div><div class="kpi" style="padding:0;border:0"><div class="v">4m 12s</div></div></div><div><div class="eyebrow">SLA met</div><div class="kpi" style="padding:0;border:0"><div class="v">91%</div></div></div></div><div style="margin-top:12px">${hbars([['WhatsApp', 62, 'var(--s1)'], ['Instagram', 17, 'var(--s1)'], ['Web Chat', 11, 'var(--s1)'], ['Email', 6, 'var(--s1)'], ['Facebook', 4, 'var(--s1)']], v => v + '%')}</div>`), { icon: 'msg', right: seeAll('/omni/inbox') })}
    ${pnl(t('adssnap'), gate(`<div class="grid g2" style="gap:10px">${[['Spend', money(spend)], ['Revenue', money(crev)], ['Leads', fN(cl)], ['ROAS', fN(crev / spend, { maximumFractionDigits: 1 }) + '×']].map(k => `<div><div class="eyebrow">${k[0]}</div><div class="kpi" style="padding:0;border:0"><div class="v">${k[1]}</div></div></div>`).join('')}</div><div class="list" style="margin:10px -14px -14px;border-top:1px solid var(--line)">${activeC.slice(0, 3).map(c => `<a class="li" href="#/ads/campaign/${c.id}"><span class="body"><b style="font-weight:550">${esc(c.name)}</b><span class="sub">${fN(c.bookings)} booking · ${money(c.spent)} / ${money(c.budget)}</span></span>${spark(ser().map(d => d.leads * (0.6 + (c.id.charCodeAt(6) % 5) / 10)), 'var(--s1)', 64, 22)}</a>`).join('')}</div>`), { icon: 'megaphone', right: seeAll('/ads') })}
    ${pnl(t('riskalerts'), gate(`<div class="list" style="margin:-14px">${[['bad', '14 login gagal · admin@segaloka', 'IP 103.21.x.x diblokir 30 mnt', '/compliance/security'], ['bad', L3(['Pola refund tidak wajar', 'Unusual refund pattern', 'نمط استرداد غير معتاد']), '3 refund dari 1 device · 24 jam', '/compliance/risk'], ['warn', L3(['Perubahan rekening + device baru', 'Account change + new device', 'تغيير حساب + جهاز جديد']), sens.requester, '/approval/' + sens.id], ['warn', 'Chargeback · Kartu Kredit', 'PAY-7700250 · Rp 12,4 jt', '/compliance/risk'], ['neu', L3(['Role finance_ops diubah', 'finance_ops role changed', 'تم تعديل الدور']), '+ refund.approve · oleh Anda', '/compliance/audit']].map(r => `<a class="li" href="#${r[3]}"><span class="sev ${r[0]}"></span><span class="body"><b style="font-weight:550">${esc(r[1])}</b><span class="sub">${esc(r[2])}</span></span></a>`).join('')}</div>`), { icon: 'shield', right: seeAll('/compliance/risk') })}
  </div>

  <div class="grid g12" style="margin-top:14px">
    <div class="c8">${pnl(t('recent'), gate(`<div class="list">${AUDIT.slice(0, 7).map(a => `<div class="li"><span class="avatar" style="width:26px;height:26px;font-size:10px">${esc(initials(a.actor) || 'SY')}</span><span class="body"><b style="font-weight:500"><span style="font-weight:600">${esc(a.actor)}</span> · <span class="mono">${esc(a.action)}</span></b><span class="sub mono">${esc(a.resource)}</span></span>${st(a.result === 'failed' ? 'failed' : a.result === 'warning' ? 'unmatched' : 'success')}<span class="when">${esc(rel(a.ts))}</span></div>`).join('')}</div>`), { raw: true, icon: 'history', right: seeAll('/compliance/audit') })}</div>
    <div class="c4" style="display:grid;gap:14px;align-content:start">
      ${pnl(t('syshealth'), `<div class="health" style="grid-template-columns:repeat(2,minmax(0,1fr))">${[['API Gateway', 'healthy', 'p95 182 ms'], ['Payment webhooks', 'healthy', 'lag 3 s'], ['DOKU provider', 'degraded', 'success 91,2%'], ['Realtime (WS)', S.ux === 'offline' ? 'down' : 'healthy', S.ux === 'offline' ? 'reconnecting' : '12.4k conn'], ['Queue worker', 'healthy', '0 DLQ'], ['WhatsApp BSP', 'healthy', 'quality: High']].map((h, i) => `<div class="hs" style="${i % 2 ? 'border-inline-end:0' : ''}">${st(h[1])}<span class="nm"><b style="font-weight:550">${esc(h[0])}</b><span>${esc(h[2])}</span></span></div>`).join('')}</div>`, { raw: true, icon: 'activity', right: `<a href="#/system/health" class="btn sm ghost">${icd('chevR', 'sm')}</a>` })}
      ${pnl(t('quick'), `<div class="qa">${[['approval', L3(['Proses approval', 'Process approvals', 'معالجة الموافقات']), '/approval'], ['building', t('add_travel'), '/travel?new'], ['target', t('new_campaign'), '/ads?new'], ['scale', L3(['Rekonsiliasi', 'Reconcile', 'مطابقة']), '/finance/reconciliation'], ['inbox', t('om_inbox'), '/omni/inbox'], ['grid', t('iamap'), '/ia']].map(q => `<button data-act="nav" data-r="${q[2]}">${ic(q[0])}${esc(q[1])}</button>`).join('')}</div>`, { icon: 'zap' })}
    </div>
  </div></div>`;
  return { html };
};

route('/overview', PAGES.overview);

/* =============================== APPROVAL CENTER =============================== */
const APF = { q: '', domain: 'all', type: 'all', prio: 'all', status: 'open', date: 'all', assignee: 'all' };
const APV = window.APV = { sel: null, refreshList() { const el = document.getElementById('apq'); if (el) el.innerHTML = apListHTML(); const c = document.getElementById('apcount'); if (c) c.textContent = apFiltered().length; } };
function apFiltered() { const n = nowTs(); return APPROVALS.filter(a => (APF.domain === 'all' || a.domain === APF.domain) && (APF.type === 'all' || a.type === APF.type) && (APF.prio === 'all' || a.priority === APF.prio) && (APF.status === 'all' || (APF.status === 'open' ? ['waiting', 'in_progress'].includes(a.status) : a.status === APF.status)) && (APF.assignee === 'all' || (APF.assignee === 'none' ? !a.assignee : a.assignee === APF.assignee)) && (APF.date === 'all' || n - a.ts < { d1: D, d7: 7 * D, d30: 30 * D }[APF.date]) && (!APF.q || (a.title + a.id + a.requester).toLowerCase().includes(APF.q.toLowerCase()))); }
function apListHTML() { if (S.ux === 'loading') return skel(6); if (S.ux === 'error') return stateBlock('error'); const L = S.ux === 'empty' ? [] : apFiltered(); if (!L.length) return S.ux === 'empty' ? stateBlock('empty', { title: L3(['Antrean kosong', 'Queue is clear', 'القائمة فارغة']), desc: L3(['Tidak ada request yang menunggu keputusan.', 'No requests waiting for a decision.', 'لا توجد طلبات بانتظار القرار.']) }) : stateBlock('noresult'); return L.map(a => `<a class="qitem" href="#/approval/${a.id}" aria-current="${APV.sel === a.id}" style="color:inherit;text-decoration:none"><span class="body"><span class="t1"><b>${esc(a.title)}</b>${a.fresh ? `<span class="st info">${L3(['Baru', 'New', 'جديد'])}</span>` : ''}</span><span class="t2">${esc(a.requester)} · <span class="mono">${a.id}</span></span><span class="t3">${prio(a.priority)}<span class="chip">${esc(a.domain)}</span>${st(a.status)}${a.risk >= 60 ? `<span class="st bad">${ic('alert')}Risk ${a.risk}</span>` : ''}<span class="muted" style="font-size:11.5px;margin-inline-start:auto">${esc(rel(a.ts))}</span></span></span></a>`).join(''); }
function apDetailHTML(a) {
  if (!a) return `<div style="margin:auto">${stateBlock('empty', { title: L3(['Pilih request', 'Select a request', 'اختر طلباً']), desc: L3(['Pilih item dari antrean untuk melihat konteks, dokumen, dan mengambil keputusan.', 'Pick an item from the queue to see context, documents and decide.', 'اختر عنصراً لعرض السياق والمستندات واتخاذ القرار.']) })}</div>`;
  const dk = DOMKEY[a.domain]; const canDecide = can('approval.decide:' + dk); const decided = ['approved', 'rejected'].includes(a.status); const riskTone = a.risk >= 60 ? 'bad' : a.risk >= 30 ? 'warn' : 'ok';
  const val = v => typeof v === 'number' ? money(v, true) : esc(v);
  return `<div class="pane-h" style="display:flex;gap:10px;align-items:flex-start;flex-wrap:wrap"><button class="btn sm ghost backm" data-act="ap-back">${icd('chevL', 'sm')}${t('back')}</button><div style="flex:1;min-width:220px"><div class="muted mono" style="font-size:11.5px">${a.id} · ${esc(a.domain)} · ${esc(L3([AP_TYPES[a.type][1], AP_TYPES[a.type][2], AP_TYPES[a.type][2]]))}</div><h2 style="margin:2px 0 6px;font-family:var(--font-display);font-size:19px;font-weight:650">${esc(a.title)}</h2><div style="display:flex;gap:6px;flex-wrap:wrap">${st(a.status)}${prio(a.priority)}<span class="chip">${ic('user', 'sm')}${esc(a.assignee || t('unassigned'))}</span><span class="chip">${ic('clock', 'sm')}${esc(fDT(a.ts))}</span></div></div>
    <div class="actions">${decided ? `<span class="muted" style="font-size:12.5px">${L3(['Keputusan final — tercatat di audit', 'Final decision — recorded in audit', 'قرار نهائي — مسجل'])}</span>` : `${permBtn('approval.decide:' + dk, ic('undo') + t('revise'), `data-act="ap-decide" data-v="needs_revision" data-id="${a.id}" data-mut`, 'warnb')}${permBtn('approval.decide:' + dk, ic('x') + t('reject'), `data-act="ap-decide" data-v="rejected" data-id="${a.id}" data-mut`, 'badb')}${permBtn('approval.decide:' + dk, ic('check') + t('approve'), `data-act="ap-decide" data-v="approved" data-id="${a.id}" data-mut`, 'primary')}`}</div></div>
  <div style="padding:16px;display:grid;gap:14px;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr)" class="apgrid">
   <div style="display:grid;gap:14px;align-content:start">
    ${!canDecide && !decided ? `<div class="banner warn" style="border:1px solid var(--warn-line);border-radius:10px">${ic('lock')}<span>${L3(['Anda dapat melihat request ini, tetapi keputusan domain', 'You can view this request, but decisions for domain', 'يمكنك العرض فقط؛ القرارات في المجال'])} <b>${esc(a.domain)}</b> ${L3(['membutuhkan permission', 'require permission', 'تتطلب الصلاحية'])} <span class="mono">approval.decide:${dk}</span>.</span></div>` : ''}
    ${pnl(t('requester'), `<div style="display:flex;gap:12px;align-items:center">${ent(a.requester, `<span class="mono">${esc(a.reqRef || '')}</span>`, colorFor(a.requester))}<span style="flex:1"></span>${a.reqRoute ? `<a class="btn sm" href="#${a.reqRoute}">${L3(['Buka resource', 'Open resource', 'فتح المورد'])}${icd('arrowR', 'sm')}</a>` : ''}</div>`, { icon: 'user' })}
    ${pnl(t('context'), `<dl class="dl">${(a.ctx || []).map(([k, v]) => `<dt>${esc(k)}</dt><dd>${val(v)}</dd>`).join('')}</dl>${a.diff ? `<div style="margin-top:14px;border:1px solid var(--line);border-radius:8px;overflow:hidden"><div class="diffrow diffhead"><div>Field</div><div>Before</div><div>After</div></div>${a.diff.map(d => `<div class="diffrow"><div class="muted">${esc(d[0])}</div><div class="b">${esc(d[1])}</div><div class="a">${esc(d[2])}</div></div>`).join('')}</div>` : ''}`, { icon: 'info' })}
    ${pnl(t('supdocs'), a.docs.length ? a.docs.map(d => `<div class="docrow"><span class="fi">${esc(d[0])}</span><span class="body"><b>${esc(d[1])}</b><span>${esc(d[2])} · ${L3(['diunggah', 'uploaded', 'مرفوع'])} ${esc(rel(a.ts))} · SHA-256 ✓</span></span><button class="btn sm ghost" data-act="doc-prev" data-n="${esc(d[1])}">${ic('eye', 'sm')}${t('view')}</button></div>`).join('') : `<div class="muted">${L3(['Tidak ada dokumen — request ini divalidasi dari data sistem.', 'No documents — validated from system data.', 'لا توجد مستندات.'])}</div>`, { icon: 'folder', small: a.docs.length })}
   </div>
   <div style="display:grid;gap:14px;align-content:start">
    ${pnl(t('riskind'), `<div class="risk"><span class="tnum" style="font-family:var(--font-display);font-size:26px;font-weight:650;color:var(--${riskTone})">${a.risk}</span><span class="muted">/100</span><div class="gauge"><i style="inset-inline-start:calc(${a.risk}% - 2px)"></i></div></div><ul style="margin:10px 0 0;padding-inline-start:18px;font-size:12.5px;color:var(--ink-2)">${a.risk >= 60 ? `<li>${L3(['Device & IP baru dalam 24 jam', 'New device & IP within 24h', 'جهاز وعنوان جديدان'])}</li><li>${L3(['Perubahan pada tujuan dana', 'Change to payout destination', 'تغيير في وجهة الأموال'])}</li><li>${L3(['Nama pemilik rekening berbeda dari badan hukum', 'Account holder differs from legal entity', 'اسم صاحب الحساب مختلف'])}</li>` : a.risk >= 30 ? `<li>${L3(['Nominal di atas rata-rata 30 hari', 'Amount above 30-day average', 'المبلغ فوق المتوسط'])}</li><li>${L3(['Dokumen perlu cek manual', 'Documents need manual check', 'المستندات تحتاج فحصاً'])}</li>` : `<li>${L3(['Tidak ada sinyal risiko signifikan', 'No significant risk signals', 'لا توجد إشارات مخاطر'])}</li>`}</ul><div class="aibox" style="margin-top:12px"><div class="h">${ic('sparkles', 'sm')}Segaloka AI · ${L3(['ringkasan', 'summary', 'ملخص'])}</div><p>${a.risk >= 60 ? L3(['Disarankan minta verifikasi video call dengan direktur sebelum menyetujui. AI hanya memberi saran — keputusan & validasi tetap mengikuti policy.', 'Recommend a video verification with the director before approving. AI only advises — decision & validation follow policy.', 'يُنصح بالتحقق عبر مكالمة فيديو. الذكاء الاصطناعي يقدم اقتراحات فقط.']) : L3(['Dokumen lengkap dan konsisten dengan data tenant. AI tidak menggantikan authorization atau policy.', 'Documents complete and consistent with tenant data. AI does not replace authorization or policy.', 'المستندات مكتملة. الذكاء الاصطناعي لا يحل محل الصلاحيات.'])}</p></div>`, { icon: 'shield' })}
    ${pnl(t('timeline'), `<ul class="tl">${a.history.map(h => `<li><span class="dotc ${h.tone}"></span><b>${esc(h.t)}</b><div class="m">${esc(fDT(h.ts))}${h.by ? ' · ' + esc(h.by) : ''}</div>${h.reason ? `<div style="font-size:12.5px;margin-top:3px;color:var(--ink-2)">“${esc(h.reason)}”</div>` : ''}</li>`).join('')}</ul>`, { icon: 'history' })}
    ${pnl(t('notes'), `${a.notes.map(n => `<div style="padding:8px 10px;background:var(--surface-2);border-radius:8px;margin-bottom:8px;font-size:12.5px"><b>${esc(n.by)}</b> <span class="muted">· ${esc(rel(n.ts))}</span><div>${esc(n.text)}</div></div>`).join('')}<div class="field" style="margin:0"><label for="apnote" class="sr">${t('notes')}</label><textarea id="apnote" placeholder="${L3(['Tambah catatan untuk reviewer lain…', 'Add a note for other reviewers…', 'أضف ملاحظة…'])}" style="min-height:60px"></textarea></div><button class="btn sm" style="margin-top:8px" data-act="ap-note" data-id="${a.id}">${ic('note', 'sm')}${L3(['Simpan catatan', 'Save note', 'حفظ'])}</button>`, { icon: 'note' })}
   </div></div>`;
}
function approvalPage(p) {
  APV.sel = p.id || null; const a = APPROVALS.find(x => x.id === APV.sel);
  const doms = [...new Set(APPROVALS.map(a => a.domain))];
  const sel = (id, v, opts, lab) => `<select class="select" id="${id}" data-apf="${v}" aria-label="${esc(lab)}">${opts.map(o => `<option value="${o[0]}" ${APF[v] === o[0] ? 'selected' : ''}>${esc(o[1])}</option>`).join('')}</select>`;
  const html = `<div class="page full"><div class="split ${a ? 'show-detail' : ''}" style="height:100%">
    <div class="pane list"><div class="pane-h">${crumbs([[t('g_utama'), '/overview'], [t('approval'), '/approval']])}<div style="display:flex;align-items:center;gap:8px"><h1 style="margin:0;font-family:var(--font-display);font-size:20px;flex:1">${t('ap_title')}</h1><span class="chip tnum" id="apcount">${apFiltered().length}</span></div><p class="muted" style="margin:4px 0 10px;font-size:12.5px">${t('ap_desc')}</p>
      <label class="input" style="min-width:0;width:100%;flex:none">${ic('search', 'sm')}<input id="apq-in" type="search" value="${esc(APF.q)}" placeholder="${L3(['Cari ID, judul, pemohon', 'Search ID, title, requester', 'ابحث'])}"></label>
      <div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px">${sel('apf-status', 'status', [['open', L3(['Terbuka', 'Open', 'مفتوحة'])], ['all', t('all')], ['waiting', 'Menunggu'], ['in_progress', 'Dalam proses'], ['needs_revision', 'Butuh revisi'], ['approved', 'Disetujui'], ['rejected', 'Ditolak']], t('status'))}${sel('apf-domain', 'domain', [['all', t('domain') + ': ' + t('all')], ...doms.map(d => [d, d])], t('domain'))}${sel('apf-type', 'type', [['all', t('reqtype') + ': ' + t('all')], ...Object.entries(AP_TYPES).map(([k, v]) => [k, L3([v[1], v[2], v[2]])])], t('reqtype'))}${sel('apf-prio', 'prio', [['all', t('priority') + ': ' + t('all')], ['p1', 'Tinggi'], ['p2', 'Sedang'], ['p3', 'Rendah']], t('priority'))}${sel('apf-date', 'date', [['all', t('submitted') + ': ' + t('all')], ['d1', '24 jam'], ['d7', '7 hari'], ['d30', '30 hari']], t('submitted'))}${sel('apf-asg', 'assignee', [['all', t('assignee') + ': ' + t('all')], ['none', t('unassigned')], ...ADMINS.map(x => [x, x])], t('assignee'))}</div></div>
      <div id="apq">${apListHTML()}</div></div>
    <div class="pane detail" id="apdetail">${apDetailHTML(a)}</div></div></div>`;
  return { html, mount() { const q = document.getElementById('apq-in'); q.addEventListener('input', () => { APF.q = q.value; APV.refreshList(); }); document.querySelectorAll('[data-apf]').forEach(s => s.addEventListener('change', () => { APF[s.dataset.apf] = s.value; APV.refreshList(); })); } };
}
route('/approval', approvalPage); route('/approval/:id', approvalPage);
function decideApproval(id, v, reason) { const a = APPROVALS.find(x => x.id === id); const prev = a.status; a.status = v; a.fresh = false; a.history.push({ t: L3(['Keputusan: ', 'Decision: ', 'القرار: ']) + L3(STATUS[v].slice(2)), ts: nowTs(), tone: v === 'approved' ? 'ok' : v === 'rejected' ? 'bad' : 'warn', by: 'Admin Pusat (' + ROLES[S.role].label + ')', reason }); audit('Admin Pusat', 'approval.' + v, 'Approval/' + id + ' (' + a.title + ')', 'success', { before: '{ "status": "' + prev + '" }', after: '{ "status": "' + v + '" }', reason });
  if (v === 'approved' && a.type === 'legal_doc') { const tr = travelById(a.reqRef); if (tr) { tr.lic.forEach(l => { if (l.status !== 'verified') { l.status = 'verified'; l.exp = T0 + 3 * 365 * D; } }); tr.legal = 'verified'; if (tr.op === 'review') tr.op = 'active'; } }
  if (a.type === 'withdrawal') { const w = WITHDRAWALS.find(w => w.party === a.requester && w.state === 'pending'); if (w) w.state = v === 'approved' ? 'approved' : v === 'rejected' ? 'rejected' : 'hold'; }
  toast(v === 'approved' ? 'ok' : v === 'rejected' ? 'bad' : 'warn', L3(STATUS[v].slice(2)) + ' · ' + id, L3(['Tercatat di Audit Log · resource terkait diperbarui', 'Recorded in Audit Log · related resource updated', 'سُجّل في سجل التدقيق']), '/compliance/audit'); rerender(); }

/* =============================== TRAVEL DIRECTORY =============================== */
const TRX = { plan: 'all', legal: 'all', pay: 'all', city: 'all' };
function licChips(tr) { return `<div class="lic">${tr.lic.map(l => `<span class="chip ${l.status === 'verified' ? 'v' : ['expired', 'rejected'].includes(l.status) ? 'x' : 'p'}" title="${esc(l.type + ' · ' + L3(STATUS[l.status].slice(2)))}">${l.type}${l.status === 'verified' ? ' ✓' : l.status === 'expiring' ? ' ⏱' : ['expired', 'rejected'].includes(l.status) ? ' ✕' : ' …'}</span>`).join('')}</div>`; }
function branchCell(tr) { const r = tr.branch.used / tr.branch.quota; return `<div style="min-width:96px"><div class="tnum" style="font-size:12.5px;margin-bottom:4px"><b>${tr.branch.used}</b> / ${tr.branch.quota}${tr.sub.addonBranch ? ` <span class="muted" style="font-size:11px" title="add-on">+${tr.sub.addonBranch}</span>` : ''}</div><div class="meter ${r >= 1 ? 'warn' : ''}"><i style="width:${r * 100}%"></i></div></div>`; }
PAGES.travelDir = () => {
  const qs = location.hash.includes('?new');
  const tb = defTable('travel', {
    name: 'Travel', placeholder: t('tr_search'), search: r => r.name + ' ' + r.id + ' ' + r.city, rows: () => TRAVELS.filter(x => (TRX.plan === 'all' || x.sub.plan === TRX.plan) && (TRX.legal === 'all' || x.legal === TRX.legal) && (TRX.pay === 'all' || x.payMode === TRX.pay) && (TRX.city === 'all' || x.city === TRX.city)), moreFilters: true,
    filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'active', label: t('f_active'), fn: r => r.op === 'active' }, { v: 'review', label: t('f_review'), fn: r => r.op === 'review' }, { v: 'inactive', label: t('f_inactive'), fn: r => r.op === 'inactive' }],
    route: r => '/travel/' + r.id, bulk: [{ k: 'export', label: 'Export' }, { k: 'remind', label: L3(['Kirim pengingat legalitas', 'Send legality reminder', 'إرسال تذكير']) }, { k: 'suspend', label: L3(['Suspend', 'Suspend', 'تعليق']) }],
    cols: [{ k: 'name', label: t('c_travel'), render: r => ent(r.name, `<span class="mono">${r.id}</span> · ${esc(r.city)}`, r.color), sv: r => r.name },
      { k: 'lic', label: t('c_license'), render: licChips, sort: false }, { k: 'legal', label: t('c_legal'), render: r => st(r.legal) },
      { k: 'sub', label: t('c_sub'), render: r => `<div style="display:grid;gap:3px">${st(r.sub.state)}<span class="muted" style="font-size:11.5px">${esc(r.sub.plan)}</span></div>`, sv: r => r.sub.state },
      { k: 'branch', label: t('c_branch'), render: branchCell, sv: r => r.branch.used }, { k: 'payMode', label: 'Payment flow', render: r => `<span class="chip mono">${r.payMode}</span>` },
      { k: 'gmv30', label: 'GMV 30d', cls: 'r tnum', render: r => money(r.gmv30) }, { k: 'op', label: t('status'), render: r => st(r.op === 'review' ? 'review' : r.op) },
      { k: 'act', label: t('action'), sort: false, cls: 'r', render: r => `<button class="iconbtn" data-act="row-menu" data-kind="travel" data-id="${r.id}" aria-label="${t('action')} ${esc(r.name)}">${ic('more')}</button>` }],
    card: r => `${ent(r.name, `<span class="mono">${r.id}</span> · ${esc(r.city)}`, r.color)}<div class="row">${st(r.op === 'review' ? 'review' : r.op)}${st(r.legal)}${licChips(r)}</div><div class="row"><span class="muted" style="font-size:12px">${esc(r.sub.plan)} · ${L3(STATUS[r.sub.state].slice(2))}</span><span class="tnum" style="font-size:12px">${t('c_branch')} ${r.branch.used}/${r.branch.quota}</span></div>`
  });
  const branches = TRAVELS.reduce((s, x) => s + x.branch.used, 0);
  const html = `<div class="page">${phead({ crumbs: [[t('g_eko'), '/travel'], ['Travel', '/travel'], [t('tr_title'), '/travel']], title: t('tr_title'), desc: t('tr_desc'), actions: `<button class="btn" data-act="preview-data">${ic('eye')}${t('preview')}</button><button class="btn" data-act="export" data-what="Travel">${ic('download')}${t('export')}</button>${permBtn('travel.create', ic('plus') + t('add_travel'), 'data-act="add-travel" data-mut', 'primary')}` })}
  ${gate(kpiRow([{ k: t('k_total'), v: fN(TRAVELS.length), d: `${TRAVELS.filter(x => x.op === 'active').length} ${L3(['aktif', 'active', 'نشطة'])} · ${mockmark()}`, icon: 'building' }, { k: t('k_verified'), v: fN(TRAVELS.filter(x => x.legal === 'verified' || x.legal === 'expiring').length), d: `${TRAVELS.filter(x => x.legal === 'expiring').length} ${L3(['segera expired', 'expiring soon', 'قاربت على الانتهاء'])}`, icon: 'filecheck', route: '/travel/legal' }, { k: t('k_waiting'), v: fN(TRAVELS.filter(x => x.legal === 'under_review').length), d: `<a href="#/approval">${L3(['Buka Approval Center', 'Open Approval Center', 'مركز الموافقات'])} →</a>`, icon: 'clock' }, { k: t('k_branch'), v: fN(branches), d: L3(['Default 2 cabang / subscription', 'Default 2 branches / subscription', 'فرعان افتراضياً']), icon: 'map', route: '/travel/branches' }]), 2)}
  <section class="panel" style="margin-top:14px">${tb}</section>
  <div class="grid g3" style="margin-top:14px">${pnl(L3(['Distribusi payment flow', 'Payment flow split', 'توزيع مسار الدفع']), hbars([['VIA_SEGALOKA', TRAVELS.filter(x => x.payMode === 'VIA_SEGALOKA').length], ['DIRECT_TO_TRAVEL', TRAVELS.filter(x => x.payMode === 'DIRECT_TO_TRAVEL').length]], fN), { icon: 'repeat' })}${pnl(L3(['Plan subscription', 'Subscription plans', 'خطط الاشتراك']), hbars(['Starter', 'Growth', 'Enterprise'].map(p => [p, TRAVELS.filter(x => x.sub.plan === p).length]), fN), { icon: 'refresh' })}${pnl(L3(['Izin per layanan', 'Licenses by service', 'التراخيص حسب الخدمة']), hbars(['BPW', 'PPIU', 'PIHK'].map(p => [p, TRAVELS.filter(x => x.lic.some(l => l.type === p)).length]), fN), { icon: 'filecheck' })}</div></div>`;
  return { html, mount() { if (qs) setTimeout(() => openAddTravel(), 60); } };
};
function openAddTravel() { if (!can('travel.create')) return; drawer({ title: t('add_travel'), sub: L3(['Tenant dibuat sebagai Draft → Submitted → verifikasi legalitas', 'Tenant is created as Draft → Submitted → legal verification', 'تُنشأ كمسودة ثم تُقدَّم للتوثيق']), body: `<div class="field"><label for="nt-name">${L3(['Nama badan usaha', 'Legal entity name', 'اسم الكيان'])} *</label><input type="text" id="nt-name" placeholder="PT …"></div><div class="grid g2" style="gap:10px"><div class="field"><label for="nt-city">${L3(['Kota', 'City', 'المدينة'])}</label><select id="nt-city">${CITIES.map(c => `<option>${c[0]}</option>`).join('')}</select></div><div class="field"><label for="nt-plan">Plan</label><select id="nt-plan"><option>Starter</option><option selected>Growth</option><option>Enterprise</option></select></div></div><div class="field"><label>${L3(['Layanan & izin wajib', 'Services & required licenses', 'الخدمات والتراخيص'])}</label><div style="display:grid;gap:6px;font-size:13px"><label><input type="checkbox" checked disabled> Tour / Halal Tour — <b>BPW</b></label><label><input type="checkbox" id="nt-u" checked> Umrah — <b>PPIU</b></label><label><input type="checkbox" id="nt-h"> Haji Khusus — <b>PIHK</b></label></div></div><div class="field"><label for="nt-pay">Payment flow</label><select id="nt-pay"><option>VIA_SEGALOKA</option><option>DIRECT_TO_TRAVEL</option></select><span class="hint">${L3(['VIA_SEGALOKA memakai ledger & settlement; DIRECT_TO_TRAVEL dana langsung ke rekening Travel via gateway terintegrasi.', 'VIA_SEGALOKA uses ledger & settlement; DIRECT_TO_TRAVEL routes funds straight to the Travel via the integrated gateway.', 'الخيار الأول عبر دفتر الأستاذ والتسوية.'])}</span></div><div class="auditbox">${ic('info')}<span>${L3(['Subscription langsung dibayar (tanpa trial otomatis). Default mencakup maks. 2 cabang; cabang tambahan berbayar.', 'Subscription is paid upfront (no automatic trial). Default covers up to 2 branches; extra branches are paid.', 'الاشتراك مدفوع مقدماً ويشمل فرعين.'])}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="add-travel-save">${L3(['Buat draft tenant', 'Create tenant draft', 'إنشاء مسودة'])}</button>` }); }
route('/travel', PAGES.travelDir);

/* =============================== TRAVEL DETAIL =============================== */
const TTABS = ['overview', 'identity', 'legal', 'branches', 'subscription', 'website', 'team', 'marketplace', 'booking', 'finance', 'activity'];
const TTLBL = { overview: 't_ov', identity: 't_id', legal: 't_legal', branches: 't_branch', subscription: 't_sub', website: 't_web', team: 't_team', marketplace: 't_mp', booking: 't_book', finance: 't_fin', activity: 't_act' };
function travelDetail(p) {
  const tr = travelById(p.id); if (!tr) return { html: `<div class="page">${crumbs([['Travel', '/travel'], [p.id, '']])}<div class="panel">${stateBlock('noresult', { title: L3(['Travel tidak ditemukan', 'Travel not found', 'غير موجود']), desc: 'ID ' + p.id + ' tidak ada atau Anda tidak memiliki akses. Backend tetap authoritative.' })}</div></div>` };
  const tab = TTABS.includes(p.tab) ? p.tab : 'overview';
  const pk = PACKAGES.filter(x => x.travel === tr.id), bk = BOOKINGS.filter(b => b.travel === tr.id), pay = PAYMENTS.filter(x => x.travel === tr.id), br = BRANCHES.filter(b => b.travel === tr.id);
  const counts = { legal: tr.lic.length, branches: br.length, marketplace: pk.length, booking: bk.length };
  const head = `${crumbs([[t('g_eko'), '/travel'], ['Travel', '/travel'], [tr.name, '/travel/' + tr.id], ...(tab !== 'overview' ? [[t(TTLBL[tab]), '']] : [])])}
  <div class="phead" style="margin-bottom:12px"><div class="ttl" style="display:flex;gap:14px;align-items:flex-start"><div class="ent"><div class="lg" style="background:${tr.color};width:52px;height:52px;border-radius:12px;font-size:17px">${initials(tr.name)}</div></div><div style="min-width:0"><h1>${esc(tr.name)}</h1><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px;align-items:center"><span class="chip mono">${tr.id}</span>${st(tr.op === 'review' ? 'review' : tr.op)}<span class="muted" style="font-size:12px">${L3(['Legal', 'Legal', 'قانوني'])}</span>${st(tr.legal)}<span class="muted" style="font-size:12px">Sub</span>${st(tr.sub.state)}<span class="chip">${esc(tr.sub.plan)}</span><span class="chip">${ic('map', 'sm')}${esc(tr.city)}</span></div><div class="muted" style="font-size:12.5px;margin-top:8px">${ic('user', 'sm')} ${esc(tr.contact.name)} · ${esc(tr.contact.role)} · <span class="mono">${esc(tr.contact.phone)}</span></div></div></div>
  <div class="actions"><a class="btn" href="#/omni/inbox">${ic('msg')}${t('contact_travel')}</a>${tr.op === 'inactive' ? permBtn('travel.suspend', ic('play') + t('reactivate'), `data-act="travel-status" data-id="${tr.id}" data-v="active" data-mut`, 'okb') : permBtn('travel.suspend', ic('ban') + t('suspend'), `data-act="travel-status" data-id="${tr.id}" data-v="inactive" data-mut`, 'badb')}<button class="btn" data-act="row-menu" data-kind="travel" data-id="${tr.id}" aria-label="More">${ic('more')}</button></div></div>
  <div class="kpis" style="grid-template-columns:repeat(5,minmax(0,1fr));margin-bottom:12px">${[['GMV 30d', money(tr.gmv30)], ['Booking 30d', fN(tr.book30)], [L3(['Paket', 'Packages', 'الباقات']), pk.filter(x => x.state === 'published').length + ' <small class="muted" style="font-size:13px">/ ' + pk.length + '</small>'], [t('c_branch'), tr.branch.used + ' <small class="muted" style="font-size:13px">/ ' + tr.branch.quota + '</small>'], ['Payment flow', `<span class="chip mono" style="font-size:11.5px">${tr.payMode}</span>`]].map(k => `<div class="kpi"><div class="k">${esc(k[0])}</div><div class="v">${k[1]}</div></div>`).join('')}</div>
  <div class="tabs" role="tablist" aria-label="Travel sections">${TTABS.map(k => `<a class="tab" role="tab" aria-selected="${k === tab}" href="#/travel/${tr.id}${k === 'overview' ? '' : '/' + k}">${esc(t(TTLBL[k]))}${counts[k] != null ? `<span class="n">${counts[k]}</span>` : ''}</a>`).join('')}</div>`;
  let body = '';
  if (tab === 'overview') {
    const exp = tr.lic.filter(l => l.status !== 'verified');
    body = `<div class="grid g12"><div class="c8" style="display:grid;gap:14px;align-content:start">
      ${pnl(L3(['Alur ekosistem tenant', 'Tenant ecosystem flow', 'تدفق منظومة الشركة']), `<div class="chain">${[['Travel', tr.id, tr.name.split(' ')[0], '/travel/' + tr.id + '/identity'], [L3(['Paket', 'Package', 'باقة']), pk.length, pk.filter(x => x.state === 'published').length + ' published', '/travel/' + tr.id + '/marketplace'], ['Marketplace', fC(pk.reduce((s, x) => s + x.views30, 0)), 'views 30d', '/marketplace/packages'], ['Booking', bk.length, bk.filter(b => ['confirmed', 'processing', 'ready'].includes(b.state)).length + ' confirmed+', '/travel/' + tr.id + '/booking'], ['Payment', pay.filter(x => x.status === 'paid').length, money(pay.filter(x => x.status === 'paid').reduce((s, x) => s + x.amount, 0)), '/travel/' + tr.id + '/finance'], ['Finance', tr.payMode === 'VIA_SEGALOKA' ? 'Ledger' : 'Direct', tr.payMode === 'VIA_SEGALOKA' ? 'settlement T+3' : 'gateway → Travel', '/travel/' + tr.id + '/finance']].map((c, i, a) => `<a class="cn" href="#${c[3]}"><span class="k">${esc(c[0])}</span><span class="v">${esc(c[1])}</span><span class="s">${esc(c[2])}</span></a>${i < a.length - 1 ? `<span class="ca">${icd('arrowR', 'sm')}</span>` : ''}`).join('')}</div>`, { icon: 'branch' })}
      ${pnl(L3(['Tren booking tenant (30 hari)', 'Tenant bookings (30 days)', 'حجوزات الشركة']), barChart(ser().map(d => ({ ts: d.ts, v: Math.round(d.book * tr.book30 / 1400 * (0.7 + ((d.ts / D) % 5) / 8)) })), { key: 'v', fmt: v => fN(Math.round(v)), label: 'bookings' }), { icon: 'bars' })}
     </div><div class="c4" style="display:grid;gap:14px;align-content:start">
      ${pnl(t('attention'), exp.length || tr.sub.state !== 'active' ? `<div class="list" style="margin:-14px">${exp.map(l => `<a class="li" href="#/travel/${tr.id}/legal"><span class="sev ${stTone(l.status)}"></span><span class="body"><b style="font-weight:550">${l.type} · ${L3(STATUS[l.status].slice(2))}</b><span class="sub">${esc(l.no)} · exp ${esc(fD(l.exp))}</span></span></a>`).join('')}${tr.sub.state !== 'active' ? `<a class="li" href="#/travel/${tr.id}/subscription"><span class="sev ${stTone(tr.sub.state)}"></span><span class="body"><b style="font-weight:550">Subscription · ${L3(STATUS[tr.sub.state].slice(2))}</b><span class="sub">${esc(tr.sub.plan)} · ${L3(['website & entitlement terdampak', 'website & entitlements affected', 'الموقع والامتيازات متأثرة'])}</span></span></a>` : ''}</div>` : `<div class="muted">${ic('check', 'sm')} ${L3(['Tidak ada isu terbuka.', 'No open issues.', 'لا توجد مشكلات.'])}</div>`, { icon: 'alert' })}
      ${pnl(t('recent'), `<ul class="tl">${tenantActivity(tr).slice(0, 5).map(h => `<li><span class="dotc ${h.tone}"></span><b style="font-weight:550">${esc(h.t)}</b><div class="m">${esc(h.by)} · ${esc(rel(h.ts))}</div></li>`).join('')}</ul>`, { icon: 'history', right: `<a class="btn sm ghost" href="#/travel/${tr.id}/activity">${icd('chevR', 'sm')}</a>` })}
     </div></div>`;
  }
  if (tab === 'identity') body = `<div class="grid g2">${pnl(L3(['Identitas badan usaha', 'Legal entity', 'الكيان القانوني']), `<dl class="dl"><dt>${L3(['Nama', 'Name', 'الاسم'])}</dt><dd>PT ${esc(tr.name)}</dd><dt>Travel ID</dt><dd class="mono">${tr.id}</dd><dt>NIB</dt><dd class="mono">${tr.nib}</dd><dt>NPWP</dt><dd class="mono">${tr.npwp}</dd><dt>${L3(['Alamat', 'Address', 'العنوان'])}</dt><dd>Jl. ${esc(tr.name.split(' ')[0])} No. ${(tr.id.charCodeAt(6) % 90) + 1}, ${esc(tr.city)}, ${esc(tr.prov)}</dd><dt>${L3(['Layanan', 'Services', 'الخدمات'])}</dt><dd>${tr.services.map(s => `<span class="chip">${s}</span>`).join(' ')}</dd><dt>${L3(['Bergabung', 'Joined', 'انضم'])}</dt><dd>${fD(tr.joined)}</dd></dl>`, { icon: 'building', right: permBtn('travel.edit', ic('note', 'sm') + L3(['Ajukan perubahan', 'Request change', 'طلب تعديل']), `data-act="sens-change" data-id="${tr.id}" data-mut`, 'sm') })}${pnl(L3(['Kontak utama & branding', 'Primary contact & branding', 'جهة الاتصال']), `<dl class="dl"><dt>PIC</dt><dd>${esc(tr.contact.name)} — ${esc(tr.contact.role)}</dd><dt>${L3(['Telepon', 'Phone', 'الهاتف'])}</dt><dd class="mono">${esc(tr.contact.phone)}</dd><dt>Email</dt><dd class="mono">${esc(tr.contact.email)}</dd><dt>Payment flow</dt><dd><span class="chip mono">${tr.payMode}</span></dd><dt>Website</dt><dd class="mono">${esc(tr.website)}</dd></dl><div class="auditbox" style="margin-top:12px">${ic('lock')}<span>${L3(['Perubahan rekening, NPWP, atau direksi adalah perubahan sensitif → masuk Approval Center.', 'Changes to bank account, tax ID or directors are sensitive → routed to Approval Center.', 'التغييرات الحساسة تمر عبر مركز الموافقات.'])}</span></div>`, { icon: 'user' })}</div>`;
  if (tab === 'legal') body = pnl(t('t_legal'), `<div class="tbl-wrap"><table class="t"><thead><tr><th>${L3(['Izin', 'License', 'الترخيص'])}</th><th>${L3(['Nomor', 'Number', 'الرقم'])}</th><th>${L3(['Berlaku s.d.', 'Valid until', 'صالح حتى'])}</th><th>${t('status')}</th><th>${L3(['Dokumen', 'Document', 'مستند'])}</th><th class="r">${t('action')}</th></tr></thead><tbody>${tr.lic.map((l, i) => `<tr><td><b>${l.type}</b><div class="muted" style="font-size:11.5px">${{ BPW: 'Biro Perjalanan Wisata', PPIU: 'Penyelenggara Perjalanan Ibadah Umrah', PIHK: 'Penyelenggara Ibadah Haji Khusus' }[l.type]}</div></td><td class="mono">${esc(l.no)}</td><td class="tnum">${fD(l.exp)}<div class="muted" style="font-size:11.5px">${rel(l.exp)}</div></td><td>${st(l.status)}</td><td><button class="btn sm ghost" data-act="doc-prev" data-n="${l.type}.pdf">${ic('filetext', 'sm')}${l.type}.pdf</button></td><td class="r">${l.status === 'verified' ? `<span class="muted" style="font-size:12px">—</span>` : `<div class="actions" style="justify-content:flex-end">${permBtn('compliance.verify', t('reject'), `data-act="lic-set" data-id="${tr.id}" data-i="${i}" data-v="rejected" data-mut`, 'sm badb')}${permBtn('compliance.verify', ic('check', 'sm') + L3(['Verifikasi', 'Verify', 'توثيق']), `data-act="lic-set" data-id="${tr.id}" data-i="${i}" data-v="verified" data-mut`, 'sm primary')}</div>`}</td></tr>`).join('')}</tbody></table></div><div class="panel-f"><span class="muted">Lifecycle:</span>${['draft', 'submitted', 'under_review', 'verified', 'rejected', 'expired'].map(s => st(s)).join('')}</div>`, { raw: true, icon: 'filecheck' });
  if (tab === 'branches') { const r = tr.branch.used / tr.branch.quota; body = `<div class="grid g12"><div class="c8">${pnl(t('t_branch'), br.length ? `<div class="list">${br.map((b, i) => `<div class="li"><span style="color:var(--ink-3)">${ic('map')}</span><span class="body"><b>${esc(b.name)}</b><span class="sub mono">${b.id} · ${esc(b.head)}</span></span>${b.paid ? `<span class="chip">Add-on</span>` : `<span class="chip">Default</span>`}${st(b.status)}</div>`).join('')}</div>` : stateBlock('empty', { title: L3(['Belum ada cabang', 'No branches yet', 'لا فروع']), desc: L3(['Subscription belum aktif atau tenant belum menambahkan cabang.', 'Subscription not active or no branches added yet.', 'الاشتراك غير نشط.']) }), { raw: true, icon: 'map', right: permBtn('travel.edit', ic('plus', 'sm') + L3(['Tambah cabang', 'Add branch', 'إضافة فرع']), `data-act="add-branch" data-id="${tr.id}" data-mut`, 'sm') })}</div><div class="c4">${pnl(L3(['Kuota cabang', 'Branch quota', 'حصة الفروع']), `<div class="kpi" style="padding:0;border:0"><div class="v">${tr.branch.used} / ${tr.branch.quota}</div></div><div class="meter ${r >= 1 ? 'warn' : ''}" style="margin:8px 0"><i style="width:${r * 100}%"></i></div><dl class="dl"><dt>Default</dt><dd>2 ${L3(['cabang', 'branches', 'فروع'])}</dd><dt>Add-on</dt><dd>${tr.sub.addonBranch} × Rp 450.000/bln</dd></dl>`, { icon: 'grid' })}</div></div>`; }
  if (tab === 'subscription') body = `<div style="display:grid;gap:14px">${pnl('Subscription lifecycle', `${lifeBar(['pending', 'active', 'grace', 'suspended', 'expired', 'cancelled'], tr.sub.state === 'trial' ? 'pending' : tr.sub.state)}<p class="muted" style="font-size:12.5px;margin:10px 0 0">${L3(['Subscription langsung dibayar. Trial hanya melalui request (Approval Center).', 'Subscriptions are paid upfront. Trial only via request (Approval Center).', 'الاشتراك مدفوع مقدماً؛ التجربة بطلب فقط.'])}</p>`, { icon: 'refresh' })}<div class="grid g3">${pnl('Plan', `<div class="kpi" style="padding:0;border:0"><div class="v">${tr.sub.plan}</div><div class="d">${money(tr.sub.price, true)} / ${L3(['bulan', 'month', 'شهر'])}</div></div><dl class="dl" style="margin-top:10px"><dt>${L3(['Perpanjangan', 'Renewal', 'التجديد'])}</dt><dd>${fD(tr.sub.renew)}</dd><dt>Status</dt><dd>${st(tr.sub.state)}</dd></dl>`, { icon: 'grid' })}${pnl('Entitlement', `<ul class="list">${[['Website Travel', ['active', 'grace', 'trial'].includes(tr.sub.state)], ['Cabang: ' + tr.branch.quota, true], ['CRM seats: ' + { Starter: 3, Growth: 10, Enterprise: 50 }[tr.sub.plan], true], ['Marketplace listing', tr.op === 'active'], ['Omnichannel WA', tr.sub.plan !== 'Starter']].map(e => `<li style="display:flex;gap:8px;padding:5px 0;font-size:13px">${e[1] ? `<span style="color:var(--ok)">${ic('check', 'sm')}</span>` : `<span style="color:var(--ink-3)">${ic('minus', 'sm')}</span>`}${esc(e[0])}</li>`).join('')}</ul>`, { icon: 'shieldc' })}${pnl(L3(['Invoice', 'Invoices', 'الفواتير']), `<div class="list" style="margin:-14px">${[0, 1, 2].map(i => `<div class="li"><span class="body"><b class="mono" style="font-weight:500">INV-SUB-${tr.id.slice(4)}-${9 - i}</b><span class="sub">${fD(tr.sub.renew - (i + 1) * 30 * D)}</span></span><span class="tnum">${money(tr.sub.price)}</span>${st(i === 0 && tr.sub.state === 'grace' ? 'awaiting_payment' : 'paid')}</div>`).join('')}</div>`, { icon: 'filetext' })}</div></div>`;
  if (tab === 'website') { const on = ['active', 'grace', 'trial'].includes(tr.sub.state); body = pnl('Website Travel', `<div class="grid g2"><div><dl class="dl"><dt>Domain</dt><dd class="mono">${esc(tr.website)}</dd><dt>Status</dt><dd>${st(on ? 'published' : 'unpublished')}</dd><dt>Entitlement</dt><dd>${L3(['Mengikuti subscription', 'Follows subscription', 'يتبع الاشتراك'])} (${L3(STATUS[tr.sub.state].slice(2))})</dd><dt>SSL</dt><dd>${st(on ? 'active' : 'inactive')}</dd><dt>${L3(['Paket tampil', 'Listed packages', 'الباقات المعروضة'])}</dt><dd>${pk.filter(x => x.state === 'published').length}</dd></dl></div><div class="brandprev"><div style="background:${tr.color};color:#fff;padding:14px 16px;font-family:var(--font-display);font-weight:650">${esc(tr.name)}</div><div style="padding:14px;display:grid;gap:8px">${pk.slice(0, 3).map(x => `<div style="display:flex;justify-content:space-between;font-size:12.5px"><span>${esc(x.name)}</span><b class="tnum">${money(x.price)}</b></div>`).join('') || '<span class="muted">—</span>'}</div></div></div>`, { icon: 'globe' }); }
  if (tab === 'team') body = pnl(t('t_team'), `<div class="tbl-wrap"><table class="t"><thead><tr><th>User</th><th>Role (tenant)</th><th>${L3(['Cabang', 'Branch', 'الفرع'])}</th><th>2FA</th><th>${L3(['Login terakhir', 'Last login', 'آخر دخول'])}</th></tr></thead><tbody>${[tr.contact.name, PEOPLE[3], PEOPLE[8], PEOPLE[12]].map((n, i) => `<tr><td>${ent(n, i === 0 ? 'Owner' : '', colorFor(n))}</td><td>${['Tenant Owner', 'Admin Operasional', 'Finance Tenant', 'Sales'][i]}</td><td>${br[i % Math.max(1, br.length)] ? esc(br[i % br.length].name) : '—'}</td><td>${st(i === 3 ? 'inactive' : 'active')}</td><td>${rel(nowTs() - (i * 7 + 2) * H)}</td></tr>`).join('')}</tbody></table></div>`, { raw: true, icon: 'users' });
  if (tab === 'marketplace') body = pnl(L3(['Paket di Marketplace', 'Packages on Marketplace', 'الباقات في السوق']), pk.length ? `<div class="tbl-wrap"><table class="t"><thead><tr><th>${L3(['Paket', 'Package', 'الباقة'])}</th><th>${L3(['Kategori', 'Category', 'الفئة'])}</th><th class="r">${L3(['Harga', 'Price', 'السعر'])}</th><th>${L3(['Berangkat', 'Departure', 'المغادرة'])}</th><th class="r">Seat</th><th>Lifecycle</th><th class="r">${t('action')}</th></tr></thead><tbody>${pk.map(x => `<tr><td><b>${esc(x.name)}</b><div class="muted mono" style="font-size:11.5px">${x.id}${typeof SD_OFF !== 'undefined' && SD_OFF.some(o => o.pkg === x.id) ? ' · SegaDeals' : ''}</div></td><td>${x.cat}</td><td class="r tnum">${money(x.price)}</td><td>${fD(x.dep)}</td><td class="r tnum">${x.sold}/${x.seats}</td><td>${st(x.state)}</td><td class="r">${pkgActions(x)}</td></tr>`).join('')}</tbody></table></div><div class="panel-f"><span class="muted">${L3(['Draft → Review → Published → Unpublished/Withdrawn → Archived. Draft & submit hanya oleh tenant pemilik resource.', 'Draft → Review → Published → Unpublished/Withdrawn → Archived. Draft & submit only by the owning tenant.', 'المسودة والتقديم من الشركة المالكة فقط.'])}</span></div>` : stateBlock('empty'), { raw: true, icon: 'package' });
  if (tab === 'booking') body = `<section class="panel">${defTable('tbk-' + tr.id, bookingTableCfg(() => BOOKINGS.filter(b => b.travel === tr.id)))}</section>`;
  if (tab === 'finance') { const stl = SETTLEMENTS.filter(s => s.travel === tr.id); body = `<div class="grid g3">${pnl('Payment flow', `<div class="chip mono" style="font-size:12px">${tr.payMode}</div><p class="muted" style="font-size:12.5px">${tr.payMode === 'VIA_SEGALOKA' ? L3(['Dana masuk ke ledger Segaloka, di-settle T+3 dikurangi fee & reserve 5%.', 'Funds land in the Segaloka ledger, settled T+3 minus fee & 5% reserve.', 'تصل الأموال إلى دفتر الأستاذ وتُسوّى T+3.']) : L3(['Dana langsung ke rekening Travel via gateway terintegrasi; Segaloka mencatat event & fee.', 'Funds go straight to the Travel account via the integrated gateway; Segaloka records events & fees.', 'تذهب الأموال مباشرة إلى الشركة.'])}</p>`, { icon: 'repeat' })}${pnl('Ledger', `<dl class="dl"><dt>${L3(['Saldo tersedia', 'Available', 'متاح'])}</dt><dd class="tnum"><b>${money(tr.gmv30 * .42, true)}</b></dd><dt>Reserve</dt><dd class="tnum">${money(tr.gmv30 * .05, true)}</dd><dt>Hold</dt><dd class="tnum">${money(0, true)}</dd></dl>`, { icon: 'layers' })}${pnl(L3(['Deposit Travel', 'Travel deposit', 'وديعة الشركة']), `<div class="kpi" style="padding:0;border:0"><div class="v">${money(50e6)}</div><div class="d">${st('active')}</div></div>`, { icon: 'download' })}</div><div style="margin-top:14px">${pnl('Settlement', stl.length ? `<div class="tbl-wrap"><table class="t"><thead><tr><th>ID</th><th class="r">Gross</th><th class="r">Fee</th><th class="r">Reserve</th><th class="r">Net</th><th>${L3(['Jadwal', 'Scheduled', 'موعد'])}</th><th>${t('status')}</th></tr></thead><tbody>${stl.map(s => `<tr><td class="mono">${s.id}</td><td class="r tnum">${money(s.gross, true)}</td><td class="r tnum">${money(s.fee, true)}</td><td class="r tnum">${money(s.reserve, true)}</td><td class="r tnum"><b>${money(s.net, true)}</b></td><td>${fD(s.sched)}</td><td>${st(s.state)}</td></tr>`).join('')}</tbody></table></div>` : stateBlock('empty', { title: L3(['Tidak ada settlement', 'No settlements', 'لا تسويات']), desc: tr.payMode === 'DIRECT_TO_TRAVEL' ? L3(['Tenant memakai DIRECT_TO_TRAVEL — tidak ada settlement dari ledger.', 'Tenant uses DIRECT_TO_TRAVEL — no ledger settlements.', 'الدفع مباشر.']) : '' }), { raw: true, icon: 'landmark' })}</div><div style="margin-top:14px">${pnl('Payment', `<div class="tbl-wrap"><table class="t"><thead><tr><th>Payment</th><th>Booking</th><th class="r">Amount</th><th>Provider</th><th>${t('status')}</th><th>Recon</th></tr></thead><tbody>${pay.slice(0, 8).map(x => `<tr class="clickable" data-href="/finance/payment/${x.id}"><td class="mono">${x.id}</td><td class="mono">${x.booking}</td><td class="r tnum">${money(x.amount, true)}</td><td>${x.provider} · ${x.channel}</td><td>${st(x.status)}</td><td>${st(x.recon)}</td></tr>`).join('')}</tbody></table></div>`, { raw: true, icon: 'card' })}</div>`; }
  if (tab === 'activity') body = pnl(t('t_act'), `<ul class="tl">${tenantActivity(tr).map(h => `<li><span class="dotc ${h.tone}"></span><b style="font-weight:550">${esc(h.t)}</b><div class="m">${esc(h.by)} · ${esc(fDT(h.ts))} · <span class="mono">${esc(h.src)}</span></div></li>`).join('')}</ul>`, { icon: 'history', right: `<a class="btn sm" href="#/compliance/audit">Audit Log${icd('arrowR', 'sm')}</a>` });
  return { html: `<div class="page">${head}<div style="margin-top:14px">${gate(body)}</div></div>` };
}
function tenantActivity(tr) { const a = AUDIT.filter(x => x.resource.includes(tr.id)).map(x => ({ t: x.action + (x.reason ? ' — ' + x.reason : ''), ts: x.ts, by: x.actor, tone: x.result === 'failed' ? 'bad' : 'ok', src: x.source })); return [...a, { t: L3(['Paket dipublikasikan', 'Package published', 'نُشرت باقة']), ts: nowTs() - 30 * H, by: 'Sistem · moderasi', tone: 'ok', src: 'Worker' }, { t: L3(['Dokumen PPIU diunggah', 'PPIU document uploaded', 'رُفع مستند PPIU']), ts: nowTs() - 3 * D, by: tr.contact.name, tone: 'info', src: 'Tenant portal' }, { t: 'Subscription ' + tr.sub.plan + ' ' + L3(['diperpanjang', 'renewed', 'جُدد']), ts: nowTs() - 20 * D, by: 'Billing', tone: 'ok', src: 'Billing worker' }, { t: L3(['Tenant dibuat', 'Tenant created', 'أُنشئت الشركة']), ts: tr.joined, by: 'Admin Pusat', tone: 'neu', src: 'Control Center' }]; }
function pkgActions(x) { if (x.state === 'published') return permBtn('marketplace.moderate', L3(['Unpublish', 'Unpublish', 'إلغاء النشر']), `data-act="pkg-set" data-id="${x.id}" data-v="unpublished" data-mut`, 'sm'); if (x.state === 'review') return `<div class="actions" style="justify-content:flex-end">${permBtn('marketplace.moderate', t('reject'), `data-act="pkg-set" data-id="${x.id}" data-v="draft" data-mut`, 'sm badb')}${permBtn('marketplace.moderate', L3(['Publish', 'Publish', 'نشر']), `data-act="pkg-set" data-id="${x.id}" data-v="published" data-mut`, 'sm primary')}</div>`; if (x.state === 'draft') return `<span class="muted" style="font-size:12px" data-tip="${esc(L3(['Hanya tenant pemilik yang dapat submit draft', 'Only the owning tenant can submit a draft', 'فقط المالك يمكنه التقديم']))}">${ic('lock', 'sm')} ${L3(['Menunggu tenant', 'Awaiting tenant', 'بانتظار الشركة'])}</span>`; if (x.state === 'unpublished') return permBtn('marketplace.moderate', ic('archive', 'sm') + t('archive'), `data-act="pkg-set" data-id="${x.id}" data-v="archived" data-mut`, 'sm'); return '<span class="muted">—</span>'; }
route('/travel/:id', travelDetail); route('/travel/:id/:tab', p => travelDetail(p));

/* booking table config shared */
function bookingTableCfg(rows) { return { name: 'Booking', placeholder: L3(['Cari Booking ID, traveler, paket', 'Search Booking ID, traveler, package', 'ابحث']), search: r => r.id + ' ' + trvName(r.traveler) + ' ' + (pkgById(r.pkg) || {}).name, rows, route: r => '/booking/' + r.id,
  filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'pay', label: 'Awaiting / Partial', fn: r => ['awaiting_payment', 'partially_paid'].includes(r.state) }, { v: 'conf', label: 'Confirmed → Ready', fn: r => ['confirmed', 'processing', 'ready'].includes(r.state) }, { v: 'exc', label: L3(['Pengecualian', 'Exceptions', 'استثناءات']), fn: r => BK_EXC.includes(r.state) }],
  cols: [{ k: 'id', label: 'Booking', render: r => `<b class="mono" style="font-weight:600">${r.id}</b><div class="muted" style="font-size:11.5px">${esc(fDT(r.created))} · ${esc(r.source)}</div>` }, { k: 'traveler', label: 'Traveler', render: r => `${esc(trvName(r.traveler))}<div class="muted" style="font-size:11.5px">${r.pax} pax</div>`, sv: r => trvName(r.traveler) }, { k: 'pkg', label: L3(['Paket', 'Package', 'الباقة']), render: r => `${esc((pkgById(r.pkg) || {}).name)}<div class="muted" style="font-size:11.5px">${esc(travelById(r.travel).name)}</div>` }, { k: 'total', label: 'Total', cls: 'r tnum', render: r => money(r.total) }, { k: 'paid', label: L3(['Terbayar', 'Paid', 'مدفوع']), cls: 'r', render: r => `<div style="min-width:90px"><div class="tnum" style="font-size:12px">${pct(r.paid / r.total * 100, 0)}</div><div class="meter ${r.paid >= r.total ? 'ok' : ''}"><i style="width:${r.paid / r.total * 100}%"></i></div></div>` }, { k: 'state', label: t('status'), render: r => st(r.state) }, { k: 'dep', label: L3(['Berangkat', 'Departure', 'المغادرة']), render: r => fD(r.dep) }],
  card: r => `<div style="display:flex;justify-content:space-between;gap:8px"><b class="mono">${r.id}</b>${st(r.state)}</div><div class="row"><span>${esc(trvName(r.traveler))} · ${r.pax} pax</span><b class="tnum">${money(r.total)}</b></div><div class="muted" style="font-size:12px;margin-top:4px">${esc((pkgById(r.pkg) || {}).name)}</div>` }; }
