/* =============================== FUNCTIONAL (medium) PAGES =============================== */
const dirPage = ({ nav, title, desc, actions, kpis, tableId, cfg, extra, note }) => { const n = NAVIDX[nav]; const tr = navTrail(nav); return { html: `<div class="page">${phead({ crumbs: tr.map(x => [x[0], x[1] || S.route]), title: title || t(nav), desc, actions: (actions || '') + `<button class="btn" data-act="export" data-what="${esc(t(nav))}">${ic('download')}Export</button>` })}${note ? `<div class="banner info" style="border:1px solid var(--info-line);border-radius:10px;margin-bottom:14px">${ic('info')}<span>${note}</span></div>` : ''}${kpis ? gate(kpiRow(kpis), 2) : ''}<section class="panel" style="${kpis ? 'margin-top:14px' : ''}">${defTable(tableId, cfg)}</section>${extra || ''}</div>` }; };
const lvlNote = () => `${mockmark()} ${L3(['Fungsional — data simulasi', 'Functional — mock data', 'وظيفي — بيانات تجريبية'])}`;

route('/travel/branches', () => dirPage({ nav: 'travel_branch', desc: L3(['Cabang milik tenant Travel. Default subscription mencakup maksimal 2 cabang; cabang tambahan berbayar (add-on).', 'Branches owned by Travel tenants. Default subscription covers up to 2 branches; extra branches are paid add-ons.', 'فروع الشركات. يشمل الاشتراك فرعين.']), tableId: 'branches', kpis: [{ k: L3(['Cabang aktif', 'Active branches', 'فروع نشطة']), v: fN(BRANCHES.filter(b => b.status === 'active').length) }, { k: 'Add-on', v: fN(BRANCHES.filter(b => b.paid).length) }, { k: L3(['Tenant penuh kuota', 'Tenants at quota', 'شركات بلغت الحصة']), v: fN(TRAVELS.filter(x => x.branch.used >= x.branch.quota).length) }, { k: L3(['Rata-rata / tenant', 'Avg / tenant', 'المتوسط']), v: fN(BRANCHES.length / TRAVELS.length, { maximumFractionDigits: 1 }) }],
  cfg: { name: 'Cabang', search: r => r.name + r.id + travelById(r.travel).name + r.city, rows: () => BRANCHES, route: r => '/travel/' + r.travel + '/branches', filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'def', label: 'Default', fn: r => !r.paid }, { v: 'add', label: 'Add-on', fn: r => r.paid }], cols: [{ k: 'name', label: L3(['Cabang', 'Branch', 'الفرع']), render: r => `<b>${esc(r.name)}</b><div class="muted mono" style="font-size:11.5px">${r.id}</div>` }, { k: 'travel', label: 'Travel', render: r => esc(travelById(r.travel).name) }, { k: 'city', label: L3(['Kota', 'City', 'المدينة']) }, { k: 'head', label: L3(['Kepala cabang', 'Branch head', 'مدير الفرع']) }, { k: 'paid', label: L3(['Tipe', 'Type', 'النوع']), render: r => `<span class="chip">${r.paid ? 'Add-on' : 'Default'}</span>` }, { k: 'status', label: t('status'), render: r => st(r.status) }] } }));
function licRows() { const out = []; TRAVELS.forEach(tr => tr.lic.forEach((l, i) => out.push({ id: tr.id + '-' + l.type, tr, l, i }))); return out; }
const licCfg = () => ({ name: 'Legalitas', placeholder: t('tr_search'), search: r => r.tr.name + r.tr.id + r.l.type + r.l.no, rows: licRows, route: r => '/travel/' + r.tr.id + '/legal', filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...['under_review', 'submitted', 'expiring', 'expired', 'rejected', 'verified'].map(s => ({ v: s, label: L3(STATUS[s].slice(2)), fn: r => r.l.status === s }))], bulk: [{ k: 'remind', label: L3(['Kirim pengingat', 'Send reminder', 'إرسال تذكير']) }],
  cols: [{ k: 'tr', label: 'Travel', render: r => ent(r.tr.name, `<span class="mono">${r.tr.id}</span>`, r.tr.color), sv: r => r.tr.name }, { k: 'type', label: L3(['Izin', 'License', 'الترخيص']), render: r => `<b>${r.l.type}</b>`, sv: r => r.l.type }, { k: 'no', label: L3(['Nomor', 'Number', 'الرقم']), render: r => `<span class="mono">${esc(r.l.no)}</span>`, sort: false }, { k: 'exp', label: L3(['Berlaku s.d.', 'Valid until', 'صالح حتى']), render: r => `${fD(r.l.exp)}<div class="muted" style="font-size:11.5px">${rel(r.l.exp)}</div>`, sv: r => r.l.exp }, { k: 'status', label: t('status'), render: r => st(r.l.status), sv: r => r.l.status }],
  card: r => `${ent(r.tr.name, r.l.type + ' · ' + esc(r.l.no), r.tr.color)}<div class="row">${st(r.l.status)}<span class="muted" style="font-size:12px">${fD(r.l.exp)}</span></div>` });
route('/travel/legal', () => dirPage({ nav: 'travel_legal', desc: L3(['Perizinan per layanan: BPW (tour), PPIU (umrah), PIHK (haji khusus). Lifecycle: Draft → Submitted → Under Review → Verified / Rejected → Expired.', 'Licensing per service: BPW (tour), PPIU (umrah), PIHK (special hajj). Lifecycle: Draft → Submitted → Under Review → Verified / Rejected → Expired.', 'التراخيص حسب الخدمة.']), tableId: 'lic', cfg: licCfg(), kpis: ['verified', 'under_review', 'expiring', 'expired'].map(s => ({ k: L3(STATUS[s].slice(2)), v: fN(licRows().filter(r => r.l.status === s).length) })) }));
route('/compliance/legal', () => dirPage({ nav: 'legal', desc: L3(['Pandangan compliance atas seluruh dokumen legal ekosistem (Travel & Vendor).', 'Compliance view of all legal documents in the ecosystem (Travel & Vendor).', 'عرض الامتثال لكل المستندات.']), tableId: 'lic2', cfg: licCfg() }));
const subsCfg = () => ({ name: 'Subscription', placeholder: t('tr_search'), search: r => r.name + r.id, rows: () => TRAVELS, route: r => '/travel/' + r.id + '/subscription', filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...['pending', 'active', 'trial', 'grace', 'suspended', 'expired', 'cancelled'].map(s => ({ v: s, label: L3(STATUS[s].slice(2)), fn: r => r.sub.state === s }))],
  cols: [{ k: 'name', label: 'Travel', render: r => ent(r.name, `<span class="mono">${r.id}</span>`, r.color) }, { k: 'plan', label: 'Plan', render: r => `<b>${r.sub.plan}</b><div class="muted tnum" style="font-size:11.5px">${money(r.sub.price, true)}/bln</div>`, sv: r => r.sub.price }, { k: 'state', label: 'Lifecycle', render: r => st(r.sub.state), sv: r => r.sub.state }, { k: 'renew', label: L3(['Perpanjangan', 'Renewal', 'التجديد']), render: r => `${fD(r.sub.renew)}<div class="muted" style="font-size:11.5px">${rel(r.sub.renew)}</div>`, sv: r => r.sub.renew }, { k: 'br', label: L3(['Cabang', 'Branches', 'الفروع']), render: branchCell, sv: r => r.branch.used }, { k: 'web', label: 'Website', render: r => st(['active', 'grace', 'trial'].includes(r.sub.state) ? 'published' : 'unpublished'), sort: false }] });
route('/travel/subscription', () => dirPage({ nav: 'travel_subs', desc: 'Pending → Active → Grace Period → Suspended → Expired → Cancelled. ' + L3(['Website Travel mengikuti entitlement subscription.', 'Travel Website follows subscription entitlement.', 'الموقع يتبع الاشتراك.']), tableId: 'subs', cfg: subsCfg(), kpis: ['active', 'grace', 'suspended', 'pending'].map(s => ({ k: L3(STATUS[s].slice(2)), v: fN(TRAVELS.filter(x => x.sub.state === s).length) })) }));
route('/saas/subscription', () => dirPage({ nav: 'sub', desc: L3(['Semua subscription SaaS (saat ini: tenant Travel). Subscription langsung dibayar; trial hanya via request.', 'All SaaS subscriptions (currently: Travel tenants). Paid upfront; trial only via request.', 'كل الاشتراكات.']), tableId: 'subs2', cfg: subsCfg(), kpis: [{ k: 'MRR', v: money(TRAVELS.filter(x => ['active', 'grace'].includes(x.sub.state)).reduce((s, x) => s + x.sub.price + x.sub.addonBranch * 45e4, 0)) }, { k: 'Active', v: fN(TRAVELS.filter(x => x.sub.state === 'active').length) }, { k: 'Grace', v: fN(TRAVELS.filter(x => x.sub.state === 'grace').length) }, { k: 'Churn 30d', v: TRAVELS.length ? pct(TRAVELS.filter(x => ['expired', 'cancelled'].includes(x.sub.state) && (x.sub.endedAt || x.sub.renew || 0) >= nowTs() - 30 * D).length / TRAVELS.length * 100) : '—' }] }));

/* Vendor */
const vendorCols = [{ k: 'name', label: 'Vendor', render: r => ent(r.name, `<span class="mono">${r.id}</span> · ${esc(r.country)}`, r.color) }, { k: 'cats', label: L3(['Kategori layanan', 'Service categories', 'الفئات']), render: r => `<div class="lic">${r.cats.map(c => `<span class="chip">${esc(c)}</span>`).join('')}</div>`, sort: false }, { k: 'verif', label: L3(['Verifikasi', 'Verification', 'التوثيق']), render: r => st(r.verif) }, { k: 'products', label: L3(['Produk', 'Products', 'منتجات']), cls: 'r tnum' }, { k: 'orders30', label: 'Order 30d', cls: 'r tnum' }, { k: 'gmv30', label: 'GMV 30d', cls: 'r tnum', render: r => money(r.gmv30) }, { k: 'sla', label: 'SLA', cls: 'r tnum', render: r => r.sla + '%' }, { k: 'status', label: t('status'), render: r => st(r.status) }];
route('/vendor', () => dirPage({ nav: 'vendor_all', desc: L3(['Penyedia layanan ekosistem — hotel, tiket, visa, catering, transportasi, land arrangement, akomodasi. Satu vendor dapat memiliki banyak jenis layanan. Vendor terpisah dari Affiliate.', 'Ecosystem service providers — hotel, ticket, visa, catering, transport, land arrangement, accommodation. One vendor can offer many service types. Vendors are separate from Affiliates.', 'مزودو الخدمات. المورد منفصل عن المسوق.']), tableId: 'vendors', kpis: [{ k: 'Total Vendor', v: fN(VENDORS.length) }, { k: L3(['Terverifikasi', 'Verified', 'موثق']), v: fN(VENDORS.filter(v => v.verif === 'verified').length) }, { k: 'GMV 30d', v: money(VENDORS.reduce((s, v) => s + v.gmv30, 0)) }, { k: L3(['Saldo belum ditarik', 'Unwithdrawn balance', 'رصيد غير مسحوب']), v: money(VENDORS.reduce((s, v) => s + v.balance, 0)), route: '/finance/withdrawal' }],
  cfg: { name: 'Vendor', search: r => r.name + r.id + r.cats.join(' '), rows: () => VENDORS, route: r => '/vendor/' + r.id, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...VENDOR_CATS.slice(0, 6).map(c => ({ v: c, label: c, fn: r => r.cats.includes(c) }))], cols: vendorCols, card: r => `${ent(r.name, r.cats.join(', '), r.color)}<div class="row">${st(r.verif)}<b class="tnum">${money(r.gmv30)}</b></div>` } }));
route('/vendor/verification', () => dirPage({ nav: 'vendor_verif', desc: L3(['Antrean verifikasi vendor. Keputusan diambil di Approval Center agar tercatat.', 'Vendor verification queue. Decisions happen in Approval Center so they are recorded.', 'قائمة توثيق الموردين.']), tableId: 'vverif', cfg: { name: 'Verifikasi', search: r => r.name + r.id, rows: () => VENDORS.filter(v => v.verif !== 'verified'), route: r => '/vendor/' + r.id, cols: vendorCols } }));
const VTABS = ['identity', 'category', 'verification', 'products', 'orders', 'finance', 'withdrawal', 'performance', 'documents', 'activity'];
function vendorDetail(p) { const v = VENDORS.find(x => x.id === p.id); if (!v) return { html: `<div class="page">${stateBlock('noresult')}</div>` }; const tab = VTABS.includes(p.tab) ? p.tab : 'identity'; const wd = WITHDRAWALS.filter(w => w.ref === v.id);
  const lbl = { identity: L3(['Identitas', 'Identity', 'الهوية']), category: L3(['Kategori', 'Category', 'الفئة']), verification: L3(['Verifikasi', 'Verification', 'التوثيق']), products: L3(['Produk & Layanan', 'Products & Services', 'المنتجات']), orders: 'Order', finance: 'Finance', withdrawal: 'Withdrawal', performance: 'Performance', documents: L3(['Dokumen', 'Documents', 'المستندات']), activity: 'Activity' };
  let body = '';
  if (tab === 'identity') body = pnl(lbl.identity, `<dl class="dl"><dt>Vendor ID</dt><dd class="mono">${v.id}</dd><dt>${L3(['Negara', 'Country', 'البلد'])}</dt><dd>${esc(v.country)}</dd><dt>${L3(['Bergabung', 'Joined', 'انضم'])}</dt><dd>${fD(v.joined)}</dd><dt>Rating</dt><dd>★ ${v.rating}</dd><dt>${L3(['Pembayaran', 'Payments', 'المدفوعات'])}</dt><dd>${L3(['Melalui Segaloka; withdrawal mengikuti transaksi/pembelian yang selesai.', 'Through Segaloka; withdrawal follows completed transactions/purchases.', 'عبر Segaloka.'])}</dd></dl>`, { icon: 'store' });
  else if (tab === 'category') body = pnl(lbl.category, `<div style="display:flex;gap:8px;flex-wrap:wrap">${VENDOR_CATS.map(c => `<span class="chip" style="${v.cats.includes(c) ? 'background:var(--accent-soft);color:var(--accent-text);font-weight:600' : ''}">${v.cats.includes(c) ? '✓ ' : ''}${c}</span>`).join('')}</div>`, { icon: 'grid' });
  else if (tab === 'verification') body = pnl(lbl.verification, `${lifeBar(['draft', 'submitted', 'under_review', 'verified'], v.verif === 'rejected' ? 'under_review' : v.verif, v.verif === 'rejected' ? 'rejected' : null)}<p class="muted" style="margin:12px 0 0">${L3(['Keputusan verifikasi dilakukan di', 'Verification decisions are made in', 'تُتخذ القرارات في'])} <a href="#/approval">Approval Center</a>.</p>`, { icon: 'shieldc' });
  else if (tab === 'withdrawal') body = pnl('Withdrawal', wd.length ? `<div class="list" style="margin:-14px">${wd.map(w => `<div class="li"><span class="body"><b class="mono">${w.id}</b><span class="sub">${esc(w.basis)} · ${rel(w.ts)}</span></span><b class="tnum">${money(w.amount)}</b>${st(w.state)}</div>`).join('')}</div>` : stateBlock('empty'), { icon: 'arrowur' });
  else if (tab === 'performance') body = `<div class="kpis">${[['Order 30d', fN(v.orders30)], ['GMV 30d', money(v.gmv30)], ['SLA', v.sla + '%'], ['Rating', '★ ' + v.rating]].map(k => `<div class="kpi"><div class="k">${k[0]}</div><div class="v">${k[1]}</div></div>`).join('')}</div>`;
  else body = vendorTab(v, tab);
  return { html: `<div class="page">${crumbs([[t('g_eko'), '/vendor'], ['Vendor', '/vendor'], [v.name, '']])}<div class="phead"><div class="ttl" style="display:flex;gap:14px"><div class="ent"><div class="lg" style="background:${v.color};width:52px;height:52px;border-radius:12px">${initials(v.name)}</div></div><div><h1>${esc(v.name)}</h1><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px"><span class="chip mono">${v.id}</span>${st(v.status)}${st(v.verif)}${v.cats.map(c => `<span class="chip">${c}</span>`).join('')}</div></div></div><div class="actions"><a class="btn" href="#/omni/inbox">${ic('msg')}${t('contact_travel')}</a>${permBtn('vendor.suspend', ic(v.status === 'inactive' ? 'play' : 'ban') + (v.status === 'inactive' ? t('reactivate') : 'Suspend vendor'), `data-act="vendor-status" data-id="${v.id}" data-mut`, v.status === 'inactive' ? 'okb' : 'badb')}</div></div><div class="kpis" style="margin-bottom:12px">${[['Order 30d', fN(v.orders30)], ['GMV 30d', money(v.gmv30)], [L3(['Saldo', 'Balance', 'الرصيد']), money(v.balance)], [L3(['Produk', 'Products', 'منتجات']), fN(v.products)]].map(k => `<div class="kpi"><div class="k">${k[0]}</div><div class="v">${k[1]}</div></div>`).join('')}</div><div class="tabs" role="tablist">${VTABS.map(k => `<a class="tab" role="tab" aria-selected="${k === tab}" href="#/vendor/${v.id}${k === 'identity' ? '' : '/' + k}">${esc(lbl[k])}</a>`).join('')}</div><div style="margin-top:14px">${gate(body)}</div></div>` }; }
route('/vendor/:id', vendorDetail); route('/vendor/:id/:tab', vendorDetail);

/* Affiliate / Mitra / Traveler */
route('/affiliate', () => dirPage({ nav: 'aff_all', desc: L3(['Affiliate adalah actor terpisah yang dapat bekerja dengan banyak Travel melalui link/kode referral. Bukan Vendor, bukan Mitra Travel.', 'Affiliates are a separate actor that can work with many Travels via referral link/code. Not a Vendor, not a Travel Partner.', 'المسوّق جهة منفصلة تعمل مع عدة شركات.']), tableId: 'aff', note: L3(['Aturan: jika sebuah entitas perlu berhubungan dengan lebih dari satu Travel, gunakan role Affiliate — Mitra Travel hanya terikat ke satu Travel.', 'Rule: if an entity needs to work with more than one Travel, use the Affiliate role — a Travel Partner is bound to exactly one Travel.', 'القاعدة: أكثر من شركة ← مسوّق.']), kpis: [{ k: 'Affiliate', v: fN(AFFILIATES.length) }, { k: 'Klik 30d', v: fC(AFFILIATES.reduce((s, a) => s + a.clicks, 0)) }, { k: L3(['Booking/konversi', 'Bookings/conversions', 'تحويلات']), v: fN(AFFILIATES.reduce((s, a) => s + a.conv, 0)) }, { k: L3(['Komisi terutang', 'Commission payable', 'عمولة مستحقة']), v: money(AFFILIATES.reduce((s, a) => s + a.payable, 0)) }],
  cfg: { name: 'Affiliate', search: r => r.name + r.id + r.code, rows: () => AFFILIATES, cols: [{ k: 'name', label: 'Affiliate', render: r => ent(r.name, `<span class="mono">${r.id}</span> · ${r.type}`, r.color) }, { k: 'travels', label: L3(['Travel terhubung', 'Linked Travels', 'الشركات المرتبطة']), render: r => `<div class="lic">${r.travels.map(id => `<a class="chip" href="#/travel/${id}">${esc(travelById(id).name.split(' ').slice(0, 2).join(' '))}</a>`).join('')}</div>`, sv: r => r.travels.length }, { k: 'code', label: 'Link / code', render: r => `<span class="chip mono">${r.code}</span>` }, { k: 'clicks', label: 'Klik', cls: 'r tnum', render: r => fN(r.clicks) }, { k: 'conv', label: 'Konversi', cls: 'r tnum' }, { k: 'gmv', label: 'GMV', cls: 'r tnum', render: r => money(r.gmv) }, { k: 'commission', label: L3(['Komisi', 'Commission', 'العمولة']), cls: 'r tnum', render: r => money(r.commission) }, { k: 'payable', label: 'Payout', cls: 'r tnum', render: r => money(r.payable) }, { k: 'status', label: t('status'), render: r => st(r.status) }] } }));
route('/mitra', () => dirPage({ nav: 'mitra', desc: L3(['Mitra Travel adalah perpanjangan satu Travel (agen/perwakilan). Setiap Mitra hanya terhubung ke SATU Travel.', 'Travel Partners extend a single Travel (agents/representatives). Each Partner is linked to exactly ONE Travel.', 'كل شريك مرتبط بشركة واحدة فقط.']), tableId: 'mitra', cfg: { name: 'Mitra', search: r => r.name + r.id + travelById(r.travel).name, rows: () => MITRA, route: r => '/travel/' + r.travel, cols: [{ k: 'name', label: t('mitra'), render: r => ent(r.name, `<span class="mono">${r.id}</span>`, colorFor(r.name)) }, { k: 'travel', label: L3(['Travel (1:1)', 'Travel (1:1)', 'الشركة (1:1)']), render: r => `<a href="#/travel/${r.travel}">${esc(travelById(r.travel).name)}</a>` }, { k: 'city', label: L3(['Wilayah', 'Area', 'المنطقة']) }, { k: 'jamaah30', label: 'Jamaah 30d', cls: 'r tnum' }, { k: 'status', label: t('status'), render: r => st(r.status) }] } }));
route('/traveler', () => dirPage({ nav: 'traveler', desc: L3(['Jamaah & pelanggan lintas Travel. Data pribadi dibatasi permission; tabel ini hanya menampilkan field operasional.', 'Pilgrims & customers across Travels. Personal data is permission-scoped; this table shows operational fields only.', 'المسافرون عبر الشركات.']), tableId: 'trvl', cfg: { name: 'Traveler', search: r => r.name + r.id + r.phone + r.city, rows: () => TRAVELERS, cols: [{ k: 'name', label: 'Traveler', render: r => ent(r.name, `<span class="mono">${r.id}</span>`, colorFor(r.name)) }, { k: 'phone', label: L3(['Telepon', 'Phone', 'الهاتف']), render: r => `<span class="mono">${esc(r.phone.replace(/\d{4}$/, '••••'))}</span>` }, { k: 'city', label: L3(['Kota', 'City', 'المدينة']) }, { k: 'passport', label: L3(['Paspor', 'Passport', 'الجواز']), render: r => st(r.passport) }, { k: 'trips', label: L3(['Perjalanan', 'Trips', 'الرحلات']), cls: 'r tnum' }, { k: 'bk', label: 'Booking', render: r => { const b = BOOKINGS.find(x => x.traveler === r.id); return b ? `<a class="mono" href="#/booking/${b.id}">${b.id}</a>` : '—'; }, sort: false }] } }));

/* Marketplace packages */
route('/marketplace/packages', () => dirPage({ nav: 'mp_pkg', desc: L3(['Paket Umrah, Haji, Halal Tour & Tour dari tenant Travel. Aksi publikasi mengikuti permission, kepemilikan tenant, dan state.', 'Umrah, Hajj, Halal Tour & Tour packages from Travel tenants. Publication actions follow permission, tenant ownership and state.', 'الباقات من الشركات.']), tableId: 'pkgs', kpis: ['published', 'review', 'draft', 'unpublished'].map(s => ({ k: L3(STATUS[s].slice(2)), v: fN(PACKAGES.filter(p => p.state === s).length) })),
  cfg: { name: 'Paket', search: r => r.name + r.id + travelById(r.travel).name, rows: () => PACKAGES, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...['Umrah', 'Haji', 'Halal Tour', 'Tour'].map(c => ({ v: c, label: c, fn: r => r.cat === c })), { v: 'deal', label: 'SegaDeals', fn: r => typeof SD_OFF !== 'undefined' && SD_OFF.some(o => o.pkg === r.id) }], cols: [{ k: 'name', label: L3(['Paket', 'Package', 'الباقة']), render: r => `<b>${esc(r.name)}</b><div class="muted" style="font-size:11.5px"><span class="mono">${r.id}</span> · <a href="#/travel/${r.travel}">${esc(travelById(r.travel).name)}</a></div>` }, { k: 'cat', label: L3(['Kategori', 'Category', 'الفئة']), render: r => `<span class="chip">${r.cat}</span>${r.segadeal ? ' <span class="chip promo">SegaDeals</span>' : ''}` }, { k: 'price', label: L3(['Harga', 'Price', 'السعر']), cls: 'r tnum', render: r => money(r.price) }, { k: 'dep', label: L3(['Berangkat', 'Departure', 'المغادرة']), render: r => fD(r.dep) }, { k: 'sold', label: 'Seat', cls: 'r tnum', render: r => r.sold + '/' + r.seats }, { k: 'state', label: 'Lifecycle', render: r => st(r.state) }, { k: 'act', label: t('action'), cls: 'r', sort: false, render: pkgActions }] } }));

/* Campaign list */
route('/ads/campaigns', () => { const r = PAGES.adsOverview(); return { html: `<div class="page">${phead({ crumbs: [[t('g_ads'), '/ads'], [t('ads_camp'), '/ads/campaigns']], title: t('ads_camp'), desc: 'Draft → Review → Scheduled → Active → Paused → Completed → Archived', actions: permBtn('ads.create', ic('plus') + t('new_campaign'), 'data-act="wizard" data-mut', 'primary') })}<section class="panel">${defTable('camps', TBL.camps)}</section></div>` }; });

/* Conversations list */
route('/omni/conversations', () => dirPage({ nav: 'om_conv', desc: L3(['Riwayat seluruh percakapan lintas channel dengan relasi ke Traveler, Lead, Booking, Travel, Vendor, Campaign.', 'History of all cross-channel conversations with relations to Traveler, Lead, Booking, Travel, Vendor, Campaign.', 'سجل المحادثات.']), tableId: 'convs', cfg: { name: 'Percakapan', search: r => r.contact + r.id, rows: () => CONVERSATIONS, route: r => '/omni/inbox/' + r.id, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...['open', 'pending', 'resolved', 'closed'].map(s => ({ v: s, label: L3(STATUS[s].slice(2)), fn: r => r.status === s }))], cols: [{ k: 'contact', label: L3(['Kontak', 'Contact', 'جهة الاتصال']), render: r => `<div class="ent">${chanBadge(r.channel)}<div><b>${esc(r.contact)}</b><span class="mono">${r.id}</span></div></div>` }, { k: 'kind', label: L3(['Relasi', 'Relation', 'العلاقة']), render: r => [r.booking && `<span class="chip mono">${r.booking}</span>`, r.campaign && `<span class="chip">${ic('target', 'sm')}Campaign</span>`, r.kind === 'vendor' && '<span class="chip">Vendor</span>', r.kind === 'lead' && !r.traveler && '<span class="chip">Lead</span>'].filter(Boolean).join(' ') || '—', sort: false }, { k: 'assignee', label: 'Agent', render: r => r.assignee ? esc(AGENTS.find(a => a.id === r.assignee).name) : `<span class="st warn">${ic('user')}Unassigned</span>` }, { k: 'status', label: t('status'), render: r => st(r.status) }, { k: 'ts', label: L3(['Terakhir', 'Last', 'الأخيرة']), render: r => rel(r.ts) }] } }));

/* Booking */
route('/booking', () => dirPage({ nav: 'booking', desc: 'Created → Awaiting Payment → Partially Paid → Confirmed → Processing → Ready → Departed / In Service → Completed · exceptions: Cancelled, Refund Requested, Refunded, Failed.', tableId: 'bookings', cfg: bookingTableCfg(() => BOOKINGS), kpis: [{ k: 'Awaiting payment', v: fN(BOOKINGS.filter(b => b.state === 'awaiting_payment').length) }, { k: 'Confirmed → Ready', v: fN(BOOKINGS.filter(b => ['confirmed', 'processing', 'ready'].includes(b.state)).length) }, { k: 'Departed', v: fN(BOOKINGS.filter(b => b.state === 'departed').length) }, { k: L3(['Pengecualian', 'Exceptions', 'استثناءات']), v: fN(BOOKINGS.filter(b => BK_EXC.includes(b.state)).length) }] }));
route('/booking/:id', p => { const b = bookingById(p.id); if (!b) return { html: `<div class="page">${stateBlock('noresult', { title: 'Booking tidak ditemukan', desc: p.id })}</div>` }; const pk = pkgById(b.pkg), tr = travelById(b.travel), trv = TRAVELERS.find(x => x.id === b.traveler); const pays = PAYMENTS.filter(x => x.booking === b.id); const exc = BK_EXC.includes(b.state) ? b.state : null; const cp = b.campaign ? campById(b.campaign) : null; const cv = CONVERSATIONS.find(c => c.booking === b.id);
  const html = `<div class="page">${crumbs([[t('g_book'), '/booking'], ['Booking', '/booking'], [b.id, '']])}<div class="phead"><div class="ttl"><h1 class="mono" style="font-family:var(--font-mono)">${b.id}</h1><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px">${st(b.state)}<span class="chip">${b.pax} pax</span><span class="chip mono">${b.payMode}</span><span class="chip">${esc(b.source)}</span></div></div><div class="actions">${cv ? `<a class="btn" href="#/omni/inbox/${cv.id}">${ic('msg')}${L3(['Percakapan', 'Conversation', 'المحادثة'])}</a>` : ''}${(b.paid && !['refunded', 'refund_requested', 'cancelled'].includes(b.state) ? permBtn('booking.manage', ic('undo') + 'Refund', `data-act="bk-refund" data-id="${b.id}" data-mut`, '') : '')}${(BK_EXC.includes(b.state) || ['departed', 'completed'].includes(b.state) ? '' : permBtn('booking.manage', ic('ban') + L3(['Batalkan', 'Cancel', 'إلغاء']), `data-act="bk-cancel" data-id="${b.id}" data-mut`, 'badb'))}</div></div>
  <section class="panel" style="padding:12px 14px;margin-bottom:14px"><div class="eyebrow" style="margin-bottom:8px">Booking lifecycle</div>${lifeBar(BK_FLOW, exc ? (b.paid ? 'confirmed' : 'awaiting_payment') : b.state, exc)}</section>
  <div class="grid g12"><div class="c7" style="display:grid;gap:14px;align-content:start">${pnl(L3(['Relasi', 'Relations', 'العلاقات']), `<a class="linkcard" href="#/traveler">${ic('user')}<span class="body"><b>${esc(trv.name)}</b><span class="mono">${trv.id}</span></span>${st(trv.passport)}</a><a class="linkcard" href="#/travel/${tr.id}">${ic('building')}<span class="body"><b>${esc(tr.name)}</b><span class="mono">${tr.id}</span></span></a><a class="linkcard" href="#/marketplace/packages">${ic('package')}<span class="body"><b>${esc(pk.name)}</b><span>${money(pk.price)} × ${b.pax} · ${fD(pk.dep)}</span></span>${st(pk.state)}</a>${cp ? `<a class="linkcard" href="#/ads/campaign/${cp.id}">${ic('target')}<span class="body"><b>${esc(cp.name)}</b><span>Attributed campaign</span></span></a>` : ''}<div class="grid g3" style="gap:8px;margin-top:6px">${[['manifest', 'list', 'Manifest', '/booking/manifest'], ['room', 'bed', 'Room List', '/booking/rooms'], ['docs', 'folder', L3(['Dokumen', 'Documents', 'المستندات']), '/booking/documents']].map(x => `<a class="linkcard" href="#${x[3]}" style="margin:0">${ic(x[1])}<span class="body"><b>${x[2]}</b></span></a>`).join('')}</div>`, { icon: 'link' })}${pnl('Payment', `<div class="kpi" style="padding:0;border:0"><div class="v">${money(b.paid, true)} <small class="muted" style="font-size:13px">/ ${money(b.total, true)}</small></div></div><div class="meter ${b.paid >= b.total ? 'ok' : ''}" style="margin:8px 0 12px"><i style="width:${b.paid / b.total * 100}%"></i></div>${pays.map(x => `<a class="linkcard" href="#/finance/payment/${x.id}">${ic('card')}<span class="body"><b class="mono">${x.id}</b><span>${money(x.amount, true)} · ${x.provider} · ${x.channel}</span></span>${st(x.status)}${st(x.recon)}</a>`).join('') || '<span class="muted">—</span>'}`, { icon: 'wallet' })}</div>
  <div class="c5">${pnl(t('timeline'), `<ul class="tl">${[['created', b.created, 'info', 'Checkout · ' + b.source], ...pays.map(x => ['payment ' + x.status + ' · ' + x.id, x.ts, x.status === 'paid' ? 'ok' : x.status === 'pending' ? 'warn' : 'bad', x.provider]), ...(b.paid >= b.total ? [['confirmed', pays[0] ? pays[0].ts + 3e3 : b.created, 'ok', 'Auto · lunas']] : []), ...(exc ? [[exc, b.created + 5 * D, 'bad', 'Admin / Traveler']] : [])].sort((a, c) => c[1] - a[1]).map(h => `<li><span class="dotc ${h[2]}"></span><b class="mono" style="font-weight:550;font-size:12.5px">${esc(h[0])}</b><div class="m">${esc(fDT(h[1]))} · ${esc(h[3])}</div></li>`).join('')}</ul>`, { icon: 'history' })}</div></div></div>`; return { html }; });

/* Finance lists */
route('/finance/transactions', () => (TBL.fintx || PAGES.finance(), dirPage({ nav: 'fin_tx', desc: L3(['Semua payment event dari gateway terintegrasi. Status payment terpisah dari settlement & reconciliation.', 'All payment events from integrated gateways. Payment status is separate from settlement & reconciliation.', 'كل أحداث الدفع.']), tableId: 'tx', cfg: Object.assign({}, TBL.fintx, { rows: () => PAYMENTS, size: 10 }) })));
route('/finance/settlement', () => dirPage({ nav: 'fin_set', desc: 'VIA_SEGALOKA · ledger → settlement batch (T+3) · gross − fee − reserve = net.', tableId: 'stl', cfg: { name: 'Settlement', search: r => r.id + travelById(r.travel).name, rows: () => SETTLEMENTS, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...['scheduled', 'processing', 'settled', 'hold', 'failed'].map(s => ({ v: s, label: L3(STATUS[s].slice(2)), fn: r => r.state === s }))], cols: [{ k: 'id', label: 'Settlement', render: r => `<b class="mono">${r.id}</b>` }, { k: 'travel', label: 'Travel', render: r => `<a href="#/travel/${r.travel}/finance">${esc(travelById(r.travel).name)}</a>` }, { k: 'gross', label: 'Gross', cls: 'r tnum', render: r => money(r.gross, true) }, { k: 'fee', label: 'Fee', cls: 'r tnum', render: r => money(r.fee, true) }, { k: 'reserve', label: 'Reserve', cls: 'r tnum', render: r => money(r.reserve, true) }, { k: 'net', label: 'Net', cls: 'r tnum', render: r => `<b>${money(r.net, true)}</b>` }, { k: 'sched', label: L3(['Jadwal', 'Scheduled', 'الموعد']), render: r => fD(r.sched) }, { k: 'state', label: t('status'), render: r => st(r.state) }] } }));
route('/finance/withdrawal', () => dirPage({ nav: 'fin_wd', desc: L3(['Penarikan saldo Vendor (mengikuti transaksi/pembelian), Travel (VIA_SEGALOKA), dan Affiliate (komisi tervalidasi). Approval & limit diatur di Payment Configuration.', 'Balance withdrawals for Vendors (per transaction/purchase), Travels (VIA_SEGALOKA) and Affiliates (validated commission). Approval & limits set in Payment Configuration.', 'سحب الأرصدة.']), tableId: 'wd', cfg: { name: 'Withdrawal', search: r => r.id + r.party, rows: () => WITHDRAWALS, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, ...['Vendor', 'Travel', 'Affiliate'].map(s => ({ v: s, label: s, fn: r => r.partyType === s })), { v: 'pending', label: 'Pending', fn: r => r.state === 'pending' }], cols: [{ k: 'id', label: 'ID', render: r => `<b class="mono">${r.id}</b><div class="muted" style="font-size:11.5px">${rel(r.ts)}</div>` }, { k: 'party', label: L3(['Penerima', 'Recipient', 'المستفيد']), render: r => `${esc(r.party)} <span class="chip" style="height:18px">${r.partyType}</span>` }, { k: 'basis', label: 'Basis' }, { k: 'amount', label: 'Amount', cls: 'r tnum', render: r => money(r.amount, true) }, { k: 'state', label: t('status'), render: r => st(r.state) }, { k: 'act', label: t('action'), cls: 'r', sort: false, render: r => r.state === 'pending' ? permBtn('finance.withdrawal', t('approve'), `data-act="wd-approve" data-id="${r.id}" data-mut`, 'sm primary') : '—' }] } }));
route('/finance/refund', () => dirPage({ nav: 'fin_ref', desc: L3(['Refund memerlukan approval dan tercatat di audit. Status refund terpisah dari status booking & payment.', 'Refunds require approval and are audited. Refund status is separate from booking & payment status.', 'الاسترداد يتطلب موافقة.']), tableId: 'ref', cfg: { name: 'Refund', search: r => r.id + r.booking, rows: () => REFUNDS, cols: [{ k: 'id', label: 'Refund', render: r => `<b class="mono">${r.id}</b>` }, { k: 'booking', label: 'Booking', render: r => `<a class="mono" href="#/booking/${r.booking}">${r.booking}</a>` }, { k: 'travel', label: 'Travel', render: r => esc(travelById(r.travel).name) }, { k: 'reason', label: t('reason') }, { k: 'amount', label: 'Amount', cls: 'r tnum', render: r => money(r.amount, true) }, { k: 'state', label: t('status'), render: r => st(r.state) }] } }));

/* Audit log */
route('/compliance/audit', () => dirPage({ nav: 'audit', desc: L3(['Jejak seluruh aksi administratif & sistem: actor, action, resource, timestamp, before/after, source, result. Read-only dan tidak dapat dihapus.', 'Trail of all administrative & system actions: actor, action, resource, timestamp, before/after, source, result. Read-only and immutable.', 'سجل غير قابل للتعديل.']), tableId: 'audit', cfg: { name: 'Audit', exportable: true, search: r => r.actor + r.action + r.resource + (r.reason || ''), rows: () => AUDIT, route: null, size: 15, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'ok', label: 'Success', fn: r => r.result === 'success' }, { v: 'fail', label: 'Failed / Warning', fn: r => r.result !== 'success' }, { v: 'sys', label: 'System', fn: r => r.actor === 'System' }], cols: [{ k: 'ts', label: 'Timestamp', render: r => `<span class="tnum">${esc(fDT(r.ts))}</span>` }, { k: 'actor', label: 'Actor' }, { k: 'action', label: 'Action', render: r => `<span class="mono">${esc(r.action)}</span>` }, { k: 'resource', label: 'Resource', render: r => `<span class="mono" style="font-size:12px">${esc(r.resource)}</span>` }, { k: 'ba', label: 'Before → After', sort: false, render: r => r.before || r.after ? `<button class="btn sm ghost" data-act="audit-diff" data-id="${r.id}">${ic('eye', 'sm')}diff</button>` : '<span class="muted">—</span>' }, { k: 'source', label: 'Source', render: r => `<span style="font-size:12px">${esc(r.source)}</span>` }, { k: 'result', label: 'Result', render: r => st(r.result === 'failed' ? 'failed' : r.result === 'warning' ? 'unmatched' : 'success') }] } }));

/* Brand & Appearance (configurable identity) */
route('/system/brand', () => { const html = `<div class="page">${phead({ crumbs: [[t('g_sys'), '/system/config'], [t('sys_brand'), '/system/brand']], title: t('sys_brand'), desc: L3(['Identitas perusahaan tidak di-hardcode. Nilai di bawah dibaca shell (logo, nama, warna, preset tipografi) dan dapat diubah tanpa deploy.', 'Company identity is not hard-coded. The shell reads these values (logo, name, color, type preset) and they can change without a deploy.', 'الهوية قابلة للتهيئة.']) })}
  <div class="grid g12"><div class="c7">${pnl(L3(['Identitas', 'Identity', 'الهوية']), `<div class="grid g2" style="gap:10px"><div class="field"><label for="br-name">${L3(['Nama publik', 'Public name', 'الاسم العام'])}</label><input type="text" id="br-name" value="${esc(BRAND.name)}"></div><div class="field"><label for="br-mark">${L3(['Logo mark (teks/inisial)', 'Logo mark (text/initial)', 'الشعار'])}</label><input type="text" id="br-mark" maxlength="2" value="${esc(BRAND.mark)}"></div></div><div class="field"><label for="br-legal">${L3(['Nama badan hukum', 'Legal entity', 'الكيان القانوني'])}</label><input type="text" id="br-legal" value="${esc(BRAND.legal)}"></div><div class="field"><label for="br-color">${L3(['Warna brand', 'Brand color', 'لون العلامة'])}</label><div style="display:flex;gap:8px;align-items:center"><input type="color" id="br-color" value="${BRAND.color}" style="width:48px;height:36px;border:1px solid var(--line-strong);border-radius:8px;background:var(--surface)"><span class="mono">${BRAND.color}</span><span class="hint">${L3(['Dipakai untuk brandmark; warna status semantik tetap terpisah.', 'Used for the brand mark; semantic status colors stay separate.', 'ألوان الحالة منفصلة.'])}</span></div></div><div class="field"><label for="br-type">Typography preset</label><select id="br-type"><option>Plex / Bricolage</option><option>Plex only</option><option>System UI</option></select></div><div class="field"><label>Assets</label><div style="display:flex;gap:8px;flex-wrap:wrap">${['Logo (SVG)', 'Favicon', 'Email header', 'Invoice header'].map(a => `<span class="docrow" style="margin:0;padding:6px 10px">${ic('upload', 'sm')}<span style="font-size:12.5px">${a}</span></span>`).join('')}</div></div>`, { icon: 'palette', foot: `${permBtn('system.brand', ic('check') + t('save'), 'data-act="brand-save" data-mut', 'primary')}<span class="muted">${L3(['Perubahan tercatat di audit (before/after).', 'Changes are audited (before/after).', 'تُسجَّل التغييرات.'])}</span>` })}</div>
  <div class="c5">${pnl('Preview', `<div class="brandprev"><div style="background:var(--side-bg);border-bottom:1px solid var(--side-line);padding:14px;display:flex;gap:10px;align-items:center"><div class="brandmark" id="bp-mark" style="background:${BRAND.color}">${esc(BRAND.mark)}</div><div><div class="brandname" id="bp-name">${esc(BRAND.name)}</div><div class="brandsub">${esc(t('control_center'))}</div></div></div><div style="padding:14px;font-size:12.5px" class="muted" id="bp-legal">${esc(BRAND.legal)}</div></div>`, { icon: 'eye' })}</div></div></div>`; return { html, mount() { ['br-name', 'br-mark', 'br-color', 'br-legal'].forEach(id => document.getElementById(id).addEventListener('input', () => { const g = i => document.getElementById(i).value; document.getElementById('bp-name').textContent = g('br-name'); document.getElementById('bp-mark').textContent = g('br-mark'); document.getElementById('bp-mark').style.background = g('br-color'); document.getElementById('bp-legal').textContent = g('br-legal'); })); } }; });

/* =============================== BLUEPRINTS (placeholder pages) =============================== */
const BP = {
 travel_web: { s: ['Daftar website per tenant', 'Domain & SSL', 'Template & konten', 'Entitlement dari subscription', 'Publikasi paket ke website'], e: ['Website{id, travelId, domain, status, template, sslState}', 'Entitlement{plan, websiteEnabled}'], l: ['draft', 'published', 'unpublished'], r: ['travel_all', 'sub', 'mp_pkg'] },
 vendor_cat: { s: ['Taxonomy kategori vendor', 'Atribut per kategori (hotel: bintang, jarak ke Haram)', 'Mapping ke kategori Marketplace'], e: ['VendorCategory{id, name, attributes[]}'], l: ['draft', 'active', 'archived'], r: ['vendor_all', 'mp_cat'] },
 vendor_prod: { s: ['Katalog produk & layanan vendor', 'Harga & allotment', 'Status moderasi'], e: ['VendorProduct{id, vendorId, category, price, allotment, state}'], l: ['draft', 'review', 'published', 'unpublished', 'archived'], r: ['vendor_all', 'mp_vprod', 'mp_mod'] },
 aff_ref: { s: ['Link & kode referral', 'Klik & sumber', 'Travel yang dipromosikan'], e: ['ReferralLink{id, affiliateId, travelId?, code, url}', 'ReferralClick{ts, source, device}'], l: ['active', 'paused', 'archived'], r: ['aff_all', 'booking', 'an_conv'] },
 aff_com: { s: ['Aturan komisi per Travel/paket', 'Komisi tervalidasi vs pending', 'Payout ke Withdrawal'], e: ['CommissionRule{scope, rate, cap}', 'Commission{bookingId, amount, state}'], l: ['pending', 'approved', 'disbursed', 'rejected'], r: ['aff_all', 'fin_wd', 'fin_fee'] },
 aff_perf: { s: ['Leaderboard affiliate', 'Konversi per Travel', 'Kualitas lead'], e: ['AffiliateStats{clicks, leads, bookings, gmv}'], l: [], r: ['aff_all', 'an_growth'] },
 mp_ov: { s: ['GMV & booking Marketplace', 'Pencarian & konversi', 'Paket terlaris', 'Antrian moderasi', 'SegaDeals aktif'], e: ['MarketplaceMetrics'], l: [], r: ['mp_pkg', 'mp_mod', 'an_mp'] },
 mp_vprod: { s: ['Produk vendor yang tampil di Marketplace', 'Moderasi', 'Harga & ketersediaan'], e: ['Listing{id, ownerType: vendor, productId, state}'], l: ['draft', 'review', 'published', 'unpublished', 'archived'], r: ['vendor_prod', 'mp_mod'] },
 segadeals: { s: ['Pengguna mengajukan permintaan (jenis, tujuan, bulan, pax, budget)', 'Travel berizin mengirim penawaran', 'Pengguna memilih penawaran → booking + DP', 'Moderasi permintaan & penawaran'], e: ['SegaDealsRequest{id, travelerId, type, dest, month, pax, budget, state}', 'SegaDealsOffer{id, requestId, travelId, packageId?, price, validUntil, state}'], l: ['open', 'offered', 'accepted', 'expired', 'cancelled'], r: ['mp_pkg', 'booking', 'travel_all'] },
 mp_cat: { s: ['Umrah', 'Haji', 'Halal Tour', 'Tour', 'Tiket', 'Hotel', 'Land arrangement', 'Produk/jasa vendor lain'], e: ['Category{id, parent, slug, attributes}'], l: ['active', 'archived'], r: ['mp_pkg', 'vendor_cat'] },
 mp_mod: { s: ['Antrian review paket & produk', 'Checklist kebijakan (klaim, harga, dokumen izin)', 'Riwayat keputusan'], e: ['ModerationCase{listingId, checks[], decision}'], l: ['review', 'published', 'needs_revision', 'rejected'], r: ['mp_pkg', 'approval', 'legal'] },
 om_ov: { s: ['Volume per channel', 'Open / pending / unassigned', 'First response & resolution time', 'Beban agent', 'SLA breach'], e: ['OmniMetrics'], l: ['open', 'pending', 'resolved', 'closed'], r: ['om_inbox', 'om_sla', 'om_ana'] },
 om_wa: { s: ['Nomor & BSP', 'Quality rating', 'Template approval (Meta)', 'Jendela 24 jam', 'Routing default'], e: ['Channel{type: whatsapp, number, bsp, quality}'], l: ['pending', 'active', 'suspended'], r: ['om_inbox', 'om_tpl', 'om_route'] },
 om_ig: { s: ['Akun terhubung', 'DM & komentar', 'Routing'], e: ['Channel{type: instagram, accountId}'], l: ['pending', 'active', 'inactive'], r: ['om_inbox'] }, om_fb: { s: ['Page terhubung', 'Messenger', 'Routing'], e: ['Channel{type: facebook, pageId}'], l: ['pending', 'active', 'inactive'], r: ['om_inbox'] }, om_email: { s: ['Mailbox & domain (SPF/DKIM)', 'Threading', 'Routing'], e: ['Channel{type: email, address}'], l: ['pending', 'active', 'inactive'], r: ['om_inbox'] }, om_web: { s: ['Widget per website Travel', 'Pra-chat form', 'Routing'], e: ['Channel{type: webchat, siteId}'], l: ['draft', 'active', 'inactive'], r: ['om_inbox', 'website'] },
 om_contact: { s: ['Kontak & lead', 'Segmen audience', 'Consent & opt-out', 'Merge duplikat', 'Sinkron ke Ads audience'], e: ['Contact{id, channels[], travelerId?, consent}', 'Segment{rules}'], l: [], r: ['traveler', 'ads_set', 'om_bc'] },
 om_tpl: { s: ['Template per channel', 'Variabel', 'Status approval WA', 'Bahasa (ID/EN/AR)'], e: ['Template{id, channel, lang, body, state}'], l: ['draft', 'review', 'approved', 'rejected'], r: ['om_bc', 'om_auto'] },
 om_bc: { s: ['Broadcast terjadwal', 'Segmen penerima', 'Template', 'Delivery & read rate'], e: ['Broadcast{id, segmentId, templateId, schedule, stats}'], l: ['draft', 'scheduled', 'processing', 'completed', 'failed'], r: ['om_contact', 'om_tpl'] },
 om_auto: { s: ['Trigger (pesan masuk, booking event, payment event)', 'Kondisi', 'Aksi (balas, assign, tag, notifikasi)'], e: ['Automation{trigger, conditions[], actions[]}'], l: ['draft', 'active', 'paused'], r: ['om_route', 'booking', 'fin_tx'] },
 om_route: { s: ['Antrian (Umrah, Haji, Finance CS)', 'Aturan routing per channel/keyword/campaign', 'Round-robin / load-based', 'Jam kerja'], e: ['Queue{id, agents[]}', 'RoutingRule{match, queue}'], l: ['active', 'inactive'], r: ['om_inbox', 'users'] },
 om_sla: { s: ['Target first response & resolution', 'Breach & eskalasi', 'Per channel/antrian'], e: ['SlaPolicy{firstResponse, resolution}'], l: [], r: ['om_inbox', 'om_ana'] },
 om_ana: { s: ['Volume & tren', 'FRT / ART', 'CSAT', 'Konversi lead → booking dari percakapan'], e: ['OmniAnalytics'], l: [], r: ['an_omni', 'an_conv'] },
 ads_ads: { s: ['Daftar iklan per ad set', 'Status review platform', 'Preview'], e: ['Ad{id, adSetId, creativeId, state}'], l: ['draft', 'review', 'active', 'paused', 'archived'], r: ['ads_camp', 'ads_cre'] },
 ads_set: { s: ['Ad set & targeting', 'Audience dari Contacts', 'Lookalike'], e: ['AdSet{id, campaignId, audience, placement, budgetShare}'], l: ['draft', 'active', 'paused'], r: ['ads_camp', 'om_contact'] },
 ads_cre: { s: ['Library creative', 'Varian & A/B', 'Kepatuhan klaim'], e: ['Creative{id, format, assets[], claims[]}'], l: ['draft', 'review', 'approved', 'rejected'], r: ['ads_ads', 'mp_mod'] },
 ads_plc: { s: ['Website Segaloka: banner beranda, sponsored pencarian, kategori, rekomendasi', 'Aplikasi Segaloka: banner, sponsored pencarian, rekomendasi, notifikasi in-app', 'Tidak ada platform iklan eksternal'], e: ['Placement{surface: web|app, slot, state}'], l: ['active', 'inactive'], r: ['sys_int', 'ads_camp'] },
 ads_bud: { s: ['Saldo iklan tenant', 'Top-up', 'Pacing & cap', 'Billing iklan'], e: ['AdBudget{tenantId, balance, spend}'], l: [], r: ['fin_tx', 'ads_camp'] },
 ads_vou: { s: ['Voucher & kode promo', 'Kuota & masa berlaku', 'Penggunaan per booking'], e: ['Voucher{code, rule, quota, window}'], l: ['draft', 'active', 'expired', 'archived'], r: ['segadeals', 'booking', 'ads_camp'] },
 ads_trk: { s: ['Event first-party web & aplikasi Segaloka', 'Server-side events (booking, payment, SegaDeals)', 'Kesehatan event'], e: ['TrackingSource{id, events[], health}'], l: ['active', 'degraded', 'inactive'], r: ['sys_int', 'ads_conv'] },
 ads_conv: { s: ['Definisi konversi (lead, booking, paid)', 'Nilai konversi', 'Deduplikasi'], e: ['ConversionEvent{name, value, source}'], l: [], r: ['ads_trk', 'ads_attr'] },
 ads_attr: { s: ['Model atribusi', 'Jendela klik/view', 'Path to conversion'], e: ['AttributionModel{type, window}'], l: [], r: ['an_conv', 'ads_camp'] },
 ads_perf: { s: ['Performa harian per campaign/ad set/creative', 'Breakdown channel', 'Anomali'], e: ['AdsPerformance'], l: [], r: ['an_ads', 'an_camp'] },
 manifest: { s: ['Manifest per keberangkatan', 'Validasi paspor & visa', 'Export maskapai/muassasah'], e: ['Manifest{departureId, travelers[], state}'], l: ['draft', 'review', 'verified', 'ready'], r: ['booking', 'opsdoc', 'roomlist'] },
 roomlist: { s: ['Rooming per hotel (quad/triple/double)', 'Mahram & keluarga', 'Sinkron ke vendor hotel'], e: ['RoomList{hotelId, rooms[]}'], l: ['draft', 'confirmed'], r: ['manifest', 'vendor_all'] },
 pkginfo: { s: ['Itinerary', 'Hotel & maskapai', 'Manasik & perlengkapan', 'Kontak tour leader'], e: ['PackageInfo{packageId, itinerary[], hotels[]}'], l: [], r: ['mp_pkg', 'booking'] },
 opsdoc: { s: ['Paspor, visa, vaksin', 'Tiket & voucher hotel', 'Dokumen per jamaah & per grup'], e: ['OpsDocument{bookingId, type, state}'], l: ['pending', 'submitted', 'verified', 'rejected', 'expired'], r: ['booking', 'manifest'] },
 fin_pg: { s: ['Provider (Midtrans, Xendit, DOKU)', 'Channel (VA, QRIS, kartu)', 'Health & failover', 'Webhook log'], e: ['Provider{id, channels[], health}', 'WebhookEvent{id, type, signature, processedAt}'], l: ['healthy', 'degraded', 'down'], r: ['fin_tx', 'sys_pay'] },
 fin_dep: { s: ['Deposit jaminan per Travel', 'Top-up & potongan', 'Riwayat'], e: ['Deposit{travelId, balance, movements[]}'], l: ['active', 'hold'], r: ['travel_all', 'fin_set'] },
 fin_rec: { s: ['Batch rekonsiliasi harian', 'Match bank vs ledger vs gateway', 'Unmatched & mismatch', 'Resolusi manual (audit)'], e: ['ReconBatch{id, date, matched, unmatched}', 'ReconItem{paymentId, bankRef, diff}'], l: ['pending', 'reconciled', 'unmatched', 'mismatch'], r: ['fin_tx', 'fin_set', 'audit'] },
 fin_fee: { s: ['Fee platform per plan/tenant', 'MDR gateway', 'Komisi affiliate', 'Simulasi'], e: ['FeeRule{scope, type, rate}'], l: ['draft', 'active', 'archived'], r: ['sys_pay', 'aff_com'] },
 plan: { s: ['Starter / Growth / Enterprise', 'Harga & siklus', 'Entitlement (website, cabang, CRM seat, omnichannel)'], e: ['Plan{id, price, entitlements}'], l: ['draft', 'active', 'archived'], r: ['sub', 'addon'] },
 addon: { s: ['Cabang tambahan', 'Seat CRM', 'Nomor WhatsApp', 'Kredit broadcast'], e: ['Addon{id, unitPrice, entitlement}'], l: ['active', 'archived'], r: ['sub', 'travel_branch'] },
 website: { s: ['Semua website Travel', 'Template', 'Domain'], e: ['Website'], l: ['draft', 'published', 'unpublished'], r: ['travel_web', 'sub'] },
 crm: { s: ['Pipeline lead per Travel', 'Aktivitas sales', 'Integrasi Omnichannel'], e: ['Lead{id, stage, ownerId}'], l: ['open', 'in_progress', 'completed', 'closed'], r: ['om_contact', 'booking'] },
 users: { s: ['User platform & tenant', 'Undangan', '2FA & sesi', 'Status'], e: ['User{id, scope, roles[], mfa}'], l: ['pending', 'active', 'suspended'], r: ['roles', 'audit', 'security'] },
 roles: { s: ['Role sebagai kumpulan permission granular', 'Scope (platform / tenant / cabang)', 'Diff perubahan + approval'], e: ['Permission{key}', 'Role{id, permissions[], scope}'], l: [], r: ['users', 'audit'] },
 notif: { s: ['Notifikasi terkirim', 'Channel (in-app, email, WA)', 'Preferensi user'], e: ['Notification{userId, type, resourceRef, readAt}'], l: [], r: ['sys_ncfg'] },
 ai: { s: ['Asisten lintas domain', 'Ringkasan approval', 'Saran balasan Omnichannel', 'Insight Ads', 'Guardrail: tidak menggantikan authorization, permission, policy, validation, business rules'], e: ['AiAction{suggestion, requiresHumanAction: true}'], l: [], r: ['approval', 'om_inbox', 'ads_ov'] },
 security: { s: ['Login & sesi', 'Percobaan gagal & blokir IP', '2FA coverage', 'API key'], e: ['SecurityEvent{type, actor, ip, result}'], l: ['open', 'resolved'], r: ['audit', 'users', 'risk'] },
 risk: { s: ['Rule & skor risiko', 'Kasus fraud (refund, chargeback, akun)', 'Hold otomatis'], e: ['RiskCase{subject, score, signals[], state}'], l: ['open', 'in_progress', 'resolved', 'closed'], r: ['approval', 'fin_wd', 'fin_ref'] },
 an_exec: { s: ['GMV, revenue, take rate', 'Pertumbuhan tenant', 'Cohort traveler', 'Kontribusi Ads ke revenue'], e: ['ExecMetrics'], l: [], r: ['an_growth', 'an_fin', 'an_ads'] },
 an_mp: { s: ['Search → view → booking', 'Kategori & harga', 'Performa SegaDeals'], e: [], l: [], r: ['mp_ov'] }, an_travel: { s: ['Ranking tenant', 'Kesehatan legal & subscription', 'Kapasitas seat'], e: [], l: [], r: ['travel_all'] }, an_vendor: { s: ['Order & SLA vendor', 'Kualitas layanan'], e: [], l: [], r: ['vendor_all'] }, an_fin: { s: ['Cashflow ledger', 'Settlement & withdrawal aging', 'Rekonsiliasi'], e: [], l: [], r: ['fin_ov'] }, an_omni: { s: ['Gabungan data Omnichannel + Booking'], e: [], l: [], r: ['om_ana'] }, an_ads: { s: ['Ads + Booking + Revenue terkonsolidasi'], e: [], l: [], r: ['ads_perf'] }, an_camp: { s: ['Perbandingan campaign lintas tenant'], e: [], l: [], r: ['ads_camp'] }, an_conv: { s: ['Multi-touch path', 'Campaign → Lead → Conversation → Booking → Payment → Revenue'], e: [], l: [], r: ['ads_attr', 'om_ana'] }, an_growth: { s: ['Akuisisi tenant & traveler', 'Retensi', 'Referral & affiliate'], e: [], l: [], r: ['aff_perf'] },
 sys_cfg: { s: ['Parameter global', 'Kebijakan bisnis (refund, reserve, SLA)', 'Riwayat perubahan'], e: ['ConfigEntry{key, value, version}'], l: [], r: ['audit'] }, sys_lang: { s: ['Bahasa: ID, EN, AR (RTL)', 'Kamus terjemahan', 'Format tanggal (Masehi & Hijriah)'], e: ['Locale{code, dir, dictionary}'], l: [], r: [] }, sys_cur: { s: ['Mata uang dasar IDR', 'Tampilan SAR/USD', 'Kurs & sumber'], e: ['Currency{code, rateSource}'], l: [], r: ['sys_pay'] },
 sys_pay: { s: ['Provider & routing per channel', 'Fee', 'Settlement cycle', 'Withdrawal limit', 'Reserve & hold', 'Approval threshold', 'Risk controls'], e: ['PaymentRouting{channel, primary, failover}', 'Limit{scope, amount}'], l: [], r: ['fin_pg', 'fin_set', 'fin_wd', 'audit'] },
 sys_ncfg: { s: ['Event → channel', 'Template notifikasi', 'Eskalasi'], e: ['NotificationRule{event, channels[]}'], l: [], r: ['notif'] }, sys_flag: { s: ['Flag per tenant/role', 'Rollout bertahap'], e: ['Flag{key, targeting}'], l: ['draft', 'active', 'archived'], r: [] }, sys_int: { s: ['Gateway pembayaran', 'Ad server Segaloka (web + app)', 'WhatsApp BSP', 'API key & webhook'], e: ['Integration{type, state}'], l: ['pending', 'active', 'degraded', 'inactive'], r: ['fin_pg', 'ads_plc', 'om_wa'] }, sys_health: { s: ['Uptime per service', 'Latency', 'Queue & DLQ', 'Incident'], e: ['ServiceHealth'], l: ['healthy', 'degraded', 'down'], r: ['overview'] }
};
PAGES.placeholder = id => {
  const n = NAVIDX[id]; const b = BP[id] || { s: [], e: [], l: [], r: [] }; const tr = navTrail(id);
  const html = `<div class="page">${phead({ crumbs: tr.map(x => [x[0], x[1] || S.route]), title: t(id), desc: t('ph_desc'), actions: `<span class="st neu">${ic('grid')}${esc(t('ph_status'))}</span><a class="btn" href="#/ia">${ic('grid')}${t('iamap')}</a>` })}
  <div class="grid g12"><div class="c8" style="display:grid;gap:14px;align-content:start">
   ${pnl(t('planned'), b.s.length ? `<div style="display:grid;gap:8px">${b.s.map(s => `<div class="bp-sec">${ic('panel', 'sm')}<span style="flex:1">${esc(s)}</span><span class="chip">${L3(['direncanakan', 'planned', 'مخطط'])}</span></div>`).join('')}</div>` : '<span class="muted">—</span>', { icon: 'list' })}
   <section class="bp" aria-label="skeleton preview"><div class="panel-h" style="border-bottom:1px dashed var(--line-strong)"><h3>${ic('eye', 'sm')}${L3(['Pratinjau layout (skeleton)', 'Layout preview (skeleton)', 'معاينة التخطيط'])}</h3></div><div style="padding:14px;display:grid;gap:10px"><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px">${[1, 2, 3, 4].map(() => `<div style="border:1px dashed var(--line-strong);border-radius:8px;padding:10px;display:grid;gap:6px"><div class="skel" style="width:50%;height:9px;animation:none"></div><div class="skel" style="width:70%;height:16px;animation:none"></div></div>`).join('')}</div><div style="border:1px dashed var(--line-strong);border-radius:8px;padding:0">${skel(4).replace(/class="skel"/g, 'class="skel" style="animation:none"')}</div></div></section>
  </div><div class="c4" style="display:grid;gap:14px;align-content:start">
   ${b.l.length ? pnl(t('lifecycle'), `<div style="display:flex;gap:6px;flex-wrap:wrap">${b.l.map(s => STATUS[s] ? st(s) : `<span class="chip">${esc(s)}</span>`).join(`<span class="muted">→</span>`)}</div>`, { icon: 'refresh' }) : ''}
   ${pnl(t('entities'), b.e.length ? b.e.map(e => `<div class="mono" style="font-size:11.5px;padding:6px 8px;background:var(--surface-2);border-radius:6px;margin-bottom:6px;overflow-wrap:anywhere">${esc(e)}</div>`).join('') : '<span class="muted">—</span>', { icon: 'layers' })}
   ${pnl(t('relations'), b.r.length ? `<div style="display:flex;gap:6px;flex-wrap:wrap">${b.r.filter(r => NAVIDX[r]).map(r => `<a class="chip" href="#${NAVIDX[r].r || (NAVIDX[r].kids || [{}])[0].r}">${ic(NAVIDX[r].i, 'sm')}${esc(t(r))}</a>`).join('')}</div>` : '<span class="muted">—</span>', { icon: 'link' })}
   ${pnl(t('perms'), `<span class="chip mono">${esc(n.p)}</span> <span class="chip mono">${esc(n.p.split('.')[0])}.manage</span>`, { icon: 'lock' })}
   ${pnl(t('states_req'), `<div style="display:flex;gap:6px;flex-wrap:wrap">${['Loading', 'Empty', 'Error', 'No permission', 'No result', 'Offline', 'Success', 'Warning', 'Destructive confirm'].map(s => `<span class="chip">${s}</span>`).join('')}</div>`, { icon: 'activity' })}
  </div></div></div>`;
  return { html };
};

/* =============================== IA MAP =============================== */
route('/ia', () => { const lv = { hi: 0, md: 0, ph: 0 }; Object.values(NAVIDX).forEach(n => { if (n.lvl) lv[n.lvl]++; }); lv.hi += 2;
  const html = `<div class="page">${phead({ crumbs: [[BRAND.name, '/overview'], [t('iamap'), '/ia']], title: t('iamap'), desc: L3(['Seluruh information architecture Control Center: Group → Module → Submodule. Tanda menunjukkan kedalaman implementasi iterasi ini.', 'The full Control Center information architecture: Group → Module → Submodule. Markers show implementation depth in this iteration.', 'البنية الكاملة للمعلومات.']) })}
  <div class="kpis" style="margin-bottom:14px">${[[t('lvl_hi'), lv.hi, 'hi'], [t('lvl_md'), lv.md, 'md'], [t('lvl_ph'), lv.ph, 'ph'], ['Route', Object.values(NAVIDX).filter(n => n.r).length + 6, null]].map(k => `<div class="kpi"><div class="k">${k[2] ? `<span class="lvl ${k[2]}"></span>` : ''}${esc(k[0])}</div><div class="v">${k[1]}</div></div>`).join('')}</div>
  <div class="panel" style="padding:10px 14px;margin-bottom:14px;font-size:12.5px;display:flex;gap:16px;flex-wrap:wrap"><span><span class="lvl hi" style="display:inline-block"></span> ${t('lvl_hi')}: Overview, Approval Center, Travel Directory, Travel Detail (/travel/[travelId]), Omnichannel Inbox, Ads Overview, Campaign Detail (/ads/campaign/[id]), Finance Overview</span><span><span class="lvl md" style="display:inline-block"></span> ${t('lvl_md')}</span><span><span class="lvl ph" style="display:inline-block"></span> ${t('lvl_ph')}</span></div>
  <div class="iamap">${NAV.map(g => `<div class="grp"><h4>${esc(t(g.g))}</h4><ul>${g.items.map(m => `<li>${m.kids ? `<a href="#${m.kids[0].r}"><span class="lvl ${m.kids.some(k => k.lvl === 'hi') ? 'hi' : m.kids.some(k => k.lvl === 'md') ? 'md' : 'ph'}"></span>${ic(m.i, 'sm')}<b>${esc(t(m.id))}</b></a><ul>${m.kids.map(k => `<li><a href="#${k.r}"><span class="lvl ${k.lvl}"></span>${esc(t(k.id))}<span class="muted mono" style="margin-inline-start:auto;font-size:10.5px">${k.r}</span></a></li>`).join('')}</ul>` : `<a href="#${m.r}"><span class="lvl ${m.lvl}"></span>${ic(m.i, 'sm')}${esc(t(m.id))}<span class="muted mono" style="margin-inline-start:auto;font-size:10.5px">${m.r}</span></a>`}</li>`).join('')}</ul></div>`).join('')}
  <div class="grp"><h4>${L3(['Route dinamis', 'Dynamic routes', 'مسارات ديناميكية'])}</h4><ul>${[['/travel/[travelId]', '/travel/' + ((TRAVELS[0]||{}).id||'')], ['/travel/[travelId]/[tab]', '/travel/' + TRAVELS[1].id + '/legal'], ['/vendor/[vendorId]', '/vendor/' + ((VENDORS[0]||{}).id||"")], ['/booking/[bookingId]', '/booking/' + ((BOOKINGS[0]||{}).id||"")], ['/finance/payment/[paymentId]', '/finance/payment/' + ((PAYMENTS[0]||{}).id||"")], ['/ads/campaign/[campaignId]', '/ads/campaign/' + ((CAMPAIGNS[0]||{}).id||"")], ['/omni/inbox/[conversationId]', '/omni/inbox/' + ((CONVERSATIONS[0]||{}).id||"")], ['/approval/[approvalId]', '/approval/' + ((APPROVALS[0]||{}).id||"")]].map(r => `<li><a href="#${r[1]}"><span class="lvl hi"></span><span class="mono" style="font-size:11.5px">${r[0]}</span></a></li>`).join('')}</ul></div></div>
  <div class="section-title"><h2>${L3(['Yang masih perlu ditambahkan', 'Still to be added', 'ما يجب إضافته'])}</h2><span class="rule"></span></div>
  <div class="grid g3">${pnl(L3(['Sudah berfungsi (client-side)', 'Working now (client-side)', 'يعمل الآن']), `<ul style="margin:0;padding-inline-start:18px;display:grid;gap:4px;font-size:13px"><li>Semua ${Object.values(NAVIDX).filter(n => n.r).length} modul: list, filter, sort, detail, create/edit</li><li>Lifecycle & state transition dengan konfirmasi + alasan</li><li>Audit Log untuk setiap aksi sensitif</li><li>Permission matrix yang mengubah menu & aksi</li><li>Export CSV, realtime simulasi, ID/EN/AR + RTL</li></ul>`, { icon: 'check' })}${pnl(L3(['Butuh keputusan bisnis', 'Needs business decisions', 'قرارات مطلوبة']), `<ul style="margin:0;padding-inline-start:18px;display:grid;gap:4px;font-size:13px"><li>Aturan komisi Affiliate lintas Travel</li><li>Kebijakan refund per kategori paket</li><li>Threshold approval withdrawal</li><li>Model atribusi default Ads</li><li>Grace period (hari) per plan</li></ul>`, { icon: 'info' })}${pnl(L3(['Belum: integrasi backend', 'Not yet: backend integration', 'لم يتم: الخادم']), `<ul style="margin:0;padding-inline-start:18px;display:grid;gap:4px;font-size:13px"><li>${SB.on ? 'Data tersimpan di Supabase (Postgres) ✓' : 'Mode lokal: data reset saat reload'}</li><li>Auth per-user (Supabase Auth) → can()</li><li>WebSocket event bus → realtime()</li><li>Search API, audit service (append-only)</li><li>Gateway, WA BSP, ad server Segaloka (web + app) sungguhan</li></ul>`, { icon: 'plug' })}</div></div>`;
  return { html }; });
