/* =============================== OMNICHANNEL =============================== */
const CHANNELS = [
 { id: 'wa', key: 'whatsapp', nav: 'om_wa', name: 'WhatsApp', account: '+62 811 7000 1448 · BSP terverifikasi', quality: 'High', state: 'active', convs: 62, cfg: { queue: 'Umrah', autoReply: true, hours: '08:00–21:00 WITA' } },
 { id: 'ig', key: 'instagram', nav: 'om_ig', name: 'Instagram', account: '@segaloka.id · DM + komentar', quality: '—', state: 'active', convs: 17, cfg: { queue: 'Sales', autoReply: true, hours: '08:00–21:00 WITA' } },
 { id: 'fb', key: 'facebook', nav: 'om_fb', name: 'Facebook', account: 'Segaloka Page · Messenger', quality: '—', state: 'active', convs: 4, cfg: { queue: 'Default', autoReply: false, hours: '08:00–17:00 WITA' } },
 { id: 'email', key: 'email', nav: 'om_email', name: 'Email', account: 'cs@segaloka.example · SPF/DKIM ✓', quality: '—', state: 'active', convs: 6, cfg: { queue: 'Finance CS', autoReply: true, hours: '24 jam' } },
 { id: 'web', key: 'webchat', nav: 'om_web', name: 'Web Chat', account: 'Widget di 21 website Travel', quality: '—', state: 'active', convs: 11, cfg: { queue: 'Default', autoReply: true, hours: '24 jam' } }
];
const QUEUES = ['Umrah', 'Haji', 'Sales', 'Finance CS', 'Default'];
CHANNELS.forEach(ch => route('/omni/channel/' + ch.key, () => { const convs = CONVERSATIONS.filter(c => c.channel === ch.id); const on = ch.state === 'active';
  return { html: `<div class="page">${phead({ crumbs: [[t('g_omni'), '/omni'], [t('om_chan'), ''], [ch.name, '']], title: ch.name, desc: ch.account, actions: on ? permBtn('omni.manage', ic('ban') + L3(['Putuskan koneksi', 'Disconnect', 'قطع الاتصال']), `data-act="ch-toggle" data-id="${ch.id}" data-mut`, 'badb') : permBtn('omni.manage', ic('plug') + L3(['Hubungkan', 'Connect', 'ربط']), `data-act="ch-toggle" data-id="${ch.id}" data-mut`, 'primary') })}
  ${kpiRow([{ k: t('status'), v: st(on ? 'active' : 'inactive') }, { k: L3(['Percakapan aktif', 'Active conversations', 'محادثات نشطة']), v: fN(convs.filter(c => ['open', 'pending'].includes(c.status)).length) }, { k: L3(['Volume 30d', 'Volume 30d', 'الحجم']), v: fN(ch.convs * 23) }, { k: ch.id === 'wa' ? 'Quality rating' : 'First response', v: ch.id === 'wa' ? ch.quality : '4m 50s' }])}
  <div class="grid g12" style="margin-top:14px"><div class="c5">${pnl(L3(['Konfigurasi channel', 'Channel configuration', 'إعدادات القناة']), `<div class="field"><label for="chq">${L3(['Antrian default', 'Default queue', 'القائمة الافتراضية'])}</label><select id="chq">${QUEUES.map(q => `<option ${ch.cfg.queue === q ? 'selected' : ''}>${q}</option>`).join('')}</select></div><div class="field"><label for="chh">${L3(['Jam layanan', 'Service hours', 'ساعات الخدمة'])}</label><input type="text" id="chh" value="${esc(ch.cfg.hours)}"></div><label class="field" style="flex-direction:row;gap:8px;font-size:13px"><input type="checkbox" id="cha" ${ch.cfg.autoReply ? 'checked' : ''}> ${L3(['Auto-reply di luar jam layanan', 'Auto-reply outside service hours', 'رد تلقائي'])}</label>${ch.id === 'wa' ? `<div class="auditbox">${ic('info')}<span>${L3(['Pesan di luar jendela 24 jam wajib memakai template yang disetujui Meta.', 'Messages outside the 24h window must use a Meta-approved template.', 'خارج نافذة 24 ساعة يلزم قالب معتمد.'])} <a href="#/omni/templates">Template</a></span></div>` : ''}`, { icon: 'sliders', foot: permBtn('omni.manage', ic('check') + t('save'), `data-act="ch-save" data-id="${ch.id}" data-mut`, 'primary') })}</div>
  <div class="c7">${pnl(L3(['Percakapan di channel ini', 'Conversations on this channel', 'محادثات القناة']), convs.length ? `<div class="list" style="margin:-14px">${convs.map(c => `<a class="li" href="#/omni/inbox/${c.id}">${chanBadge(c.channel)}<span class="body"><b>${esc(c.contact)}</b><span class="sub">${esc(c.messages[c.messages.length - 1].text)}</span></span>${st(c.status)}</a>`).join('')}</div>` : stateBlock('empty'), { icon: 'msg', right: seeAll('/omni/inbox') })}
  ${pnl(L3(['Kirim pesan uji', 'Send test message', 'رسالة اختبار']), `<div style="display:flex;gap:8px;flex-wrap:wrap"><label class="input" style="flex:1"><span class="sr">To</span><input id="cht" value="${ch.id === 'email' ? 'qa@segaloka.example' : '+62 811 0000 0000'}"></label>${permBtn('omni.manage', icd('send', 'sm') + L3(['Kirim uji', 'Send test', 'إرسال']), `data-act="ch-test" data-id="${ch.id}" data-mut`, '')}</div>`, { icon: 'send', cls: '' }).replace('<section class="panel ', '<section style="margin-top:14px" class="panel ')}</div></div></div>` }; }));
Object.assign(A, {
  'ch-toggle': el => { const ch = CHANNELS.find(c => c.id === el.dataset.id); const off = ch.state === 'active'; confirmAction({ title: (off ? L3(['Putuskan ', 'Disconnect ', 'قطع ']) : L3(['Hubungkan ', 'Connect ', 'ربط '])) + ch.name, desc: off ? L3(['Pesan masuk tidak akan diterima di Inbox sampai channel dihubungkan kembali.', 'Inbound messages will not reach the Inbox until reconnected.', 'لن تصل الرسائل.']) : L3(['Token OAuth / BSP akan divalidasi oleh backend.', 'OAuth / BSP token will be validated by the backend.', 'سيتم التحقق.']), tone: off ? 'danger' : 'primary', reason: off, resource: 'Channel/' + ch.name, onOk: r => { ch.state = off ? 'inactive' : 'active'; audit('Admin Pusat', 'channel.' + (off ? 'disconnect' : 'connect'), 'Channel/' + ch.name, 'success', { reason: r }); toast(off ? 'warn' : 'ok', ch.name + ' · ' + L3(STATUS[ch.state].slice(2)), ''); rerender(); } }); },
  'ch-save': el => { const ch = CHANNELS.find(c => c.id === el.dataset.id); const before = JSON.stringify(ch.cfg); ch.cfg = { queue: document.getElementById('chq').value, hours: document.getElementById('chh').value, autoReply: document.getElementById('cha').checked }; audit('Admin Pusat', 'channel.config.update', 'Channel/' + ch.name, 'success', { before, after: JSON.stringify(ch.cfg) }); toast('ok', L3(['Konfigurasi disimpan', 'Configuration saved', 'تم الحفظ']), ch.name + ' → ' + ch.cfg.queue); },
  'ch-test': el => { const ch = CHANNELS.find(c => c.id === el.dataset.id); if (ch.state !== 'active') { toast('bad', L3(['Channel tidak terhubung', 'Channel not connected', 'القناة غير متصلة']), ch.name); return; } toast('ok', L3(['Pesan uji terkirim', 'Test message sent', 'أُرسلت']), ch.name + ' → ' + document.getElementById('cht').value + ' · delivered'); audit('Admin Pusat', 'channel.test', 'Channel/' + ch.name, 'success'); }
});
route('/omni', () => { const act = CONVERSATIONS.filter(c => ['open', 'pending'].includes(c.status)); const breach = CONVERSATIONS.filter(c => c.sla != null && c.sla < 0);
  return { html: `<div class="page">${phead({ crumbs: [[t('g_omni'), '/omni'], [t('om_ov'), '/omni']], title: 'Omnichannel', desc: L3(['Percakapan terpusat dari semua channel — routing, agent, SLA, dan hubungan ke Booking & Campaign.', 'Centralized conversations from every channel — routing, agents, SLA, and links to Booking & Campaign.', 'محادثات مركزية.']), actions: `<a class="btn primary" href="#/omni/inbox">${ic('inbox')}${t('om_inbox')}</a>` })}
  ${kpiRow([{ k: 'Open', v: fN(CONVERSATIONS.filter(c => c.status === 'open').length), route: '/omni/inbox' }, { k: 'Pending', v: fN(CONVERSATIONS.filter(c => c.status === 'pending').length) }, { k: 'Unassigned', v: fN(act.filter(c => !c.assignee).length) }, { k: 'SLA breach', v: `<span style="color:var(--bad)">${breach.length}</span>` }])}
  <div class="grid g3" style="margin-top:14px">${pnl(L3(['Volume per channel', 'Volume by channel', 'حسب القناة']), hbars(CHANNELS.map(c => [c.name, c.convs * 23]), fN), { icon: 'radio' })}${pnl(L3(['Beban agent', 'Agent load', 'حمل الوكلاء']), hbars(AGENTS.map(a => [a.name + (a.online ? '' : ' (offline)'), CONVERSATIONS.filter(c => c.assignee === a.id && ['open', 'pending'].includes(c.status)).length + a.load]), fN, 'var(--s3)'), { icon: 'users', right: seeAll('/omni/routing') })}${pnl('SLA breach', breach.length ? `<div class="list" style="margin:-14px">${breach.map(c => `<a class="li" href="#/omni/inbox/${c.id}">${chanBadge(c.channel)}<span class="body"><b>${esc(c.contact)}</b><span class="sub">+${-c.sla}m · ${c.assignee ? esc(AGENTS.find(a => a.id === c.assignee).name) : 'Unassigned'}</span></span></a>`).join('')}</div>` : stateBlock('empty', { title: 'SLA OK' }), { icon: 'timer' })}</div>
  <div class="grid g12" style="margin-top:14px"><div class="c8">${pnl(L3(['Percakapan masuk / hari', 'Inbound conversations / day', 'المحادثات يومياً']), barChart(ser().map(d => ({ ts: d.ts, v: Math.round(d.conv) })), { key: 'v', fmt: v => fN(Math.round(v)) }), { icon: 'bars', right: periodSel() })}</div><div class="c4">${pnl('Channel', `<div class="list" style="margin:-14px">${CHANNELS.map(c => `<a class="li" href="#/omni/channel/${c.key}">${chanBadge(c.id === 'email' ? 'email' : c.id)}<span class="body"><b>${c.name}</b><span class="sub">${esc(c.account)}</span></span>${st(c.state)}</a>`).join('')}</div>`, { icon: 'plug' })}</div></div></div>` }; });
route('/omni/analytics', () => omniAnalytics('om_ana'));
function omniAnalytics(nav) { return { html: `<div class="page">${phead({ crumbs: navTrail(nav).map(x => [x[0], x[1] || S.route]), title: t(nav), desc: L3(['Kinerja layanan & kontribusi percakapan ke booking.', 'Service performance & conversation contribution to bookings.', 'أداء الخدمة.']), actions: periodSel() })}${omniAnaBody()}</div>` }; }
function omniAnaBody() { const res = CONVERSATIONS.filter(c => ['resolved', 'closed'].includes(c.status)).length; return `${kpiRow([{ k: 'First response (median)', v: '4m 12s', d: delta(-8.4, true) }, { k: 'Resolution time', v: '3j 20m', d: delta(-3.1, true) }, { k: 'CSAT', v: '4,6 / 5', d: delta(1.2) }, { k: L3(['Lead → booking', 'Lead → booking', 'عميل ← حجز']), v: pct(11.4), d: delta(0.9) }])}
  <div class="grid g12" style="margin-top:14px"><div class="c8">${pnl(L3(['Percakapan / hari', 'Conversations / day', 'المحادثات']), areaChart(ser(), { key: 'conv', fmt: v => fN(Math.round(v)), h: 170 }), { icon: 'trend' })}</div><div class="c4">${pnl(L3(['Resolusi', 'Resolution', 'الحل']), hbars([['Resolved/Closed', res], ['Open', CONVERSATIONS.filter(c => c.status === 'open').length], ['Pending', CONVERSATIONS.filter(c => c.status === 'pending').length]], fN), { icon: 'check' })}</div></div>
  <section class="panel" style="margin-top:14px"><div class="panel-h"><h3>${ic('users', 'sm')}${L3(['Kinerja agent', 'Agent performance', 'أداء الوكلاء'])}</h3></div><div class="tbl-wrap"><table class="t"><thead><tr><th>Agent</th><th class="r">Assigned</th><th class="r">FRT</th><th class="r">Resolved</th><th class="r">CSAT</th><th>${t('status')}</th></tr></thead><tbody>${AGENTS.map((a, i) => `<tr><td><b>${esc(a.name)}</b></td><td class="r tnum">${CONVERSATIONS.filter(c => c.assignee === a.id).length + a.load}</td><td class="r tnum">${[3.2, 4.1, 6.8, 2.9][i]}m</td><td class="r tnum">${[41, 36, 18, 27][i]}</td><td class="r tnum">${[4.7, 4.5, 4.4, 4.8][i]}</td><td>${st(a.online ? 'active' : 'inactive')}</td></tr>`).join('')}</tbody></table></div></section>`; }
const CONTACTS = [...TRAVELERS.map((x, i) => ({ id: 'CT-' + (70100 + i * 3), name: x.name, phone: x.phone, email: x.email, type: 'Traveler', traveler: x.id, channel: ['WhatsApp', 'Email', 'Instagram'][i % 3], segment: ['Jamaah 2025', 'Keluarga muda', 'Komunitas kajian'][i % 3], consent: i % 9 === 4 ? 'opt_out' : 'opt_in', state: i % 9 === 4 ? 'inactive' : 'active' })), ...CONVERSATIONS.filter(c => !c.traveler).map((c, i) => ({ id: 'CT-' + (71100 + i * 3), name: c.contact, phone: '—', email: '—', type: 'Lead', traveler: null, channel: CH[c.channel][1], segment: 'Lead baru', consent: 'opt_in', state: 'active' }))];
route('/omni/contacts', () => resPage({ id: 'contacts', nav: 'om_contact', noun: 'Kontak', desc: L3(['Kontak & lead lintas channel dengan consent. Segmen dipakai untuk Broadcast dan Ads audience.', 'Cross-channel contacts & leads with consent. Segments feed Broadcast and Ads audiences.', 'جهات الاتصال.']), data: CONTACTS, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'tr', label: 'Traveler', fn: r => r.type === 'Traveler' }, { v: 'lead', label: 'Lead', fn: r => r.type === 'Lead' }, { v: 'out', label: 'Opt-out', fn: r => r.consent === 'opt_out' }], newLabel: L3(['Tambah kontak', 'Add contact', 'إضافة']),
  kpis: () => [{ k: L3(['Kontak', 'Contacts', 'جهات']), v: fN(CONTACTS.length) }, { k: 'Lead', v: fN(CONTACTS.filter(c => c.type === 'Lead').length) }, { k: 'Opt-in', v: pct(CONTACTS.filter(c => c.consent === 'opt_in').length / CONTACTS.length * 100, 0) }, { k: L3(['Segmen', 'Segments', 'الشرائح']), v: fN(new Set(CONTACTS.map(c => c.segment)).size) }],
  cols: [{ k: 'name', label: L3(['Kontak', 'Contact', 'جهة الاتصال']), render: r => ent(r.name, r.type, colorFor(r.name)) }, { k: 'channel', label: 'Channel' }, { k: 'segment', label: L3(['Segmen', 'Segment', 'الشريحة']), render: r => `<span class="chip">${esc(r.segment)}</span>` }, { k: 'consent', label: 'Consent', render: r => r.consent === 'opt_in' ? st('active').replace(L3(STATUS.active.slice(2)), 'Opt-in') : st('inactive').replace(L3(STATUS.inactive.slice(2)), 'Opt-out') }, { k: 'traveler', label: 'Traveler', render: r => r.traveler ? `<span class="mono">${r.traveler}</span>` : '—' }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'phone', label: L3(['Telepon', 'Phone', 'الهاتف']) }, { k: 'email', label: 'Email' }, { k: 'channel', label: 'Channel', type: 'select', options: ['WhatsApp', 'Instagram', 'Facebook', 'Email', 'Web Chat'] }, { k: 'segment', label: L3(['Segmen', 'Segment', 'الشريحة']), type: 'select', options: ['Lead baru', 'Jamaah 2025', 'Keluarga muda', 'Komunitas kajian'] }],
  make: v => ({ id: 'CT-' + (72000 + CONTACTS.length), ...v, type: 'Lead', traveler: null, consent: 'opt_in', state: 'active' }),
  acts: r => [r.type === 'Lead' ? { label: L3(['Konversi ke Traveler', 'Convert to Traveler', 'تحويل']), tone: 'primary', fn: x => { const id = 'TRL-' + (310000 + TRAVELERS.length); TRAVELERS.push({ id, name: x.name, phone: x.phone, email: x.email, city: '—', passport: 'pending', trips: 0, since: nowTs() }); x.type = 'Traveler'; x.traveler = id; }, msg: L3(['Traveler dibuat', 'Traveler created', 'أُنشئ المسافر']) } : null, r.consent === 'opt_in' ? { label: 'Opt-out', tone: 'badb', fn: x => { x.consent = 'opt_out'; x.state = 'inactive'; }, reason: true } : { label: 'Opt-in', tone: 'primary', fn: x => { x.consent = 'opt_in'; x.state = 'active'; } }].filter(Boolean) }));
const TPLS = TEMPLATES.map((x, i) => ({ id: 'TPL-' + (201 + i), name: x[0], body: x[1], channel: i % 2 ? 'WhatsApp' : 'Semua', lang: 'id', state: i === 3 ? 'review' : 'approved', uses: ri(30, 900) })).concat([{ id: 'TPL-209', name: 'Pengingat pelunasan', body: 'Bapak/Ibu {nama}, pelunasan booking {booking} jatuh tempo {tanggal}. Klik tautan pembayaran: {link}', channel: 'WhatsApp', lang: 'id', state: 'approved', uses: 1240 }, { id: 'TPL-210', name: 'Payment reminder (EN)', body: 'Dear {nama}, your balance for {booking} is due on {tanggal}.', channel: 'Email', lang: 'en', state: 'draft', uses: 0 }, { id: 'TPL-211', name: 'تذكير بالدفع', body: 'السيد/السيدة {nama}، موعد سداد الحجز {booking} هو {tanggal}.', channel: 'WhatsApp', lang: 'ar', state: 'rejected', uses: 0 }]);
TEMPLATES.length = 0; const syncTpl = () => { TEMPLATES.length = 0; TPLS.filter(x => x.state === 'approved').forEach(x => TEMPLATES.push([x.name, x.body])); }; syncTpl();
route('/omni/templates', () => resPage({ id: 'tpl', nav: 'om_tpl', noun: 'Template', desc: L3(['Template pesan per channel & bahasa. Template WhatsApp harus disetujui sebelum dipakai di luar jendela 24 jam. Hanya template Approved yang muncul di Inbox.', 'Message templates per channel & language. WhatsApp templates must be approved before use outside the 24h window. Only Approved templates appear in the Inbox.', 'قوالب الرسائل.']), data: TPLS, states: ['draft', 'review', 'approved', 'rejected'], lifecycle: ['draft', 'review', 'approved'], newLabel: L3(['Buat template', 'Create template', 'إنشاء قالب']),
  cols: [{ k: 'name', label: 'Template', render: r => `<b>${esc(r.name)}</b><div class="muted" style="font-size:12px;max-width:46ch;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(r.body)}</div>` }, { k: 'channel', label: 'Channel' }, { k: 'lang', label: L3(['Bahasa', 'Language', 'اللغة']), render: r => `<span class="chip mono">${r.lang.toUpperCase()}</span>` }, { k: 'uses', label: L3(['Dipakai', 'Used', 'الاستخدام']), cls: 'r tnum', render: r => fN(r.uses) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'channel', label: 'Channel', type: 'select', options: ['Semua', 'WhatsApp', 'Email', 'Instagram', 'Web Chat'] }, { k: 'lang', label: L3(['Bahasa', 'Language', 'اللغة']), type: 'select', options: [['id', 'Indonesia'], ['en', 'English'], ['ar', 'العربية']] }, { k: 'body', label: L3(['Isi (variabel: {nama}, {booking}, {tanggal}, {link})', 'Body (variables: {nama}, {booking}, {tanggal}, {link})', 'النص']), type: 'textarea', req: true }],
  make: v => ({ id: 'TPL-' + (201 + TPLS.length), ...v, state: 'draft', uses: 0 }), onEdit: r => { if (r.state === 'approved') r.state = 'review'; syncTpl(); },
  acts: r => ({ draft: [{ label: t('submit_review'), to: 'review', tone: 'primary' }], review: [{ label: t('reject'), to: 'rejected', tone: 'badb', reason: true, fn: syncTpl }, { label: t('approve'), to: 'approved', tone: 'primary', fn: syncTpl }], rejected: [{ label: L3(['Kembalikan ke draft', 'Back to draft', 'إرجاع']), to: 'draft' }], approved: [{ label: t('archive'), to: 'archived', tone: 'badb', reason: true, fn: syncTpl }] })[r.state] || [] }));
const BROADCASTS = [['Pengingat manasik Oktober', 'Jamaah 2025', 'TPL-203', 'completed', 1840], ['Promo Umrah Akhir Tahun', 'Keluarga muda', 'TPL-201', 'scheduled', 0], ['Info pelunasan batch 2', 'Jamaah 2025', 'TPL-209', 'processing', 620], ['Undangan kajian & expo', 'Komunitas kajian', 'TPL-201', 'draft', 0], ['Survei kepuasan', 'Jamaah 2025', 'TPL-201', 'failed', 0]].map((b, i) => ({ id: 'BC-' + (901 + i), name: b[0], segment: b[1], tpl: b[2], state: b[3], sent: b[4], delivered: Math.round(b[4] * .97), read: Math.round(b[4] * .71), when: T0 + [-6, 3, 0, 9, -2][i] * D }));
route('/omni/broadcast', () => resPage({ id: 'bc', nav: 'om_bc', noun: 'Broadcast', desc: L3(['Broadcast ke segmen kontak yang opt-in memakai template yang disetujui.', 'Broadcasts to opted-in contact segments using approved templates.', 'بث للشرائح الموافقة.']), data: BROADCASTS, states: ['draft', 'scheduled', 'processing', 'completed', 'failed'], lifecycle: ['draft', 'scheduled', 'processing', 'completed'], newLabel: L3(['Buat broadcast', 'Create broadcast', 'إنشاء بث']),
  cols: [{ k: 'name', label: 'Broadcast', render: r => `<b>${esc(r.name)}</b>` }, { k: 'segment', label: L3(['Segmen', 'Segment', 'الشريحة']), render: r => `<span class="chip">${esc(r.segment)}</span> <span class="muted tnum" style="font-size:12px">${CONTACTS.filter(c => c.segment === r.segment && c.consent === 'opt_in').length} opt-in</span>` }, { k: 'tpl', label: 'Template', render: r => esc((TPLS.find(x => x.id === r.tpl) || {}).name || r.tpl) }, { k: 'when', label: L3(['Jadwal', 'Schedule', 'الموعد']), render: r => fDT(r.when) }, { k: 'sent', label: 'Sent · Read', cls: 'r tnum', render: r => r.sent ? fN(r.sent) + ' · ' + pct(r.read / r.sent * 100, 0) : '—' }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'segment', label: L3(['Segmen', 'Segment', 'الشريحة']), type: 'select', options: () => [...new Set(CONTACTS.map(c => c.segment))] }, { k: 'tpl', label: 'Template (Approved)', type: 'select', options: () => TPLS.filter(x => x.state === 'approved').map(x => [x.id, x.name]) }, { k: 'date', label: L3(['Tanggal kirim', 'Send date', 'التاريخ']), type: 'date', def: '2026-09-30' }],
  make: v => ({ id: 'BC-' + (901 + BROADCASTS.length), name: v.name, segment: v.segment, tpl: v.tpl, when: new Date(v.date).getTime(), state: 'draft', sent: 0, delivered: 0, read: 0 }),
  acts: r => ({ draft: [{ label: L3(['Jadwalkan', 'Schedule', 'جدولة']), to: 'scheduled', tone: 'primary' }], scheduled: [{ label: L3(['Kirim sekarang', 'Send now', 'إرسال الآن']), to: 'completed', tone: 'primary', fn: x => { x.sent = CONTACTS.filter(c => c.segment === x.segment && c.consent === 'opt_in').length * 60; x.delivered = Math.round(x.sent * .97); x.read = Math.round(x.sent * .62); x.when = nowTs(); }, desc: L3(['Hanya kontak opt-in yang menerima pesan.', 'Only opted-in contacts receive it.', 'فقط الموافقون.']) }, { label: t('cancel'), to: 'draft', tone: 'badb', reason: true }], failed: [{ label: t('retry'), to: 'scheduled', tone: 'primary' }] })[r.state] || [] }));
const AUTOMATIONS = [['Auto-assign WA Umrah', 'Pesan masuk · WhatsApp · kata kunci "umrah"', 'Assign ke antrian Umrah', 'active'], ['Konfirmasi pembayaran', 'Event payment.paid', 'Kirim template "Info pembayaran"', 'active'], ['Pengingat pelunasan H-14', 'Booking partially_paid & H-14 keberangkatan', 'Kirim template "Pengingat pelunasan"', 'active'], ['Eskalasi SLA', 'SLA first response terlewati', 'Notifikasi supervisor + tag Prioritas', 'active'], ['Lead dari campaign', 'Pesan dari Click-to-Chat campaign', 'Tag Lead + hubungkan Campaign', 'paused'], ['Survei pasca-perjalanan', 'Booking completed', 'Kirim survei CSAT', 'draft']].map((a, i) => ({ id: 'AUT-' + (51 + i), name: a[0], trigger: a[1], action: a[2], state: a[3], runs: a[3] === 'draft' ? 0 : ri(40, 3000) }));
route('/omni/automation', () => resPage({ id: 'auto', nav: 'om_auto', noun: 'Automation', desc: L3(['Trigger → kondisi → aksi. Automation tidak melewati permission & policy — aksi dijalankan oleh service account dengan izin terbatas.', 'Trigger → condition → action. Automations never bypass permission & policy — actions run under a scoped service account.', 'الأتمتة.']), data: AUTOMATIONS, states: ['draft', 'active', 'paused'], newLabel: L3(['Buat automation', 'Create automation', 'إنشاء']),
  cols: [{ k: 'name', label: 'Automation', render: r => `<b>${esc(r.name)}</b>` }, { k: 'trigger', label: 'Trigger', render: r => `<span style="font-size:12.5px">${esc(r.trigger)}</span>` }, { k: 'action', label: L3(['Aksi', 'Action', 'الإجراء']), render: r => `<span style="font-size:12.5px">${esc(r.action)}</span>` }, { k: 'runs', label: 'Runs 30d', cls: 'r tnum', render: r => fN(r.runs) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'trigger', label: 'Trigger', type: 'select', options: ['Pesan masuk · WhatsApp', 'Pesan masuk · semua channel', 'Event payment.paid', 'Event booking.confirmed', 'Booking completed', 'SLA first response terlewati'] }, { k: 'action', label: L3(['Aksi', 'Action', 'الإجراء']), type: 'select', options: ['Assign ke antrian Umrah', 'Assign ke antrian Finance CS', 'Kirim template "Info pembayaran"', 'Tag Prioritas', 'Notifikasi supervisor'] }],
  make: v => ({ id: 'AUT-' + (51 + AUTOMATIONS.length), ...v, state: 'draft', runs: 0 }), acts: r => [r.state === 'active' ? { label: t('pause'), to: 'paused', tone: 'warnb' } : { label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }] }));
const RULES = [['WA · kata kunci umrah', 'WhatsApp', 'Umrah', 'Load-based'], ['WA · kata kunci haji', 'WhatsApp', 'Haji', 'Round-robin'], ['Refund / pembayaran', 'Semua', 'Finance CS', 'Load-based'], ['Click-to-Chat campaign', 'WhatsApp', 'Sales', 'Round-robin'], ['Instagram DM', 'Instagram', 'Sales', 'Round-robin'], ['Fallback', 'Semua', 'Default', 'Round-robin']].map((r, i) => ({ id: 'RTE-' + (11 + i), name: r[0], channel: r[1], queue: r[2], method: r[3], priority: i + 1, state: 'active' }));
route('/omni/routing', () => resPage({ id: 'rte', nav: 'om_route', noun: 'Aturan', desc: L3(['Aturan dievaluasi berurutan (prioritas). Percakapan tanpa kecocokan jatuh ke Fallback.', 'Rules evaluate in priority order. Unmatched conversations fall to Fallback.', 'تُقيّم القواعد بالترتيب.']), data: RULES, states: ['active', 'inactive'], newLabel: L3(['Tambah aturan', 'Add rule', 'إضافة قاعدة']),
  top: () => `<div class="grid g4" style="margin-bottom:14px">${QUEUES.slice(0, 4).map(q => pnl(q, `<div class="kpi" style="padding:0;border:0"><div class="v">${CONVERSATIONS.filter(c => ['open', 'pending'].includes(c.status)).length % 5 + QUEUES.indexOf(q)}</div><div class="d">${AGENTS.filter((a, i) => i % 4 === QUEUES.indexOf(q) % 4 || q === 'Default').map(a => a.name.split(' ')[0]).join(', ') || '—'}</div></div>`, { icon: 'inbox' })).join('')}</div>`,
  cols: [{ k: 'priority', label: '#', cls: 'tnum' }, { k: 'name', label: L3(['Aturan', 'Rule', 'القاعدة']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'channel', label: 'Channel' }, { k: 'queue', label: L3(['Antrian', 'Queue', 'القائمة']), render: r => `<span class="chip">${esc(r.queue)}</span>` }, { k: 'method', label: L3(['Metode', 'Method', 'الطريقة']) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'channel', label: 'Channel', type: 'select', options: ['Semua', 'WhatsApp', 'Instagram', 'Facebook', 'Email', 'Web Chat'] }, { k: 'queue', label: L3(['Antrian', 'Queue', 'القائمة']), type: 'select', options: QUEUES }, { k: 'method', label: L3(['Metode', 'Method', 'الطريقة']), type: 'select', options: ['Round-robin', 'Load-based'] }, { k: 'priority', label: L3(['Prioritas', 'Priority', 'الأولوية']), type: 'number', def: 1, min: 1 }],
  make: v => ({ id: 'RTE-' + (11 + RULES.length), ...v, state: 'active' }), acts: r => [r.state === 'active' ? { label: L3(['Nonaktifkan', 'Deactivate', 'تعطيل']), to: 'inactive', tone: 'badb', reason: true, why: r.name === 'Fallback' ? L3(['Fallback wajib aktif', 'Fallback must stay active', 'مطلوب']) : null } : { label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }] }));
const SLAS = [['WhatsApp', 5, 240], ['Instagram', 15, 480], ['Facebook', 30, 480], ['Email', 120, 1440], ['Web Chat', 3, 120]].map((s, i) => ({ id: 'SLA-' + (1 + i), name: 'SLA · ' + s[0], channel: s[0], frt: s[1], res: s[2], met: [0.93, 0.88, 0.95, 0.9, 0.91][i], state: 'active' }));
route('/omni/sla', () => resPage({ id: 'sla', nav: 'om_sla', noun: 'SLA', desc: L3(['Target first response & resolution per channel. Pelanggaran memicu eskalasi (lihat Automation).', 'First response & resolution targets per channel. Breaches trigger escalation (see Automation).', 'أهداف الاستجابة.']), data: SLAS, create: false,
  kpis: () => [{ k: 'SLA met (rata-rata)', v: pct(SLAS.reduce((s, x) => s + x.met, 0) / SLAS.length * 100, 0) }, { k: 'Breach aktif', v: fN(CONVERSATIONS.filter(c => c.sla != null && c.sla < 0).length) }, { k: 'FRT median', v: '4m 12s' }, { k: L3(['Eskalasi 7d', 'Escalations 7d', 'التصعيد']), v: '9' }],
  cols: [{ k: 'channel', label: 'Channel', render: r => `<b>${esc(r.channel)}</b>` }, { k: 'frt', label: 'First response', cls: 'r tnum', render: r => r.frt + ' mnt' }, { k: 'res', label: 'Resolution', cls: 'r tnum', render: r => (r.res / 60) + ' jam' }, { k: 'met', label: 'SLA met', render: r => pctBar(r.met, r.met < .9 ? 'warn' : 'ok') }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'frt', label: 'First response (menit)', type: 'number', min: 1, req: true }, { k: 'res', label: 'Resolution (menit)', type: 'number', min: 10, req: true }], acts: () => [] }));

/* =============================== ADS (submodules) =============================== */
const ADSETS = []; const ADS = []; const CREATIVES = [];
CAMPAIGNS.forEach(c => c.channels.forEach((ch, i) => { const share = 1 / c.channels.length; ADSETS.push({ id: 'AS-' + c.id.slice(4) + '-' + (i + 1), name: (i ? 'Lookalike · ' : '') + c.audience, campaign: c.id, channel: ch, budgetShare: share, spent: Math.round(c.spent * share), leads: Math.round(c.leads * share), state: ['active', 'paused', 'completed', 'archived'].includes(c.state) ? (c.state === 'active' ? 'active' : c.state) : 'draft' }); }));
CAMPAIGNS.forEach((c, ci) => { for (let k = 0; k < Math.min(3, c.creatives); k++) { const cr = { id: 'CR-' + c.id.slice(4) + '-' + (k + 1), name: ['Kaaba skyline 4:5', 'Testimoni jamaah 15s', 'Carousel itinerary', 'Story countdown'][k % 4] + ' · ' + c.name.split(' ').slice(0, 2).join(' '), campaign: c.id, format: ['Image 1080×1350', 'Video 15s', 'Carousel', 'Story 9:16'][k % 4], ctr: 0.9 + ((ci + k) % 5) * .35, claim: k === 0 && c.state === 'review' ? 'Klaim "pasti berangkat"' : '—', state: c.state === 'review' && k === 0 ? 'needs_revision' : ['draft', 'review'].includes(c.state) ? 'review' : 'approved' }; CREATIVES.push(cr); } });
CREATIVES.forEach((cr, i) => { const as = ADSETS.find(a => a.campaign === cr.campaign); ADS.push({ id: 'AD-' + (60100 + i * 3), name: cr.name, campaign: cr.campaign, adset: as ? as.id : '—', creative: cr.id, impr: Math.round((campById(cr.campaign).impr || 0) / 3), clicks: Math.round((campById(cr.campaign).clicks || 0) / 3), state: as ? as.state : 'draft' }); });
const campName = id => { const c = campById(id); return c ? `<a href="#/ads/campaign/${c.id}">${esc(c.name)}</a>` : '—'; };
const pauseActs = r => r.state === 'active' ? [{ label: t('pause'), to: 'paused', tone: 'warnb' }] : r.state === 'paused' ? [{ label: t('resume'), to: 'active', tone: 'primary', why: campById(r.campaign).state !== 'active' ? L3(['Campaign induk tidak aktif', 'Parent campaign not active', 'الحملة غير نشطة']) : null }] : [];
route('/ads/ads', () => resPage({ id: 'ads', nav: 'ads_ads', noun: 'Ad', desc: 'Campaign → Ad set → Ad (creative). ' + L3(['Status Ad mengikuti Campaign induk.', 'Ad status follows its parent Campaign.', 'تتبع الحملة.']), data: ADS, states: ['active', 'paused', 'draft', 'completed'], create: false,
  cols: [{ k: 'name', label: 'Ad', render: r => `<b>${esc(r.name)}</b><div class="muted mono" style="font-size:11.5px">${r.id}</div>` }, { k: 'campaign', label: 'Campaign', render: r => campName(r.campaign) }, { k: 'adset', label: 'Ad set', render: r => `<span class="mono" style="font-size:12px">${r.adset}</span>` }, { k: 'impr', label: 'Impr.', cls: 'r tnum', render: r => fC(r.impr) }, { k: 'clicks', label: 'CTR', cls: 'r tnum', render: r => r.impr ? pct(r.clicks / r.impr * 100, 2) : '—' }, { k: 'state', label: t('status'), render: r => st(r.state) }], acts: pauseActs }));
route('/ads/adsets', () => resPage({ id: 'adset', nav: 'ads_set', noun: 'Ad set', desc: L3(['Targeting audience per placement. Audience bersumber dari Contacts / Audience (Omnichannel) & event booking.', 'Audience targeting per placement. Audiences come from Contacts / Audience (Omnichannel) & booking events.', 'استهداف الجمهور.']), data: ADSETS, states: ['active', 'paused', 'draft', 'completed'],
  cols: [{ k: 'name', label: 'Audience', render: r => `<b>${esc(r.name)}</b><div class="muted mono" style="font-size:11.5px">${r.id}</div>` }, { k: 'campaign', label: 'Campaign', render: r => campName(r.campaign) }, { k: 'channel', label: 'Placement' }, { k: 'budgetShare', label: 'Budget share', cls: 'r tnum', render: r => pct(r.budgetShare * 100, 0) }, { k: 'spent', label: 'Spend', cls: 'r tnum', render: r => money(r.spent) }, { k: 'leads', label: 'Leads', cls: 'r tnum' }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: 'Audience', type: 'select', options: ['Jamaah 30–55 th · Jabodetabek', 'Komunitas kajian · Sumatera', 'Retargeting pengunjung paket 30 hari', 'Keluarga muda · Jawa Timur', 'Lookalike booking 2025 (1%)'] }, { k: 'campaign', label: 'Campaign', type: 'select', options: () => CAMPAIGNS.filter(c => !['archived', 'completed'].includes(c.state)).map(c => [c.id, c.name]) }, { k: 'channel', label: 'Placement', type: 'select', options: AD_CHANNELS }, { k: 'budgetShare', label: 'Budget share (0–1)', type: 'number', step: '0.05', def: 0.2 }],
  make: v => ({ id: 'AS-' + v.campaign.slice(4) + '-' + (ADSETS.filter(a => a.campaign === v.campaign).length + 1), ...v, spent: 0, leads: 0, state: campById(v.campaign).state === 'active' ? 'active' : 'draft' }), acts: pauseActs }));
route('/ads/creative', () => resPage({ id: 'cre', nav: 'ads_cre', noun: 'Creative', desc: L3(['Library creative dengan review kepatuhan klaim (mis. "pasti berangkat", "termurah").', 'Creative library with claim-compliance review (e.g. "guaranteed departure", "cheapest").', 'مكتبة التصاميم.']), data: CREATIVES, states: ['review', 'approved', 'needs_revision', 'rejected'], lifecycle: ['draft', 'review', 'approved'], newLabel: L3(['Unggah creative', 'Upload creative', 'رفع تصميم']),
  cols: [{ k: 'name', label: 'Creative', render: (r, i) => `<div class="ent"><div class="lg" style="background:linear-gradient(135deg,#2b3e72,#6f8cff)">${r.format.startsWith('Video') ? '▶' : 'IMG'}</div><div><b>${esc(r.name)}</b><span>${esc(r.format)}</span></div></div>` }, { k: 'campaign', label: 'Campaign', render: r => campName(r.campaign) }, { k: 'ctr', label: 'CTR', cls: 'r tnum', render: r => pct(r.ctr, 2) }, { k: 'claim', label: L3(['Klaim ditandai', 'Flagged claim', 'ادعاء']), render: r => r.claim === '—' ? '—' : `<span class="st warn">${ic('alert')}${esc(r.claim)}</span>` }, { k: 'state', label: 'Review', render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'campaign', label: 'Campaign', type: 'select', options: () => CAMPAIGNS.map(c => [c.id, c.name]) }, { k: 'format', label: 'Format', type: 'select', options: ['Image 1080×1350', 'Video 15s', 'Carousel', 'Story 9:16'] }, { k: 'claim', label: L3(['Klaim di copy (untuk dicek)', 'Claims in copy (to check)', 'الادعاءات']), def: '—' }],
  make: v => ({ id: 'CR-' + (90000 + CREATIVES.length), ...v, ctr: 0, state: 'review' }),
  acts: r => ({ review: [{ label: t('revise'), to: 'needs_revision', tone: 'warnb', reason: true, perm: 'ads.approve' }, { label: t('approve'), to: 'approved', tone: 'primary', perm: 'ads.approve', why: r.claim !== '—' ? L3(['Klaim sensitif harus direvisi dulu', 'Sensitive claim must be revised first', 'يجب تعديل الادعاء']) : null }], needs_revision: [{ label: L3(['Tandai sudah direvisi', 'Mark revised', 'تم التعديل']), to: 'review', tone: 'primary', fn: x => x.claim = '—' }], approved: [{ label: t('reject'), to: 'rejected', tone: 'badb', reason: true }] })[r.state] || [] }));
const PLACEMENTS = AD_CHANNELS.map((ch, i) => ({ id: 'PLC-' + (1 + i), name: ch, kind: ch.includes('Marketplace') ? 'Internal' : ch.includes('WhatsApp') ? 'Omnichannel' : ch === 'Email' ? 'Omnichannel' : 'Eksternal', account: ['act_2291… (Business Manager)', 'AW-8812…', 'TT-5510…', 'Slot sponsor · pencarian & kategori', 'WA +62 811 7000 1448', 'Mailer · cs@segaloka.example'][i], campaigns: CAMPAIGNS.filter(c => c.channels.includes(ch) && c.state === 'active').length, state: i === 2 ? 'degraded' : 'active' }));
route('/ads/placement', () => resPage({ id: 'plc', nav: 'ads_plc', noun: 'Placement', desc: L3(['Integrasi platform iklan eksternal, slot sponsor Marketplace, dan channel Omnichannel sebagai placement.', 'External ad platform integrations, Marketplace sponsored slots, and Omnichannel channels as placements.', 'مواضع الإعلانات.']), data: PLACEMENTS, create: false,
  cols: [{ k: 'name', label: 'Placement', render: r => `<b>${esc(r.name)}</b>` }, { k: 'kind', label: L3(['Tipe', 'Type', 'النوع']), render: r => `<span class="chip">${r.kind}</span>` }, { k: 'account', label: L3(['Akun', 'Account', 'الحساب']), render: r => `<span class="mono" style="font-size:12px">${esc(r.account)}</span>` }, { k: 'campaigns', label: 'Campaign aktif', cls: 'r tnum' }, { k: 'state', label: 'Integrasi', render: r => st(r.state) }],
  acts: r => [r.state === 'inactive' ? { label: L3(['Hubungkan', 'Connect', 'ربط']), to: 'active', tone: 'primary' } : { label: L3(['Putuskan', 'Disconnect', 'قطع']), to: 'inactive', tone: 'badb', reason: true, desc: L3(['Campaign aktif di placement ini akan berhenti delivery.', 'Active campaigns on this placement will stop delivering.', 'ستتوقف الحملات.']) }, r.state === 'degraded' ? { label: L3(['Sinkron ulang token', 'Resync token', 'مزامنة']), to: 'active', confirm: false } : null].filter(Boolean) }));
const ADBUDGETS = [...new Set(CAMPAIGNS.filter(c => c.owner).map(c => c.owner))].map((tid, i) => { const cs = CAMPAIGNS.filter(c => c.owner === tid); return { id: 'ADB-' + tid.slice(4), name: travelById(tid).name, travel: tid, balance: ri(5, 120) * 1e6, spend: cs.reduce((s, c) => s + c.spent, 0), campaigns: cs.length, state: 'active' }; });
route('/ads/budget', () => resPage({ id: 'adb', nav: 'ads_bud', noun: 'Saldo iklan', desc: L3(['Saldo iklan per tenant (prepaid). Spend dipotong dari saldo ini, terpisah dari ledger settlement booking.', 'Prepaid ad balance per tenant. Spend deducts from this balance, separate from the booking settlement ledger.', 'رصيد الإعلانات.']), data: ADBUDGETS, create: false,
  kpis: () => [{ k: L3(['Total saldo', 'Total balance', 'الرصيد']), v: money(ADBUDGETS.reduce((s, b) => s + b.balance, 0)) }, { k: 'Spend', v: money(ADBUDGETS.reduce((s, b) => s + b.spend, 0)) }, { k: L3(['Saldo menipis', 'Low balance', 'رصيد منخفض']), v: fN(ADBUDGETS.filter(b => b.balance < 20e6).length) }, { k: 'Tenant', v: fN(ADBUDGETS.length) }],
  cols: [{ k: 'name', label: 'Travel', render: r => trvLink(r.travel) }, { k: 'balance', label: L3(['Saldo', 'Balance', 'الرصيد']), cls: 'r tnum', render: r => `<b style="color:var(--${r.balance < 20e6 ? 'warn' : 'ink'})">${money(r.balance, true)}</b>` }, { k: 'spend', label: 'Spend', cls: 'r tnum', render: r => money(r.spend) }, { k: 'campaigns', label: 'Campaign', cls: 'r tnum' }, { k: 'state', label: t('status'), render: r => st(r.balance < 20e6 ? 'hold' : 'active') }],
  acts: () => [{ label: 'Top-up', tone: 'primary', icon: 'plus', fields: [{ k: 'amount', label: L3(['Jumlah (Rp)', 'Amount (Rp)', 'المبلغ']), type: 'number', req: true, min: 100000, step: 100000, def: 10000000 }, { k: 'method', label: L3(['Metode', 'Method', 'الطريقة']), type: 'select', options: ['VA BCA', 'VA Mandiri', 'QRIS'] }], fn: (x, r, v) => { x.balance += v.amount; }, msg: L3(['Saldo iklan bertambah (invoice top-up dibuat)', 'Ad balance increased (top-up invoice created)', 'زاد الرصيد']) }] }));
const VOUCHERS = [['UMRAH1448', 'Potongan Rp 1.500.000', 'Umrah', 500, 212, 'active'], ['KELUARGA4', '5% untuk 4 pax+', 'Semua paket', 200, 41, 'active'], ['EARLYRMD', 'Rp 2.000.000 Umrah Ramadhan', 'Umrah', 150, 0, 'scheduled'], ['HALALJP', '7% Halal Tour Jepang', 'Halal Tour', 100, 100, 'expired'], ['SEGADEAL10', '10% SegaDeals', 'SegaDeals', 300, 88, 'active'], ['TEST-QA', 'Voucher QA', '—', 5, 0, 'draft']].map((v, i) => ({ id: 'VCH-' + (41 + i), name: v[0], rule: v[1], scope: v[2], quota: v[3], used: v[4], state: v[5], end: T0 + [40, 60, 120, -5, 20, 30][i] * D }));
route('/ads/voucher', () => resPage({ id: 'vch', nav: 'ads_vou', noun: 'Voucher', desc: L3(['Kode promo dengan kuota & masa berlaku. Validasi dilakukan server saat checkout.', 'Promo codes with quota & validity. Validated server-side at checkout.', 'قسائم الخصم.']), data: VOUCHERS, states: ['draft', 'scheduled', 'active', 'expired', 'archived'], newLabel: L3(['Buat voucher', 'Create voucher', 'إنشاء قسيمة']),
  cols: [{ k: 'name', label: L3(['Kode', 'Code', 'الرمز']), render: r => `<span class="chip mono">${esc(r.name)}</span>` }, { k: 'rule', label: L3(['Aturan', 'Rule', 'القاعدة']) }, { k: 'scope', label: 'Scope' }, { k: 'used', label: 'Kuota', render: r => pctBar(r.used / r.quota, r.used >= r.quota ? 'warn' : '') }, { k: 'end', label: L3(['Berakhir', 'Ends', 'ينتهي']), render: r => fD(r.end) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Kode', 'Code', 'الرمز']), req: true }, { k: 'rule', label: L3(['Aturan diskon', 'Discount rule', 'القاعدة']), req: true }, { k: 'scope', label: 'Scope', type: 'select', options: ['Semua paket', 'Umrah', 'Haji', 'Halal Tour', 'SegaDeals'] }, { k: 'quota', label: 'Kuota', type: 'number', def: 100, min: 1 }],
  make: v => ({ id: 'VCH-' + (41 + VOUCHERS.length), ...v, name: v.name.toUpperCase().replace(/\s+/g, ''), used: 0, state: 'draft', end: nowTs() + 30 * D }),
  acts: r => ({ draft: [{ label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }], scheduled: [{ label: L3(['Aktifkan sekarang', 'Activate now', 'تفعيل']), to: 'active', tone: 'primary' }], active: [{ label: L3(['Hentikan', 'Stop', 'إيقاف']), to: 'expired', tone: 'badb', reason: true }], expired: [{ label: t('archive'), to: 'archived' }] })[r.state] || [] }));
const TRACKERS = [['Meta Pixel + CAPI', 'Meta Ads', 'lead, initiate_checkout, purchase', 'active', 98], ['Google Ads tag', 'Google Ads', 'lead, purchase', 'active', 95], ['TikTok Events API', 'TikTok Ads', 'lead, purchase', 'degraded', 71], ['Server events · booking', 'Segaloka backend', 'booking.created, booking.confirmed', 'active', 100], ['Server events · payment', 'Segaloka backend', 'payment.paid', 'active', 100]].map((x, i) => ({ id: 'TRK-' + (1 + i), name: x[0], dest: x[1], events: x[2], state: x[3], match: x[4] }));
route('/ads/tracking', () => resPage({ id: 'trk', nav: 'ads_trk', noun: 'Sumber tracking', desc: L3(['Event dikirim server-side dari booking & payment — bukan dari browser — agar atribusi konsisten dengan ledger.', 'Events are sent server-side from booking & payment — not the browser — so attribution matches the ledger.', 'أحداث من الخادم.']), data: TRACKERS, create: false,
  cols: [{ k: 'name', label: L3(['Sumber', 'Source', 'المصدر']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'dest', label: L3(['Tujuan', 'Destination', 'الوجهة']) }, { k: 'events', label: 'Events', render: r => `<span class="mono" style="font-size:11.5px">${esc(r.events)}</span>` }, { k: 'match', label: 'Match quality', render: r => pctBar(r.match / 100, r.match < 80 ? 'warn' : 'ok') }, { k: 'state', label: 'Health', render: r => st(r.state) }],
  acts: r => [{ label: L3(['Kirim event uji', 'Send test event', 'حدث اختبار']), confirm: false, fn: x => { if (x.state === 'degraded') { x.match = Math.min(100, x.match + 12); if (x.match >= 80) x.state = 'active'; } }, msg: L3(['Event uji diterima (200 OK)', 'Test event received (200 OK)', 'تم الاستلام']) }] }));
const CONVDEFS = [['Lead', 'lead', 'Pesan pertama / form', 0, 'Last non-direct click'], ['Checkout dimulai', 'initiate_checkout', 'Klik "Pesan" di paket', 0, 'Last non-direct click'], ['Booking dibuat', 'booking.created', 'Server event', 0, 'Last non-direct click'], ['Booking terbayar', 'payment.paid', 'Server event (webhook)', 1, 'Last non-direct click']].map((c, i) => ({ id: 'CNV-D' + (1 + i), name: c[0], event: c[1], source: c[2], value: c[3] ? 'Nilai payment' : '—', model: c[4], state: 'active' }));
route('/ads/conversion', () => resPage({ id: 'cdef', nav: 'ads_conv', noun: 'Konversi', desc: L3(['Definisi konversi & nilainya. "Booking terbayar" memakai nilai payment dari webhook gateway.', 'Conversion definitions & values. "Paid booking" uses the payment value from the gateway webhook.', 'تعريفات التحويل.']), data: CONVDEFS, states: ['active', 'inactive'],
  cols: [{ k: 'name', label: L3(['Konversi', 'Conversion', 'التحويل']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'event', label: 'Event', render: r => `<span class="mono">${r.event}</span>` }, { k: 'source', label: L3(['Sumber', 'Source', 'المصدر']) }, { k: 'value', label: L3(['Nilai', 'Value', 'القيمة']) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'event', label: 'Event', type: 'select', options: ['lead', 'initiate_checkout', 'booking.created', 'booking.confirmed', 'payment.paid'] }, { k: 'source', label: L3(['Sumber', 'Source', 'المصدر']), def: 'Server event' }], make: v => ({ id: 'CNV-D' + (1 + CONVDEFS.length), ...v, value: '—', model: 'Last non-direct click', state: 'active' }),
  acts: r => [r.state === 'active' ? { label: L3(['Nonaktifkan', 'Deactivate', 'تعطيل']), to: 'inactive', tone: 'badb', reason: true } : { label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }] }));
const ATTR = { model: 'last_non_direct', click: 7, view: 1, crossDevice: true };
route('/ads/attribution', () => { const src = {}; BOOKINGS.forEach(b => src[b.source] = (src[b.source] || 0) + 1); return { html: `<div class="page">${phead({ crumbs: [[t('g_ads'), '/ads'], [t('ads_attr'), '']], title: t('ads_attr'), desc: L3(['Model atribusi yang dipakai laporan Ads & Analytics. Perubahan berlaku ke depan dan dicatat di audit.', 'Attribution model used by Ads & Analytics reports. Changes apply going forward and are audited.', 'نموذج الإسناد.']) })}
  <div class="grid g12"><div class="c5">${pnl(L3(['Pengaturan model', 'Model settings', 'إعدادات النموذج']), `<div class="optgrid" style="grid-template-columns:1fr">${[['last_non_direct', 'Last non-direct click', L3(['Kredit penuh ke klik terakhir non-direct', 'Full credit to last non-direct click', 'آخر نقرة'])], ['first_click', 'First click', L3(['Kredit ke sentuhan pertama', 'Credit to first touch', 'أول نقرة'])], ['linear', 'Linear', L3(['Dibagi rata ke semua sentuhan', 'Split evenly across touches', 'بالتساوي'])], ['position', 'Position-based (40/20/40)', L3(['Awal & akhir dominan', 'First & last weighted', 'حسب الموضع'])]].map(m => `<button class="opt" role="radio" aria-checked="${ATTR.model === m[0]}" data-act="attr-model" data-v="${m[0]}"><span><b>${m[1]}</b><span>${esc(m[2])}</span></span></button>`).join('')}</div><div class="grid g2" style="gap:10px;margin-top:12px"><div class="field"><label for="at-c">Click window (hari)</label><input type="number" id="at-c" value="${ATTR.click}" min="1" max="30"></div><div class="field"><label for="at-v">View window (hari)</label><input type="number" id="at-v" value="${ATTR.view}" min="0" max="7"></div></div>`, { icon: 'branch', foot: permBtn('ads.manage', ic('check') + t('save'), 'data-act="attr-save" data-mut', 'primary') })}</div>
  <div class="c7">${pnl(L3(['Booking per sumber', 'Bookings by source', 'الحجوزات حسب المصدر']), hbars(Object.entries(src).sort((a, b) => b[1] - a[1]), fN), { icon: 'bars' })}<div style="margin-top:14px">${pnl(L3(['Contoh path konversi', 'Sample conversion paths', 'مسارات']), `<div class="list" style="margin:-14px">${[['Meta Ads', 'WhatsApp Click-to-Chat', 'Booking', 'Payment'], ['Google Ads', 'Marketplace', 'Booking', 'Payment'], ['Affiliate', 'Website Travel', 'Booking'], ['TikTok Ads', 'Instagram DM', 'WhatsApp', 'Booking', 'Payment']].map(p => `<div class="li" style="flex-wrap:wrap;gap:6px">${p.map((s, i) => `<span class="chip">${esc(s)}</span>${i < p.length - 1 ? icd('arrowR', 'sm muted') : ''}`).join('')}</div>`).join('')}</div>`, { icon: 'route' })}</div></div></div></div>` }; });
Object.assign(A, { 'attr-model': el => { ATTR.model = el.dataset.v; document.querySelectorAll('[data-act="attr-model"]').forEach(b => b.setAttribute('aria-checked', b === el)); },
  'attr-save': () => confirmAction({ title: L3(['Simpan model atribusi', 'Save attribution model', 'حفظ']), desc: ATTR.model + ' · click ' + document.getElementById('at-c').value + 'd / view ' + document.getElementById('at-v').value + 'd', reason: true, resource: 'Config/attribution', onOk: r => { const before = JSON.stringify(ATTR); ATTR.click = +document.getElementById('at-c').value; ATTR.view = +document.getElementById('at-v').value; const lbl = { last_non_direct: 'Last non-direct click', first_click: 'First click', linear: 'Linear', position: 'Position-based' }[ATTR.model]; CAMPAIGNS.forEach(c => c.attribution = lbl + ' · ' + ATTR.click + 'd click / ' + ATTR.view + 'd view'); audit('Admin Pusat', 'attribution.update', 'Config/attribution', 'success', { before, after: JSON.stringify(ATTR), reason: r }); toast('ok', L3(['Model atribusi disimpan', 'Attribution model saved', 'تم الحفظ']), lbl); } }) });
route('/ads/performance', () => { const L = CAMPAIGNS.filter(c => c.spent > 0).sort((a, b) => campRoas(b) - campRoas(a)); return { html: `<div class="page">${phead({ crumbs: [[t('g_ads'), '/ads'], [t('ads_perf'), '']], title: t('ads_perf'), desc: L3(['Monitoring harian untuk operasional iklan. Versi konsolidasi dengan Booking & Revenue ada di Analytics.', 'Daily monitoring for ad operations. The consolidated version with Booking & Revenue lives in Analytics.', 'مراقبة يومية.']), actions: periodSel() + `<a class="btn" href="#/analytics/ads">Analytics${icd('arrowR', 'sm')}</a>` })}
  <div class="grid g2">${pnl('Spend', areaChart(ser(), { key: 'spend', fmt: v => money(v), h: 150 }), { icon: 'trend' })}${pnl('Leads', barChart(ser(), { key: 'leads', fmt: v => fN(Math.round(v)), h: 150 }), { icon: 'bars' })}</div>
  <section class="panel" style="margin-top:14px"><div class="tbl-wrap"><table class="t"><thead><tr><th>Campaign</th><th>${t('status')}</th><th class="r">Spend</th><th class="r">Impr.</th><th class="r">CTR</th><th class="r">CPL</th><th class="r">Booking</th><th class="r">ROAS</th><th>Trend</th></tr></thead><tbody>${L.map(c => `<tr class="clickable" data-href="/ads/campaign/${c.id}"><td><b>${esc(c.name)}</b></td><td>${st(c.state)}</td><td class="r tnum">${money(c.spent)}</td><td class="r tnum">${fC(c.impr)}</td><td class="r tnum">${pct(c.clicks / c.impr * 100, 2)}</td><td class="r tnum">${money(c.spent / Math.max(1, c.leads))}</td><td class="r tnum">${c.bookings}</td><td class="r tnum"><b>${fN(campRoas(c), { maximumFractionDigits: 1 })}×</b></td><td>${spark(ser().map(d => d.leads * (0.5 + (c.id.charCodeAt(7) % 7) / 10)), 'var(--s1)', 80, 22)}</td></tr>`).join('')}</tbody></table></div></section></div>` }; });
