/* =====================================================================
   BIAYA PENDAFTARAN MITRA & AGEN
   - Travel menentukan biaya pendaftaran Mitra dan Agen di bawahnya (0 = gratis).
   - Pendaftar membayar lewat gateway (otomatis terkonfirmasi) → status aktif.
   - Segaloka mengambil fee % (default 20%, diatur admin; bisa per Travel).
     Sisanya masuk saldo Travel.
   ===================================================================== */
const REGCFG = { pct: 20 };
const REG_FEES = [];
const regFeeFor = (tr, kind) => Math.max(0, +((tr && tr.regFee && tr.regFee[kind]) || 0));
const regPctFor = tr => tr && tr.regPct != null ? +tr.regPct : +REGCFG.pct;
const regUnpaid = x => x && x.regState === 'awaiting_payment';
/* pasang biaya pada entitas yang baru dibuat */
function regApply(x, kind) { const tr = travelById(x.travel); const fee = regFeeFor(tr, kind); if (!fee) { x.regState = 'free'; return; } x.regFee = fee; x.regPct = regPctFor(tr); x.regState = 'awaiting_payment'; x.status = 'review'; }
function regWrap(act, arr, kind) { const f = A[act]; if (!f) return; A[act] = el => { const before = new Set(arr().map(x => x.id)); const r = f(el); arr().filter(x => !before.has(x.id)).forEach(x => { regApply(x, kind); if (regUnpaid(x)) partyNotify([ntKey(kind, x.id)], 'payment', 'warn', L3(['Bayar biaya pendaftaran', 'Pay the registration fee', 'ادفع رسوم التسجيل']), money(x.regFee, true) + ' · ' + ((travelById(x.travel) || {}).name || ''), { [kind]: '/p/' + kind }); }); if (arr().some(x => !before.has(x.id))) rerender(); return r; }; }
regWrap('tm-save', () => MITRA, 'mitra'); regWrap('ag-save', () => AGEN, 'agen');
(() => { const f = A['ob-save']; A['ob-save'] = el => { const ws = el.dataset.ws; if (ws !== 'mitra' && ws !== 'agen') return f(el); const arr = ws === 'mitra' ? MITRA : AGEN; const before = new Set(arr.map(x => x.id)); f(el); arr.filter(x => !before.has(x.id)).forEach(x => regApply(x, ws)); rerender(); }; })();
/* belum bayar → tidak bisa mendaftarkan jamaah / menambah agen */
['ma-reg', 'ag-new'].forEach(k => { const f = A[k]; if (!f) return; A[k] = el => { const ws = (el && el.dataset && el.dataset.ws) || wsOf(); const x = me(ws); if (regUnpaid(x)) return toast('warn', L3(['Selesaikan pembayaran pendaftaran dulu', 'Complete your registration payment first', 'ادفع أولاً']), money(x.regFee, true)); return f(el); }; });
A['reg-pay'] = async el => { const ws = el.dataset.ws; const x = me(ws); if (!regUnpaid(x)) return; await gwCheckout('registration', x.id, x.regFee); };

/* banner pembayaran di portal Mitra/Agen */
(() => { const f = portalStatusBanner; portalStatusBanner = function (ws) { let h = f(ws); if (ws === 'mitra' || ws === 'agen') { const x = me(ws); if (regUnpaid(x)) { const tr = travelById(x.travel) || {}; h = `<div class="banner warn" role="status" style="border:1px solid var(--warn-line, var(--line));border-radius:10px;margin-bottom:12px">${ic('card')}<span style="flex:1"><b>${L3(['Biaya pendaftaran ', 'Registration fee ', 'رسوم التسجيل ']) + (ws === 'mitra' ? 'Mitra' : 'Agen')} · ${money(x.regFee, true)}</b><br><span style="font-size:12.5px">${L3(['Ditetapkan oleh ', 'Set by ', 'حددها ']) + esc(tr.name || '') + L3(['. Akun aktif otomatis setelah pembayaran berhasil.', '. Your account activates automatically once paid.', '.'])}</span></span><button class="btn sm primary" data-act="reg-pay" data-ws="${ws}">${ic('card', 'sm')}${L3(['Bayar sekarang', 'Pay now', 'ادفع'])}</button></div>` + h; } } return h; }; })();

/* ---------- Portal Travel: atur biaya ---------- */
function regTravelPanel(tr) { const pct = regPctFor(tr); const R = REG_FEES.filter(r => r.travel === tr.id); const unpaid = [...MITRA.filter(m => m.travel === tr.id), ...AGEN.filter(a => a.travel === tr.id)].filter(regUnpaid);
  const row = (k, l) => { const fee = regFeeFor(tr, k); return `<div class="docrow"><span class="fi">${k === 'mitra' ? 'MT' : 'AG'}</span><span class="body"><b>${l}</b><span>${fee ? money(fee, true) + ' · ' + L3(['Anda terima ', 'You receive ', 'تستلم ']) + money(Math.round(fee * (100 - pct) / 100), true) + ' · Segaloka ' + pct + '%' : L3(['Gratis', 'Free', 'مجاني'])}</span></span></div>`; };
  return `<section class="panel" style="margin-bottom:14px"><div class="panel-h"><h3>${ic('card', 'sm')}${L3(['Biaya pendaftaran kemitraan & keagenan', 'Partner & agent registration fees', 'رسوم التسجيل'])}</h3><button class="btn sm" data-act="reg-set">${ic('sliders', 'sm')}${L3(['Atur biaya', 'Set fees', 'ضبط'])}</button></div><div class="panel-b">${row('mitra', 'Mitra Travel')}${row('agen', 'Agen')}
  <div class="grid g3" style="margin-top:10px">${kpiRow([{ k: L3(['Pendaftaran berbayar', 'Paid registrations', 'مدفوعة']), v: fN(R.length) }, { k: L3(['Pendapatan bersih', 'Net income', 'الصافي']), v: money(R.reduce((s, r) => s + r.net, 0)) }, { k: L3(['Menunggu pembayaran', 'Awaiting payment', 'بانتظار الدفع']), v: fN(unpaid.length) }])}</div>
  ${unpaid.length ? `<div class="muted" style="font-size:12.5px;margin-top:8px">${L3(['Belum bayar: ', 'Unpaid: ', 'غير مدفوع: ']) + unpaid.map(x => esc(x.name)).join(', ')}</div>` : ''}</div></section>`; }
Object.assign(A, {
  'reg-set': () => { const tr = me('travel'); const pct = regPctFor(tr); modal({ title: L3(['Biaya pendaftaran', 'Registration fees', 'رسوم التسجيل']), body: fields([{ k: 'mitra', label: L3(['Biaya pendaftaran Mitra (Rp) — 0 = gratis', 'Partner registration fee (Rp) — 0 = free', 'رسوم الشريك']), type: 'number', min: 0, step: 50000, def: regFeeFor(tr, 'mitra') }, { k: 'agen', label: L3(['Biaya pendaftaran Agen (Rp) — 0 = gratis', 'Agent registration fee (Rp) — 0 = free', 'رسوم الوكيل']), type: 'number', min: 0, step: 50000, def: regFeeFor(tr, 'agen') }], 'rg-') + `<div class="auditbox">${ic('percent')}<span>${L3(['Segaloka mengambil fee ', 'Segaloka takes a ', 'تأخذ سيجالوكا ']) + pct + L3(['% dari setiap pembayaran pendaftaran (ditetapkan admin). Sisanya masuk saldo Anda.', '% fee on each registration payment (set by admin). The rest goes to your balance.', '%.'])}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="reg-set-go">${t('save')}</button>` }); },
  'reg-set-go': () => { const tr = me('travel'); const v = formVals([{ k: 'mitra', type: 'number' }, { k: 'agen', type: 'number' }], 'rg-'); if (!v) return; if (v.mitra < 0 || v.agen < 0) return toast('bad', L3(['Tidak boleh negatif', 'Cannot be negative', 'غير صالح']), ''); const before = JSON.stringify(tr.regFee || {}); tr.regFee = { mitra: +v.mitra || 0, agen: +v.agen || 0 }; pAudit('travel', 'registration_fee.update', 'Travel/' + tr.id, { before, after: JSON.stringify(tr.regFee) }); closeOverlays(); toast('ok', L3(['Biaya pendaftaran disimpan', 'Registration fees saved', 'حُفظ']), 'Mitra ' + money(tr.regFee.mitra) + ' · Agen ' + money(tr.regFee.agen)); rerender(); },
  /* admin */
  'reg-cfg': () => modal({ title: L3(['Fee Segaloka dari pendaftaran', 'Segaloka fee on registrations', 'رسوم سيجالوكا']), body: fields([{ k: 'pct', label: L3(['Fee default (%)', 'Default fee (%)', 'النسبة']), type: 'number', req: true, min: 0, max: 100, step: 1, def: REGCFG.pct }], 'rc-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="reg-cfg-go">${t('save')}</button>` }),
  'reg-cfg-go': () => { const v = formVals([{ k: 'pct', type: 'number', req: true }], 'rc-'); if (!v || v.pct < 0 || v.pct > 100) return toast('bad', '0–100%', ''); const prev = REGCFG.pct; REGCFG.pct = v.pct; audit('Admin Pusat', 'registration_fee.pct.update', 'Settings/registration', 'success', { before: prev + '%', after: v.pct + '%' }); closeOverlays(); toast('ok', L3(['Fee disimpan', 'Fee saved', 'حُفظ']), v.pct + '%'); rerender(); },
  'reg-trpct': el => { const tr = travelById(el.dataset.id); modal({ title: 'Fee % · ' + tr.name, body: fields([{ k: 'pct', label: L3(['Fee untuk Travel ini (%) — kosongkan untuk default', 'Fee for this Travel (%) — blank for default', 'النسبة']), type: 'number', min: 0, max: 100, def: tr.regPct != null ? tr.regPct : '' }], 'rt-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="reg-trpct-go" data-id="${tr.id}">${t('save')}</button>` }); },
  'reg-trpct-go': el => { const tr = travelById(el.dataset.id); const v = formVals([{ k: 'pct', type: 'number' }], 'rt-'); if (!v) return; if (v.pct !== '' && (v.pct < 0 || v.pct > 100)) return toast('bad', '0–100%', ''); const prev = regPctFor(tr); tr.regPct = v.pct === '' ? null : v.pct; audit('Admin Pusat', 'registration_fee.pct.override', 'Travel/' + tr.id, 'success', { before: prev + '%', after: regPctFor(tr) + '%' }); partyNotify([ntKey('travel', tr.id)], 'payment', 'info', L3(['Fee Segaloka pendaftaran: ', 'Segaloka registration fee: ', 'الرسوم: ']) + regPctFor(tr) + '%', '', { travel: '/p/travel/mitra' }); closeOverlays(); rerender(); }
});
function regAdminPanel() { const tot = REG_FEES.reduce((s, r) => s + r.amount, 0), seg = REG_FEES.reduce((s, r) => s + r.segFee, 0); const trs = TRAVELS.filter(tr => regFeeFor(tr, 'mitra') || regFeeFor(tr, 'agen') || tr.regPct != null);
  return `<section class="panel" style="margin-bottom:14px"><div class="panel-h"><h3>${ic('percent', 'sm')}${L3(['Fee pendaftaran Mitra & Agen', 'Partner & Agent registration fees', 'رسوم التسجيل'])}</h3>${permBtn('finance.withdrawal', ic('sliders', 'sm') + L3(['Fee default ', 'Default fee ', 'الافتراضي ']) + REGCFG.pct + '%', 'data-act="reg-cfg" data-mut', 'sm')}</div><div class="panel-b">${kpiRow([{ k: L3(['Total pembayaran pendaftaran', 'Registration payments', 'المدفوعات']), v: money(tot) }, { k: L3(['Pendapatan Segaloka', 'Segaloka revenue', 'إيراد سيجالوكا']), v: money(seg) }, { k: L3(['Pendaftaran berbayar', 'Paid registrations', 'مدفوعة']), v: fN(REG_FEES.length) }])}
  <div style="margin-top:10px">${tbl(['Travel', L3(['Biaya Mitra', 'Partner fee', 'الشريك']), L3(['Biaya Agen', 'Agent fee', 'الوكيل']), 'Fee %', ''], trs.map(tr => `<tr><td>${esc(tr.name)}</td><td class="r tnum">${regFeeFor(tr, 'mitra') ? money(regFeeFor(tr, 'mitra')) : L3(['Gratis', 'Free', 'مجاني'])}</td><td class="r tnum">${regFeeFor(tr, 'agen') ? money(regFeeFor(tr, 'agen')) : L3(['Gratis', 'Free', 'مجاني'])}</td><td class="r tnum">${regPctFor(tr)}%${tr.regPct != null ? ' *' : ''}</td><td class="r">${permBtn('finance.withdrawal', L3(['Ubah %', 'Change %', 'تغيير']), `data-act="reg-trpct" data-id="${tr.id}" data-mut`, 'sm')}</td></tr>`), L3(['Belum ada Travel yang memasang biaya pendaftaran', 'No Travel charges registration fees yet', 'لا أحد']))}</div>
  ${REG_FEES.length ? `<div style="margin-top:10px">${tbl(['ID', L3(['Pendaftar', 'Registrant', 'المسجل']), 'Travel', 'Rp', 'Segaloka', L3(['Waktu', 'Time', 'الوقت'])], REG_FEES.slice().sort((a, b) => b.ts - a.ts).slice(0, 10).map(r => `<tr><td class="mono">${r.id}</td><td>${esc(r.name)} <span class="chip">${r.kind}</span></td><td>${esc((travelById(r.travel) || {}).name || r.travel)}</td><td class="r tnum">${money(r.amount)}</td><td class="r tnum">${money(r.segFee)} · ${r.pct}%</td><td>${rel(r.ts)}</td></tr>`))}</div>` : ''}</div></section>`; }
[['/p/travel/mitra', () => regTravelPanel(me('travel'))], ['/agen', regAdminPanel], ['/mitra', regAdminPanel]].forEach(([pat, blk]) => { const R = ROUTES.find(x => x.pattern === pat); if (!R) return; const prev = R.fn; reroute(pat, p => { const out = prev(p); if (!out || !out.html) return out; const i = out.html.indexOf('</div>', out.html.indexOf('class="phead')) ; const anchor = out.html.indexOf('<div class="chain"') > 0 ? out.html.indexOf('<div class="chain"') : out.html.indexOf('<section'); const k = anchor > 0 ? anchor : i + 6; out.html = out.html.slice(0, k) + blk() + out.html.slice(k); return out; }); });
