/* =====================================================================
   SETELAH BERANGKAT: tidak ada refund, hanya ulasan.
   - Booking berstatus Berangkat / Selesai tidak bisa dibatalkan atau direfund
     (dijaga di semua pintu: admin, Travel, aplikasi pengguna).
   - Pengguna memberi rating & ulasan untuk Travel dan paket yang dipilih.
   - Travel membalas ulasan; admin dapat menyembunyikan ulasan yang melanggar.
   ===================================================================== */
const REVIEWS = [];
const NO_REFUND = ['departed', 'completed'];
const refundBlocked = b => b && NO_REFUND.includes(b.state);
const blockMsg = () => toast('warn', L3(['Tidak bisa refund / batal', 'Refund / cancel not allowed', 'لا يمكن الاسترداد']), L3(['Jamaah sudah berangkat — yang tersedia hanya ulasan.', 'The pilgrim has departed — only a review is available.', 'بعد السفر: التقييم فقط.']));
['bk-cancel', 'bk-refund'].forEach(k => { const f = A[k]; if (f) A[k] = el => { if (refundBlocked(bookingById(el.dataset.id))) return blockMsg(); return f(el); }; });
if (A['pay-refund']) { const f = A['pay-refund']; A['pay-refund'] = el => { const p = PAYMENTS.find(x => x.id === el.dataset.id); if (p && refundBlocked(bookingById(p.booking))) return blockMsg(); return f(el); }; }

/* pengguna: ajukan pembatalan/refund (hanya sebelum berangkat) */
A['u-cancel'] = el => { const u = me('traveler'); const b = bookingById(el.dataset.id); if (!b || b.traveler !== u.id) return; if (refundBlocked(b)) return blockMsg(); if (BK_EXC.includes(b.state)) return;
  confirmAction({ title: (b.paid ? L3(['Ajukan refund', 'Request refund', 'طلب استرداد']) : L3(['Batalkan booking', 'Cancel booking', 'إلغاء الحجز'])) + ' · ' + b.id, desc: b.paid ? L3(['Dana ', 'Your ', 'المبلغ ']) + '<b>' + money(b.paid, true) + '</b>' + L3([' akan diproses refund sesuai kebijakan Travel. Travel & Finance akan meninjau.', ' will be refunded per the Travel’s policy after review.', ' سيُراجع.']) : L3(['Seat dilepas dan tagihan dibatalkan.', 'Seats are released and invoices cancelled.', 'تُحرر المقاعد.']), tone: 'danger', label: b.paid ? L3(['Ajukan refund', 'Request refund', 'طلب']) : L3(['Batalkan', 'Cancel', 'إلغاء']), resource: 'Booking/' + b.id, onOk: r => {
    const prev = b.state; b.prevState = prev; b.state = b.paid ? 'refund_requested' : 'cancelled'; PAYMENTS.filter(x => x.booking === b.id && x.status === 'pending').forEach(x => x.status = 'expired');
    if (b.paid) REFUNDS.unshift({ id: uid('RF'), booking: b.id, travel: b.travel, amount: b.paid, reason: r, state: 'pending', ts: nowTs(), by: u.name });
    recompute(); audit(u.name, b.paid ? 'booking.refund_request' : 'booking.cancel', 'Booking/' + b.id, 'success', { source: 'Aplikasi Pengguna', before: prev, after: b.state, reason: r });
    pNotif('booking', 'warn', b.paid ? L3(['Permintaan refund', 'Refund request', 'طلب استرداد']) : L3(['Booking dibatalkan pengguna', 'Booking cancelled by user', 'أُلغي']), b.id + ' · ' + u.name, '/booking/' + b.id);
    partyNotify([ntKey('travel', b.travel), b.mitra && ntKey('mitra', b.mitra), b.agen && ntKey('agen', b.agen)], 'payment', 'warn', b.paid ? L3(['Pengajuan refund dari jamaah', 'Refund request from pilgrim', 'طلب استرداد']) : L3(['Booking dibatalkan jamaah', 'Booking cancelled by pilgrim', 'أُلغي']), b.id + ' · ' + u.name + (b.paid ? ' · ' + money(b.paid) + ' · ' + r : ''), { travel: '/p/travel/bookings/' + b.id });
    toast('ok', stLbl(b.state), b.id); rerender(); } }); };

/* ---------- ulasan ---------- */
const stars = (n, size) => `<span aria-label="${n}/5" style="color:#F5A524;letter-spacing:1px;font-size:${size || 14}px">${'★'.repeat(Math.round(n || 0))}<span style="color:var(--line-strong)">${'★'.repeat(5 - Math.round(n || 0))}</span></span>`;
const pubReviews = () => REVIEWS.filter(r => r.state !== 'hidden');
const avgOf = (L, k) => L.length ? Math.round(L.reduce((s, r) => s + (+r[k] || 0), 0) / L.length * 10) / 10 : null;
const reviewOf = b => REVIEWS.find(r => r.booking === b.id);
const RATE_OPTS = [[5, '★★★★★ · 5'], [4, '★★★★ · 4'], [3, '★★★ · 3'], [2, '★★ · 2'], [1, '★ · 1']];
function reviewCard(r, opts) { opts = opts || {}; const tr = travelById(r.travel) || {}; const pk = pkgById(r.pkg) || {};
  return `<div style="border:1px solid var(--line);border-radius:10px;padding:12px;margin-bottom:10px${r.state === 'hidden' ? ';opacity:.55' : ''}"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><b>${esc(trvName(r.traveler))}</b><span class="muted" style="font-size:12px">${rel(r.ts)}${r.edited ? ' · ' + L3(['diubah', 'edited', 'معدل']) : ''}</span><span style="flex:1"></span>${r.state === 'hidden' ? st('inactive') : ''}</div>
  <div style="display:flex;gap:14px;flex-wrap:wrap;margin-top:6px;font-size:12.5px"><span>Travel ${stars(r.rTravel)}</span><span>${L3(['Paket', 'Package', 'الباقة'])} ${stars(r.rPkg)}</span></div>
  ${opts.showPkg ? `<div class="muted" style="font-size:12px;margin-top:4px">${esc(tr.name || '')} · ${esc(pk.name || '')}</div>` : ''}
  <p style="margin:8px 0 0;white-space:pre-wrap">${esc(r.text)}</p>
  ${r.reply ? `<div style="margin-top:10px;padding:8px 10px;border-inline-start:3px solid var(--accent);background:var(--surface-2);border-radius:6px;font-size:13px"><b>${esc(tr.name || 'Travel')}</b> <span class="muted" style="font-size:11.5px">${rel(r.replyTs)}</span><br>${esc(r.reply)}</div>` : ''}
  ${r.state === 'hidden' && r.hideReason ? `<div class="muted" style="font-size:12px;margin-top:6px">${L3(['Disembunyikan: ', 'Hidden: ', 'مخفي: ']) + esc(r.hideReason)}</div>` : ''}
  ${opts.actions || ''}</div>`; }
const RV_FORM = r => [{ k: 'rTravel', label: L3(['Rating Travel', 'Travel rating', 'تقييم الشركة']), type: 'select', options: RATE_OPTS, def: r ? r.rTravel : 5 }, { k: 'rPkg', label: L3(['Rating paket', 'Package rating', 'تقييم الباقة']), type: 'select', options: RATE_OPTS, def: r ? r.rPkg : 5 }, { k: 'text', label: L3(['Ulasan Anda', 'Your review', 'تقييمك']), type: 'textarea', req: true, def: r ? r.text : '' }];
Object.assign(A, {
  'rv-new': el => { const u = me('traveler'); const b = bookingById(el.dataset.id); if (!b || b.traveler !== u.id || !refundBlocked(b)) return; const r = reviewOf(b);
    modal({ title: (r ? L3(['Ubah ulasan', 'Edit review', 'تعديل']) : L3(['Beri ulasan', 'Write a review', 'اكتب تقييماً'])) + ' · ' + ((pkgById(b.pkg) || {}).name || ''), body: fields(RV_FORM(r), 'rv-') + `<p class="muted" style="font-size:12px;margin:6px 0 0">${L3(['Ulasan tampil publik di halaman Travel & paket, atas nama Anda.', 'Your review is shown publicly on the Travel & package pages under your name.', 'يظهر للعامة.'])}</p>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="rv-save" data-id="${b.id}">${ic('send', 'sm')}${L3(['Kirim ulasan', 'Submit review', 'إرسال'])}</button>` }); },
  'rv-save': el => { const u = me('traveler'); const b = bookingById(el.dataset.id); if (!b || !refundBlocked(b)) return; const v = formVals(RV_FORM().map(f => ({ k: f.k, req: f.req })), 'rv-'); if (!v) return; if (String(v.text).trim().length < 10) { document.getElementById('rv-text').style.borderColor = 'var(--bad)'; toast('warn', L3(['Ulasan terlalu singkat', 'Review too short', 'قصير جداً']), L3(['Minimal 10 karakter', 'At least 10 characters', '10 أحرف'])); return; }
    let r = reviewOf(b); const isNew = !r; if (!r) { r = { id: uid('REV'), booking: b.id, traveler: u.id, travel: b.travel, pkg: b.pkg, ts: nowTs(), state: 'published' }; REVIEWS.unshift(r); } else { r.edited = nowTs(); }
    Object.assign(r, { rTravel: +v.rTravel, rPkg: +v.rPkg, text: String(v.text).trim() }); recompute();
    audit(u.name, isNew ? 'review.create' : 'review.update', 'Review/' + r.id, 'success', { source: 'Aplikasi Pengguna', after: r.rTravel + '★ travel · ' + r.rPkg + '★ paket' });
    partyNotify([ntKey('travel', b.travel)], 'marketplace', r.rTravel >= 4 ? 'ok' : r.rTravel <= 2 ? 'bad' : 'info', (isNew ? L3(['Ulasan baru ', 'New review ', 'تقييم جديد ']) : L3(['Ulasan diubah ', 'Review updated ', 'تم التعديل '])) + '★'.repeat(r.rTravel), trvName(u.id) + ' · ' + r.text.slice(0, 80), { travel: '/p/travel/reviews' });
    closeOverlays(); toast('ok', L3(['Terima kasih atas ulasan Anda', 'Thanks for your review', 'شكراً لتقييمك']), ''); rerender(); },
  'rv-reply': el => { const r = REVIEWS.find(x => x.id === el.dataset.id); if (!r) return; modal({ title: L3(['Balas ulasan', 'Reply to review', 'الرد']), body: reviewCard(r) + fields([{ k: 'reply', label: L3(['Balasan Anda (publik)', 'Your reply (public)', 'ردك']), type: 'textarea', req: true, def: r.reply || '' }], 'rr-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="rv-reply-go" data-id="${r.id}">${L3(['Kirim balasan', 'Send reply', 'إرسال'])}</button>` }); },
  'rv-reply-go': el => { const r = REVIEWS.find(x => x.id === el.dataset.id); const tr = me('travel'); if (!r || r.travel !== tr.id) return; const v = formVals([{ k: 'reply', req: true }], 'rr-'); if (!v) return; r.reply = v.reply.trim(); r.replyTs = nowTs(); pAudit('travel', 'review.reply', 'Review/' + r.id); partyNotify([ntKey('traveler', r.traveler)], 'marketplace', 'info', tr.name + L3([' membalas ulasan Anda', ' replied to your review', ' رد على تقييمك']), r.reply.slice(0, 80), { traveler: '/p/traveler/bookings/' + r.booking }); closeOverlays(); toast('ok', L3(['Balasan terkirim', 'Reply sent', 'أُرسل']), ''); rerender(); },
  'rv-mod': el => { const r = REVIEWS.find(x => x.id === el.dataset.id); if (!r) return; const hide = r.state !== 'hidden'; confirmAction({ title: (hide ? L3(['Sembunyikan ulasan', 'Hide review', 'إخفاء']) : L3(['Tampilkan lagi', 'Show again', 'إظهار'])) + ' · ' + r.id, desc: esc(r.text.slice(0, 160)), tone: hide ? 'danger' : 'primary', reason: hide, resource: 'Review/' + r.id, onOk: reason => { r.state = hide ? 'hidden' : 'published'; r.hideReason = hide ? reason : ''; recompute(); audit('Admin Pusat', hide ? 'review.hide' : 'review.show', 'Review/' + r.id, 'success', { reason }); if (hide) partyNotify([ntKey('traveler', r.traveler), ntKey('travel', r.travel)], 'marketplace', 'warn', L3(['Ulasan disembunyikan admin', 'Review hidden by admin', 'أُخفي التقييم']), reason, { traveler: '/p/traveler/bookings/' + r.booking, travel: '/p/travel/reviews' }); toast('ok', stLbl(hide ? 'inactive' : 'active'), r.id); rerender(); } }); }
});

/* aplikasi pengguna: booking — refund sebelum berangkat, ulasan setelah berangkat */
(() => { const R = ROUTES.find(x => x.pattern === '/p/traveler/bookings/:id'); if (!R) return; const prev = R.fn;
  reroute('/p/traveler/bookings/:id', p => { const out = prev(p); const b = bookingById(p.id); const u = me('traveler'); if (!b || !u || b.traveler !== u.id || !out || !out.html) return out;
    const r = reviewOf(b); let extra = '';
    if (refundBlocked(b)) extra = `<div class="panel" style="padding:12px;margin-top:12px"><div class="eyebrow">${L3(['Ulasan', 'Review', 'التقييم'])}</div>${r ? reviewCard(r) + `<button class="btn sm" data-act="rv-new" data-id="${b.id}">${ic('note', 'sm')}${L3(['Ubah ulasan', 'Edit review', 'تعديل'])}</button>` : `<p class="muted" style="font-size:12.5px;margin:6px 0 10px">${L3(['Perjalanan Anda sudah berjalan. Bagikan pengalaman Anda tentang Travel dan paket ini.', 'Your trip is under way. Share your experience with this Travel and package.', 'شارك تجربتك.'])}</p><button class="btn primary" style="width:100%;justify-content:center" data-act="rv-new" data-id="${b.id}">${ic('star')}${L3(['Beri ulasan', 'Write a review', 'اكتب تقييماً'])}</button>`}<div class="muted" style="font-size:11.5px;margin-top:8px">${ic('info', 'sm')} ${L3(['Setelah berangkat, pembatalan & refund tidak tersedia.', 'After departure, cancellation & refunds are not available.', 'لا استرداد بعد السفر.'])}</div></div>`;
    else if (!BK_EXC.includes(b.state)) extra = `<button class="btn badb" style="width:100%;justify-content:center;margin-top:12px" data-act="u-cancel" data-id="${b.id}">${ic('ban')}${b.paid ? L3(['Ajukan refund', 'Request refund', 'طلب استرداد']) : L3(['Batalkan booking', 'Cancel booking', 'إلغاء الحجز'])}</button>`;
    else extra = `<div class="panel" style="padding:12px;margin-top:12px">${st(b.state)} <span class="muted" style="font-size:12.5px">${esc((REFUNDS.find(x => x.booking === b.id) || {}).reason || '')}</span></div>`;
    const anchor = '<a class="btn" style="width:100%;justify-content:center;margin-top:10px" href="#/p/traveler/chat">'; out.html = out.html.includes(anchor) ? out.html.replace(anchor, extra + anchor) : out.html; return out; }); })();

/* aplikasi pengguna: halaman paket menampilkan rating & ulasan */
(() => { const R = ROUTES.find(x => x.pattern === '/p/traveler/pkg/:id'); if (!R) return; const prev = R.fn;
  reroute('/p/traveler/pkg/:id', p => { const out = prev(p); const pk = pkgById(p.id); if (!pk || !out || !out.html) return out; const L = pubReviews().filter(r => r.pkg === pk.id || r.travel === pk.travel).sort((a, b) => (b.pkg === pk.id) - (a.pkg === pk.id) || b.ts - a.ts); const T = pubReviews().filter(r => r.travel === pk.travel);
    const blk = `<div class="eyebrow" style="margin:14px 0 6px">${L3(['Ulasan jamaah', 'Pilgrim reviews', 'التقييمات'])} · ${T.length}</div>${T.length ? `<div style="display:flex;gap:14px;font-size:13px;margin-bottom:8px"><span>Travel ${stars(avgOf(T, 'rTravel'))} <b>${avgOf(T, 'rTravel')}</b></span>${L.some(r => r.pkg === pk.id) ? `<span>${L3(['Paket', 'Package', 'الباقة'])} ${stars(avgOf(L.filter(r => r.pkg === pk.id), 'rPkg'))}</span>` : ''}</div>` + L.slice(0, 5).map(r => reviewCard(r)).join('') : `<div class="muted" style="font-size:12.5px">${L3(['Belum ada ulasan', 'No reviews yet', 'لا تقييمات'])}</div>`}`;
    const anchor = '<div class="field" style="margin-top:14px"><label for="u-pax">'; out.html = out.html.replace(anchor, blk + anchor); return out; }); })();

/* portal Travel: ulasan */
PNAV.travel.splice(PNAV.travel.findIndex(x => x[2] === '/finance'), 0, ['star', ['Ulasan', 'Reviews', 'التقييمات'], '/reviews']);
route('/p/travel/reviews', () => { const tr = me('travel'); const L = REVIEWS.filter(r => r.travel === tr.id).sort((a, b) => b.ts - a.ts); const P = L.filter(r => r.state !== 'hidden');
  return { html: `<div class="page">${pHead('travel', L3(['Ulasan', 'Reviews', 'التقييمات']), L3(['Ulasan dari jamaah yang sudah berangkat. Balasan Anda tampil publik di bawah ulasan.', 'Reviews from pilgrims who have departed. Your replies are shown publicly under each review.', 'تقييمات المعتمرين.']))}
  ${kpiRow([{ k: L3(['Rating Travel', 'Travel rating', 'تقييم الشركة']), v: P.length ? avgOf(P, 'rTravel') + ' / 5' : '—', icon: 'star' }, { k: L3(['Rating paket', 'Package rating', 'تقييم الباقات']), v: P.length ? avgOf(P, 'rPkg') + ' / 5' : '—', icon: 'package' }, { k: L3(['Jumlah ulasan', 'Reviews', 'العدد']), v: fN(P.length), icon: 'msg' }, { k: L3(['Belum dibalas', 'Awaiting reply', 'بلا رد']), v: fN(P.filter(r => !r.reply).length), icon: 'clock' }])}
  <section class="panel" style="margin-top:14px"><div class="panel-b">${L.length ? L.map(r => reviewCard(r, { showPkg: true, actions: r.state !== 'hidden' ? `<div style="margin-top:8px"><button class="btn sm" data-act="rv-reply" data-id="${r.id}">${ic('msg', 'sm')}${r.reply ? L3(['Ubah balasan', 'Edit reply', 'تعديل الرد']) : L3(['Balas', 'Reply', 'رد'])}</button></div>` : '' })).join('') : stateBlock('empty', { title: L3(['Belum ada ulasan', 'No reviews yet', 'لا تقييمات']) })}</div></section></div>` }; });

/* admin: Marketplace › Ulasan */
route('/marketplace/reviews', () => { const L = REVIEWS.slice().sort((a, b) => b.ts - a.ts); const P = pubReviews();
  return { html: `<div class="page">${phead({ crumbs: [[t('g_mp'), '/marketplace'], [t('mp_rev'), '']], title: t('mp_rev'), desc: L3(['Ulasan jamaah untuk Travel & paket (hanya dari booking yang sudah berangkat). Admin dapat menyembunyikan ulasan yang melanggar kebijakan.', 'Pilgrim reviews for Travels & packages (only from departed bookings). Admins can hide reviews that violate policy.', 'التقييمات.']) })}
  ${kpiRow([{ k: L3(['Ulasan tampil', 'Visible reviews', 'ظاهرة']), v: fN(P.length) }, { k: L3(['Rata-rata Travel', 'Avg Travel', 'متوسط']), v: P.length ? avgOf(P, 'rTravel') + ' / 5' : '—' }, { k: L3(['Rata-rata paket', 'Avg package', 'متوسط']), v: P.length ? avgOf(P, 'rPkg') + ' / 5' : '—' }, { k: L3(['Disembunyikan', 'Hidden', 'مخفية']), v: fN(L.length - P.length) }])}
  <section class="panel" style="margin-top:14px"><div class="panel-b">${L.length ? L.map(r => reviewCard(r, { showPkg: true, actions: `<div style="margin-top:8px">${permBtn('marketplace.manage', r.state === 'hidden' ? L3(['Tampilkan lagi', 'Show again', 'إظهار']) : L3(['Sembunyikan', 'Hide', 'إخفاء']), `data-act="rv-mod" data-id="${r.id}" data-mut`, 'sm ' + (r.state === 'hidden' ? '' : 'badb'))}</div>` })).join('') : stateBlock('empty', { title: L3(['Belum ada ulasan', 'No reviews yet', 'لا تقييمات']) })}</div></section></div>` }; });

/* rating Travel & paket dihitung dari ulasan nyata */
const _recomputeBase = recompute;
recompute = function () { _recomputeBase.apply(this, arguments); const P = pubReviews(); TRAVELS.forEach(tr => { const L = P.filter(r => r.travel === tr.id); tr.rating = L.length ? avgOf(L, 'rTravel') : '—'; tr.reviews = L.length; }); PACKAGES.forEach(pk => { const L = P.filter(r => r.pkg === pk.id); pk.rating = L.length ? avgOf(L, 'rPkg') : null; pk.reviews = L.length; }); };

/* ---------- Refund: Travel diberi tahu & memproses ---------- */
const refundOf = b => REFUNDS.find(x => x.booking === b.id && x.state === 'pending') || REFUNDS.find(x => x.booking === b.id);
function refundPanel(b) { const r = refundOf(b); if (!r || b.state !== 'refund_requested' && r.state === 'pending') return ''; const proof = r.proof && UPLOADS.find(u => u.id === r.proof);
  return `<section class="panel" style="margin-bottom:14px;border-color:var(--warn-line, var(--line))"><div class="panel-h"><h3>${ic('undo', 'sm')}${L3(['Permintaan refund', 'Refund request', 'طلب استرداد'])} · <span class="mono">${r.id}</span></h3>${st(r.state === 'pending' ? (r.approved ? 'approved' : 'pending') : r.state)}</div><div class="panel-b"><dl class="dl"><dt>${L3(['Diajukan', 'Requested', 'قُدم'])}</dt><dd>${esc(r.by || trvName(b.traveler))} · ${fDT(r.ts)}</dd><dt>${L3(['Alasan', 'Reason', 'السبب'])}</dt><dd>${esc(r.reason || '—')}</dd><dt>${L3(['Sudah dibayar', 'Paid', 'مدفوع'])}</dt><dd class="tnum">${money(b.paid, true)}</dd>${r.approved ? `<dt>${L3(['Disetujui', 'Approved', 'معتمد'])}</dt><dd class="tnum"><b>${money(r.approved, true)}</b>${r.note ? ' · ' + esc(r.note) : ''}</dd>` : ''}${r.refRef ? `<dt>Ref</dt><dd class="mono">${esc(r.refRef)}</dd>` : ''}${r.rejectReason ? `<dt>${L3(['Ditolak', 'Rejected', 'مرفوض'])}</dt><dd>${esc(r.rejectReason)}</dd>` : ''}</dl>${proof ? upRow(proof) : ''}
  ${r.state === 'pending' ? `<div class="actions" style="margin-top:10px;flex-wrap:wrap">${r.approved ? `<button class="btn primary" data-act="rf-paid" data-id="${r.id}">${ic('check')}${L3(['Tandai dana sudah dikembalikan', 'Mark refunded', 'تم الإرجاع'])}</button>` : `<button class="btn primary" data-act="rf-approve" data-id="${r.id}">${ic('check')}${L3(['Setujui refund', 'Approve refund', 'موافقة'])}</button><button class="btn badb" data-act="rf-reject" data-id="${r.id}">${L3(['Tolak refund', 'Reject refund', 'رفض'])}</button>`}</div>` : ''}</div></section>`; }
Object.assign(A, {
  'rf-approve': el => { const r = REFUNDS.find(x => x.id === el.dataset.id); const b = bookingById(r.booking); modal({ title: L3(['Setujui refund · ', 'Approve refund · ', 'موافقة · ']) + r.id, body: `<p class="muted" style="margin-top:0">${L3(['Sudah dibayar jamaah: ', 'Paid by pilgrim: ', 'مدفوع: ']) + '<b>' + money(b.paid, true) + '</b>'}</p>` + fields([{ k: 'amount', label: L3(['Jumlah dikembalikan (Rp)', 'Refund amount (Rp)', 'المبلغ']), type: 'number', req: true, min: 0, max: b.paid, step: 10000, def: b.paid }, { k: 'note', label: L3(['Rincian potongan / catatan untuk jamaah', 'Deduction details / note to pilgrim', 'ملاحظة']), type: 'textarea' }], 'ra-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="rf-approve-go" data-id="${r.id}">${t('approve')}</button>` }); },
  'rf-approve-go': el => { const r = REFUNDS.find(x => x.id === el.dataset.id); const b = bookingById(r.booking); const v = formVals([{ k: 'amount', type: 'number', req: true }, { k: 'note' }], 'ra-'); if (!v) return; if (v.amount < 0 || v.amount > b.paid) { document.getElementById('ra-amount').style.borderColor = 'var(--bad)'; toast('bad', L3(['Melebihi yang dibayar', 'Exceeds amount paid', 'يتجاوز']), money(b.paid, true)); return; }
    r.approved = v.amount; r.note = v.note; r.amount = v.amount; r.approvedAt = nowTs(); pAudit('travel', 'refund.approve', 'Refund/' + r.id, { after: money(v.amount), reason: v.note }); partyNotify([ntKey('traveler', b.traveler)], 'payment', 'ok', L3(['Refund disetujui Travel', 'Refund approved by Travel', 'تمت الموافقة']), money(v.amount) + (v.note ? ' · ' + v.note : ''), { traveler: '/p/traveler/bookings/' + b.id }); pNotif('payment', 'info', L3(['Refund disetujui Travel', 'Refund approved by Travel', 'موافقة']), b.id + ' · ' + money(v.amount), '/finance/refund'); closeOverlays(); toast('ok', L3(['Refund disetujui', 'Refund approved', 'تمت الموافقة']), money(v.amount)); rerender(); },
  'rf-reject': el => { const r = REFUNDS.find(x => x.id === el.dataset.id); const b = bookingById(r.booking); confirmAction({ title: L3(['Tolak refund · ', 'Reject refund · ', 'رفض · ']) + r.id, desc: L3(['Booking kembali ke status sebelumnya.', 'The booking returns to its previous status.', 'يعود الحجز.']), tone: 'danger', label: t('reject'), resource: 'Refund/' + r.id, onOk: why => { r.state = 'rejected'; r.rejectReason = why; const prev = b.state; b.state = b.prevState && !BK_EXC.includes(b.prevState) ? b.prevState : (b.paid >= b.total ? 'confirmed' : 'partially_paid'); pAudit('travel', 'refund.reject', 'Refund/' + r.id, { before: prev, after: b.state, reason: why }); partyNotify([ntKey('traveler', b.traveler)], 'payment', 'bad', L3(['Refund ditolak Travel', 'Refund rejected by Travel', 'رُفض']), why, { traveler: '/p/traveler/bookings/' + b.id }); rerender(); } }); },
  'rf-paid': el => { const r = REFUNDS.find(x => x.id === el.dataset.id); modal({ title: L3(['Tandai sudah dikembalikan · ', 'Mark refunded · ', 'تم الإرجاع · ']) + r.id, body: `<p class="muted" style="margin-top:0">${money(r.approved, true)}</p>` + fields([{ k: 'ref', label: L3(['No. referensi transfer', 'Transfer reference', 'المرجع']), req: true }], 'rp-') + `<div class="field"><label for="rp-file">${L3(['Bukti transfer', 'Transfer proof', 'الإثبات'])} *</label><input type="file" id="rp-file" accept="image/*,.pdf"></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="rf-paid-go" data-id="${r.id}">${t('save')}</button>` }); },
  'rf-paid-go': async el => { const r = REFUNDS.find(x => x.id === el.dataset.id); const b = bookingById(r.booking); const v = formVals([{ k: 'ref', req: true }], 'rp-'); if (!v) return; const f = document.getElementById('rp-file').files[0]; if (!f) { toast('warn', L3(['Unggah bukti transfer', 'Upload transfer proof', 'ارفع الإثبات']), ''); return; }
    try { const up = await saveUpload(f, { ref: r.id, booking: b.id, traveler: b.traveler, travel: b.travel, kind: 'refundproof', by: me('travel').name, byWs: 'travel', state: 'verified' }); r.proof = up.id; r.refRef = v.ref; r.state = 'refunded'; r.refundedAt = nowTs(); const prev = b.state; b.state = 'refunded'; PAYMENTS.filter(x => x.booking === b.id && x.status === 'paid').forEach(x => x.status = 'refunded'); const pk = pkgById(b.pkg); if (pk) recompute();
      pAudit('travel', 'refund.paid', 'Refund/' + r.id, { before: prev, after: 'refunded', reason: 'Ref ' + v.ref }); partyNotify([ntKey('traveler', b.traveler)], 'payment', 'ok', L3(['Dana refund sudah dikirim', 'Refund sent', 'أُرسل المبلغ']), money(r.approved) + ' · Ref ' + v.ref, { traveler: '/p/traveler/bookings/' + b.id }); closeOverlays(); toast('ok', 'Refund → ' + stLbl('refunded'), v.ref); rerender(); } catch (e) { toast('bad', 'Upload', String(e.message || e)); } }
});
(() => { const R = ROUTES.find(x => x.pattern === '/p/travel/bookings/:id'); if (!R) return; const prev = R.fn;
  reroute('/p/travel/bookings/:id', p => { const out = prev(p); const b = bookingById(p.id); if (!b || !out || !out.html || b.travel !== (me('travel') || {}).id) return out; const pnlH = refundPanel(b); if (pnlH) out.html = out.html.replace('<section class="panel" style="padding:12px 14px;margin-bottom:14px">', pnlH + '<section class="panel" style="padding:12px 14px;margin-bottom:14px">'); return out; }); })();
