/* =====================================================================
   SEGADEALS — "reverse marketplace"
   Pengguna mengajukan permintaan (jenis, tujuan, bulan, pax, budget)  →
   Travel berizin (Umrah→PPIU, Haji→PIHK, Tour→BPW) mengirim penawaran berbasis paket published  →
   Pengguna memilih satu penawaran  →  Booking (source "SegaDeals") + tagihan DP 30%  →
   Admin memantau & memoderasi di Marketplace › SegaDeals.
   ===================================================================== */
Object.assign(STATUS, {
  offered: ['info', 'msg', 'Ada penawaran', 'Offers received', 'وصلت عروض'],
  accepted: ['ok', 'check', 'Diterima', 'Accepted', 'مقبول'],
  sent: ['info', 'send', 'Terkirim', 'Sent', 'مرسل'],
  withdrawn: ['neu', 'undo', 'Ditarik', 'Withdrawn', 'مسحوب']
});
const SD_TYPES = ['Umrah', 'Haji', 'Halal Tour', 'Tour'];
const SD_DEST = { Umrah: ['Makkah & Madinah', 'Umrah Plus Turki', 'Umrah Plus Thaif', 'Umrah Plus Dubai'], Haji: ['Haji Khusus', 'Haji Furoda'], 'Halal Tour': ['Jepang', 'Turki', 'Korea Selatan', 'Uzbekistan'], Tour: ['Eropa Barat', 'Mesir & Yordania'] };
const SD_DP = 0.3;
const SD_REQ = [];
const SD_OFF = [];
(() => {
  const months = ['2026-12', '2027-01', '2027-02', '2027-03', '2027-04', '2027-05'];
  const types = ['Umrah', 'Umrah', 'Halal Tour', 'Umrah', 'Haji', 'Umrah', 'Tour', 'Umrah', 'Halal Tour', 'Umrah', 'Umrah', 'Halal Tour'];
  const states = ['offered', 'open', 'offered', 'offered', 'open', 'expired', 'offered', 'cancelled', 'open', 'offered', 'offered', 'open'];
  const notes = ['Ada 1 lansia, mohon hotel dekat Masjidil Haram.', 'Ingin berangkat dari Makassar, keluarga 4 orang.', 'Butuh makanan halal terjamin & mushola di itinerary.', 'Budget fleksibel bila hotel bintang 5.', 'Mohon dibantu info kuota & persyaratan.', '', 'Honeymoon, kamar double.', '', 'Rombongan majelis taklim.', 'Pertama kali umrah, perlu bimbingan manasik.', 'Minta pembimbing perempuan.', ''];
  types.forEach((tp, i) => {
    const u = TRAVELERS[(i * 7 + 2) % TRAVELERS.length]; const created = T0 - (i * 13 % 9 + 1) * D - i * 3600e3;
    const base = { Umrah: 33e6, Haji: 240e6, 'Halal Tour': 26e6, Tour: 38e6 }[tp];
    SD_REQ.push({ id: 'SDR-' + (5101 + i * 7), traveler: u.id, type: tp, dest: SD_DEST[tp][i % SD_DEST[tp].length], month: months[i % months.length], pax: [4, 2, 2, 1, 2, 3, 2, 5, 12, 1, 2, 3][i], budget: Math.round(base * (0.85 + (i % 4) * 0.07) / 1e5) * 1e5, city: u.city, notes: notes[i], created, expires: states[i] === 'expired' ? T0 - D : created + 10 * D, state: states[i] });
  });
  SD_REQ.forEach((r, ri_) => {
    if (!['offered', 'expired', 'cancelled'].includes(r.state)) return;
    const trs = TRAVELS.filter(tr => tr.op === 'active' && licOk(tr, r.type) && PACKAGES.some(p => p.travel === tr.id && p.cat === r.type && p.state === 'published'));
    const n = r.state === 'offered' ? 1 + ri_ % 3 : ri_ % 2;
    for (let k = 0; k < Math.min(n, trs.length); k++) {
      const tr = trs[(ri_ * 5 + k * 3) % trs.length]; if (SD_OFF.some(o => o.request === r.id && o.travel === tr.id)) continue;
      const pk = PACKAGES.find(p => p.travel === tr.id && p.cat === r.type && p.state === 'published');
      SD_OFF.push({ id: 'SDO-' + (7201 + SD_OFF.length * 3), request: r.id, travel: tr.id, pkg: pk.id, price: Math.round(r.budget * (0.92 + ((ri_ + k) % 5) * 0.04) / 1e5) * 1e5, includes: ['Tiket PP, hotel ★4 dekat masjid, visa, muthawwif', 'Tiket PP, hotel ★5, visa, city tour, perlengkapan', 'Tiket PP, hotel ★3, visa, handling bandara'][k % 3], note: k === 0 ? 'Harga sudah termasuk asuransi perjalanan.' : '', validUntil: r.expires - k * 3600e3, created: r.created + (k + 1) * 5 * 3600e3, state: r.state === 'offered' ? 'sent' : r.state === 'cancelled' ? 'withdrawn' : 'expired' });
    }
    if (r.state === 'offered' && !SD_OFF.some(o => o.request === r.id)) r.state = 'open';
  });
})();
const sdReq = id => SD_REQ.find(r => r.id === id);
const sdOffers = rid => SD_OFF.filter(o => o.request === rid);
const sdLive = r => ['open', 'offered'].includes(r.state);
/* permintaan & penawaran yang lewat masa berlaku ditandai expired saat dibaca */
function sdSweep() { const now = nowTs(); SD_REQ.forEach(r => { if (sdLive(r) && r.expires < now) { r.state = 'expired'; sdOffers(r.id).forEach(o => { if (o.state === 'sent') o.state = 'expired'; }); } }); SD_OFF.forEach(o => { if (o.state === 'sent' && o.validUntil < now) o.state = 'expired'; }); SD_REQ.forEach(r => { if (r.state === 'offered' && !sdOffers(r.id).some(o => o.state === 'sent')) r.state = 'open'; }); }
const sdEligible = (tr, r) => tr.op === 'active' && licOk(tr, r.type);
const sdBasePkgs = (tr, type) => PACKAGES.filter(p => p.travel === tr.id && p.cat === type && p.state === 'published' && p.seats - p.sold > 0);
const sdMonth = m => { const [y, mo] = String(m).split('-'); return fD(new Date(+y, +mo - 1, 15).getTime(), { month: 'long', year: 'numeric' }); };
const sdTitle = r => r.type + ' · ' + r.dest;
const sdOfferName = o => { const pk = o.pkg && pkgById(o.pkg); return pk ? pk.name : (o.custom && o.custom.name) || L3(['Paket khusus', 'Custom package', 'باقة مخصصة']); };
const sdOfferDep = o => { const pk = o.pkg && pkgById(o.pkg); return pk ? pk.dep : (o.custom && o.custom.dep) || nowTs(); };
/* paket privat dibuat saat pengguna memilih penawaran tanpa paket dasar */
function sdMakePackage(o, r) { const c = o.custom || {}; const p = { id: uid('PKG'), name: c.name || sdTitle(r), cat: r.type, travel: o.travel, price: o.price, seats: r.pax, sold: 0, dep: c.dep || nowTs() + 60 * D, state: 'draft', private: true, sdRequest: r.id, sdOffer: o.id, info: { duration: c.duration, hotel: c.hotel, airline: c.airline, includes: o.includes }, views30: 0, segadeal: true, created: nowTs() }; PACKAGES.unshift(p); audit('System', 'package.create_from_segadeals', 'Package/' + p.id, 'success', { source: 'SegaDeals · ' + r.id, after: p.name }); return p; }

/* ---------- Aplikasi Pengguna ---------- */
PNAV.traveler.splice(1, 0, ['tag', ['SegaDeals', 'SegaDeals', 'SegaDeals'], '/segadeals']);
route('/p/traveler/segadeals', () => { sdSweep(); const u = me('traveler'); const L = SD_REQ.filter(r => r.traveler === u.id).sort((a, b) => b.created - a.created);
  return { html: phone(`<div class="ph-top"><b style="font-size:17px">SegaDeals</b><div class="muted" style="font-size:12px">${L3(['Ajukan permintaan perjalanan — Travel berizin akan mengirim penawaran untuk Anda.', 'Submit a trip request — licensed Travels send you offers.', 'قدّم طلبك وستصلك عروض.'])}</div></div><div class="ph-body">
  <a class="btn primary" style="width:100%;justify-content:center;height:44px" href="#/p/traveler/segadeals/new">${ic('plus')}${L3(['Ajukan permintaan baru', 'Submit a new request', 'طلب جديد'])}</a>
  <div class="eyebrow" style="margin:14px 0 6px">${L3(['Permintaan saya', 'My requests', 'طلباتي'])} · ${L.length}</div>
  ${L.length ? L.map(r => { const n = sdOffers(r.id).filter(o => o.state === 'sent').length; return `<a class="ucard" href="#/p/traveler/segadeals/${r.id}"><div style="flex:1;min-width:0"><div style="display:flex;justify-content:space-between;gap:6px"><b>${esc(sdTitle(r))}</b>${st(r.state)}</div><div class="muted" style="font-size:12px;margin-top:2px">${esc(sdMonth(r.month))} · ${r.pax} pax · ${money(r.budget)}/pax</div><div style="font-size:12.5px;margin-top:6px;color:var(--accent-text)">${sdLive(r) ? (n ? n + ' ' + L3(['penawaran menunggu keputusan Anda', 'offers awaiting your decision', 'عروض بانتظارك']) : L3(['Menunggu penawaran Travel…', 'Waiting for Travel offers…', 'بانتظار العروض…'])) : r.state === 'accepted' ? L3(['Booking dibuat', 'Booking created', 'تم الحجز']) + ' · ' + esc(r.booking || '') : ''}</div></div></a>`; }).join('') : stateBlock('empty', { title: L3(['Belum ada permintaan', 'No requests yet', 'لا طلبات']), desc: L3(['Ceritakan perjalanan impian Anda, biar Travel yang menawarkan.', 'Describe your trip and let Travels make offers.', 'صف رحلتك.']) })}</div>`, '/segadeals') }; });
const SD_FORM = u => [{ k: 'type', label: L3(['Jenis perjalanan', 'Trip type', 'النوع']), type: 'select', options: SD_TYPES }, { k: 'dest', label: L3(['Tujuan / program', 'Destination / program', 'الوجهة']), req: true, def: 'Makkah & Madinah' }, { k: 'month', label: L3(['Bulan berangkat', 'Departure month', 'شهر السفر']), type: 'month', req: true, def: '2027-01' }, { k: 'pax', label: L3(['Jumlah jamaah', 'Travellers', 'العدد']), type: 'number', req: true, min: 1, max: 60, def: 2 }, { k: 'budget', label: L3(['Budget per orang (Rp)', 'Budget per person (Rp)', 'الميزانية للفرد']), type: 'number', req: true, min: 1000000, step: 500000, def: 32000000 }, { k: 'city', label: L3(['Kota keberangkatan', 'Departure city', 'مدينة المغادرة']), def: u.city }, { k: 'notes', label: L3(['Catatan untuk Travel', 'Notes for Travels', 'ملاحظات']), type: 'textarea', def: '' }];
route('/p/traveler/segadeals/new', () => { const u = me('traveler'); return { html: phone(`<div class="ph-top"><a href="#/p/traveler/segadeals" style="color:inherit">${icd('chevL', 'sm')}</a> <b>${L3(['Permintaan SegaDeals', 'SegaDeals request', 'طلب SegaDeals'])}</b></div><div class="ph-body">${fields(SD_FORM(u), 'sd-')}<div class="auditbox">${ic('shieldc')}<span>${L3(['Hanya Travel dengan izin sesuai (Umrah→PPIU, Haji→PIHK, Tour→BPW) yang dapat menawar. Data kontak Anda tidak dibagikan sampai Anda memilih penawaran.', 'Only Travels with the matching licence (Umrah→PPIU, Hajj→PIHK, Tour→BPW) can bid. Your contact details are not shared until you choose an offer.', 'فقط الشركات المرخصة.'])}</span></div><button class="btn primary" style="width:100%;justify-content:center;height:44px;margin-top:12px" data-act="sd-submit">${ic('send')}${L3(['Kirim permintaan', 'Submit request', 'إرسال'])}</button></div>`, '/segadeals'), mount() { const tp = document.getElementById('sd-type'), ds = document.getElementById('sd-dest'); tp.addEventListener('change', () => { ds.value = SD_DEST[tp.value][0]; }); } }; });
route('/p/traveler/segadeals/:id', p => { sdSweep(); const u = me('traveler'); const r = sdReq(p.id); if (!r || r.traveler !== u.id) return { html: phone(stateBlock('noperm', { desc: L3(['Permintaan ini bukan milik Anda.', 'This request is not yours.', 'ليس لك.']) }), '/segadeals') };
  const O = sdOffers(r.id).slice().sort((a, b) => (a.state === 'sent' ? 0 : 1) - (b.state === 'sent' ? 0 : 1) || a.price - b.price);
  return { html: phone(`<div class="ph-top"><a href="#/p/traveler/segadeals" style="color:inherit">${icd('chevL', 'sm')}</a> <b class="mono">${r.id}</b></div><div class="ph-body">
  <div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><b>${esc(sdTitle(r))}</b>${st(r.state)}</div>
  <dl class="dl" style="margin:10px 0"><dt>${L3(['Berangkat', 'Departure', 'المغادرة'])}</dt><dd>${esc(sdMonth(r.month))} · ${esc(r.city || '—')}</dd><dt>Pax</dt><dd>${r.pax}</dd><dt>Budget</dt><dd class="tnum">${money(r.budget, true)} / pax</dd><dt>${L3(['Berlaku s/d', 'Open until', 'صالح حتى'])}</dt><dd>${fDT(r.expires)}</dd>${r.notes ? `<dt>${L3(['Catatan', 'Notes', 'ملاحظات'])}</dt><dd>${esc(r.notes)}</dd>` : ''}</dl>
  ${r.state === 'accepted' && r.booking ? `<a class="btn primary" style="width:100%;justify-content:center" href="#/p/traveler/bookings/${r.booking}">${ic('calendar')}${L3(['Lihat booking & bayar DP', 'View booking & pay deposit', 'عرض الحجز'])} · ${r.booking}</a>` : ''}
  <div class="eyebrow" style="margin:14px 0 6px">${L3(['Penawaran Travel', 'Travel offers', 'عروض الشركات'])} · ${O.length}</div>
  ${O.length ? O.map(o => { const tr = travelById(o.travel); const pk = pkgById(o.pkg); return `<div class="panel" style="padding:12px;margin-bottom:10px"><div style="display:flex;justify-content:space-between;gap:8px;align-items:flex-start">${ent(tr.name, tr.lic.filter(l => ['verified', 'expiring'].includes(l.status)).map(l => l.type + ' ✓').join(' · ') || '—', tr.color)}${st(o.state)}</div><div style="display:flex;justify-content:space-between;align-items:flex-end;margin-top:10px"><div><div class="muted" style="font-size:12px">${L3(['Harga / pax', 'Price / pax', 'السعر للفرد'])}</div><b class="tnum" style="font-size:18px;color:var(--accent-text)">${money(o.price, true)}</b>${o.price <= r.budget ? ` <span class="chip" style="background:var(--ok-soft,rgba(16,185,129,.12));color:var(--ok)">${L3(['sesuai budget', 'within budget', 'ضمن الميزانية'])}</span>` : ''}</div><div class="muted tnum" style="font-size:12px;text-align:end">Total ${money(o.price * r.pax, true)}</div></div><div style="font-size:12.5px;margin-top:8px">${esc(sdOfferName(o))} · ${fD(sdOfferDep(o))}${o.custom && o.custom.duration ? ' · ' + o.custom.duration + ' ' + L3(['hari', 'days', 'يوم']) : ''}</div>${o.custom && (o.custom.hotel || o.custom.airline) ? `<div class="muted" style="font-size:12px;margin-top:2px">${esc([o.custom.hotel, o.custom.airline].filter(Boolean).join(' · '))}</div>` : ''}<div class="muted" style="font-size:12px;margin-top:2px">${esc(o.includes)}</div>${o.note ? `<div class="muted" style="font-size:12px;margin-top:2px">“${esc(o.note)}”</div>` : ''}<div class="muted" style="font-size:11.5px;margin-top:6px">${L3(['Berlaku s/d', 'Valid until', 'صالح حتى'])} ${fDT(o.validUntil)}</div>${sdLive(r) && o.state === 'sent' ? `<button class="btn primary" style="width:100%;justify-content:center;margin-top:10px" data-act="sd-accept" data-id="${o.id}">${ic('check')}${L3(['Pilih penawaran ini', 'Choose this offer', 'اختر هذا العرض'])}</button>` : ''}</div>`; }).join('') : `<div class="muted" style="font-size:13px">${sdLive(r) ? L3(['Belum ada penawaran. Travel berizin di Segaloka sudah menerima permintaan Anda.', 'No offers yet. Licensed Travels on Segaloka have received your request.', 'لا عروض بعد.']) : '—'}</div>`}
  ${sdLive(r) ? `<button class="btn" style="width:100%;justify-content:center;margin-top:12px" data-act="sd-cancel" data-id="${r.id}">${ic('x')}${L3(['Batalkan permintaan', 'Cancel request', 'إلغاء الطلب'])}</button>` : ''}</div>`, '/segadeals') }; });

/* ---------- Portal Travel ---------- */
PNAV.travel.splice(2, 0, ['tag', ['SegaDeals', 'SegaDeals', 'SegaDeals'], '/segadeals']);
route('/p/travel/segadeals', () => { sdSweep(); const tr = me('travel'); const open = SD_REQ.filter(r => sdLive(r)).sort((a, b) => b.created - a.created); const mine = SD_OFF.filter(o => o.travel === tr.id).sort((a, b) => b.created - a.created);
  const rows = open.map(r => { const ok = sdEligible(tr, r); const base = sdBasePkgs(tr, r.type); const my = SD_OFF.find(o => o.request === r.id && o.travel === tr.id && o.state === 'sent'); const why = !ok ? (tr.op !== 'active' ? L3(['Tenant tidak aktif', 'Tenant not active', 'غير نشط']) : L3(['Izin ', 'Licence ', 'الترخيص ']) + licFor[r.type] + L3([' belum terverifikasi', ' not verified', ' غير موثق'])) : null;
    return `<tr><td><b>${esc(sdTitle(r))}</b><div class="muted mono" style="font-size:11.5px">${r.id} · ${esc(r.city || '')}</div>${r.notes ? `<div class="muted" style="font-size:12px;max-width:320px">“${esc(r.notes)}”</div>` : ''}</td><td>${esc(sdMonth(r.month))}</td><td class="r tnum">${r.pax}</td><td class="r tnum">${money(r.budget)}</td><td class="r tnum">${sdOffers(r.id).filter(o => o.state === 'sent').length}</td><td>${rel(r.expires)}</td><td class="r">${my ? `<span class="st info">${ic('send')}${L3(['Sudah menawar', 'Offer sent', 'تم الإرسال'])} · ${money(my.price)}</span>` : why ? `<button class="btn sm" aria-disabled="true" data-tip="${esc(why)}">${L3(['Kirim penawaran', 'Send offer', 'إرسال عرض'])}</button>` : `<button class="btn sm primary" data-act="sd-offer" data-id="${r.id}">${ic('send', 'sm')}${L3(['Kirim penawaran', 'Send offer', 'إرسال عرض'])}</button>`}</td></tr>`; });
  const won = mine.filter(o => o.state === 'accepted');
  return { html: `<div class="page">${pHead('travel', 'SegaDeals', L3(['Permintaan perjalanan dari pengguna Segaloka. Kirim penawaran sesuai jenis perjalanan yang diminta — tidak perlu punya paket dulu. Bila pengguna memilih penawaran Anda, paket khusus, booking & tagihan DP dibuat otomatis.', 'Trip requests from Segaloka users. Send offers for the requested trip type — no package needed upfront. When a user picks yours, a custom package, the booking & deposit invoice are created automatically.', 'طلبات المستخدمين.']))}
  ${kpiRow([{ k: L3(['Permintaan terbuka', 'Open requests', 'طلبات مفتوحة']), v: fN(open.length), icon: 'tag' }, { k: L3(['Bisa Anda tawar', 'You can bid', 'يمكنك العرض']), v: fN(open.filter(r => sdEligible(tr, r)).length), icon: 'check' }, { k: L3(['Penawaran aktif', 'Active offers', 'عروض نشطة']), v: fN(mine.filter(o => o.state === 'sent').length), icon: 'send' }, { k: L3(['Diterima pengguna', 'Accepted by users', 'مقبولة']), v: fN(won.length) + (mine.length ? ' · ' + pct(won.length / mine.length * 100, 0) : ''), icon: 'star' }])}
  <section class="panel" style="margin-top:14px"><div class="panel-h"><h3>${L3(['Permintaan terbuka', 'Open requests', 'طلبات مفتوحة'])}</h3></div>${tbl([L3(['Permintaan', 'Request', 'الطلب']), L3(['Bulan', 'Month', 'الشهر']), 'Pax', 'Rp Budget/pax', L3(['Penawaran', 'Offers', 'العروض']), L3(['Berakhir', 'Ends', 'ينتهي']), t('action')], rows, L3(['Belum ada permintaan terbuka', 'No open requests', 'لا طلبات']))}</section>
  <section class="panel" style="margin-top:14px"><div class="panel-h"><h3>${L3(['Penawaran saya', 'My offers', 'عروضي'])}</h3></div>${tbl([L3(['Permintaan', 'Request', 'الطلب']), L3(['Program', 'Program', 'البرنامج']), 'Rp Harga/pax', 'Total', L3(['Berlaku s/d', 'Valid until', 'صالح حتى']), t('status'), t('action')], mine.map(o => { const r = sdReq(o.request) || {}; const pk = pkgById(o.pkg); return `<tr><td><b>${esc(r.type ? sdTitle(r) : o.request)}</b><div class="muted mono" style="font-size:11.5px">${o.id} · ${o.request}</div></td><td>${esc(sdOfferName(o))}${o.pkg ? '' : ' <span class="chip">' + L3(['khusus', 'custom', 'مخصص']) + '</span>'}</td><td class="r tnum">${money(o.price)}</td><td class="r tnum">${money(o.price * (r.pax || 1))}</td><td>${fD(o.validUntil)}</td><td>${st(o.state)}</td><td class="r">${o.state === 'sent' ? `<button class="btn sm badb" data-act="sd-withdraw" data-id="${o.id}">${L3(['Tarik', 'Withdraw', 'سحب'])}</button>` : o.state === 'accepted' && r.booking ? `<a class="btn sm" href="#/p/travel/bookings/${r.booking}">Booking ${icd('chevR', 'sm')}</a>` : ''}</td></tr>`; }), L3(['Belum ada penawaran', 'No offers yet', 'لا عروض']))}</section></div>` }; });

Object.assign(A, {
  'sd-submit': () => { const u = me('traveler'); const v = formVals(SD_FORM(u), 'sd-'); if (!v) { toast('warn', L3(['Lengkapi isian bertanda *', 'Fill in the required fields', 'أكمل الحقول']), ''); return; } if (v.pax < 1 || v.budget < 1e6) { toast('warn', L3(['Pax & budget tidak valid', 'Invalid pax or budget', 'قيم غير صالحة']), ''); return; }
    const r = { id: uid('SDR'), traveler: u.id, type: v.type, dest: v.dest.trim(), month: v.month, pax: v.pax, budget: v.budget, city: v.city, notes: v.notes, created: nowTs(), expires: nowTs() + 10 * D, state: 'open' }; SD_REQ.unshift(r);
    audit(u.name, 'segadeals.request.create', 'SegaDealsRequest/' + r.id, 'success', { source: 'Aplikasi Pengguna', after: sdTitle(r) + ' · ' + r.pax + ' pax · ' + money(r.budget) });
    pNotif('marketplace', 'info', L3(['Permintaan SegaDeals baru', 'New SegaDeals request', 'طلب SegaDeals جديد']), sdTitle(r) + ' · ' + r.pax + ' pax · ' + u.name, '/marketplace/segadeals');
    toast('ok', L3(['Permintaan terkirim', 'Request submitted', 'تم الإرسال']), L3(['Travel berizin akan mengirim penawaran', 'Licensed Travels will send offers', 'ستصلك العروض'])); go('/p/traveler/segadeals/' + r.id); },
  'sd-cancel': el => { const u = me('traveler'); const r = sdReq(el.dataset.id); if (!r || r.traveler !== u.id || !sdLive(r)) return; confirmAction({ title: L3(['Batalkan permintaan', 'Cancel request', 'إلغاء الطلب']) + ' · ' + r.id, desc: esc(sdTitle(r)) + ' — ' + L3(['semua penawaran yang masuk akan ditutup.', 'all received offers will be closed.', 'ستُغلق العروض.']), tone: 'danger', label: L3(['Batalkan', 'Cancel', 'إلغاء']), resource: 'SegaDealsRequest/' + r.id, reason: false, onOk: () => { r.state = 'cancelled'; sdOffers(r.id).forEach(o => { if (o.state === 'sent') o.state = 'withdrawn'; }); audit(u.name, 'segadeals.request.cancel', 'SegaDealsRequest/' + r.id, 'success', { source: 'Aplikasi Pengguna', before: 'open', after: 'cancelled' }); toast('ok', L3(['Permintaan dibatalkan', 'Request cancelled', 'أُلغي الطلب']), r.id); rerender(); } }); },
  'sd-accept': el => { sdSweep(); const u = me('traveler'); const o = SD_OFF.find(x => x.id === el.dataset.id); const r = o && sdReq(o.request); if (!o || !r || r.traveler !== u.id || !sdLive(r) || o.state !== 'sent') { toast('warn', L3(['Penawaran tidak lagi tersedia', 'Offer no longer available', 'العرض غير متاح']), ''); rerender(); return; } const tr = travelById(o.travel); const pk = pkgById(o.pkg); const total = o.price * r.pax;
    confirmAction({ title: L3(['Pilih penawaran', 'Choose offer', 'اختيار العرض']) + ' · ' + tr.name, desc: `${esc(sdOfferName(o))} · ${r.pax} pax × ${money(o.price, true)} = <b>${money(total, true)}</b><br>${L3(['DP 30% ditagihkan via Virtual Account', '30% deposit billed via Virtual Account', 'عربون 30%'])}: <b>${money(Math.round(total * SD_DP / 1000) * 1000, true)}</b> · ${L3(['Alur dana', 'Fund flow', 'تدفق الأموال'])}: <span class="mono">${tr.payMode}</span>`, label: L3(['Pilih & buat booking', 'Choose & create booking', 'اختر واحجز']), resource: o.id, reason: false,
      onOk: () => { let usePk = pk; if (o.pkg) { if (!pk || pk.state !== 'published') { toast('bad', L3(['Paket dasar tidak lagi published', 'Base package no longer published', 'الباقة غير منشورة']), ''); return; } } else { usePk = sdMakePackage(o, r); } const b = createBooking(usePk.id, u.id, r.pax, 'SegaDeals', { total, sdRequest: r.id, sdOffer: o.id }); if (!b) return;
        o.state = 'accepted'; sdOffers(r.id).forEach(x => { if (x.id !== o.id && x.state === 'sent') x.state = 'rejected'; }); r.state = 'accepted'; r.offer = o.id; r.booking = b.id;
        audit(u.name, 'segadeals.offer.accept', 'SegaDealsOffer/' + o.id, 'success', { source: 'Aplikasi Pengguna', after: 'Booking/' + b.id + ' · ' + money(total) }); audit(u.name, 'booking.create', 'Booking/' + b.id, 'success', { source: 'SegaDeals · ' + r.id });
        toast('ok', L3(['Penawaran dipilih · booking dibuat', 'Offer chosen · booking created', 'تم الحجز']), b.id + ' · ' + L3(['bayar DP 30% via VA', 'pay 30% deposit via VA', 'ادفع العربون'])); go('/p/traveler/bookings/' + b.id); } }); },
  'sd-offer': el => { sdSweep(); const tr = me('travel'); const r = sdReq(el.dataset.id); if (!r || !sdLive(r)) { toast('warn', L3(['Permintaan sudah ditutup', 'Request already closed', 'الطلب مغلق']), ''); rerender(); return; } if (!sdEligible(tr, r)) { toast('bad', L3(['Izin tidak sesuai', 'Licence mismatch', 'الترخيص غير مطابق']), licFor[r.type]); return; } const base = sdBasePkgs(tr, r.type); const depDef = r.month + '-15';
    modal({ title: L3(['Kirim penawaran', 'Send offer', 'إرسال عرض']) + ' · ' + r.id, body: `<div class="docrow" style="margin-bottom:12px"><span class="fi">SD</span><span class="body"><b>${esc(sdTitle(r))}</b><span>${esc(sdMonth(r.month))} · ${r.pax} pax · budget ${money(r.budget, true)}/pax · ${esc(r.city || '')}</span></span></div>${r.notes ? `<p class="muted" style="margin:-4px 0 12px;font-size:13px">“${esc(r.notes)}”</p>` : ''}` + fields([{ k: 'pkg', label: L3(['Dasar penawaran', 'Offer basis', 'أساس العرض']), type: 'select', options: [['', L3(['Paket khusus untuk permintaan ini (dibuat saat dipilih pengguna)', 'Custom package for this request (created when the user chooses it)', 'باقة مخصصة'])], ...base.map(p => [p.id, L3(['Paket yang ada: ', 'Existing package: ', 'باقة موجودة: ']) + p.name + ' · ' + fD(p.dep) + ' · ' + (p.seats - p.sold) + ' seat'])] }, { k: 'name', label: L3(['Nama program', 'Program name', 'اسم البرنامج']), req: true, def: sdTitle(r) + ' · ' + r.pax + ' pax' }, { k: 'dep', label: L3(['Tanggal berangkat', 'Departure date', 'تاريخ المغادرة']), type: 'date', req: true, def: depDef }, { k: 'duration', label: L3(['Durasi (hari)', 'Duration (days)', 'المدة']), type: 'number', min: 1, max: 60, def: r.type === 'Haji' ? 30 : 9 }, { k: 'hotel', label: L3(['Hotel', 'Hotel', 'الفندق']), def: r.type === 'Umrah' ? 'Makkah ★4 (±300 m) · Madinah ★4' : '' }, { k: 'airline', label: L3(['Maskapai', 'Airline', 'الطيران']), def: '' }, { k: 'price', label: L3(['Harga penawaran / pax (Rp)', 'Offer price / pax (Rp)', 'السعر للفرد']), type: 'number', req: true, min: 1000000, step: 100000, def: r.budget }, { k: 'includes', label: L3(['Sudah termasuk', 'Includes', 'يشمل']), req: true, def: 'Tiket PP, hotel ★4, visa, muthawwif' }, { k: 'days', label: L3(['Berlaku (hari)', 'Valid (days)', 'الصلاحية']), type: 'number', min: 1, max: 14, def: 3 }, { k: 'note', label: L3(['Pesan untuk pengguna', 'Message to user', 'رسالة']), type: 'textarea', def: '' }], 'so-') + `<div class="auditbox">${ic('shieldc')}<span>${L3(['Penawaran mengikat selama masa berlaku. Harga final di booking = harga penawaran × pax.', 'Offers are binding while valid. Final booking price = offer price × pax.', 'العرض ملزم.'])}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="sd-offer-go" data-id="${r.id}">${ic('send', 'sm')}${L3(['Kirim', 'Send', 'إرسال'])}</button>` }); },
  'sd-offer-go': el => { const tr = me('travel'); const r = sdReq(el.dataset.id); const v = formVals([{ k: 'pkg' }, { k: 'name', req: true }, { k: 'dep', req: true }, { k: 'duration', type: 'number' }, { k: 'hotel' }, { k: 'airline' }, { k: 'price', type: 'number', req: true }, { k: 'includes', req: true }, { k: 'days', type: 'number' }, { k: 'note' }], 'so-'); if (!v) return; if (!r || !sdLive(r)) { closeOverlays(); toast('warn', L3(['Permintaan sudah ditutup', 'Request already closed', 'الطلب مغلق']), ''); rerender(); return; } if (v.price < 1e6) { toast('warn', L3(['Harga tidak valid', 'Invalid price', 'سعر غير صالح']), ''); return; } if (SD_OFF.some(o => o.request === r.id && o.travel === tr.id && o.state === 'sent')) { closeOverlays(); toast('warn', L3(['Anda sudah mengirim penawaran untuk permintaan ini', 'You already sent an offer for this request', 'أرسلت عرضاً']), ''); rerender(); return; }
    const o = { id: uid('SDO'), request: r.id, travel: tr.id, pkg: v.pkg || null, custom: { name: v.name, dep: new Date(v.dep).getTime(), duration: v.duration || null, hotel: v.hotel, airline: v.airline }, price: v.price, includes: v.includes, note: v.note, validUntil: Math.min(r.expires, nowTs() + Math.max(1, v.days || 3) * D), created: nowTs(), state: 'sent' }; SD_OFF.unshift(o); if (r.state === 'open') r.state = 'offered';
    pAudit('travel', 'segadeals.offer.create', 'SegaDealsOffer/' + o.id, { after: r.id + ' · ' + money(o.price) + '/pax' }); closeOverlays(); toast('ok', L3(['Penawaran terkirim ke pengguna', 'Offer sent to the user', 'أُرسل العرض']), r.id + ' · ' + money(o.price, true) + '/pax'); rerender(); },
  'sd-withdraw': el => { const tr = me('travel'); const o = SD_OFF.find(x => x.id === el.dataset.id); if (!o || o.travel !== tr.id || o.state !== 'sent') return; confirmAction({ title: L3(['Tarik penawaran', 'Withdraw offer', 'سحب العرض']) + ' · ' + o.id, desc: L3(['Pengguna tidak lagi bisa memilih penawaran ini.', 'The user can no longer choose this offer.', 'لن يتمكن المستخدم من اختياره.']), tone: 'danger', label: L3(['Tarik', 'Withdraw', 'سحب']), resource: 'SegaDealsOffer/' + o.id, onOk: reason => { o.state = 'withdrawn'; sdSweep(); pAudit('travel', 'segadeals.offer.withdraw', 'SegaDealsOffer/' + o.id, { before: 'sent', after: 'withdrawn', reason }); toast('ok', L3(['Penawaran ditarik', 'Offer withdrawn', 'سُحب العرض']), o.id); rerender(); } }); },
  'sd-adm-withdraw': el => { const o = SD_OFF.find(x => x.id === el.dataset.id); if (!o || o.state !== 'sent') return; confirmAction({ title: L3(['Tarik penawaran (moderasi)', 'Withdraw offer (moderation)', 'سحب العرض']) + ' · ' + o.id, desc: esc(travelById(o.travel).name) + ' · ' + money(o.price, true) + '/pax', tone: 'danger', label: L3(['Tarik', 'Withdraw', 'سحب']), resource: 'SegaDealsOffer/' + o.id, onOk: reason => { o.state = 'withdrawn'; sdSweep(); audit('Admin Pusat', 'segadeals.offer.moderate_withdraw', 'SegaDealsOffer/' + o.id, 'success', { before: 'sent', after: 'withdrawn', reason }); toast('ok', L3(['Penawaran ditarik', 'Offer withdrawn', 'سُحب العرض']), o.id); closeOverlays(); rerender(); } }); }
});

/* ---------- Admin: Marketplace › SegaDeals ---------- */
route('/marketplace/segadeals', () => { sdSweep(); const acc = SD_REQ.filter(r => r.state === 'accepted'); const decided = SD_REQ.filter(r => ['accepted', 'expired', 'cancelled'].includes(r.state)); const withOff = SD_REQ.filter(r => sdOffers(r.id).length);
  return resPage({ id: 'sdreq', nav: 'segadeals', noun: L3(['Permintaan', 'Request', 'طلب']), desc: L3(['SegaDeals = permintaan dari pengguna → penawaran dari Travel berizin → pengguna memilih → booking + DP. Admin tidak membuat deal; admin memantau & memoderasi.', 'SegaDeals = user request → offers from licensed Travels → user chooses → booking + deposit. Admins do not create deals; they monitor & moderate.', 'SegaDeals: طلب المستخدم ← عروض الشركات.']), data: SD_REQ, states: ['open', 'offered', 'accepted', 'expired', 'cancelled'], lifecycle: ['open', 'offered', 'accepted'], create: false,
    kpis: () => [{ k: L3(['Permintaan terbuka', 'Open requests', 'طلبات مفتوحة']), v: fN(SD_REQ.filter(sdLive).length) }, { k: L3(['Penawaran aktif', 'Active offers', 'عروض نشطة']), v: fN(SD_OFF.filter(o => o.state === 'sent').length) }, { k: L3(['Konversi ke booking', 'Converted to booking', 'التحويل']), v: decided.length ? pct(acc.length / decided.length * 100, 0) : '—' }, { k: 'GMV SegaDeals', v: money(BOOKINGS.filter(b => b.source === 'SegaDeals').reduce((s, b) => s + b.total, 0)) }],
    cols: [{ k: 'id', label: L3(['Permintaan', 'Request', 'الطلب']), render: r => `<b>${esc(sdTitle(r))}</b><div class="muted" style="font-size:11.5px"><span class="mono">${r.id}</span> · ${esc(trvName(r.traveler))}</div>` }, { k: 'month', label: L3(['Bulan', 'Month', 'الشهر']), render: r => esc(sdMonth(r.month)) }, { k: 'pax', label: 'Pax', cls: 'r tnum' }, { k: 'budget', label: 'Budget/pax', cls: 'r tnum', render: r => money(r.budget) }, { k: 'offers', label: L3(['Penawaran', 'Offers', 'العروض']), cls: 'r tnum', render: r => fN(sdOffers(r.id).length), sv: r => sdOffers(r.id).length }, { k: 'created', label: L3(['Diajukan', 'Submitted', 'قُدم']), render: r => rel(r.created) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
    show: r => [[L3(['Pengguna', 'User', 'المستخدم']), `<a href="#/traveler">${esc(trvName(r.traveler))}</a> <span class="mono muted">${r.traveler}</span>`], [L3(['Jenis', 'Type', 'النوع']), esc(r.type) + ' · ' + L3(['izin wajib', 'licence required', 'الترخيص']) + ' ' + licFor[r.type]], [L3(['Tujuan', 'Destination', 'الوجهة']), esc(r.dest)], [L3(['Bulan', 'Month', 'الشهر']), esc(sdMonth(r.month)) + ' · ' + esc(r.city || '')], ['Pax', r.pax], ['Budget', money(r.budget, true) + ' / pax'], [L3(['Catatan', 'Notes', 'ملاحظات']), esc(r.notes || '—')], [L3(['Berlaku s/d', 'Open until', 'صالح حتى']), fDT(r.expires)], ['Booking', r.booking ? `<a href="#/booking/${r.booking}" class="mono">${r.booking}</a>` : '—']],
    detailExtra: r => { const O = sdOffers(r.id); return `<div class="eyebrow" style="margin:18px 0 8px">${L3(['Penawaran', 'Offers', 'العروض'])} · ${O.length}</div>${O.length ? `<div class="list" style="border:1px solid var(--line);border-radius:10px">${O.map(o => `<div class="li"><span class="body"><b>${esc(travelById(o.travel).name)}</b><span class="sub">${money(o.price, true)}/pax · ${esc(sdOfferName(o))} · ${fD(o.validUntil)}</span></span>${st(o.state)}${o.state === 'sent' ? permBtn('marketplace.manage', L3(['Tarik', 'Withdraw', 'سحب']), `data-act="sd-adm-withdraw" data-id="${o.id}" data-mut`, 'sm badb') : ''}</div>`).join('')}</div>` : `<div class="muted">—</div>`}`; },
    acts: r => sdLive(r) ? [{ label: L3(['Tutup permintaan', 'Close request', 'إغلاق الطلب']), to: 'cancelled', tone: 'badb', reason: true, desc: L3(['Semua penawaran aktif ikut ditutup. Pengguna menerima notifikasi.', 'All active offers are closed too. The user is notified.', 'تُغلق العروض.']), fn: x => sdOffers(x.id).forEach(o => { if (o.state === 'sent') o.state = 'withdrawn'; }) }, { label: L3(['Perpanjang 7 hari', 'Extend 7 days', 'تمديد 7 أيام']), confirm: false, fn: x => { x.expires = Math.max(x.expires, nowTs()) + 7 * D; } }] : [],
    extra: () => `<section class="panel" style="margin-top:14px"><div class="panel-h"><h3>${L3(['Penawaran terbaru', 'Latest offers', 'أحدث العروض'])}</h3></div>${tbl(['Offer', 'Travel', L3(['Permintaan', 'Request', 'الطلب']), 'Rp Harga/pax', L3(['Berlaku s/d', 'Valid until', 'صالح حتى']), t('status')], SD_OFF.slice().sort((a, b) => b.created - a.created).slice(0, 12).map(o => `<tr><td class="mono">${o.id}</td><td>${trvLink(o.travel)}</td><td><span class="mono">${o.request}</span></td><td class="r tnum">${money(o.price)}</td><td>${fD(o.validUntil)}</td><td>${st(o.state)}</td></tr>`))}</section>` }); });
