/* =====================================================================
   RESOURCE ENGINE — list · create · edit · lifecycle transition · drawer · audit
   Setiap perubahan state lewat konfirmasi (alasan bila destruktif) dan dicatat di AUDIT.
   ===================================================================== */
const RES = {};
const periodSel = () => `<select class="select" id="period-sel" aria-label="Periode" data-act-change="period">${[[7, '7'], [30, '30'], [90, '90']].map(([v, l]) => `<option value="${v}" ${PERIOD === v ? 'selected' : ''}>${l} ${L3(['hari', 'days', 'يوماً'])}</option>`).join('')}</select>`;
const logTo = (r, text, tone = 'neu', by = 'Admin Pusat') => { (r._log = r._log || []).unshift({ t: text, ts: nowTs(), tone, by }); };
const opt = a => a.map(x => Array.isArray(x) ? x : [x, x]);
function fieldHTML(f, v, pfx) {
  const id = pfx + f.k; const val = v == null ? (f.def != null ? f.def : '') : v; const req = f.req ? ' *' : '';
  if (f.type === 'select') return `<div class="field"><label for="${id}">${esc(f.label)}${req}</label><select id="${id}">${opt(typeof f.options === 'function' ? f.options() : f.options).map(o => `<option value="${esc(o[0])}" ${String(val) === String(o[0]) ? 'selected' : ''}>${esc(o[1])}</option>`).join('')}</select>${f.hint ? `<span class="hint">${esc(f.hint)}</span>` : ''}</div>`;
  if (f.type === 'textarea') return `<div class="field"><label for="${id}">${esc(f.label)}${req}</label><textarea id="${id}">${esc(val)}</textarea>${f.hint ? `<span class="hint">${esc(f.hint)}</span>` : ''}</div>`;
  if (f.type === 'toggle') return `<label class="field" style="flex-direction:row;align-items:center;gap:8px;font-size:13px"><input type="checkbox" id="${id}" ${val ? 'checked' : ''}> ${esc(f.label)}</label>`;
  return `<div class="field"><label for="${id}">${esc(f.label)}${req}</label><input type="${f.type || 'text'}" id="${id}" value="${esc(val)}" ${f.min != null ? 'min="' + f.min + '"' : ''} ${f.max != null ? 'max="' + f.max + '"' : ''} ${f.step ? 'step="' + f.step + '"' : ''}>${f.hint ? `<span class="hint">${esc(f.hint)}</span>` : ''}</div>`;
}
function formVals(fields, pfx) { const o = {}; let ok = true; fields.forEach(f => { const el = document.getElementById(pfx + f.k); if (!el) return; let v = f.type === 'toggle' ? el.checked : el.value; if (f.type === 'number') v = v === '' ? '' : +v; if (f.req && (v === '' || v == null)) { ok = false; el.style.borderColor = 'var(--bad)'; if (ok === false && !o.__f) { o.__f = 1; el.focus(); } } o[f.k] = v; }); delete o.__f; return ok ? o : null; }
function resPage(cfg) {
  RES[cfg.id] = cfg; cfg.data = cfg.data || []; const n = NAVIDX[cfg.nav]; const trl = navTrail(cfg.nav);
  const sk = cfg.stateKey || 'state';
  const filters = cfg.filters || (cfg.states ? [{ v: 'all', label: t('f_all'), fn: () => true }, ...cfg.states.map(s => ({ v: s, label: STATUS[s] ? L3(STATUS[s].slice(2)) : s, fn: r => r[sk] === s }))] : null);
  const actCol = { k: '_a', label: t('action'), sort: false, cls: 'r', render: r => { const L = (cfg.acts ? cfg.acts(r) : []).filter(x => x.when !== false); const a = L.find(x => (x.tone || '').includes('primary') && !x.why) || L.find(x => !x.why) || L[0]; return `<div class="actions" style="justify-content:flex-end;flex-wrap:nowrap">${a ? actBtn(cfg.id, r, a, 'sm') : ''}<button class="iconbtn" data-act="res-open" data-tbl="${cfg.id}" data-id="${esc(r.id)}" aria-label="${t('open_detail')}">${ic('more')}</button></div>`; } };
  const tb = defTable(cfg.id, { name: cfg.noun || t(cfg.nav), placeholder: cfg.ph, search: cfg.search || (r => Object.values(r).filter(v => typeof v === 'string' || typeof v === 'number').join(' ')), rows: cfg.rows || (() => cfg.data), filters, open: true, cols: [...cfg.cols, actCol], card: cfg.card || (r => `<div style="display:flex;justify-content:space-between;gap:8px"><b>${esc(r.name || r.id)}</b>${r[sk] ? st(r[sk]) : ''}</div><div class="muted mono" style="font-size:11.5px;margin-top:4px">${esc(r.id)}</div>`), bulk: cfg.bulk, size: cfg.size || 10 });
  const kp = cfg.kpis ? cfg.kpis() : null;
  const html = `<div class="page">${phead({ crumbs: trl.map(x => [x[0], x[1] || S.route]), title: cfg.title || t(cfg.nav), desc: cfg.desc, actions: (cfg.topActs || '') + `<button class="btn" data-act="export" data-what="${esc(t(cfg.nav))}">${ic('download')}Export</button>` + (cfg.form && cfg.create !== false ? permBtn(cfg.perm || n.p.split('.')[0] + '.manage', ic('plus') + esc(cfg.newLabel || L3(['Tambah', 'Add', 'إضافة'])), `data-act="res-new" data-tbl="${cfg.id}" data-mut`, 'primary') : '') })}
  ${cfg.note ? `<div class="banner info" style="border:1px solid var(--info-line);border-radius:10px;margin-bottom:14px">${ic('info')}<span>${cfg.note}</span></div>` : ''}
  ${cfg.top ? cfg.top() : ''}${kp ? gate(kpiRow(kp), 2) : ''}<section class="panel" style="${kp || cfg.top ? 'margin-top:14px' : ''}">${tb}</section>${cfg.extra ? cfg.extra() : ''}</div>`;
  return { html, mount: cfg.mount };
}
function actBtn(tid, r, a, sz) { const perm = a.perm || RES[tid].perm || NAVIDX[RES[tid].nav].p.split('.')[0] + '.manage'; if (a.why) return `<button class="btn ${sz || ''}" aria-disabled="true" data-tip="${esc(a.why)}">${a.icon ? ic(a.icon, 'sm') : ''}${esc(a.label)}</button>`; return permBtn(perm, (a.icon ? ic(a.icon, 'sm') : '') + esc(a.label), `data-act="res-act" data-tbl="${tid}" data-id="${esc(r.id)}" data-a="${esc(a.label)}" data-mut`, (sz || '') + ' ' + (a.tone || '')); }
function resDetail(tid, id) {
  const cfg = RES[tid]; const r = cfg.data.find(x => x.id === id) || (cfg.rows ? cfg.rows().find(x => x.id === id) : null); if (!r) return; const sk = cfg.stateKey || 'state';
  const acts = (cfg.acts ? cfg.acts(r) : []).filter(x => x.when !== false);
  const show = cfg.show ? cfg.show(r) : cfg.cols.map(c => [c.label, c.render ? c.render(r) : esc(r[c.k])]);
  drawer({ title: r.name || r.id, sub: `<span class="mono">${esc(r.id)}</span> ${r[sk] ? st(r[sk]) : ''}`, body: `${cfg.lifecycle ? `<div class="eyebrow" style="margin-bottom:6px">Lifecycle</div>${lifeBar(cfg.lifecycle, cfg.lifecycle.includes(r[sk]) ? r[sk] : cfg.lifecycle[0], cfg.lifecycle.includes(r[sk]) ? null : r[sk])}<div style="height:14px"></div>` : ''}<dl class="dl">${show.map(([k, v]) => `<dt>${esc(k)}</dt><dd>${v}</dd>`).join('')}</dl>${cfg.detailExtra ? cfg.detailExtra(r) : ''}<div class="eyebrow" style="margin:18px 0 8px">${t('timeline')}</div><ul class="tl">${(r._log || []).concat([{ t: L3(['Dibuat', 'Created', 'أُنشئ']), ts: r.created || (T0 - 20 * D), tone: 'neu', by: r.by || 'System' }]).map(h => `<li><span class="dotc ${h.tone}"></span><b style="font-weight:550">${esc(h.t)}</b><div class="m">${esc(h.by)} · ${esc(fDT(h.ts))}${h.reason ? ' · “' + esc(h.reason) + '”' : ''}</div></li>`).join('')}</ul>`,
    foot: `${cfg.form && cfg.edit !== false ? permBtn(cfg.perm || NAVIDX[cfg.nav].p.split('.')[0] + '.manage', ic('note', 'sm') + 'Edit', `data-act="res-edit" data-tbl="${tid}" data-id="${esc(r.id)}" data-mut`, '') : ''}<span style="flex:1"></span>${acts.map(a => actBtn(tid, r, a)).join('')}` });
}
function resForm(tid, r) { const cfg = RES[tid]; const fields = typeof cfg.form === 'function' ? cfg.form(r) : cfg.form; drawer({ title: r ? 'Edit · ' + (r.name || r.id) : (cfg.newLabel || L3(['Tambah', 'Add', 'إضافة'])) + ' · ' + t(cfg.nav), sub: cfg.formHint || '', body: fields.map(f => fieldHTML(f, r ? r[f.k] : null, 'rf-')).join('') + `<div class="auditbox">${ic('history')}<span>${esc(t('audit_note'))}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="res-save" data-tbl="${tid}" data-id="${r ? esc(r.id) : ''}">${t('save')}</button>` }); }
let PEND = null;
function doResAct(tid, r, a, reason, vals) { const cfg = RES[tid]; const sk = cfg.stateKey || 'state'; const prev = r[sk]; if (a.to) r[sk] = a.to; if (a.fn) a.fn(r, reason, vals); logTo(r, a.label + (a.to ? ' → ' + (STATUS[a.to] ? L3(STATUS[a.to].slice(2)) : a.to) : '') + (vals ? ' · ' + Object.entries(vals).filter(e => e[0] !== 'reason').map(e => typeof e[1] === 'number' && e[1] > 9999 ? money(e[1], true) : e[1]).join(', ') : ''), a.tone && /bad|danger/.test(a.tone) ? 'bad' : 'ok'); if (reason) r._log[0].reason = reason; audit('Admin Pusat', (cfg.act || cfg.id) + '.' + (a.to || a.label.toLowerCase().replace(/\W+/g, '_')), t(cfg.nav) + '/' + r.id, 'success', { before: a.to ? prev : null, after: a.to || (vals ? JSON.stringify(vals) : null), reason }); toast(a.tone && /bad|danger/.test(a.tone) ? 'warn' : 'ok', a.label + ' · ' + (r.name || r.id), a.msg || L3(['Tercatat di audit', 'Recorded in audit', 'مسجل'])); rerender(); }
Object.assign(A, {
  'res-open': el => resDetail(el.dataset.tbl, el.dataset.id),
  'res-new': el => { const cf = RES[el.dataset.tbl]; const miss = ((cf && (typeof cf.form === 'function' ? cf.form() : cf.form)) || []).find(f => f.type === 'select' && (() => { const o = typeof f.options === 'function' ? f.options() : f.options; return !o || !o.length; })()); if (miss) { toast('warn', L3(['Belum bisa membuat data', 'Cannot create yet', 'لا يمكن الإنشاء بعد']), L3(['Pilihan untuk', 'No options yet for', 'لا خيارات لـ']) + ' "' + miss.label + '" ' + L3(['belum tersedia — buat datanya dulu.', '— create that data first.', ''])); return; } return resForm(el.dataset.tbl, null); },
  'res-edit': el => { const cfg = RES[el.dataset.tbl]; resForm(el.dataset.tbl, cfg.data.find(x => x.id === el.dataset.id)); },
  'res-save': el => { const cfg = RES[el.dataset.tbl]; const fields = typeof cfg.form === 'function' ? cfg.form(el.dataset.id ? cfg.data.find(x => x.id === el.dataset.id) : null) : cfg.form; const v = formVals(fields, 'rf-'); if (!v) return; if (S.ux === 'offline') { toast('warn', t('offline'), t('offline_b')); return; }
    if (el.dataset.id) { const r = cfg.data.find(x => x.id === el.dataset.id); const before = {}, after = {}; fields.forEach(f => { if (String(r[f.k]) !== String(v[f.k])) { before[f.k] = r[f.k]; after[f.k] = v[f.k]; } }); if (!Object.keys(after).length) { closeOverlays(); return; } Object.assign(r, v); if (cfg.onEdit) cfg.onEdit(r, v); logTo(r, 'Edit: ' + Object.keys(after).join(', '), 'info'); audit('Admin Pusat', (cfg.act || cfg.id) + '.update', t(cfg.nav) + '/' + r.id, 'success', { before: JSON.stringify(before), after: JSON.stringify(after) }); closeOverlays(); toast('ok', L3(['Tersimpan', 'Saved', 'تم الحفظ']), r.name || r.id); }
    else { const r = cfg.make(v); r.created = nowTs(); r.by = 'Admin Pusat'; cfg.data.unshift(r); audit('Admin Pusat', (cfg.act || cfg.id) + '.create', t(cfg.nav) + '/' + r.id, 'success', { after: JSON.stringify(v).slice(0, 160) }); closeOverlays(); toast('ok', L3(['Dibuat', 'Created', 'تم الإنشاء']) + ' · ' + (r.name || r.id), r.id); }
    rerender(); },
  'res-act': el => { const cfg = RES[el.dataset.tbl]; const r = cfg.data.find(x => x.id === el.dataset.id) || cfg.rows().find(x => x.id === el.dataset.id); const a = cfg.acts(r).find(x => x.label === el.dataset.a); if (!a) return;
    if (a.fields) { if (S.ux === 'offline') { toast('warn', t('offline'), t('offline_b')); return; } PEND = { tid: el.dataset.tbl, r, a }; modal({ title: a.label + ' · ' + (r.name || r.id), body: (a.desc ? `<p class="muted" style="margin-top:0">${a.desc}</p>` : '') + a.fields.map(f => fieldHTML(f, null, 'af-')).join('') + `<div class="auditbox">${ic('history')}<span>${esc(t('audit_note'))}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn ${a.tone || 'primary'}" data-act="res-act-go">${esc(a.label)}</button>` }); return; }
    if (a.confirm === false) doResAct(el.dataset.tbl, r, a, null); else confirmAction({ title: a.label + ' · ' + (r.name || r.id), desc: a.desc || '', tone: a.tone && /bad|danger/.test(a.tone) ? 'danger' : 'primary', label: a.label, reason: !!a.reason, resource: r.id, onOk: reason => doResAct(el.dataset.tbl, r, a, reason) }); },
  'res-act-go': () => { const v = formVals(PEND.a.fields, 'af-'); if (!v) return; const p = PEND; PEND = null; closeOverlays(); doResAct(p.tid, p.r, p.a, v.reason || null, v); },
  period: el => { PERIOD = +el.value; rerender(); }
});

/* shared tiny helpers */
const yes = (b, a, c) => b ? `<span style="color:var(--ok)">${ic('check', 'sm')}</span> ${a || ''}` : `<span class="muted">${ic('minus', 'sm')} ${c || ''}</span>`;
const pctBar = (v, tone) => `<div style="min-width:90px"><div class="tnum" style="font-size:12px">${pct(v * 100, 0)}</div><div class="meter ${tone || ''}"><i style="width:${Math.min(100, v * 100)}%"></i></div></div>`;
const travelOpts = () => TRAVELS.filter(x => x.op !== 'inactive').map(x => [x.id, x.name]);
const trvLink = id => { const x = travelById(id); return x ? `<a href="#/travel/${x.id}">${esc(x.name)}</a>` : '—'; };
const nid = (p, arr, base) => p + '-' + (base + arr.length * 7 + ri(1, 5));

/* =============================== DATA (demo) — ekosistem & marketplace =============================== */
const WEBSITES = TRAVELS.map((tr, i) => ({ id: 'WEB-' + tr.id.slice(4), name: tr.name, travel: tr.id, domain: tr.website, custom: i % 5 === 0 ? 'www.' + tr.website.split('.')[0] + '.co.id' : '', template: ['Hijaz', 'Madinah', 'Nusantara'][i % 3], ssl: ['active', 'grace', 'trial'].includes(tr.sub.state) ? 'active' : 'inactive', state: ['active', 'grace', 'trial'].includes(tr.sub.state) ? 'published' : 'unpublished', visits: ri(400, 22000) }));
const VCATS = VENDOR_CATS.map((c, i) => ({ id: 'VCAT-' + (101 + i), name: c, attrs: { Hotel: 'bintang, jarak ke Haram (m), tipe kamar', Tiket: 'rute, maskapai, bagasi', Visa: 'jenis visa, SLA terbit (hari)', Catering: 'menu, porsi/hari', Transportasi: 'jenis armada, kapasitas', 'Land Arrangement': 'durasi, cakupan', Akomodasi: 'tipe, kapasitas', Perlengkapan: 'item, ukuran' }[c], mp: ['Hotel', 'Tiket', 'Visa', 'Land Arrangement'].includes(c) ? c : 'Produk/jasa vendor', state: 'active' }));
const VP_TPL = { Hotel: ['Kamar Quad', 'Kamar Double'], Tiket: ['Seat CGK–JED PP', 'Seat SUB–MED PP'], Visa: ['Visa Umrah (e-visa)'], Catering: ['Paket makan 3×/hari'], Transportasi: ['Bus Makkah–Madinah', 'Transfer bandara'], 'Land Arrangement': ['LA 9 hari', 'LA 12 hari'], Akomodasi: ['Apartemen keluarga'], Perlengkapan: ['Kit ihram & koper'] };
const VPRODUCTS = []; VENDORS.forEach(v => v.cats.forEach(c => (VP_TPL[c] || []).forEach(n => VPRODUCTS.push({ id: 'VP-' + (40100 + VPRODUCTS.length * 3), name: n + ' · ' + v.name.split(' ')[0], vendor: v.id, cat: c, price: ri(3, 90) * 1e5 * (c === 'Tiket' ? 40 : c === 'Land Arrangement' ? 30 : 1), unit: { Hotel: '/malam', Tiket: '/pax', Visa: '/pax', Catering: '/pax/hari', Transportasi: '/trip', 'Land Arrangement': '/pax', Akomodasi: '/malam', Perlengkapan: '/set' }[c], allot: ri(10, 400), state: v.verif !== 'verified' ? 'draft' : wpick(['published', 'review', 'draft', 'unpublished'], [60, 15, 10, 15]) }))));
const REFLINKS = []; AFFILIATES.forEach(a => a.travels.forEach(tid => REFLINKS.push({ id: 'REF-' + (8100 + REFLINKS.length * 3), name: a.code + '-' + tid.slice(4), aff: a.id, travel: tid, url: travelById(tid).website + '/?ref=' + a.code, clicks: ri(100, 8000), conv: ri(0, 30), state: rnd() < .85 ? 'active' : 'paused' })));
const COMMISSIONS = BOOKINGS.slice(0, 26).map((b, i) => { const a = AFFILIATES[i % AFFILIATES.length]; const rate = [2, 2.5, 3][i % 3]; return { id: 'COM-' + (5500 + i * 7), name: a.name + ' · ' + b.id, aff: a.id, booking: b.id, travel: b.travel, rate, amount: Math.round(b.total * rate / 100), state: ['refunded', 'cancelled', 'failed'].includes(b.state) ? 'rejected' : wpick(['pending', 'approved', 'paid'], [35, 25, 40]) }; });
/* SegaDeals: lihat segadeals.js (permintaan pengguna → penawaran Travel) */
const MPCATS = ['Umrah', 'Haji', 'Halal Tour', 'Tour', 'Tiket', 'Hotel', 'Land Arrangement', 'Visa', 'Perlengkapan'].map((c, i) => ({ id: 'CAT-' + (11 + i), name: c, parent: i < 4 ? 'Paket Travel' : 'Produk Vendor', slug: c.toLowerCase().replace(/\s+/g, '-'), listings: i < 4 ? PACKAGES.filter(p => p.cat === c).length : VPRODUCTS.filter(v => v.cat === c).length, state: 'active' }));

/* ---------- Ekosistem ---------- */
route('/travel/website', () => resPage({ id: 'web', nav: 'travel_web', noun: 'Website', desc: L3(['Website Travel mengikuti entitlement subscription. Tenant tanpa subscription aktif tidak dapat dipublikasikan.', 'Travel websites follow subscription entitlement. Tenants without an active subscription cannot be published.', 'الموقع يتبع الاشتراك.']), data: WEBSITES, states: ['published', 'unpublished'],
  kpis: () => [{ k: 'Published', v: fN(WEBSITES.filter(w => w.state === 'published').length) }, { k: 'Custom domain', v: fN(WEBSITES.filter(w => w.custom).length) }, { k: 'SSL aktif', v: fN(WEBSITES.filter(w => w.ssl === 'active').length) }, { k: L3(['Kunjungan 30d', 'Visits 30d', 'الزيارات']), v: fC(WEBSITES.reduce((s, w) => s + w.visits, 0)) }],
  cols: [{ k: 'name', label: 'Travel', render: r => ent(r.name, `<span class="mono">${esc(r.domain)}</span>`, travelById(r.travel).color) }, { k: 'custom', label: 'Custom domain', render: r => r.custom ? `<span class="mono">${esc(r.custom)}</span>` : '—' }, { k: 'template', label: 'Template' }, { k: 'sub', label: 'Entitlement', render: r => st(travelById(r.travel).sub.state), sort: false }, { k: 'ssl', label: 'SSL', render: r => st(r.ssl) }, { k: 'visits', label: L3(['Kunjungan', 'Visits', 'زيارات']), cls: 'r tnum', render: r => fN(r.visits) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'custom', label: 'Custom domain', hint: 'CNAME → sites.segaloka.site' }, { k: 'template', label: 'Template', type: 'select', options: ['Hijaz', 'Madinah', 'Nusantara'] }], create: false,
  acts: r => { const ent = ['active', 'grace', 'trial'].includes(travelById(r.travel).sub.state); return [r.state === 'published' ? { label: 'Unpublish', to: 'unpublished', tone: 'badb', reason: true } : { label: 'Publish', to: 'published', tone: 'primary', why: ent ? null : L3(['Subscription tidak aktif — entitlement website tidak tersedia', 'Subscription not active — no website entitlement', 'الاشتراك غير نشط']) }, { label: L3(['Perbarui SSL', 'Renew SSL', 'تجديد SSL']), fn: x => x.ssl = 'active', confirm: false, when: r.ssl !== 'active' && ent }]; } }));
route('/vendor/categories', () => resPage({ id: 'vcat', nav: 'vendor_cat', noun: 'Kategori', desc: L3(['Taxonomy kategori vendor. Satu vendor dapat berada di banyak kategori.', 'Vendor category taxonomy. One vendor can belong to many categories.', 'تصنيف الموردين.']), data: VCATS, states: ['active', 'archived'],
  cols: [{ k: 'name', label: L3(['Kategori', 'Category', 'الفئة']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'attrs', label: L3(['Atribut', 'Attributes', 'السمات']), render: r => `<span class="muted" style="font-size:12px">${esc(r.attrs)}</span>` }, { k: 'vendors', label: 'Vendor', cls: 'r tnum', render: r => VENDORS.filter(v => v.cats.includes(r.name)).length, sort: false }, { k: 'mp', label: L3(['Kategori Marketplace', 'Marketplace category', 'فئة السوق']) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama kategori', 'Category name', 'الاسم']), req: true }, { k: 'attrs', label: L3(['Atribut (pisahkan koma)', 'Attributes (comma-separated)', 'السمات']), type: 'textarea' }, { k: 'mp', label: 'Mapping Marketplace', type: 'select', options: () => MPCATS.map(c => c.name).concat(['Produk/jasa vendor']) }],
  make: v => ({ id: 'VCAT-' + (101 + VCATS.length), ...v, state: 'active' }), acts: r => [r.state === 'active' ? { label: t('archive'), to: 'archived', tone: 'badb', reason: true, why: VENDORS.some(v => v.cats.includes(r.name)) ? L3(['Masih dipakai vendor aktif', 'Still used by active vendors', 'مستخدمة']) : null } : { label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }] }));
const vprodActs = r => ({ draft: [{ label: L3(['Kirim ke review', 'Submit for review', 'إرسال للمراجعة']), to: 'review', tone: 'primary', why: VENDORS.find(v => v.id === r.vendor).verif !== 'verified' ? L3(['Vendor belum terverifikasi', 'Vendor not verified', 'المورد غير موثق']) : null }], review: [{ label: t('reject'), to: 'draft', tone: 'badb', reason: true }, { label: 'Publish', to: 'published', tone: 'primary' }], published: [{ label: 'Unpublish', to: 'unpublished', tone: 'badb', reason: true }], unpublished: [{ label: 'Publish', to: 'published', tone: 'primary' }, { label: t('archive'), to: 'archived', reason: true }], archived: [] })[r.state];
const vprodCols = [{ k: 'name', label: L3(['Produk / layanan', 'Product / service', 'المنتج']), render: r => `<b>${esc(r.name)}</b><div class="muted mono" style="font-size:11.5px">${r.id}</div>` }, { k: 'vendor', label: 'Vendor', render: r => `<a href="#/vendor/${r.vendor}">${esc(VENDORS.find(v => v.id === r.vendor).name)}</a>` }, { k: 'cat', label: L3(['Kategori', 'Category', 'الفئة']), render: r => `<span class="chip">${esc(r.cat)}</span>` }, { k: 'price', label: L3(['Harga', 'Price', 'السعر']), cls: 'r tnum', render: r => money(r.price) + ' <span class="muted">' + r.unit + '</span>' }, { k: 'allot', label: 'Allotment', cls: 'r tnum' }, { k: 'state', label: 'Lifecycle', render: r => st(r.state) }];
const vprodForm = [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'vendor', label: 'Vendor', type: 'select', options: () => VENDORS.map(v => [v.id, v.name]) }, { k: 'cat', label: L3(['Kategori', 'Category', 'الفئة']), type: 'select', options: VENDOR_CATS }, { k: 'price', label: L3(['Harga (Rp)', 'Price (Rp)', 'السعر']), type: 'number', req: true, min: 0 }, { k: 'unit', label: 'Unit', def: '/pax' }, { k: 'allot', label: 'Allotment', type: 'number', def: 50 }];
route('/vendor/products', () => resPage({ id: 'vprod', nav: 'vendor_prod', noun: 'Produk', desc: L3(['Katalog produk & layanan vendor. Draft → Review → Published → Unpublished → Archived.', 'Vendor product & service catalogue. Draft → Review → Published → Unpublished → Archived.', 'كتالوج المنتجات.']), data: VPRODUCTS, states: ['draft', 'review', 'published', 'unpublished', 'archived'], lifecycle: ['draft', 'review', 'published', 'unpublished', 'archived'], cols: vprodCols, form: vprodForm, make: v => ({ id: 'VP-' + (40100 + VPRODUCTS.length * 3), ...v, state: 'draft' }), acts: vprodActs, kpis: () => ['published', 'review', 'draft', 'unpublished'].map(s => ({ k: L3(STATUS[s].slice(2)), v: fN(VPRODUCTS.filter(p => p.state === s).length) })) }));
route('/affiliate/referral', () => resPage({ id: 'ref', nav: 'aff_ref', noun: 'Referral', desc: L3(['Link & kode referral per Affiliate per Travel. Satu Affiliate boleh punya link ke banyak Travel.', 'Referral links & codes per Affiliate per Travel. One Affiliate may link to many Travels.', 'روابط الإحالة.']), data: REFLINKS, states: ['active', 'paused'], newLabel: L3(['Buat link', 'Create link', 'إنشاء رابط']),
  cols: [{ k: 'name', label: 'Kode', render: r => `<span class="chip mono">${esc(r.name)}</span>` }, { k: 'aff', label: 'Affiliate', render: r => esc(AFFILIATES.find(a => a.id === r.aff).name) }, { k: 'travel', label: 'Travel', render: r => trvLink(r.travel) }, { k: 'url', label: 'URL', render: r => `<span class="mono" style="font-size:11.5px">${esc(r.url)}</span> <button class="btn sm ghost" data-act="copy" data-v="${esc(r.url)}" aria-label="Copy">${ic('copy', 'sm')}</button>` }, { k: 'clicks', label: 'Klik', cls: 'r tnum', render: r => fN(r.clicks) }, { k: 'conv', label: 'Konversi', cls: 'r tnum' }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'aff', label: 'Affiliate', type: 'select', options: () => AFFILIATES.map(a => [a.id, a.name]) }, { k: 'travel', label: 'Travel', type: 'select', options: travelOpts }],
  make: v => { const a = AFFILIATES.find(x => x.id === v.aff); if (!a.travels.includes(v.travel)) a.travels.push(v.travel); return { id: 'REF-' + (8100 + REFLINKS.length * 3), name: a.code + '-' + v.travel.slice(4), ...v, url: travelById(v.travel).website + '/?ref=' + a.code, clicks: 0, conv: 0, state: 'active' }; },
  acts: r => [r.state === 'active' ? { label: t('pause'), to: 'paused', tone: 'warnb' } : { label: t('resume'), to: 'active', tone: 'primary' }] }));
route('/affiliate/commission', () => resPage({ id: 'com', nav: 'aff_com', noun: 'Komisi', desc: L3(['Komisi dihitung dari booking terbayar. Approved → dibayar lewat Withdrawal Affiliate.', 'Commission is computed from paid bookings. Approved → paid via Affiliate Withdrawal.', 'تُحسب العمولة من الحجوزات المدفوعة.']), data: COMMISSIONS, states: ['pending', 'approved', 'paid', 'rejected'], create: false, bulk: [{ k: 'export', label: 'Export' }],
  kpis: () => [{ k: 'Pending', v: money(COMMISSIONS.filter(c => c.state === 'pending').reduce((s, c) => s + c.amount, 0)) }, { k: 'Approved', v: money(COMMISSIONS.filter(c => c.state === 'approved').reduce((s, c) => s + c.amount, 0)) }, { k: 'Paid', v: money(COMMISSIONS.filter(c => c.state === 'paid').reduce((s, c) => s + c.amount, 0)) }, { k: L3(['Rata-rata rate', 'Avg rate', 'متوسط']), v: (() => { const L = COMMISSIONS.filter(c => c.rate != null); return L.length ? pct(L.reduce((s, c) => s + c.rate, 0) / L.length) : '—'; })() }],
  cols: [{ k: 'aff', label: 'Affiliate', render: r => esc(AFFILIATES.find(a => a.id === r.aff).name) }, { k: 'booking', label: 'Booking', render: r => `<a class="mono" href="#/booking/${r.booking}">${r.booking}</a> ${st(bookingById(r.booking).state)}` }, { k: 'travel', label: 'Travel', render: r => trvLink(r.travel) }, { k: 'rate', label: 'Rate', cls: 'r tnum', render: r => r.rate + '%' }, { k: 'amount', label: L3(['Komisi', 'Commission', 'العمولة']), cls: 'r tnum', render: r => money(r.amount, true) }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  acts: r => ({ pending: [{ label: t('approve'), to: 'approved', tone: 'primary', why: ['refunded', 'cancelled', 'failed', 'awaiting_payment'].includes(bookingById(r.booking).state) ? L3(['Booking belum terbayar / dibatalkan', 'Booking unpaid / cancelled', 'الحجز غير مدفوع']) : null }, { label: t('reject'), to: 'rejected', tone: 'badb', reason: true }], approved: [{ label: L3(['Bayar via withdrawal', 'Pay via withdrawal', 'الدفع']), to: 'paid', tone: 'primary', fn: x => WITHDRAWALS.unshift({ id: 'WD-' + (58000 + WITHDRAWALS.length), party: AFFILIATES.find(a => a.id === x.aff).name, partyType: 'Affiliate', ref: x.aff, amount: x.amount, state: 'pending', basis: 'Komisi ' + x.id, ts: nowTs() }), msg: L3(['Withdrawal dibuat → menunggu approval Finance', 'Withdrawal created → awaiting Finance approval', 'تم إنشاء السحب']) }] })[r.state] || [] }));
route('/affiliate/performance', () => { const rows = AFFILIATES.slice().sort((a, b) => b.gmv - a.gmv); return { html: `<div class="page">${phead({ crumbs: [[t('g_eko'), '/affiliate'], ['Affiliate', '/affiliate'], [t('aff_perf'), '']], title: t('aff_perf'), desc: L3(['Leaderboard & kontribusi Affiliate ke GMV lintas Travel.', 'Affiliate leaderboard & GMV contribution across Travels.', 'لوحة الصدارة.']), actions: periodSel() })}${kpiRow([{ k: 'Klik', v: fC(rows.reduce((s, a) => s + a.clicks, 0)) }, { k: 'Konversi', v: fN(rows.reduce((s, a) => s + a.conv, 0)) }, { k: 'CVR', v: pct(rows.reduce((s, a) => s + a.conv, 0) / rows.reduce((s, a) => s + a.clicks, 0) * 100, 2) }, { k: 'GMV', v: money(rows.reduce((s, a) => s + a.gmv, 0)) }])}<div class="grid g2" style="margin-top:14px">${pnl('GMV per Affiliate', hbars(rows.map(a => [a.name, a.gmv]), v => money(v)), { icon: 'bars' })}${pnl(L3(['Travel per Affiliate', 'Travels per Affiliate', 'الشركات لكل مسوق']), hbars(rows.map(a => [a.name, a.travels.length]), fN, 'var(--s3)'), { icon: 'link' })}</div><section class="panel" style="margin-top:14px"><div class="tbl-wrap"><table class="t"><thead><tr><th>#</th><th>Affiliate</th><th class="r">Klik</th><th class="r">Konversi</th><th class="r">CVR</th><th class="r">GMV</th><th class="r">Komisi</th></tr></thead><tbody>${rows.map((a, i) => `<tr><td class="tnum">${i + 1}</td><td>${ent(a.name, a.type, a.color)}</td><td class="r tnum">${fN(a.clicks)}</td><td class="r tnum">${a.conv}</td><td class="r tnum">${pct(a.conv / a.clicks * 100, 2)}</td><td class="r tnum">${money(a.gmv)}</td><td class="r tnum">${money(a.commission)}</td></tr>`).join('')}</tbody></table></div></section></div>` }; });

/* ---------- Marketplace ---------- */
route('/marketplace', () => { const pub = PACKAGES.filter(p => p.state === 'published'); const views = PACKAGES.reduce((s, p) => s + p.views30, 0); const bk = ser().reduce((s, d) => s + d.book, 0); const mod = PACKAGES.filter(p => p.state === 'review').length + VPRODUCTS.filter(v => v.state === 'review').length;
  return { html: `<div class="page">${phead({ crumbs: [[t('g_mp'), '/marketplace'], [t('mp_ov'), '/marketplace']], title: t('mp_ov'), desc: L3(['Etalase paket Travel & produk Vendor — dari pencarian hingga booking.', 'Storefront of Travel packages & Vendor products — from search to booking.', 'واجهة الباقات والمنتجات.']), actions: periodSel() })}${gate(kpiRow([{ k: 'Listing published', v: fN(pub.length + VPRODUCTS.filter(v => v.state === 'published').length), d: pub.length + ' paket · ' + VPRODUCTS.filter(v => v.state === 'published').length + ' produk vendor' }, { k: 'Views', v: fC(views) }, { k: 'Booking', v: fN(bk), d: 'CVR ' + pct(bk / views * 100, 2) }, { k: L3(['Antrian moderasi', 'Moderation queue', 'قائمة المراجعة']), v: fN(mod), route: '/marketplace/moderation' }]), 2)}
  <div class="grid g12" style="margin-top:14px"><div class="c8">${pnl('Booking / ' + L3(['hari', 'day', 'يوم']), barChart(ser(), { key: 'book', fmt: v => fN(Math.round(v)) }), { icon: 'bars' })}</div><div class="c4">${pnl(L3(['Listing per kategori', 'Listings by category', 'حسب الفئة']), hbars(MPCATS.map(c => [c.name, c.listings]), fN), { icon: 'grid', right: seeAll('/marketplace/categories') })}</div></div>
  <div class="grid g2" style="margin-top:14px">${pnl(L3(['Paket paling banyak dilihat', 'Most viewed packages', 'الأكثر مشاهدة']), `<div class="list" style="margin:-14px">${pub.slice().sort((a, b) => b.views30 - a.views30).slice(0, 6).map(p => `<a class="li" href="#/travel/${p.travel}/marketplace"><span class="body"><b style="font-weight:550">${esc(p.name)}</b><span class="sub">${esc(travelById(p.travel).name)} · ${money(p.price)}</span></span><span class="tnum">${fC(p.views30)}</span></a>`).join('')}</div>`, { icon: 'eye' })}${pnl('SegaDeals', `<div class="list" style="margin:-14px">${SD_REQ.slice().sort((a, b) => b.created - a.created).slice(0, 6).map(r => `<a class="li" href="#/marketplace/segadeals"><span class="body"><b style="font-weight:550">${esc(sdTitle(r))}</b><span class="sub">${esc(trvName(r.traveler))} · ${r.pax} pax · ${sdOffers(r.id).length} ${L3(['penawaran', 'offers', 'عروض'])}</span></span>${st(r.state)}</a>`).join('')}</div>`, { icon: 'tag', right: seeAll('/marketplace/segadeals') })}</div></div>` }; });
route('/marketplace/vendor-products', () => resPage({ id: 'mpv', nav: 'mp_vprod', noun: 'Produk vendor', desc: L3(['Produk vendor yang tampil di Marketplace. Moderasi & publikasi mengikuti permission marketplace.moderate.', 'Vendor products listed on the Marketplace. Moderation & publication follow the marketplace.moderate permission.', 'منتجات الموردين في السوق.']), data: VPRODUCTS, rows: () => VPRODUCTS.filter(v => ['published', 'review', 'unpublished'].includes(v.state)), states: ['published', 'review', 'unpublished'], cols: vprodCols, acts: r => (vprodActs(r) || []).map(a => ({ ...a, perm: 'marketplace.moderate' })), create: false }));
route('/marketplace/categories', () => resPage({ id: 'mpcat', nav: 'mp_cat', noun: 'Kategori', desc: L3(['Kategori Marketplace: paket Travel (Umrah, Haji, Halal Tour, Tour) & produk Vendor.', 'Marketplace categories: Travel packages (Umrah, Hajj, Halal Tour, Tour) & Vendor products.', 'فئات السوق.']), data: MPCATS, states: ['active', 'archived'],
  cols: [{ k: 'name', label: L3(['Kategori', 'Category', 'الفئة']), render: r => `<b>${esc(r.name)}</b>` }, { k: 'parent', label: 'Parent', render: r => `<span class="chip">${esc(r.parent)}</span>` }, { k: 'slug', label: 'Slug', render: r => `<span class="mono">/${esc(r.slug)}</span>` }, { k: 'listings', label: 'Listing', cls: 'r tnum' }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  form: [{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'parent', label: 'Parent', type: 'select', options: ['Paket Travel', 'Produk Vendor'] }, { k: 'slug', label: 'Slug', req: true }], make: v => ({ id: 'CAT-' + (11 + MPCATS.length), ...v, listings: 0, state: 'active' }),
  acts: r => [r.state === 'active' ? { label: t('archive'), to: 'archived', tone: 'badb', reason: true, why: r.listings ? L3(['Masih ada listing di kategori ini', 'Category still has listings', 'توجد قوائم']) : null } : { label: L3(['Aktifkan', 'Activate', 'تفعيل']), to: 'active', tone: 'primary' }] }));
const MODQ = () => [...PACKAGES.filter(p => p.state === 'review').map(p => ({ id: p.id, kind: 'Paket', name: p.name, owner: travelById(p.travel).name, price: p.price, ref: p, state: 'review' })), ...VPRODUCTS.filter(v => v.state === 'review').map(v => ({ id: v.id, kind: 'Produk vendor', name: v.name, owner: VENDORS.find(x => x.id === v.vendor).name, price: v.price, ref: v, state: 'review' }))];
route('/marketplace/moderation', () => resPage({ id: 'mod', nav: 'mp_mod', noun: 'Moderasi', desc: L3(['Antrian review listing sebelum tampil di Marketplace. Checklist kebijakan: klaim, harga wajar, izin layanan valid.', 'Review queue before listings go live. Policy checklist: claims, fair price, valid service licence.', 'قائمة المراجعة.']), rows: MODQ, data: [], create: false,
  cols: [{ k: 'name', label: 'Listing', render: r => `<b>${esc(r.name)}</b><div class="muted mono" style="font-size:11.5px">${r.id}</div>` }, { k: 'kind', label: L3(['Tipe', 'Type', 'النوع']), render: r => `<span class="chip">${r.kind}</span>` }, { k: 'owner', label: L3(['Pemilik', 'Owner', 'المالك']) }, { k: 'price', label: L3(['Harga', 'Price', 'السعر']), cls: 'r tnum', render: r => money(r.price) }, { k: 'chk', label: 'Checklist', sort: false, render: r => { const lic = r.kind === 'Paket' ? travelById(r.ref.travel).legal : 'verified'; return `${yes(true, 'Klaim')} · ${yes(true, 'Harga')} · ${yes(['verified', 'expiring'].includes(lic), 'Izin', 'Izin')}`; } }, { k: 'state', label: t('status'), render: r => st(r.state) }],
  show: r => [['Listing', esc(r.name)], [L3(['Tipe', 'Type', 'النوع']), r.kind], [L3(['Pemilik', 'Owner', 'المالك']), esc(r.owner)], [L3(['Harga', 'Price', 'السعر']), money(r.price, true)]],
  acts: r => { const lic = r.kind === 'Paket' ? travelById(r.ref.travel).legal : 'verified'; return [{ label: t('reject'), tone: 'badb', reason: true, perm: 'marketplace.moderate', fn: x => { x.ref.state = 'draft'; x.state = 'draft'; } }, { label: 'Publish', tone: 'primary', perm: 'marketplace.moderate', fn: x => { x.ref.state = 'published'; x.state = 'published'; }, why: ['verified', 'expiring'].includes(lic) ? null : L3(['Izin layanan tenant belum valid', 'Tenant licence not valid', 'الترخيص غير صالح']) }]; } }));
