/* =====================================================================
   SEGADEALS v2
   - Travel wajib menyetujui S&K SegaDeals sebelum bisa menawar.
   - Biaya SegaDeals per pax (default Rp 200.000, bisa diturunkan admin
     global atau per Travel) sudah termasuk di harga penawaran.
   - Saat penawaran dipilih pengguna, Travel wajib punya deposit SegaDeals
     ≥ biaya × pax. Kurang → setor deposit (bukti transfer) → Finance konfirmasi
     → biaya dipotong otomatis. Booking tidak bisa diproses sebelum lunas.
   - Pengguna langsung mengisi data peserta (nama lengkap / diwakilkan).
   - Rekomendasi paspor (unggah KTP + kantor imigrasi) & surat cuti
     (semua / sebagian jamaah) diajukan ke Travel, diterbitkan dengan file.
   ===================================================================== */
const SDCFG = { fee: 200000, maxFee: 200000, version: 1, terms: ['Travel wajib memiliki izin yang sesuai (Umrah→PPIU, Haji→PIHK, Tour→BPW) dan status aktif.', 'Harga penawaran sudah termasuk biaya SegaDeals per jamaah sesuai ketentuan admin Segaloka.', 'Saat penawaran dipilih pengguna, Travel wajib menyetor deposit SegaDeals sama dengan atau lebih dari biaya SegaDeals × jumlah jamaah. Booking baru diproses setelah biaya terpenuhi.', 'Penawaran mengikat selama masa berlaku; harga tidak boleh diubah setelah dipilih pengguna.', 'Paket khusus hasil SegaDeals hanya untuk pemesan terkait dan tidak dipublikasikan.', 'Pelanggaran dapat menyebabkan akses SegaDeals dicabut oleh admin.'] };
const SD_LEDGER = [];
const LETTERS = [];
const sdFeeFor = tr => Math.min(SDCFG.maxFee || 200000, tr && tr.sdFee != null ? tr.sdFee : SDCFG.fee);
const sdTermsOk = tr => !!(tr && tr.sdTerms && tr.sdTerms.version >= SDCFG.version && !tr.sdTerms.revoked);
const sdBalance = tid => SD_LEDGER.filter(x => x.travel === tid && x.state === 'confirmed').reduce((s, x) => s + (x.kind === 'fee' ? -x.amount : x.amount), 0);
const sdOwed = tid => SD_LEDGER.filter(x => x.travel === tid && x.kind === 'fee' && x.state === 'awaiting_deposit').reduce((s, x) => s + x.amount, 0);

/* biaya dipotong saat penawaran dipilih */
function sdChargeFee(o, r, b) { const tr = travelById(o.travel); const fee = (o.fee != null ? o.fee : sdFeeFor(tr)) * r.pax; if (!fee) return;
  const bal = sdBalance(tr.id); const e = { id: uid('SDL'), travel: tr.id, kind: 'fee', amount: fee, booking: b.id, request: r.id, offer: o.id, ts: nowTs(), state: bal >= fee ? 'confirmed' : 'awaiting_deposit' }; SD_LEDGER.unshift(e);
  b.sdFee = fee; b.sdFeeState = e.state === 'confirmed' ? 'paid' : 'awaiting_deposit';
  audit('System', 'segadeals.fee.' + (e.state === 'confirmed' ? 'charged' : 'awaiting_deposit'), 'Travel/' + tr.id, 'success', { source: 'SegaDeals · ' + r.id, after: money(fee) });
  partyNotify([ntKey('travel', tr.id)], 'marketplace', e.state === 'confirmed' ? 'ok' : 'warn', e.state === 'confirmed' ? L3(['Penawaran dipilih · biaya SegaDeals dipotong', 'Offer chosen · SegaDeals fee charged', 'تم الخصم']) : L3(['Penawaran dipilih · wajib setor deposit SegaDeals', 'Offer chosen · SegaDeals deposit required', 'مطلوب إيداع']), r.id + ' · ' + money(fee) + (e.state === 'confirmed' ? '' : ' · ' + L3(['kurang ', 'short by ', 'ناقص ']) + money(fee - Math.max(0, bal))), { travel: '/p/travel/segadeals' }); }
/* setelah deposit dikonfirmasi: lunasi biaya yang tertunda (paling lama dulu) */
function sdSettleOwed(tid) { SD_LEDGER.filter(x => x.travel === tid && x.kind === 'fee' && x.state === 'awaiting_deposit').sort((a, b) => a.ts - b.ts).forEach(x => { if (sdBalance(tid) >= x.amount) { x.state = 'confirmed'; x.settledAt = nowTs(); const b = bookingById(x.booking); if (b) b.sdFeeState = 'paid'; } }); }
/* booking SegaDeals tidak bisa diproses Travel sebelum biaya terpenuhi */
if (A['tb-next']) { const f = A['tb-next']; A['tb-next'] = el => { const b = bookingById(el.dataset.id); if (b && b.sdFeeState === 'awaiting_deposit') return toast('warn', L3(['Setor deposit SegaDeals dulu', 'Top up your SegaDeals deposit first', 'أودع أولاً']), money(b.sdFee)); return f(el); }; }

/* ---------- Portal Travel: S&K, deposit ---------- */
function sdTravelPanel(tr) {
  if (!sdTermsOk(tr)) return `<section class="panel" style="margin-bottom:14px;border-color:var(--accent)"><div class="panel-h"><h3>${ic('shieldc', 'sm')}${L3(['Syarat & Ketentuan SegaDeals', 'SegaDeals Terms & Conditions', 'الشروط والأحكام'])}</h3>${tr.sdTerms && tr.sdTerms.revoked ? st('inactive') : ''}</div><div class="panel-b"><p class="muted" style="margin-top:0">${L3(['Travel hanya bisa menerima & menawar permintaan SegaDeals setelah menyetujui ketentuan berikut.', 'Travels can only receive & bid on SegaDeals requests after accepting these terms.', 'وافق للمشاركة.'])}</p><ol style="margin:0 0 12px;padding-inline-start:20px;display:grid;gap:4px;font-size:13px">${SDCFG.terms.map(x => `<li>${esc(x)}</li>`).join('')}</ol><div class="docrow"><span class="fi">Rp</span><span class="body"><b>${L3(['Biaya SegaDeals untuk Anda', 'Your SegaDeals fee', 'رسومك'])}: ${money(sdFeeFor(tr), true)} / pax</b><span>${L3(['Ditetapkan admin Segaloka (maks. ', 'Set by Segaloka admin (max ', 'الحد ']) + money(SDCFG.maxFee, true)})</span></span></div>${tr.sdTerms && tr.sdTerms.revoked ? `<div class="banner bad" style="border-radius:10px;margin-top:10px">${ic('alert')}<span>${L3(['Akses SegaDeals dicabut admin: ', 'SegaDeals access revoked by admin: ', 'أُلغي: ']) + esc(tr.sdTerms.reason || '')}</span></div>` : `<label class="field" style="flex-direction:row;align-items:center;gap:8px;margin-top:12px"><input type="checkbox" id="sd-agree"> ${L3(['Saya telah membaca & menyetujui S&K SegaDeals', 'I have read & agree to the SegaDeals T&C', 'أوافق'])}</label><button class="btn primary" data-act="sd-terms-accept" style="margin-top:8px">${ic('check')}${L3(['Setujui & aktifkan SegaDeals', 'Accept & enable SegaDeals', 'موافقة وتفعيل'])}</button>`}</div></section>`;
  const bal = sdBalance(tr.id), owed = sdOwed(tr.id); const L = SD_LEDGER.filter(x => x.travel === tr.id).slice(0, 10);
  return `<div class="grid g12" style="margin-bottom:14px"><div class="c5">${pnl(L3(['Deposit SegaDeals', 'SegaDeals deposit', 'الإيداع']), `<div class="kpi" style="padding:0;border:0"><div class="v">${money(bal)}</div><div class="d">${L3(['Biaya Anda', 'Your fee', 'رسومك'])}: ${money(sdFeeFor(tr))}/pax${owed ? ` · <b style="color:var(--bad)">${L3(['Tertunda ', 'Owed ', 'مستحق ']) + money(owed)}</b>` : ''}</div></div>${owed > bal ? `<div class="banner bad" style="border-radius:10px;margin-top:10px">${ic('alert')}<span>${L3(['Wajib setor minimal ', 'You must deposit at least ', 'أودع على الأقل ']) + money(owed - Math.max(0, bal), true) + L3([' agar booking SegaDeals bisa diproses.', ' so SegaDeals bookings can proceed.', '.'])}</span></div>` : ''}<button class="btn primary" style="margin-top:10px" data-act="sd-topup">${ic('plus')}${L3(['Setor deposit', 'Top up deposit', 'إيداع'])}</button> <span class="muted" style="font-size:12px">${L3(['S&K disetujui ', 'T&C accepted ', 'وافق ']) + fD(tr.sdTerms.at)}</span>`, { icon: 'wallet' })}</div>
  <div class="c7">${pnl(L3(['Mutasi deposit', 'Deposit ledger', 'الحركات']), tbl(['ID', L3(['Jenis', 'Type', 'النوع']), 'Rp', t('status'), L3(['Waktu', 'Time', 'الوقت'])], L.map(x => `<tr><td class="mono">${x.id}${x.booking ? `<div class="muted" style="font-size:11px">${x.booking}</div>` : ''}</td><td>${x.kind === 'fee' ? L3(['Biaya SegaDeals', 'SegaDeals fee', 'رسوم']) : x.kind === 'refund' ? 'Refund' : L3(['Setoran', 'Top-up', 'إيداع'])}</td><td class="r tnum" style="color:${x.kind === 'fee' ? 'var(--bad)' : 'var(--ok)'}">${x.kind === 'fee' ? '−' : '+'}${money(x.amount)}</td><td>${st(x.state === 'awaiting_deposit' ? 'pending' : x.state)}</td><td>${rel(x.ts)}</td></tr>`), L3(['Belum ada mutasi', 'No entries yet', 'لا حركات'])), { raw: true, icon: 'list' })}</div></div>`; }
Object.assign(A, {
  'sd-terms-accept': () => { const tr = me('travel'); const c = document.getElementById('sd-agree'); if (!c || !c.checked) { toast('warn', L3(['Centang persetujuan S&K dulu', 'Tick the T&C agreement first', 'وافق أولاً']), ''); return; } tr.sdTerms = { version: SDCFG.version, at: nowTs(), by: tr.contact && tr.contact.name || tr.name, fee: sdFeeFor(tr) }; pAudit('travel', 'segadeals.terms.accept', 'Travel/' + tr.id, { after: 'v' + SDCFG.version + ' · ' + money(sdFeeFor(tr)) + '/pax' }); pNotif('marketplace', 'info', L3(['Travel bergabung SegaDeals', 'Travel joined SegaDeals', 'انضم']), tr.name, '/marketplace/segadeals'); toast('ok', L3(['SegaDeals aktif', 'SegaDeals enabled', 'مفعل']), L3(['Anda sekarang bisa menawar permintaan pengguna', 'You can now bid on user requests', 'يمكنك العرض'])); rerender(); },
  'sd-topup': () => { const tr = me('travel'); const need = Math.max(0, sdOwed(tr.id) - sdBalance(tr.id)); modal({ title: L3(['Setor deposit SegaDeals', 'Top up SegaDeals deposit', 'إيداع']), body: `<p class="muted" style="margin-top:0">${need ? L3(['Minimal setor ', 'Minimum top-up ', 'الحد الأدنى ']) + '<b>' + money(need, true) + '</b>' : L3(['Tidak ada biaya tertunda. Setoran menambah saldo deposit.', 'No fees owed. A top-up adds to your balance.', 'لا مستحقات.'])}</p>` + fields([{ k: 'amount', label: L3(['Jumlah setoran (Rp)', 'Amount (Rp)', 'المبلغ']), type: 'number', req: true, min: Math.max(need, 100000), step: 100000, def: Math.max(need, 1000000) }, { k: 'ref', label: L3(['No. referensi transfer', 'Transfer reference', 'المرجع']), req: true }], 'st-') + `<div class="field"><label for="st-file">${L3(['Bukti transfer', 'Transfer proof', 'الإثبات'])} *</label><input type="file" id="st-file" accept="image/*,.pdf"></div><div class="auditbox">${ic('landmark')}<span>${L3(['Transfer ke rekening SegaDeals Segaloka. Finance mengonfirmasi setoran, lalu biaya tertunda dipotong otomatis.', 'Transfer to the Segaloka SegaDeals account. Finance confirms, then owed fees are deducted automatically.', 'يؤكد القسم المالي.'])}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="sd-topup-go" data-need="${need}">${L3(['Kirim', 'Submit', 'إرسال'])}</button>` }); },
  'sd-topup-go': async el => { const tr = me('travel'); const need = +el.dataset.need; const v = formVals([{ k: 'amount', type: 'number', req: true }, { k: 'ref', req: true }], 'st-'); if (!v) return; if (v.amount < need || v.amount < 100000) { document.getElementById('st-amount').style.borderColor = 'var(--bad)'; toast('bad', L3(['Setoran harus sama atau lebih dari yang dibutuhkan', 'Top-up must be equal to or more than required', 'يجب أن يساوي أو يزيد']), money(need, true)); return; } const f = (document.getElementById('st-file') || {}).files; if (!f || !f[0]) { toast('warn', L3(['Unggah bukti transfer', 'Upload the transfer proof', 'ارفع الإثبات']), ''); return; }
    try { const e = { id: uid('SDL'), travel: tr.id, kind: 'topup', amount: v.amount, ref: v.ref, ts: nowTs(), state: 'pending' }; const up = await saveUpload(f[0], { ref: e.id, kind: 'sdproof', travel: tr.id, by: tr.name, byWs: 'travel', state: 'submitted' }); e.proof = up.id; SD_LEDGER.unshift(e); pAudit('travel', 'segadeals.deposit.topup', 'SegaDealsDeposit/' + e.id, { after: money(v.amount) }); pNotif('payment', 'warn', L3(['Setoran deposit SegaDeals', 'SegaDeals deposit top-up', 'إيداع']), tr.name + ' · ' + money(v.amount), '/marketplace/segadeals'); closeOverlays(); toast('ok', L3(['Setoran dikirim', 'Top-up submitted', 'أُرسل']), L3(['Menunggu konfirmasi Finance', 'Awaiting Finance confirmation', 'بانتظار التأكيد'])); rerender(); } catch (e) { toast('bad', 'Upload', String(e.message || e)); } },
  /* admin */
  'sd-dep-ok': el => { const e = SD_LEDGER.find(x => x.id === el.dataset.id); if (!e || e.state !== 'pending') return; confirmAction({ title: L3(['Konfirmasi setoran ', 'Confirm top-up ', 'تأكيد ']) + e.id, desc: esc((travelById(e.travel) || {}).name || '') + ' · <b>' + money(e.amount, true) + '</b> · Ref ' + esc(e.ref || ''), reason: false, resource: 'SegaDealsDeposit/' + e.id, label: L3(['Dana diterima', 'Funds received', 'تم الاستلام']), onOk: () => { e.state = 'confirmed'; e.confirmedAt = nowTs(); const u = UPLOADS.find(x => x.id === e.proof); if (u) u.state = 'verified'; sdSettleOwed(e.travel); audit('Admin Pusat', 'segadeals.deposit.confirm', 'SegaDealsDeposit/' + e.id, 'success', { after: money(e.amount) }); partyNotify([ntKey('travel', e.travel)], 'payment', 'ok', L3(['Setoran SegaDeals dikonfirmasi', 'SegaDeals top-up confirmed', 'تم التأكيد']), money(e.amount) + ' · ' + L3(['saldo ', 'balance ', 'الرصيد ']) + money(sdBalance(e.travel)), { travel: '/p/travel/segadeals' }); toast('ok', L3(['Setoran dikonfirmasi', 'Top-up confirmed', 'تم']), e.id); rerender(); } }); },
  'sd-dep-no': el => { const e = SD_LEDGER.find(x => x.id === el.dataset.id); if (!e || e.state !== 'pending') return; confirmAction({ title: L3(['Tolak setoran ', 'Reject top-up ', 'رفض ']) + e.id, tone: 'danger', resource: 'SegaDealsDeposit/' + e.id, label: t('reject'), onOk: r => { e.state = 'rejected'; e.reason = r; audit('Admin Pusat', 'segadeals.deposit.reject', 'SegaDealsDeposit/' + e.id, 'success', { reason: r }); partyNotify([ntKey('travel', e.travel)], 'payment', 'bad', L3(['Setoran SegaDeals ditolak', 'SegaDeals top-up rejected', 'رُفض']), r, { travel: '/p/travel/segadeals' }); rerender(); } }); },
  'sd-cfg': () => modal({ title: L3(['Pengaturan SegaDeals', 'SegaDeals settings', 'الإعدادات']), body: fields([{ k: 'fee', label: L3(['Biaya default per pax (Rp)', 'Default fee per pax (Rp)', 'الرسوم']), type: 'number', req: true, min: 0, step: 10000, def: SDCFG.fee }, { k: 'maxFee', label: L3(['Batas maksimum per pax (Rp)', 'Maximum per pax (Rp)', 'الحد الأقصى']), type: 'number', req: true, min: 0, step: 10000, def: SDCFG.maxFee }, { k: 'terms', label: L3(['S&K (satu poin per baris)', 'T&C (one point per line)', 'الشروط']), type: 'textarea', req: true, def: SDCFG.terms.join('\n') }, { k: 'bump', label: L3(['Wajibkan semua Travel menyetujui ulang', 'Require all Travels to re-accept', 'إعادة الموافقة']), type: 'toggle' }], 'sc-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="sd-cfg-go">${t('save')}</button>` }),
  'sd-cfg-go': () => { const v = formVals([{ k: 'fee', type: 'number', req: true }, { k: 'maxFee', type: 'number', req: true }, { k: 'terms', req: true }, { k: 'bump', type: 'toggle' }], 'sc-'); if (!v) return; if (v.fee > v.maxFee) { toast('bad', L3(['Biaya melebihi batas maksimum', 'Fee exceeds maximum', 'يتجاوز']), ''); return; } const before = money(SDCFG.fee) + '/v' + SDCFG.version; Object.assign(SDCFG, { fee: v.fee, maxFee: v.maxFee, terms: v.terms.split('\n').map(x => x.trim()).filter(Boolean) }); if (v.bump) SDCFG.version++; audit('Admin Pusat', 'segadeals.config.update', 'Settings/segadeals', 'success', { before, after: money(SDCFG.fee) + '/v' + SDCFG.version }); if (v.bump) partyNotify(TRAVELS.filter(x => x.sdTerms).map(x => ntKey('travel', x.id)), 'marketplace', 'warn', L3(['S&K SegaDeals diperbarui — setujui ulang', 'SegaDeals T&C updated — please re-accept', 'حُدثت الشروط']), '', { travel: '/p/travel/segadeals' }); closeOverlays(); toast('ok', L3(['Pengaturan disimpan', 'Settings saved', 'حُفظ']), ''); rerender(); },
  'sd-trfee': el => { const tr = travelById(el.dataset.id); modal({ title: L3(['Biaya SegaDeals · ', 'SegaDeals fee · ', 'الرسوم · ']) + tr.name, body: fields([{ k: 'fee', label: L3(['Biaya per pax (Rp) — kosongkan untuk default', 'Fee per pax (Rp) — blank for default', 'الرسوم']), type: 'number', min: 0, max: SDCFG.maxFee, step: 10000, def: tr.sdFee != null ? tr.sdFee : '' }], 'tf-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="sd-trfee-go" data-id="${tr.id}">${t('save')}</button>` }); },
  'sd-trfee-go': el => { const tr = travelById(el.dataset.id); const v = formVals([{ k: 'fee', type: 'number' }], 'tf-'); if (!v) return; if (v.fee !== '' && (v.fee < 0 || v.fee > SDCFG.maxFee)) { toast('bad', L3(['Di luar batas', 'Out of range', 'خارج الحد']), money(SDCFG.maxFee)); return; } const prev = sdFeeFor(tr); tr.sdFee = v.fee === '' ? null : v.fee; audit('Admin Pusat', 'segadeals.fee.override', 'Travel/' + tr.id, 'success', { before: money(prev), after: money(sdFeeFor(tr)) }); partyNotify([ntKey('travel', tr.id)], 'marketplace', 'info', L3(['Biaya SegaDeals Anda: ', 'Your SegaDeals fee: ', 'رسومك: ']) + money(sdFeeFor(tr)) + '/pax', '', { travel: '/p/travel/segadeals' }); closeOverlays(); rerender(); },
  'sd-revoke': el => { const tr = travelById(el.dataset.id); const on = !(tr.sdTerms && tr.sdTerms.revoked); confirmAction({ title: (on ? L3(['Cabut akses SegaDeals · ', 'Revoke SegaDeals · ', 'إلغاء · ']) : L3(['Pulihkan akses SegaDeals · ', 'Restore SegaDeals · ', 'استعادة · '])) + tr.name, tone: on ? 'danger' : 'primary', reason: on, resource: 'Travel/' + tr.id, onOk: r => { tr.sdTerms = Object.assign({}, tr.sdTerms, { revoked: on, reason: on ? r : '' }); audit('Admin Pusat', on ? 'segadeals.revoke' : 'segadeals.restore', 'Travel/' + tr.id, 'success', { reason: r }); partyNotify([ntKey('travel', tr.id)], 'marketplace', on ? 'bad' : 'ok', on ? L3(['Akses SegaDeals dicabut', 'SegaDeals access revoked', 'أُلغي']) : L3(['Akses SegaDeals dipulihkan', 'SegaDeals access restored', 'استعيد']), r || '', { travel: '/p/travel/segadeals' }); rerender(); } }); }
});
(() => { const R = ROUTES.find(x => x.pattern === '/p/travel/segadeals'); if (!R) return; const prev = R.fn;
  reroute('/p/travel/segadeals', p => { const out = prev(p); const tr = me('travel'); if (!out || !out.html || !tr) return out; const k = out.html.indexOf('<div class="kpis">'); if (k > 0) out.html = out.html.slice(0, k) + sdTravelPanel(tr) + out.html.slice(k); return out; }); })();
(() => { const R = ROUTES.find(x => x.pattern === '/marketplace/segadeals'); if (!R) return; const prev = R.fn;
  reroute('/marketplace/segadeals', p => { const out = prev(p); if (!out || !out.html) return out; const pend = SD_LEDGER.filter(x => x.kind === 'topup' && x.state === 'pending'); const joined = TRAVELS.filter(x => x.sdTerms);
    const blk = `<div class="grid g2" style="margin-top:14px">${pnl(L3(['Setoran deposit menunggu konfirmasi', 'Top-ups awaiting confirmation', 'بانتظار التأكيد']), pend.length ? pend.map(e => { const u = UPLOADS.find(x => x.id === e.proof); return `<div class="docrow"><span class="fi">Rp</span><span class="body"><b>${esc((travelById(e.travel) || {}).name || e.travel)} · ${money(e.amount, true)}</b><span>Ref ${esc(e.ref || '—')} · ${rel(e.ts)}</span></span>${u ? `<button class="btn sm ghost" data-act="file-view" data-id="${u.id}">${ic('eye', 'sm')}</button>` : ''}${permBtn('finance.withdrawal', L3(['Terima', 'Confirm', 'تأكيد']), `data-act="sd-dep-ok" data-id="${e.id}" data-mut`, 'sm primary')}${permBtn('finance.withdrawal', t('reject'), `data-act="sd-dep-no" data-id="${e.id}" data-mut`, 'sm badb')}</div>`; }).join('') : `<span class="muted">—</span>`, { icon: 'wallet' })}
    ${pnl(L3(['Travel peserta SegaDeals', 'SegaDeals Travels', 'الشركات المشاركة']), `<div style="display:flex;gap:8px;align-items:center;margin:-4px 0 10px"><span class="muted" style="font-size:12.5px">${L3(['Biaya default ', 'Default fee ', 'الرسوم ']) + money(SDCFG.fee) + '/pax · maks ' + money(SDCFG.maxFee) + ' · S&K v' + SDCFG.version}</span><span style="flex:1"></span>${permBtn('marketplace.manage', ic('sliders', 'sm') + L3(['Pengaturan', 'Settings', 'الإعدادات']), 'data-act="sd-cfg" data-mut', 'sm')}</div>${joined.length ? tbl(['Travel', L3(['Biaya/pax', 'Fee/pax', 'الرسوم']), 'Deposit', L3(['Tertunda', 'Owed', 'مستحق']), 'S&K', ''], joined.map(tr => `<tr><td>${esc(tr.name)}</td><td class="r tnum">${money(sdFeeFor(tr))}${tr.sdFee != null ? ' *' : ''}</td><td class="r tnum">${money(sdBalance(tr.id))}</td><td class="r tnum">${sdOwed(tr.id) ? money(sdOwed(tr.id)) : '—'}</td><td>${tr.sdTerms.revoked ? st('inactive') : sdTermsOk(tr) ? st('active') : st('pending')}</td><td class="r"><div class="actions" style="justify-content:flex-end;flex-wrap:nowrap">${permBtn('marketplace.manage', L3(['Biaya', 'Fee', 'الرسوم']), `data-act="sd-trfee" data-id="${tr.id}" data-mut`, 'sm')}${permBtn('marketplace.manage', tr.sdTerms.revoked ? L3(['Pulihkan', 'Restore', 'استعادة']) : L3(['Cabut', 'Revoke', 'إلغاء']), `data-act="sd-revoke" data-id="${tr.id}" data-mut`, 'sm ' + (tr.sdTerms.revoked ? '' : 'badb'))}</div></td></tr>`)) : `<span class="muted">${L3(['Belum ada Travel yang menyetujui S&K', 'No Travel has accepted the T&C yet', 'لا أحد'])}</span>`}`, { icon: 'shieldc' })}</div>`;
    const i = out.html.lastIndexOf('</div>'); out.html = out.html.slice(0, i) + blk + out.html.slice(i); return out; }); })();

/* ---------- Pengguna: isi data peserta langsung setelah memilih penawaran ---------- */
route('/p/traveler/sd-data/:id', p => { const u = me('traveler'); const b = bookingById(p.id); if (!b || b.traveler !== u.id) return { html: phone(stateBlock('noperm'), '/segadeals') }; const P = ensurePilgrims(b);
  return { html: phone(`<div class="ph-top"><b style="font-size:17px">${L3(['Isi data peserta', 'Enter traveller details', 'بيانات المسافرين'])}</b><div class="muted" style="font-size:12px">${esc((pkgById(b.pkg) || {}).name || '')} · ${b.pax} pax · ${b.id}</div></div><div class="ph-body">
  <p class="muted" style="font-size:12.5px;margin-top:0">${L3(['Tulis nama lengkap sesuai KTP/paspor untuk setiap peserta. Jika belum tahu, pilih "Diwakilkan oleh saya" — Anda bisa melengkapinya nanti.', 'Write each traveller’s full name as on ID/passport. If unknown, choose “Represented by me” — you can complete it later.', 'اكتب الأسماء.'])}</p>
  ${P.map((x, i) => `<div class="panel" style="padding:10px;margin-bottom:8px"><div class="eyebrow">${L3(['Peserta ', 'Traveller ', 'مسافر ']) + (i + 1)}${i === 0 ? ' · ' + L3(['pemesan', 'booker', 'صاحب الحجز']) : ''}</div><div class="field" style="margin-top:6px"><label for="sdd-name-${i}">${L3(['Nama lengkap', 'Full name', 'الاسم الكامل'])}</label><input id="sdd-name-${i}" value="${esc(x.name || '')}"></div><label class="field" style="flex-direction:row;align-items:center;gap:8px;font-size:13px"><input type="checkbox" id="sdd-rep-${i}" ${x.represented ? 'checked' : ''}> ${L3(['Diwakilkan oleh saya (pemesan)', 'Represented by me (booker)', 'ينوب عنه صاحب الحجز'])}</label><div class="field"><label for="sdd-pp-${i}">${L3(['Paspor', 'Passport', 'الجواز'])}</label><select id="sdd-pp-${i}"><option value="yes" ${x.hasPassport !== 'no' ? 'selected' : ''}>${L3(['Sudah punya paspor', 'Has a passport', 'لديه جواز'])}</option><option value="no" ${x.hasPassport === 'no' ? 'selected' : ''}>${L3(['Belum punya paspor', 'No passport yet', 'لا يوجد جواز'])}</option></select></div></div>`).join('')}
  <button class="btn primary" style="width:100%;justify-content:center;height:44px" data-act="sdd-save" data-id="${b.id}">${ic('check')}${L3(['Simpan & lanjut', 'Save & continue', 'حفظ ومتابعة'])}</button></div>`, '/segadeals') }; });
A['sdd-save'] = el => { const u = me('traveler'); const b = bookingById(el.dataset.id); const P = ensurePilgrims(b); let bad = false;
  P.forEach((x, i) => { const n = document.getElementById('sdd-name-' + i).value.trim(); const rep = document.getElementById('sdd-rep-' + i).checked; if (!n && !rep) { bad = true; document.getElementById('sdd-name-' + i).style.borderColor = 'var(--bad)'; } x.name = n || x.name || ''; x.represented = rep; x.representedBy = rep ? u.id : null; x.hasPassport = document.getElementById('sdd-pp-' + i).value; });
  if (bad) { toast('warn', L3(['Isi nama atau pilih "Diwakilkan"', 'Enter a name or choose “Represented”', 'أدخل الاسم']), ''); return; }
  audit(u.name, 'booking.pilgrims.set', 'Booking/' + b.id, 'success', { source: 'Aplikasi Pengguna · SegaDeals', after: P.map(x => x.name || '(diwakilkan)').join(', ') }); partyNotify([ntKey('travel', b.travel)], 'booking', 'info', L3(['Data peserta SegaDeals masuk', 'SegaDeals traveller data received', 'بيانات جديدة']), b.id + ' · ' + b.pax + ' pax', { travel: '/p/travel/bookings/' + b.id });
  toast('ok', L3(['Data peserta tersimpan', 'Traveller data saved', 'حُفظت']), L3(['Lanjut: dokumen & pembayaran', 'Next: documents & payment', 'التالي'])); go('/p/traveler/bookings/' + b.id); };

/* ---------- Rekomendasi paspor & surat cuti ---------- */
const IMIGRASI = ['Kanim Jakarta Selatan', 'Kanim Jakarta Pusat', 'Kanim Jakarta Timur', 'Kanim Bandung', 'Kanim Bogor', 'Kanim Tangerang', 'Kanim Bekasi', 'Kanim Semarang', 'Kanim Yogyakarta', 'Kanim Surabaya', 'Kanim Malang', 'Kanim Denpasar', 'Kanim Makassar', 'Kanim Medan', 'Kanim Palembang', 'Kanim Pekanbaru', 'Kanim Banjarmasin', 'Kanim Balikpapan', 'Kanim Manado', 'Kanim Mataram', 'Lainnya'];
const letterLabel = k => k === 'passport_rec' ? L3(['Rekomendasi paspor', 'Passport recommendation', 'توصية جواز']) : L3(['Surat cuti', 'Leave letter', 'خطاب إجازة']);
const leaveReady = p => !!(p && p.name && p.nik && p.birth);
const lettersOf = (b, k, i) => LETTERS.filter(l => l.booking === b.id && (!k || l.type === k) && (i == null || l.pax === i));
function lettersBlock(b, mode) { const P = ensurePilgrims(b); const L = LETTERS.filter(l => l.booking === b.id);
  const row = l => { const f = l.file && UPLOADS.find(u => u.id === l.file); const ktp = l.ktp && UPLOADS.find(u => u.id === l.ktp); return `<div class="docrow"><span class="fi">${l.type === 'leave' ? 'CT' : 'PP'}</span><span class="body"><b>${letterLabel(l.type)} · ${esc((P[l.pax] || {}).name || L3(['Jamaah ', 'Pilgrim ', 'معتمر ']) + (l.pax + 1))}</b><span>${l.type === 'passport_rec' ? esc(l.office) : esc(l.employer || '')}${l.reason ? ' · “' + esc(l.reason) + '”' : ''} · ${rel(l.ts)}</span></span>${st(l.state === 'requested' ? 'submitted' : l.state === 'issued' ? 'approved' : 'rejected')}${ktp ? `<button class="btn sm ghost" data-act="file-view" data-id="${ktp.id}">KTP</button>` : ''}${f ? `<button class="btn sm ghost" data-act="file-view" data-id="${f.id}">${ic('eye', 'sm')}${L3(['Surat', 'Letter', 'الخطاب'])}</button>` : ''}${mode === 'travel' && l.state === 'requested' ? `<button class="btn sm primary" data-act="lt-issue" data-id="${l.id}">${ic('upload', 'sm')}${L3(['Terbitkan', 'Issue', 'إصدار'])}</button><button class="btn sm badb" data-act="lt-reject" data-id="${l.id}">${t('reject')}</button>` : ''}</div>`; };
  const party = mode === 'traveler' || mode === 'party';
  const passBtns = party ? P.map((x, i) => x.hasPassport === 'no' && !lettersOf(b, 'passport_rec', i).some(l => l.state !== 'rejected') ? `<button class="btn sm" data-act="lt-pass" data-b="${b.id}" data-i="${i}">${ic('filecheck', 'sm')}${L3(['Minta rekomendasi paspor · ', 'Request passport recommendation · ', 'طلب توصية · ']) + esc(x.name || L3(['Jamaah ', 'Pilgrim ', 'معتمر ']) + (i + 1))}</button>` : '').join('') : '';
  const canLeave = P.map((x, i) => [x, i]).filter(([x, i]) => leaveReady(x) && !lettersOf(b, 'leave', i).some(l => l.state !== 'rejected'));
  const leave = party ? (canLeave.length ? `<div style="margin-top:10px"><div class="muted" style="font-size:12.5px;margin-bottom:6px">${L3(['Surat cuti — pilih jamaah (data sudah lengkap):', 'Leave letter — choose pilgrims (data complete):', 'خطاب الإجازة:'])}</div>${canLeave.map(([x, i]) => `<label class="field" style="flex-direction:row;align-items:center;gap:8px;font-size:13px"><input type="checkbox" class="lt-pick" value="${i}" checked> ${esc(x.name)}</label>`).join('')}<div class="actions" style="flex-wrap:wrap"><button class="btn sm primary" data-act="lt-leave" data-b="${b.id}" data-all="1">${ic('send', 'sm')}${L3(['Ajukan surat cuti semua', 'Request for all', 'للجميع'])} (${canLeave.length})</button><button class="btn sm" data-act="lt-leave" data-b="${b.id}">${L3(['Ajukan yang dipilih', 'Request for selected', 'للمحددين'])}</button></div></div>` : `<div class="muted" style="font-size:12px;margin-top:8px">${L3(['Surat cuti bisa diajukan setelah data jamaah (nama, NIK, tanggal lahir) lengkap.', 'Leave letters can be requested once pilgrim data (name, NIK, birth date) is complete.', 'أكمل البيانات أولاً.'])}</div>`) : '';
  return `${L.length ? L.map(row).join('') : `<div class="muted" style="font-size:12.5px">${L3(['Belum ada permintaan surat', 'No letter requests yet', 'لا طلبات'])}</div>`}${passBtns ? `<div class="actions" style="flex-wrap:wrap;margin-top:10px">${passBtns}</div>` : ''}${leave}`; }
Object.assign(A, {
  'lt-pass': el => { const b = bookingById(el.dataset.b); const i = +el.dataset.i; const x = ensurePilgrims(b)[i]; modal({ title: L3(['Minta rekomendasi paspor', 'Request passport recommendation', 'طلب توصية']) + ' · ' + (x.name || ''), body: `<div class="field"><label for="lp-ktp">${L3(['Unggah KTP', 'Upload ID card (KTP)', 'ارفع الهوية'])} *</label><input type="file" id="lp-ktp" accept="image/*,.pdf"></div>` + fields([{ k: 'office', label: L3(['Kantor imigrasi yang dituju', 'Immigration office', 'مكتب الهجرة']), type: 'select', options: IMIGRASI.map(o => [o, o]) }, { k: 'other', label: L3(['Nama kantor (jika Lainnya)', 'Office name (if Other)', 'الاسم']) }, { k: 'nik', label: 'NIK', def: x.nik || '' }], 'lp-') + `<p class="muted" style="font-size:12px">${L3(['Travel menerbitkan surat rekomendasi paspor umrah/haji untuk dibawa ke kantor imigrasi.', 'Your Travel issues the umrah/hajj passport recommendation letter to take to the immigration office.', 'تصدر الشركة الخطاب.'])}</p>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="lt-pass-go" data-b="${b.id}" data-i="${i}">${ic('send', 'sm')}${L3(['Ajukan', 'Submit', 'إرسال'])}</button>` }); },
  'lt-pass-go': async el => { const b = bookingById(el.dataset.b); const i = +el.dataset.i; const v = formVals([{ k: 'office' }, { k: 'other' }, { k: 'nik' }], 'lp-'); const f = document.getElementById('lp-ktp').files[0]; if (!f) { toast('warn', L3(['Unggah KTP dulu', 'Upload the KTP first', 'ارفع الهوية']), ''); return; } const office = v.office === 'Lainnya' ? v.other.trim() : v.office; if (!office) { document.getElementById('lp-other').style.borderColor = 'var(--bad)'; return; } if (v.nik && !/^\d{16}$/.test(v.nik)) { document.getElementById('lp-nik').style.borderColor = 'var(--bad)'; toast('warn', 'NIK', L3(['NIK harus 16 digit', 'NIK must be 16 digits', '16 رقماً'])); return; }
    const ws = wsOf(); const who = me(ws).name; try { const up = await saveUpload(f, { ref: b.id, booking: b.id, traveler: b.traveler, travel: b.travel, kind: 'ktp', pax: i, by: who, byWs: ws }); if (v.nik) ensurePilgrims(b)[i].nik = v.nik; const l = { id: uid('LTR'), type: 'passport_rec', booking: b.id, traveler: b.traveler, travel: b.travel, pax: i, office, ktp: up.id, state: 'requested', by: who, ts: nowTs() }; LETTERS.unshift(l);
      audit(who, 'letter.passport_rec.request', 'Letter/' + l.id, 'success', { source: L3(WS[ws].label), after: office }); partyNotify([ntKey('travel', b.travel)], 'booking', 'warn', L3(['Permintaan rekomendasi paspor', 'Passport recommendation request', 'طلب توصية']), b.id + ' · ' + (ensurePilgrims(b)[i].name || '') + ' · ' + office, { travel: '/p/travel/bookings/' + b.id }); closeOverlays(); toast('ok', L3(['Permintaan terkirim ke Travel', 'Request sent to Travel', 'أُرسل']), office); rerender(); } catch (e) { toast('bad', 'Upload', String(e.message || e)); } },
  'lt-leave': el => { const b = bookingById(el.dataset.b); const all = !!el.dataset.all; const P = ensurePilgrims(b); const idx = all ? P.map((x, i) => i).filter(i => leaveReady(P[i]) && !lettersOf(b, 'leave', i).some(l => l.state !== 'rejected')) : [...document.querySelectorAll('.lt-pick:checked')].map(x => +x.value); if (!idx.length) { toast('warn', L3(['Pilih minimal satu jamaah', 'Choose at least one pilgrim', 'اختر واحداً']), ''); return; }
    modal({ title: L3(['Ajukan surat cuti', 'Request leave letter', 'خطاب إجازة']) + ' · ' + idx.length + ' ' + L3(['jamaah', 'pilgrims', 'معتمر']), body: `<p class="muted" style="margin-top:0">${idx.map(i => esc(P[i].name)).join(', ')}</p>` + fields([{ k: 'employer', label: L3(['Instansi / perusahaan tujuan surat', 'Employer / institution', 'جهة العمل']), req: true }, { k: 'from', label: L3(['Cuti mulai', 'Leave from', 'من']), type: 'date', req: true, def: new Date(b.dep - 2 * D).toISOString().slice(0, 10) }, { k: 'to', label: L3(['Cuti sampai', 'Leave until', 'إلى']), type: 'date', req: true, def: new Date(b.dep + (((pkgById(b.pkg) || {}).info || {}).duration || 12) * D).toISOString().slice(0, 10) }], 'll-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="lt-leave-go" data-b="${b.id}" data-idx="${idx.join(',')}">${ic('send', 'sm')}${L3(['Ajukan', 'Submit', 'إرسال'])}</button>` }); },
  'lt-leave-go': el => { const b = bookingById(el.dataset.b); const idx = el.dataset.idx.split(',').map(Number); const v = formVals([{ k: 'employer', req: true }, { k: 'from', req: true }, { k: 'to', req: true }], 'll-'); if (!v) return; const ws = wsOf(); const who = me(ws).name;
    idx.forEach(i => LETTERS.unshift({ id: uid('LTR'), type: 'leave', booking: b.id, traveler: b.traveler, travel: b.travel, pax: i, employer: v.employer, from: new Date(v.from).getTime(), to: new Date(v.to).getTime(), state: 'requested', by: who, ts: nowTs() }));
    audit(who, 'letter.leave.request', 'Booking/' + b.id, 'success', { source: L3(WS[ws].label), after: idx.length + ' jamaah · ' + v.employer }); partyNotify([ntKey('travel', b.travel)], 'booking', 'warn', L3(['Permintaan surat cuti', 'Leave letter request', 'طلب خطاب']) + ' · ' + idx.length + ' ' + L3(['jamaah', 'pilgrims', 'معتمر']), b.id + ' · ' + v.employer, { travel: '/p/travel/bookings/' + b.id }); closeOverlays(); toast('ok', L3(['Surat cuti diajukan', 'Leave letters requested', 'أُرسل']), idx.length + ' ' + L3(['jamaah', 'pilgrims', 'معتمر'])); rerender(); },
  'lt-issue': el => { const l = LETTERS.find(x => x.id === el.dataset.id); modal({ title: L3(['Terbitkan ', 'Issue ', 'إصدار ']) + letterLabel(l.type), body: `<div class="field"><label for="li-file">${L3(['File surat (PDF/gambar, bertanda tangan)', 'Signed letter file (PDF/image)', 'ملف الخطاب'])} *</label><input type="file" id="li-file" accept="image/*,.pdf"></div>` + fields([{ k: 'no', label: L3(['Nomor surat', 'Letter number', 'رقم الخطاب']), req: true }], 'li-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="lt-issue-go" data-id="${l.id}">${ic('check', 'sm')}${L3(['Terbitkan', 'Issue', 'إصدار'])}</button>` }); },
  'lt-issue-go': async el => { const l = LETTERS.find(x => x.id === el.dataset.id); const v = formVals([{ k: 'no', req: true }], 'li-'); if (!v) return; const f = document.getElementById('li-file').files[0]; if (!f) { toast('warn', L3(['Unggah file surat', 'Upload the letter file', 'ارفع الملف']), ''); return; }
    try { const up = await saveUpload(f, { ref: l.id, booking: l.booking, traveler: l.traveler, travel: l.travel, kind: l.type === 'leave' ? 'leave_letter' : 'passport_letter', pax: l.pax, by: me('travel').name, byWs: 'travel', state: 'verified' }); l.file = up.id; l.no = v.no; l.state = 'issued'; l.issuedAt = nowTs(); pAudit('travel', 'letter.' + l.type + '.issue', 'Letter/' + l.id, { after: v.no });
      partyNotify([ntKey('traveler', l.traveler)], 'booking', 'ok', letterLabel(l.type) + ' ' + L3(['sudah terbit', 'issued', 'صدر']), v.no, { traveler: '/p/traveler/bookings/' + l.booking }); closeOverlays(); toast('ok', letterLabel(l.type), v.no); rerender(); } catch (e) { toast('bad', 'Upload', String(e.message || e)); } },
  'lt-reject': el => { const l = LETTERS.find(x => x.id === el.dataset.id); confirmAction({ title: L3(['Tolak ', 'Reject ', 'رفض ']) + letterLabel(l.type), tone: 'danger', resource: 'Letter/' + l.id, label: t('reject'), onOk: r => { l.state = 'rejected'; l.reason = r; pAudit('travel', 'letter.' + l.type + '.reject', 'Letter/' + l.id, { reason: r }); partyNotify([ntKey('traveler', l.traveler)], 'booking', 'bad', letterLabel(l.type) + ' ' + L3(['ditolak', 'rejected', 'رُفض']), r, { traveler: '/p/traveler/bookings/' + l.booking }); rerender(); } }); }
});
/* sisipkan panel surat ke halaman booking pengguna, Travel, Mitra/Agen, admin */
const _registrantBlock = registrantBlock;
registrantBlock = function (b, mode) { return _registrantBlock(b, mode) + `<div style="margin-top:14px">${pnl(L3(['Surat & rekomendasi', 'Letters & recommendations', 'الخطابات']), lettersBlock(b, mode), { icon: 'filetext' })}</div>`; };
(() => { const R = ROUTES.find(x => x.pattern === '/p/travel/bookings/:id'); if (!R) return; const prev = R.fn;
  reroute('/p/travel/bookings/:id', p => { const out = prev(p); const b = bookingById(p.id); if (!b || !out || !out.html || b.travel !== (me('travel') || {}).id) return out; const fee = b.sdFeeState === 'awaiting_deposit' ? `<div class="banner bad" style="border-radius:10px;margin-bottom:12px">${ic('alert')}<span><b>${L3(['Biaya SegaDeals belum terpenuhi', 'SegaDeals fee not covered', 'الرسوم غير مسددة'])}</b> · ${money(b.sdFee, true)} — <a href="#/p/travel/segadeals">${L3(['Setor deposit', 'Top up deposit', 'إيداع'])}</a></span></div>` : '';
    const i = out.html.lastIndexOf('</div>'); out.html = out.html.slice(0, i) + `<div style="margin-top:14px">${pnl(L3(['Surat & rekomendasi', 'Letters & recommendations', 'الخطابات']), lettersBlock(b, 'travel'), { icon: 'filetext' })}</div>` + out.html.slice(i); if (fee) out.html = out.html.replace('<section class="panel" style="padding:12px 14px;margin-bottom:14px">', fee + '<section class="panel" style="padding:12px 14px;margin-bottom:14px">'); return out; }); })();
(() => { const R = ROUTES.find(x => x.pattern === '/p/traveler/bookings/:id'); if (!R) return; const prev = R.fn;
  reroute('/p/traveler/bookings/:id', p => { const out = prev(p); const b = bookingById(p.id); const u = me('traveler'); if (!b || !u || b.traveler !== u.id || !out || !out.html) return out; const blk = `<div class="eyebrow" style="margin:12px 0 6px">${L3(['Surat & rekomendasi', 'Letters & recommendations', 'الخطابات'])}</div>${lettersBlock(b, 'traveler')}`;
    const anchor = '<a class="btn" style="width:100%;justify-content:center;margin-top:10px" href="#/p/traveler/chat">'; out.html = out.html.replace(anchor, blk + anchor); return out; }); })();
