"use client";

import { useState } from "react";

type Language="id"|"en"|"ar";
type Tab="description"|"itinerary"|"facilities"|"hotel"|"policy"|"reviews";
const order:Tab[]=["description","itinerary","facilities","hotel","policy","reviews"];
const gallery=[
  ["Makkah","Ka'bah & Masjidil Haram","linear-gradient(145deg,#d9edff 0%,#f7fbff 45%,#dff4eb 100%)"],
  ["Madinah","Masjid Nabawi","linear-gradient(145deg,#e5f5ef 0%,#fbfdfc 50%,#dceeff 100%)"],
  ["Hotel","Akomodasi","linear-gradient(145deg,#fff1dc 0%,#fffaf3 50%,#e7eff8 100%)"],
  ["Perjalanan","Penerbangan","linear-gradient(145deg,#e8edff 0%,#f8f9ff 48%,#e2f5f0 100%)"],
] as const;

export function PackageDetailShowcase({language}:{language:Language;description:string|null;durationDays:number;inclusions:string[];exclusions:string[];rating:number|null;reviewCount:number}){
 const [tab,setTab]=useState<Tab>("description"),[itineraryDay,setItineraryDay]=useState(0),[hotelSlide,setHotelSlide]=useState(0),[activeImage,setActiveImage]=useState(0);
 const t={id:{tabs:["Deskripsi","Itinerary","Fasilitas","Tiket & Hotel","Kebijakan","Ulasan"],info:"Informasi",included:"Termasuk",hotel:"Hotel",flight:"Tiket",policy:"Ketentuan",review:"4.7/5",reviewMeta:"Dari 10 ulasan"},en:{tabs:["Description","Itinerary","Facilities","Ticket & Hotel","Policy","Reviews"],info:"Information",included:"Included",hotel:"Hotel",flight:"Ticket",policy:"Terms",review:"4.7/5",reviewMeta:"From 10 reviews"},ar:{tabs:["الوصف","البرنامج","المرافق","التذاكر والفندق","السياسة","التقييمات"],info:"المعلومات",included:"مشمول",hotel:"الفندق",flight:"التذكرة",policy:"الشروط",review:"4.7/5",reviewMeta:"من 10 تقييمات"}}[language];
 const body:Record<Tab,JSX.Element>={
 description:<><b>{t.info}</b><p>Informasi lengkap mengenai paket perjalanan, layanan, jadwal, fasilitas, serta ketentuan perjalanan akan ditampilkan pada bagian ini. Konten dibuat ringkas agar mudah dibaca sebelum melakukan pemesanan. Informasi tambahan mengenai keberangkatan, pelayanan Travel, akomodasi, transportasi, perlengkapan dan kebutuhan perjalanan juga dapat dicantumkan pada area ini.</p></>,
 itinerary:<><b>{language==="ar"?`اليوم ${itineraryDay+1}`:language==="en"?`Day ${itineraryDay+1}`:`Hari ${itineraryDay+1}`}</b><p>{["Keberangkatan dan proses perjalanan awal. Informasi waktu berkumpul, transportasi, serta agenda hari pertama ditampilkan pada bagian ini.","Agenda perjalanan hari kedua mencakup kegiatan utama, waktu kunjungan, konsumsi, transportasi, dan waktu istirahat.","Rangkaian kegiatan lanjutan, perpindahan lokasi, aktivitas jamaah, dan informasi akomodasi ditampilkan secara ringkas.","Agenda akhir perjalanan, persiapan kepulangan, waktu check-out, transportasi menuju bandara, dan informasi penerbangan pulang."][itineraryDay]}</p></>,
 facilities:<><b>{t.included}</b><div className="grid grid-cols-2 gap-x-8 gap-y-1"><span>◎ Akomodasi</span><span>◎ Transportasi</span><span>◎ Konsumsi</span><span>◎ Pendamping perjalanan</span><span>◎ Bagasi sesuai ketentuan</span><span>◎ Perlengkapan paket</span></div></>,
 hotel:hotelSlide===0
 ? <><b>{t.hotel}</b><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><div><p className="font-semibold">Hilton Makkah Convention Hotel</p><p className="mt-1 text-[#748297]">Mekkah · dekat area Masjidil Haram</p><p className="mt-2">Informasi tipe kamar, fasilitas, check-in/check-out dan layanan akomodasi ditampilkan di sini.</p></div><div className="relative min-h-[88px] overflow-hidden rounded-lg border border-[#dfe7f0] bg-[linear-gradient(135deg,#d9edff,#f8fbff_48%,#dff4eb)]"><div className="absolute inset-x-4 top-1/2 border-t-2 border-dashed border-primary/30"/><div className="absolute left-1/3 top-5 h-3 w-3 rounded-full bg-primary"/><div className="absolute bottom-3 right-5 text-[10px] font-bold text-[#60738d]">Preview lokasi hotel</div></div></div></>
 : <><b>{t.flight}</b><div className="rounded-xl border border-[#edf1f6] p-3"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className="font-extrabold">Pulang</span><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#0c7891] text-[9px] font-bold text-white">WY</span><span className="font-medium">Oman Air WY674</span></div><span className="text-[#60738d]">Ekonomi · Transit</span></div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-4"><div><p className="text-2xl font-medium">MCT</p><p>Muscat, Terminal</p><p className="mt-3">02.15 | 27 Okt 2025</p></div><div className="text-center"><div className="flex items-center gap-2 text-primary"><span className="w-10 border-t border-dashed border-[#9aa6b5]"/><span>✈</span><span className="w-10 border-t border-dashed border-[#9aa6b5]"/></div><p className="mt-3">8j 05m</p></div><div className="text-end"><p className="text-2xl font-medium">CGK</p><p>Soekarno Hatta, Terminal 3</p><p className="mt-3">13.20 | 27 Okt 2025</p></div></div></div></>,
 policy:<><b>{t.policy}</b><div><p>1. Pemesanan mengikuti ketersediaan jadwal dan kuota.</p><p>2. Perubahan jadwal mengikuti ketentuan Travel dan penyedia layanan.</p><p>3. Pembatalan dan refund mengikuti kebijakan paket yang berlaku.</p><p>4. Ketentuan dokumen dan pembayaran akan mengikuti rincian paket.</p></div></>,
 reviews:<><div><b>{t.review}</b><p className="mt-1">{t.reviewMeta}</p></div><div><p>Pelayanan Travel ramah dan responsif. Informasi perjalanan mudah dipahami dan proses pemesanan dapat dipantau dengan jelas.</p><p className="mt-4 text-xs font-semibold">Ahmad Fauzi · Jamaah Umrah Januari 2025</p></div></>
 };
 const tile=(index:number,large=false)=><button type="button" onClick={()=>setActiveImage(index)} aria-label={`Tampilkan gambar ${gallery[index][1]}`} className={`group relative h-full w-full overflow-hidden rounded-[9px] border bg-white text-start transition ${activeImage===index?"border-primary ring-1 ring-primary/20":"border-[#e2e7ed] hover:border-primary/50"}`} style={{backgroundImage:gallery[index][2]}}><div className="absolute -bottom-10 -left-8 h-28 w-28 rounded-full border-[18px] border-white/45"/><div className="absolute -right-8 -top-10 h-28 w-28 rounded-full bg-white/40"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#10223f]/70 to-transparent p-3 pt-10 text-white"><p className={large?"text-sm font-extrabold":"text-xs font-extrabold"}>{gallery[index][0]}</p><p className="mt-0.5 text-[10px] text-white/80">{gallery[index][1]}</p></div></button>;
 const thumbs=[0,1,2,3].filter(i=>i!==activeImage);
 return <div className="flex h-full flex-col rounded-[16px] bg-[#f4f4f4] p-2.5 font-sans">
  <div className="grid h-[315px] grid-cols-[1.25fr_.9fr] gap-2.5">
   {tile(activeImage,true)}
   <div className="grid min-h-0 grid-rows-2 gap-2.5">{tile(thumbs[0])}<div className="grid min-h-0 grid-cols-2 gap-2.5">{tile(thumbs[1])}{tile(thumbs[2])}</div></div>
  </div>
  <div className="mt-2.5 flex h-[250px] shrink-0 flex-col rounded-[12px] bg-white px-5 pb-4">
   <div className="overflow-x-auto border-b border-[#d9d9d9]"><div className="flex min-w-max justify-between gap-4">{order.map((key,i)=><button key={key} type="button" onClick={()=>setTab(key)} className={`border-b-2 py-3 text-xs font-medium leading-none transition sm:text-sm ${tab===key?"border-primary font-bold text-primary":"border-transparent text-[#454545] hover:text-primary"}`}>{t.tabs[i]}</button>)}</div></div>
   <div className={`relative min-h-0 flex-1 pe-3 pt-4 text-xs leading-5 text-[#454545] sm:text-sm sm:leading-6 ${tab==="description"||tab==="policy"||tab==="hotel"||tab==="facilities"||tab==="reviews"?"overflow-y-scroll":"overflow-hidden"} [scrollbar-color:#8a8a8a_#f1f3f5] [scrollbar-width:thin]`}>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-[78px_1fr] sm:gap-4">{body[tab]}</div>
   </div>
   {tab==="itinerary"&&<div className="mt-2 flex items-center gap-3"><button type="button" onClick={()=>setItineraryDay(v=>(v+3)%4)} className="flex h-6 w-6 items-center justify-center rounded-full border border-[#9b9b9b]">←</button><button type="button" onClick={()=>setItineraryDay(v=>(v+1)%4)} className="flex h-6 w-6 items-center justify-center rounded-full border border-primary text-primary">→</button><span className="text-xs font-semibold text-[#8a8a8a]">{itineraryDay+1} / 4</span></div>}
   {tab==="hotel"&&<div className="mt-2 flex items-center gap-3"><button type="button" onClick={()=>setHotelSlide(v=>(v+1)%2)} className="flex h-6 w-6 items-center justify-center rounded-full border border-[#9b9b9b]">←</button><button type="button" onClick={()=>setHotelSlide(v=>(v+1)%2)} className="flex h-6 w-6 items-center justify-center rounded-full border border-primary text-primary">→</button><span className="text-xs font-semibold text-[#8a8a8a]">{hotelSlide+1} / 2</span></div>}
  </div>
 </div>;
}